[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "dbof-in-native-grid"
version = "0.0.dev0"
description = "Fronts in the Ocean"
readme = "README.md"
license = { text = "BSD" }
authors = [
    { name = "J. Xavier Prochaska", email = "jxp@ucsc.edu" },
    { name = "P. Cornillon"},
    { name = "J. Tallman", email = "jttallman@ucdavis.edu" }
]
classifiers = [
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Oceanography",
    "Programming Language :: Python :: 3"
]

urls = { "Homepage" = "https://github.com/AI-for-Ocean-Science/" }
requires-python = ">=3.12"

dependencies = [
    "numpy",
    "Reader",
    "aiohttp",
    "torch==2.8.0",
    "torchvision",
    "smart-open[s3]",
    "pyarrow",
    "scikit-learn",
    "scikit-image",
    "tqdm",
    "cftime",
    "umap-learn",
    "llvmlite",
    "boto3==1.41.5",
    "xarray==2025.10.1",
    "h5netcdf",
    "emcee",
    "corner",
    "importlib-metadata",
    "timm==0.3.2",
    "xmitgcm",
    "dask==2025.10.0",
    "s3fs==2025.9.0",
    "ujson",
    "zarr",
    "gsw",
    "xgcm",
    "seawater",
    "ecco_v4_py",
    "scikit-fmm",
    "pyyaml"
]

[project.optional-dependencies]

plotting = [
    "matplotlib",
    "seaborn",
    "bokeh",
    "cmocean",
]

test = ["pytest"]

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
generate-llc-dataset = "dbof.cli.generate_front_training_data:main"
generate-global-llc-dataset = "dbof.cli.generate_fronts_global:main"
generate-global-grid = "dbof.cli.generate_grid_netcdf:main"
zarr-to-netcdf = "dbof.cli.zarr_to_netcdf:main"
