"""
depth_figures.py
----------------
Figures for the DEPTH field-validation notebooks, plus the small amount
of data shaping they need.

A note on the word "grid", because this repo uses it for two unrelated
things.  In THIS module a *grid* is the rows x columns array of panels
in a figure -- matplotlib's sense, and the same sense as the surface
module ``pipeline_grids.py``.  The model's Arakawa C-grid (tracer
centres, staggered faces, corners) is a different thing entirely and
lives in ``docs/Grid.md``, ``docs/Gradients.md`` and
``utils/native_gradient.py``.  Nothing here touches it.

Layout
------
The surface notebooks put a REGION on each row.  The depth notebooks
fix one tile and put a DEPTH LEVEL on each row instead.  Columns are
unchanged: the dependency chain, raw -> intermediate -> final.

:func:`depth_map_grid` is eight rows: the four levels over the whole
tile, then the same four zoomed to a 200 x 200 km box, whose position
is the crimson square on the whole-tile rows.

:func:`depth_pdf_grid` is four rows -- the whole tile at each level.
The zoom boxes are too small to make an honest histogram, so they are
deliberately absent.  Bins are shared down a COLUMN, so reading a
column top to bottom shows how the distribution changes with depth.

Data shaping
------------
:func:`compute_levels` reduces lazy 3D fields to the four levels, and
:func:`pack_tile_levels` turns computed channels into the
``{base: {level: (x, y, arr)}}`` mapping both figure functions consume
-- NaN'ing the tile's edge rim and masking land on the way.  Same job
``live_fields.py`` does for the surface notebooks.

Colour conventions (cmaps, labels, log scales, diverging centring, land
grey) come from the same registry and the same helpers the surface
figures use.  Nothing is hard-coded here.

Generated by LH and Claude.
"""

import dask
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import numpy as np

from dbof.plotting import regions as regions_mod
from dbof.plotting.global_maps import make_field_norm, plot_global_field
# ``_clean_values`` is private to pdfs.py but is the single definition of
# the NaN-drop / log10 convention; reusing it keeps the depth PDFs and
# the surface PDFs from drifting apart.
from dbof.plotting.pdfs import N_BINS, _clean_values, pdf_panel, shared_bins
from dbof.preprocessing.depth_strategies import apply_depth_strategies
from dbof.preprocessing.vertical_helpers import (
    _get_depth_coord, _get_vertical_dim,
)
from dbof.tiles.field_registry import TILE_PROPERTIES

PANEL_W = 4.2
PANEL_H = 3.2
LAND_COLOR = "0.85"
BOX_KW = {"color": "crimson", "linewidth": 1.4}

#: The four depth levels, in the order the figures use as rows.
DEPTH_LEVELS = ("sfc", "z25m", "mld", "mld_mean")

#: Row titles.
LEVEL_TITLES = {
    "sfc":      "surface (k=0)",
    "z25m":     "25 m",
    "mld":      "at MLD",
    "mld_mean": "MLD mean",
}

#: Default half-width of the zoom box, in km (so a 200 x 200 km square).
ZOOM_HALF_KM = 100.0

#: Colours for the profile locations, in FIXED order -- never cycled.
#: Okabe-Ito, the colourblind-safe qualitative set that is also the de
#: facto standard for oceanography figures.  Validated all-pairs under
#: deuteranopia / protanopia / tritanopia: the worst pair (purple vs
#: green) sits at dE 7.6, inside the floor band that is permissible ONLY
#: with a second, non-colour channel -- which is why every location also
#: carries its NUMBER on the map and in the legend.  Identity here never
#: depends on colour alone.
LOCATION_COLORS = ("#0072B2", "#D55E00", "#009E73", "#CC79A7", "#E69F00")

#: Default number of profile locations.
N_PROFILE_POINTS = 5

#: Vertical dimension names, for spotting an inherently 2D field.
_VERTICAL_DIMS = {"k", "k_l", "k_u", "k_p1", "Z", "Zl", "Zu", "Zp1"}


# ---------------------------------------------------------------------------
# Picking the tile
# ---------------------------------------------------------------------------

def region_anchor(region):
    """Return the ``(lon, lat)`` a region's tile and zoom are centred on.

    A tile SAMPLES a region, it does not cover it, so a depth notebook
    needs a point rather than a box.  We reuse the ``zoom`` anchors
    already pinned in ``regions.py`` -- the same points the surface
    notebooks zoom into -- so surface and depth look at the same water.

    Inputs
    ------
    region : str
        Key in ``regions.REGIONS`` carrying a ``zoom`` anchor.

    Outputs
    -------
    (lon, lat) : tuple[float, float]

    Raises
    ------
    ValueError
        If the region has no anchor (``global``, ``kerguelen``).

    Generated by LH and Claude.
    """
    anchor = regions_mod.REGIONS.get(region, {}).get("zoom")
    if anchor is None:
        have = sorted(k for k, v in regions_mod.REGIONS.items()
                      if v.get("zoom"))
        raise ValueError(
            f"region '{region}' has no 'zoom' anchor in regions.py, so "
            f"there is no point to centre a tile on.  Regions with one: "
            f"{have}"
        )
    return float(anchor[0]), float(anchor[1])


def edge_margin_for(bases):
    """Widest invalid rim among these fields, from the tile registry.

    A tile's xgcm grid has no face connections, so fields with a
    horizontal stencil are wrong near the boundary.  ``field_registry``
    already records how many cells that is per field (0 vertical-only,
    1 staggered interpolation, 3 gradient / Jacobian chains); this just
    takes the worst case over the chain so one rim covers the figure.

    Names the registry does not know (live intermediates such as
    ``rho_theta``) are skipped -- pass an explicit margin if one of them
    is the widest thing in your chain.

    Inputs
    ------
    bases : iterable of str
        Field base names.

    Outputs
    -------
    int
        Rim width in cells; 0 if none of the names is in the registry.

    Generated by LH and Claude.
    """
    known = [TILE_PROPERTIES[b].edge_margin for b in bases
             if b in TILE_PROPERTIES]
    return max(known) if known else 0


# ---------------------------------------------------------------------------
# Shaping the data
# ---------------------------------------------------------------------------

def tile_coords(ds_grid):
    """Return the tile's 2D ``(XC, YC)`` as plain numpy arrays.

    Inputs
    ------
    ds_grid : xr.Dataset
        Tile grid from ``tile_utils._load_grid_for_tile``.

    Outputs
    -------
    (XC, YC) : tuple[np.ndarray, np.ndarray]
        Longitude / latitude on dims ``(j, i)``, face squeezed out.

    Generated by LH and Claude.
    """
    return (ds_grid["XC"].isel(face=0).values,
            ds_grid["YC"].isel(face=0).values)


def tile_land_mask(ds_grid):
    """Boolean land mask (True = land) from the tile's surface ``hFacC``.

    The DEPTH grid store's ``hFacC`` is already collapsed to ``k=0``, and
    the production depth pipeline masks with that same surface mask, so
    this matches what the global stores contain.

    Inputs
    ------
    ds_grid : xr.Dataset
        Tile grid from ``tile_utils._load_grid_for_tile``.

    Outputs
    -------
    np.ndarray
        Boolean ``(j, i)`` array, True where the cell is land.

    Generated by LH and Claude.
    """
    hfac = ds_grid["hFacC"]
    if "k" in hfac.dims:
        hfac = hfac.isel(k=0)
    return (hfac.isel(face=0).values == 0)


#: Horizontal dimension names that must be chunked identically before a
#: field and the MLD are indexed together.
_HORIZONTAL_DIMS = ("j", "i", "j_g", "i_g")


def align_chunks(*arrays):
    """Force one common horizontal chunking across several arrays.

    ``_extract_at_mld`` (and anything else that feeds a 3D field and a
    2D MLD into a single ``apply_ufunc``) indexes the two together
    inside one block, so their horizontal chunks must match exactly.
    They often do not: xgcm's ``diff`` / ``interp`` can fuse or split
    blocks, so a field derived through a gradient chain can come out
    chunked 360x360 while the MLD it will be sampled at is still
    180x180.  xarray does not always unify these, and the failure is an
    ``IndexError`` deep inside the ufunc rather than anything readable.

    Production never hits this because ``_ensure_depth_chunking`` uses a
    single 720x720 horizontal block; it only appears once you rechunk
    the horizontal to bound memory.

    Inputs
    ------
    *arrays : xr.DataArray
        Any mix of 2D and 3D arrays.  Non-dask arrays pass through.

    Outputs
    -------
    tuple[xr.DataArray] or xr.DataArray
        The inputs rechunked to the SMALLEST block size present for
        each horizontal dimension.  A single input is returned bare.

    Generated by LH and Claude.
    """
    target = {}
    for a in arrays:
        sizes = getattr(a, "chunksizes", None) or {}
        for d in _HORIZONTAL_DIMS:
            if d in sizes and len(sizes[d]):
                target[d] = min(target.get(d, min(sizes[d])),
                                min(sizes[d]))
    if not target:
        return arrays if len(arrays) > 1 else arrays[0]

    out = tuple(
        a.chunk({d: n for d, n in target.items() if d in a.dims})
        for a in arrays
    )
    return out if len(out) > 1 else out[0]


def reduce_to_levels(field3d, base, ds_merge, mld, levels=DEPTH_LEVELS):
    """Reduce one lazy 3D field to the requested depth levels (still lazy).

    Fields with no vertical dimension (Eta, coriolis_f, MLD itself) pass
    straight through under ``{base}_2d``; :func:`pack_tile_levels`
    broadcasts those down the rows later.

    Inputs
    ------
    field3d : xr.DataArray
        Lazy field on the tile.
    base : str
        Channel base name, e.g. ``"rho_theta"``.
    ds_merge : xr.Dataset
        Merged tile dataset.
    mld : xr.DataArray or None
        Lazy MLD; required for the ``mld`` / ``mld_mean`` levels.
    levels : tuple[str]
        Subset of :data:`DEPTH_LEVELS`.

    Outputs
    -------
    dict[str, xr.DataArray]
        Lazy arrays keyed ``{base}_{level}`` (or ``{base}_2d``).

    Generated by LH and Claude.
    """
    if not (set(field3d.dims) & _VERTICAL_DIMS):
        return {f"{base}_2d": field3d}

    # The mld / mld_mean strategies index the field and the MLD inside
    # one apply_ufunc, so their horizontal chunks have to match.
    if mld is not None:
        field3d, mld = align_chunks(field3d, mld)

    return apply_depth_strategies(
        field3d, base, ds_merge, mld=mld,
        requested={f"{base}_{lev}" for lev in levels},
    )


def compute_levels(lazy_3d, ds_merge, *, mld=None, levels=DEPTH_LEVELS,
                   verbose=True):
    """Reduce a dict of lazy fields to levels, in one ``dask.compute``.

    Use this for the chain's raw inputs and live intermediates (Theta,
    Salt, rho_theta, db_dx, ...) -- the things the global stores never
    keep but the dependency figures need.

    Inputs
    ------
    lazy_3d : dict[str, xr.DataArray]
        Base name -> lazy field on the tile.
    ds_merge : xr.Dataset
        Merged tile dataset.
    mld : xr.DataArray or None
        Lazy MLD.  Required if ``levels`` includes ``mld`` / ``mld_mean``.
    levels : tuple[str]
        Depth levels to produce.
    verbose : bool
        Print the channels produced.

    Outputs
    -------
    dict[str, xr.DataArray]
        Materialised, keyed ``{base}_{level}`` / ``{base}_2d``.

    Generated by LH and Claude.
    """
    lazy_out = {}
    for base, field in lazy_3d.items():
        lazy_out.update(
            reduce_to_levels(field, base, ds_merge, mld, levels=levels))

    keys = list(lazy_out)
    values = dask.compute(*[lazy_out[k] for k in keys], retries=10)
    out = dict(zip(keys, values))
    if verbose:
        print(f"live fields : {sorted(out)}")
    return out


def _as_2d(value):
    """Squeeze a computed channel to a 2D ``(j, i)`` numpy array.

    Inputs
    ------
    value : xr.DataArray or np.ndarray
        A computed channel; may still carry a size-1 ``face`` dim.

    Outputs
    -------
    np.ndarray

    Generated by LH and Claude.
    """
    return np.squeeze(np.asarray(getattr(value, "values", value)))


def channel_base(name, levels=DEPTH_LEVELS):
    """Strip a depth suffix: ``"N2_mld_mean"`` -> ``"N2"``.

    Inputs
    ------
    name : str
        Channel name, with or without a level suffix.
    levels : tuple[str]
        Level suffixes to recognise.

    Outputs
    -------
    str

    Generated by LH and Claude.
    """
    return _split_channel(name, levels)[0]


def _split_channel(name, levels):
    """Split ``"N2_mld_mean"`` into ``("N2", "mld_mean")``.

    Inputs
    ------
    name : str
        Channel name.
    levels : tuple[str]
        Level suffixes to look for.

    Outputs
    -------
    (base, level) : tuple[str, str or None]
        ``level`` is None when there is no recognised suffix.

    Generated by LH and Claude.
    """
    # Longest suffix first, so "mld_mean" wins over "mld".
    for lev in sorted(set(levels) | {"2d", "sfc"}, key=len, reverse=True):
        if name.endswith("_" + lev):
            return name[: -len(lev) - 1], lev
    return name, None


def _nan_rim(arr, margin):
    """NaN a border of *margin* cells on all four sides.

    Same convention as ``tile_utils.compute_tile_property``: the array
    keeps its full 720 x 720 shape and the unusable cells become NaN,
    rather than being trimmed away.

    Inputs
    ------
    arr : np.ndarray
        2D field (modified on a copy).
    margin : int
        Rim width in cells; 0 is a no-op.

    Outputs
    -------
    np.ndarray

    Generated by LH and Claude.
    """
    if margin <= 0:
        return arr
    out = arr.copy()
    out[:margin, :] = np.nan
    out[-margin:, :] = np.nan
    out[:, :margin] = np.nan
    out[:, -margin:] = np.nan
    return out


def pack_tile_levels(channels, XC, YC, *, edge_margin=0, land_mask=None,
                     levels=DEPTH_LEVELS, verbose=True):
    """Turn computed channels into the ``{base: {level: (x, y, arr)}}`` map.

    This is the structure both figure functions consume.  On the way it
    does the two clean-up steps every tile result needs:

    - **NaNs the edge rim**, where the local (no face connections) grid
      made horizontal stencils invalid;
    - **masks land** with the surface ``hFacC``, matching production.

    Channels with no depth suffix, and bases that only ever produce
    ``_sfc`` (Eta, gradeta2, ug, vg), are BROADCAST down the rows so the
    dependency chain still reads left-to-right at every level.  Which
    ones were broadcast is printed, and belongs in the figure caption.

    Inputs
    ------
    channels : dict[str, xr.DataArray | np.ndarray]
        Computed channels, keyed ``{base}_{level}`` / ``{base}_2d`` /
        bare (e.g. ``"mixed_layer_depth"``).
    XC, YC : np.ndarray
        Tile coordinates from :func:`tile_coords`.
    edge_margin : int
        Rim width to NaN; see :func:`edge_margin_for`.
    land_mask : np.ndarray or None
        Boolean ``(j, i)`` land mask from :func:`tile_land_mask`.
        ``None`` skips masking.
    levels : tuple[str]
        Row order.
    verbose : bool
        Print the shape and which bases were broadcast.

    Outputs
    -------
    dict[str, dict[str, tuple]]
        ``out[base][level] = (x, y, arr)``.

    Generated by LH and Claude.
    """
    def _finish(value):
        arr = _nan_rim(_as_2d(value).astype("float32"), edge_margin)
        if land_mask is not None:
            arr = np.where(land_mask, np.nan, arr)
        return (XC, YC, arr)

    grouped = {}
    for name, value in channels.items():
        base, level = _split_channel(name, levels)
        grouped.setdefault(base, {})[level or "2d"] = _finish(value)

    out, broadcast = {}, []
    for base, by_level in grouped.items():
        missing = [lev for lev in levels if lev not in by_level]
        if missing:
            # A 2D field (or a surface-only base): repeat it down the rows.
            source = by_level.get("2d") or by_level.get("sfc")
            if source is None:
                raise KeyError(
                    f"'{base}' has levels {sorted(by_level)} but none of "
                    f"{missing} and nothing to broadcast from."
                )
            broadcast.append(base)
            by_level = {lev: by_level.get(lev, source) for lev in levels}
        out[base] = {lev: by_level[lev] for lev in levels}

    if verbose:
        n_j, n_i = out[next(iter(out))][levels[0]][2].shape
        print(f"packed      : {len(out)} fields on a {n_j} x {n_i} tile, "
              f"{edge_margin}-cell rim NaN'd")
        if broadcast:
            print(f"broadcast   : {sorted(broadcast)} are 2D / surface-only "
                  "-- the same map repeats down the depth rows")
    return out


# ---------------------------------------------------------------------------
# Cropping to the zoom box
# ---------------------------------------------------------------------------

def crop_lonlat_box(x, y, arr, west, east, south, north):
    """Crop a tile to the tightest window covering a lon/lat box.

    Unlike ``regions.crop_zoom`` this makes no assumption that array
    rows are lines of constant latitude.  A tile's face-local axes can
    be rotated or mirrored relative to geographic north, so we build a
    boolean mask of cells inside the box and take its bounding box in
    ARRAY space.

    Inputs
    ------
    x, y : np.ndarray
        2D longitude / latitude of the tile.
    arr : np.ndarray
        2D field on the same mesh.
    west, east, south, north : float
        Box edges in degrees.

    Outputs
    -------
    (xz, yz, sub) : tuple[np.ndarray, np.ndarray, np.ndarray]

    Raises
    ------
    ValueError
        If no cell falls inside the box.

    Generated by LH and Claude.
    """
    # Wrap longitudes onto the box so the dateline is not a special case.
    dlon = (x - west + 180.0) % 360.0 - 180.0
    span = (east - west + 180.0) % 360.0 - 180.0
    if span <= 0:
        span += 360.0
    inside = (dlon >= 0) & (dlon <= span) & (y >= south) & (y <= north)

    if not inside.any():
        raise ValueError(
            f"no tile cells inside lon [{west}, {east}], "
            f"lat [{south}, {north}] -- is the zoom anchor on this tile?"
        )

    rows = np.where(inside.any(axis=1))[0]
    cols = np.where(inside.any(axis=0))[0]
    jsl = slice(int(rows[0]), int(rows[-1]) + 1)
    isl = slice(int(cols[0]), int(cols[-1]) + 1)
    return x[jsl, isl], y[jsl, isl], arr[jsl, isl]


def zoom_bounds(region, *, half_km=ZOOM_HALF_KM):
    """Return ``(west, east, south, north)`` of a region's zoom square.

    Thin wrapper over ``regions.zoom_box`` so this module has one place
    that knows the zoom convention.  The square is centred on the same
    anchor :func:`region_anchor` picks the tile with, so it always falls
    on the tile -- though it can sit near an edge, in which case the
    crop is clipped to whatever the tile holds.

    Inputs
    ------
    region : str
        Region key with a ``zoom`` anchor.
    half_km : float
        Half-width of the square, in km.

    Outputs
    -------
    tuple[float, float, float, float]

    Generated by LH and Claude.
    """
    (west, east), (south, north) = regions_mod.zoom_box(
        region, half_km=half_km)
    return west, east, south, north


def _draw_box(ax, bounds):
    """Draw the crimson zoom locator square on a lon/lat axis.

    Inputs
    ------
    ax : matplotlib axis
    bounds : tuple[float, float, float, float]
        ``(west, east, south, north)``.

    Outputs
    -------
    None (draws on ``ax``).

    Generated by LH and Claude.
    """
    w, e, s, n = bounds
    ax.plot([w, e, e, w, w], [s, s, n, n, s], **BOX_KW)


# ---------------------------------------------------------------------------
# Figure 1 -- maps
# ---------------------------------------------------------------------------

def depth_map_grid(chain, level_arrays, cmap_cfg, *, region,
                   levels=DEPTH_LEVELS,
                   diverging_cmaps=frozenset(),
                   log_scale_channels=frozenset(),
                   percentiles=(1, 99),
                   zoom_rows=True,
                   zoom_half_km=ZOOM_HALF_KM,
                   row_labels=None,
                   suptitle=None):
    """Figure 1: dependency chain across columns, depth levels down rows.

    Rows 1..N are the levels over the whole tile; rows N+1..2N repeat
    them zoomed to a ``2 * zoom_half_km`` square, whose position is
    drawn as a crimson box on the whole-tile rows.

    For a field that does NOT vary with depth (``mixed_layer_depth``,
    ``ml_heat_content`` -- both are integrals over the whole column)
    pass ``levels=("sfc",)`` and a two-entry ``row_labels``: four
    identical depth rows would say nothing.

    One colour scale per COLUMN, built from the pooled whole-tile values
    of every level and reused by that column's zoom rows -- so both the
    depth rows and the zoom rows are directly comparable.

    Inputs
    ------
    chain : list[str]
        Field base names in dependency order (the columns).  Every entry
        must be a key of ``level_arrays``.
    level_arrays : dict[str, dict[str, tuple]]
        ``level_arrays[base][level] = (x, y, arr)`` -- from
        :func:`pack_tile_levels`.
    cmap_cfg : dict[str, tuple[str, str]]
        ``field_cmaps.load_field_cmaps()`` registry: name -> (cmap, label).
    region : str
        Region key, used for the zoom anchor.
    levels : tuple[str]
        Depth levels, in row order.
    diverging_cmaps : set[str]
        Colormap NAMES to centre at zero.
    log_scale_channels : set[str]
        Field names drawn on a log colour scale.
    percentiles : tuple[float, float]
        Colour-limit percentiles.
    zoom_rows : bool
        Add the zoomed rows.  Turn off for a quick 4-row look.
    zoom_half_km : float
        Half-width of the zoom square, in km.
    row_labels : sequence[str] or None
        Override the row labels.  Must match the row count
        (``2 * len(levels)`` with zooms, else ``len(levels)``).
    suptitle : str or None
        Figure title.

    Outputs
    -------
    (fig, axes) : tuple
        ``axes`` has shape ``(n_rows, len(chain))``.

    Generated by LH and Claude.
    """
    n_lev = len(levels)
    n_rows = n_lev * 2 if zoom_rows else n_lev
    n_cols = len(chain)

    bounds = zoom_bounds(region, half_km=zoom_half_km) if zoom_rows else None

    if row_labels is not None and len(row_labels) != n_rows:
        raise ValueError(
            f"row_labels has {len(row_labels)} entries but the figure has "
            f"{n_rows} rows"
        )

    fig, axes = plt.subplots(
        n_rows, n_cols, squeeze=False,
        figsize=(n_cols * PANEL_W, n_rows * PANEL_H),
    )

    for j, field in enumerate(chain):
        by_level = level_arrays[field]
        cmap_name, _ = cmap_cfg.get(field, ("viridis", field))

        # ONE norm per column, pooled over the whole-tile rows.  The zoom
        # rows reuse it so a feature does not change colour when you zoom.
        pooled = np.concatenate(
            [by_level[lev][2].ravel() for lev in levels])
        norm = make_field_norm(
            pooled, cmap_name,
            log=field in log_scale_channels,
            diverging_cmaps=diverging_cmaps,
            percentiles=percentiles,
        )

        im_last, label = None, field
        for i in range(n_rows):
            lev = levels[i % n_lev]
            zoomed = zoom_rows and i >= n_lev
            x, y, arr = by_level[lev]
            if zoomed:
                x, y, arr = crop_lonlat_box(x, y, arr, *bounds)

            ax = axes[i, j]
            ax.set_facecolor(LAND_COLOR)   # NaNs are not drawn -> grey land
            im, label = plot_global_field(
                ax, x, y, arr, field, cmap_cfg,
                diverging_cmaps=diverging_cmaps,
                transform=None, add_coastline=False, norm=norm,
            )
            if im is not None:
                im_last = im
            if not zoomed and zoom_rows:
                _draw_box(ax, bounds)

            ax.set_xticks([])
            ax.set_yticks([])
            if i == 0:
                ax.set_title(field, fontsize=9)
            if j == 0:
                if row_labels is not None:
                    title = row_labels[i]
                else:
                    title = LEVEL_TITLES.get(lev, lev)
                    if zoomed:
                        title = f"{title}\n{2 * zoom_half_km:.0f} km zoom"
                ax.set_ylabel(title, fontsize=9)

        if im_last is not None:
            fig.colorbar(im_last, ax=axes[:, j].tolist(),
                         orientation="horizontal", fraction=0.03,
                         pad=0.02, label=label)

    if suptitle:
        fig.suptitle(suptitle, fontsize=12, y=1.005)
    return fig, axes


# ---------------------------------------------------------------------------
# Figure 2 -- PDFs
# ---------------------------------------------------------------------------

def depth_pdf_grid(chain, level_arrays, cmap_cfg, *,
                   levels=DEPTH_LEVELS,
                   log10_fields=frozenset(),
                   n_bins=N_BINS,
                   log_y=False,
                   row_labels=None,
                   suptitle=None):
    """Figure 2: PDFs, dependency chain across columns, levels down rows.

    Whole-tile values only.  Conventions are the surface ones
    (probability density; land and rim NaNs dropped; log10-x for the
    proportional-to-squared fields), with bins shared down a COLUMN so
    the change with depth is readable.

    Inputs
    ------
    chain : list[str]
        Field base names (the columns).
    level_arrays : dict[str, dict[str, tuple]]
        As for :func:`depth_map_grid`.
    cmap_cfg : dict[str, tuple[str, str]]
        Registry -- labels only here.
    levels : tuple[str]
        Depth levels, in row order.
    log10_fields : set[str]
        Fields binned in log10(x).
    n_bins : int
        Shared bin count per field.
    log_y : bool
        Logarithmic density axis.
    row_labels : sequence[str] or None
        Override the row labels; must match ``len(levels)``.
    suptitle : str or None
        Figure title.

    Outputs
    -------
    (fig, axes) : tuple

    Generated by LH and Claude.
    """
    n_rows, n_cols = len(levels), len(chain)
    fig, axes = plt.subplots(
        n_rows, n_cols, squeeze=False,
        figsize=(n_cols * PANEL_W, n_rows * 2.4),
    )

    for j, field in enumerate(chain):
        log10 = field in log10_fields
        _, label = cmap_cfg.get(field, ("viridis", field))
        if log10:
            label = f"log₁₀[{label}]"

        vals = [_clean_values(level_arrays[field][lev][2], log10=log10)
                for lev in levels]
        bins = shared_bins(vals, n_bins=n_bins)

        for i, v in enumerate(vals):
            pdf_panel(axes[i, j], v, bins,
                      label=label if i == n_rows - 1 else None,
                      log_y=log_y)
            if i == 0:
                axes[i, j].set_title(field, fontsize=9)
            if j == 0:
                lab = (row_labels[i] if row_labels is not None
                       else LEVEL_TITLES.get(levels[i], levels[i]))
                axes[i, j].set_ylabel(lab, fontsize=9)

    fig.text(0.005, 0.5, "probability density", rotation=90,
             va="center", fontsize=9)
    if suptitle:
        fig.suptitle(suptitle, fontsize=12, y=1.005)
    fig.tight_layout()
    return fig, axes


# ---------------------------------------------------------------------------
# Figure 3 -- depth profiles
# ---------------------------------------------------------------------------

def pick_profile_points(land_mask, *, n=N_PROFILE_POINTS, edge_margin=0,
                        inset_frac=0.15, seed=42, verbose=True):
    """Choose *n* well-separated ocean columns to draw profiles at.

    Seeded, so every field in a notebook profiles the SAME columns and
    the panels are comparable.

    Two constraints shape the choice.  Candidates are restricted to the
    tile's INTERIOR (``inset_frac`` in from each side), because a plain
    farthest-point spread pins every profile to a corner -- the least
    representative water on the tile, and the closest to the invalid
    rim.  Within that interior they are then spread greedily, because a
    plain random draw clusters and gives five profiles of the same
    water.

    Inputs
    ------
    land_mask : np.ndarray
        Boolean ``(j, i)``, True on land -- from :func:`tile_land_mask`.
    n : int
        How many locations.  Do not exceed ``len(LOCATION_COLORS)``.
    edge_margin : int
        Cells to stay clear of at the tile boundary.
    inset_frac : float
        Fraction of the tile to exclude on each side before choosing.
        0 uses the whole tile (and will hug the corners).
    seed : int
        RNG seed.
    verbose : bool
        Print the chosen indices.

    Outputs
    -------
    list[tuple[int, int]]
        ``(j, i)`` index pairs, one per location.

    Generated by LH and Claude.
    """
    if n > len(LOCATION_COLORS):
        raise ValueError(
            f"n={n} exceeds the {len(LOCATION_COLORS)} fixed location "
            "colours; categorical hues are never cycled."
        )

    n_j, n_i = land_mask.shape
    m = max(int(edge_margin), 1)
    ok = ~land_mask
    ok[:m, :] = ok[-m:, :] = False
    ok[:, :m] = ok[:, -m:] = False

    # Keep the profiles off the tile edge entirely.
    ij = int(n_j * inset_frac)
    ii = int(n_i * inset_frac)
    if ij and ii:
        inset = np.zeros_like(ok)
        inset[ij:n_j - ij, ii:n_i - ii] = True
        if (ok & inset).sum() >= n:
            ok = ok & inset

    js, is_ = np.nonzero(ok)
    if js.size < n:
        raise ValueError(
            f"only {js.size} usable ocean cells on this tile -- cannot "
            f"place {n} profiles."
        )

    rng = np.random.default_rng(seed)
    take = rng.choice(js.size, size=min(js.size, 4000), replace=False)
    cand = np.column_stack([js[take], is_[take]]).astype(float)

    # Greedy farthest-point: start at the candidate nearest the tile
    # centre, then repeatedly take whichever candidate is furthest from
    # everything chosen so far.
    centre = np.array([n_j / 2.0, n_i / 2.0])
    chosen = [int(np.argmin(((cand - centre) ** 2).sum(axis=1)))]
    while len(chosen) < n:
        d = np.min(
            [((cand - cand[c]) ** 2).sum(axis=1) for c in chosen], axis=0)
        chosen.append(int(np.argmax(d)))

    points = [(int(cand[c, 0]), int(cand[c, 1])) for c in chosen]
    if verbose:
        print(f"profiles at : {points}  (seed={seed})")
    return points


def sample_profiles(lazy_3d, ds_merge, points, *, verbose=True):
    """Pull full water-column profiles at *points*, in one ``dask.compute``.

    Only the 5 columns are read, so this is cheap next to the maps --
    a few hundred numbers per field.

    Inputs
    ------
    lazy_3d : dict[str, xr.DataArray]
        Base name -> lazy field on the tile.  Entries with no vertical
        dimension are skipped (they have no profile).
    ds_merge : xr.Dataset
        Merged tile dataset, for the depth coordinate.
    points : list[tuple[int, int]]
        ``(j, i)`` pairs from :func:`pick_profile_points`.
    verbose : bool
        Print which fields were sampled.

    Outputs
    -------
    (profiles, depth) : tuple
        ``profiles[base]`` is ``(n_k, n_points)``; ``depth`` is the
        ``(n_k,)`` depth coordinate in metres, POSITIVE DOWNWARD.

    Generated by LH and Claude.
    """
    import xarray as xr
    from dbof.preprocessing.vertical_helpers import (
        _get_depth_coord, _get_vertical_dim,
    )

    j_sel = xr.DataArray([p[0] for p in points], dims="pt")
    i_sel = xr.DataArray([p[1] for p in points], dims="pt")

    lazy_cols, zdims = {}, {}
    for base, field in lazy_3d.items():
        if not (set(field.dims) & _VERTICAL_DIMS):
            continue          # 2D field: nothing to profile
        col = field
        if "face" in col.dims:
            col = col.isel(face=0)
        zdims[base] = _get_vertical_dim(col)
        lazy_cols[base] = col.isel(j=j_sel, i=i_sel)

    keys = list(lazy_cols)
    values = dask.compute(*[lazy_cols[k] for k in keys], retries=10)
    profiles = {
        k: np.asarray(v.transpose(zdims[k], "pt").values)
        for k, v in zip(keys, values)
    }

    depth = np.asarray(_get_depth_coord(ds_merge).values, dtype=float)
    if verbose:
        print(f"profiled    : {sorted(profiles)} over {len(depth)} levels, "
              f"0 to {depth.max():.0f} m")
    return profiles, depth


def depth_profile_grid(chain, profiles, depth, cmap_cfg, *, points,
                       level_arrays, region, map_field=None,
                       map_level="sfc", mld_at_points=None,
                       diverging_cmaps=frozenset(),
                       log_scale_channels=frozenset(),
                       max_depth=None, suptitle=None):
    """Figure 3: where the profiles are, then one profile panel per column.

    Leftmost panel is the tile with a numbered, colour-coded X at each
    location.  Then one panel per 3D field in the chain: value across,
    depth down, **surface at the top and depth increasing downward**.
    Each location keeps its colour across every panel, and its number,
    so the identity is readable without relying on colour.

    Columns of the chain that are inherently 2D have no profile and are
    skipped; pass ``mld_at_points`` to draw the mixed-layer depth as a
    dashed horizontal line per location instead, which is usually the
    most useful thing on a profile plot.

    Inputs
    ------
    chain : list[str]
        Field base names in dependency order.
    profiles : dict[str, np.ndarray]
        ``(n_k, n_points)`` per field -- from :func:`sample_profiles`.
    depth : np.ndarray
        ``(n_k,)`` depth in metres, positive downward.
    cmap_cfg : dict[str, tuple[str, str]]
        Registry; used for the axis labels and the map panel.
    points : list[tuple[int, int]]
        ``(j, i)`` locations, same order as the profile columns.
    level_arrays : dict[str, dict[str, tuple]]
        For the locator map.
    region : str
        Region key (titles only).
    map_field : str or None
        Field for the locator map; defaults to the chain's last entry.
    map_level : str
        Depth level for the locator map.
    mld_at_points : sequence[float] or None
        MLD in metres at each location; drawn as dashed lines.
    diverging_cmaps, log_scale_channels : set[str]
        Passed through to the map panel.
    max_depth : float or None
        Clip the depth axis, e.g. 400.0 to zoom on the upper ocean.
    suptitle : str or None
        Figure title.

    Outputs
    -------
    (fig, axes) : tuple

    Generated by LH and Claude.
    """
    cols = [f for f in chain if f in profiles]
    skipped = [f for f in chain if f not in profiles]
    if not cols:
        raise ValueError(
            f"no column of {chain} was sampled for profiles.  Add the "
            f"lazy 3D fields to PROFILE_3D in the notebook -- a field "
            f"missing here is usually one that was only ever computed "
            f"at the four reduced levels, not kept in 3D."
        )

    colors = LOCATION_COLORS[:len(points)]
    n_cols = len(cols) + 1
    # The locator map gets a wider slot than the profile panels -- it is
    # carrying the geographic context for the whole figure.
    fig, axes = plt.subplots(
        1, n_cols, squeeze=False,
        figsize=(n_cols * PANEL_W, PANEL_H * 2.0),
        gridspec_kw={"width_ratios": [1.35] + [1.0] * len(cols)},
    )
    axes = axes[0]

    # --- locator map -------------------------------------------------
    # Deliberately the WHOLE tile, never a crop: the profiles are drawn
    # from anywhere on it, so the map has to show all of it or the
    # reader cannot tell what they are looking at.  The perimeter
    # outline and the lon/lat ticks make the extent explicit even where
    # land or the NaN'd rim eats into the edges.
    # The locator map shows the FINAL field of the chain -- the thing
    # the figure is about -- not whichever column happened to be
    # sampled last.  Fall back only if the final has no 2D map.
    mfield = map_field or (chain[-1] if chain[-1] in level_arrays
                           else cols[-1])
    x, y, arr = level_arrays[mfield][map_level]
    ax = axes[0]
    ax.set_facecolor(LAND_COLOR)
    plot_global_field(
        ax, x, y, arr, mfield, cmap_cfg,
        diverging_cmaps=diverging_cmaps, transform=None,
        add_coastline=False,
    )

    # Trace the tile's true boundary (it is a rotated quadrilateral in
    # lon/lat -- the face axes are not north/east aligned).
    edge_x = np.concatenate([x[0, :], x[:, -1], x[-1, ::-1], x[::-1, 0]])
    edge_y = np.concatenate([y[0, :], y[:, -1], y[-1, ::-1], y[::-1, 0]])
    ax.plot(edge_x, edge_y, color="0.35", linewidth=1.0, zorder=4)

    pad_x = 0.03 * (np.nanmax(x) - np.nanmin(x))
    pad_y = 0.03 * (np.nanmax(y) - np.nanmin(y))
    ax.set_xlim(np.nanmin(x) - pad_x, np.nanmax(x) + pad_x)
    ax.set_ylim(np.nanmin(y) - pad_y, np.nanmax(y) + pad_y)

    for n, ((pj, pi), c) in enumerate(zip(points, colors), start=1):
        # White halo so the marker reads on any colormap underneath.
        ax.plot(x[pj, pi], y[pj, pi], "x", color=c, markersize=11,
                markeredgewidth=3.4, zorder=5)
        ax.plot(x[pj, pi], y[pj, pi], "x", color="white", markersize=11,
                markeredgewidth=1.2, zorder=6)
        ax.annotate(
            str(n), (x[pj, pi], y[pj, pi]),
            textcoords="offset points", xytext=(7, 5),
            fontsize=9, fontweight="bold", color=c, zorder=7,
            path_effects=None,
            bbox={"boxstyle": "round,pad=0.12", "facecolor": "white",
                  "edgecolor": "none", "alpha": 0.75},
        )
    # Real lon/lat ticks, so "where are we" is answerable from the panel.
    ax.tick_params(labelsize=7)
    ax.xaxis.set_major_formatter(mticker.FuncFormatter(
        lambda v, _: f"{abs(v):.0f}°{'E' if v >= 0 else 'W'}"))
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(
        lambda v, _: f"{abs(v):.0f}°{'N' if v >= 0 else 'S'}"))
    ax.locator_params(nbins=4)
    n_j, n_i = arr.shape
    ax.set_title(
        f"profile locations — whole tile, {n_j}×{n_i}\n"
        f"({mfield}, {LEVEL_TITLES.get(map_level, map_level)})",
        fontsize=9)

    # --- one profile panel per 3D column -----------------------------
    ymax = max_depth if max_depth is not None else float(depth.max())
    for k, field in enumerate(cols, start=1):
        ax = axes[k]
        _, label = cmap_cfg.get(field, ("viridis", field))
        prof = profiles[field]

        for n, c in enumerate(colors):
            ax.plot(prof[:, n], depth, color=c, linewidth=2.0,
                    label=str(n + 1), zorder=3)
            if mld_at_points is not None:
                ax.axhline(mld_at_points[n], color=c, linewidth=1.0,
                           linestyle="--", alpha=0.55, zorder=2)

        # Surface at the top, depth increasing downward.
        ax.set_ylim(ymax, 0.0)
        ax.set_xlabel(label, fontsize=8)
        ax.tick_params(labelsize=7)
        ax.grid(alpha=0.25, linewidth=0.6)
        ax.set_title(field, fontsize=9)
        if k == 1:
            ax.set_ylabel("depth (m)", fontsize=9)
            ax.legend(title="location", fontsize=7, title_fontsize=7,
                      loc="lower right", framealpha=0.85)
        else:
            ax.set_yticklabels([])

    if skipped:
        fig.text(0.5, -0.055,
                 "no profile for: " + ", ".join(skipped)
                 + "  (inherently 2D, or not kept as a 3D field)",
                 ha="center", fontsize=8, style="italic", color="0.35")
    if mld_at_points is not None:
        fig.text(0.5, -0.02,
                 "dashed horizontal lines: mixed-layer depth at each "
                 "location", ha="center", fontsize=8, style="italic")
    if suptitle:
        fig.suptitle(suptitle, fontsize=12, y=1.04)
    fig.tight_layout()
    return fig, axes


# ---------------------------------------------------------------------------
# Vertical-stencil A/B  (the depth analogue of the surface sparkle test)
# ---------------------------------------------------------------------------

def vertical_stencil_ab(field, ds_merge):
    """Centred vs one-sided d/dz, separating curvature from cancellation.

    The production vertical derivative uses a CENTRED stencil at
    interior levels::

        (f[k+1] - f[k-1]) / (z[k+1] - z[k-1])

    which never reads level k.  Two DIFFERENT things follow from that,
    and conflating them is misleading:

    - **Curvature.**  Where the two one-sided slopes have the SAME sign
      but different magnitudes -- a monotone kink, e.g. the base of the
      mixed layer -- the centred form returns roughly their mean.  That
      is not an error: it is a correct second-order estimate at a place
      where the derivative genuinely is not well defined.  It drives
      ``dz_asym`` up to at most ~0.5 and no further.
    - **Cancellation.**  Where the two one-sided slopes have OPPOSITE
      signs -- level k is a vertical extremum, an inversion or a spike
      -- they partly annihilate and the centred form can collapse
      toward zero while both one-sided slopes are large.  THIS is the
      vertical analogue of the horizontal "sparkle"
      (``docs/Gradients.md``), and it is what ``dz_signflip`` marks.

    On even spacing ``dz_asym > 0.5`` is reachable ONLY through a sign
    flip, so the two diagnostics agree at the boundary; they are
    reported separately because the interesting quantity is the sign
    flip, and the asymmetry alone overstates the problem badly.

    Returns
    -------
    dict[str, xr.DataArray]
        - ``dz_centred``  -- what the pipeline computes;
        - ``dz_onesided`` -- the larger-magnitude one-sided slope
          straddling level k;
        - ``dz_asym``     -- ``1 - |centred| / |onesided|``.  Bounded by
          ~0.5 for same-sign slopes; mostly a CURVATURE map;
        - ``dz_signflip`` -- 1.0 where the two one-sided slopes have
          opposite signs, else 0.0.  **This is the artifact map.**

    Everything stays lazy.  Top and bottom levels are NaN: the centred
    stencil is undefined there and the production code falls back to a
    one-sided difference, which has no cancellation to measure.

    Inputs
    ------
    field : xr.DataArray
        Lazy 3D field on tracer levels (e.g. potential density, U).
    ds_merge : xr.Dataset
        Merged tile dataset, for the depth coordinate.

    Generated by LH and Claude.
    """
    import xarray as xr

    zdim = _get_vertical_dim(field)
    z = _get_depth_coord(ds_merge, zdim=zdim)

    f_below, f_above = field.shift({zdim: -1}), field.shift({zdim: 1})
    z_below, z_above = z.shift({zdim: -1}), z.shift({zdim: 1})

    # The production stencil: spans 2 levels, never reads level k.
    dz_centred = (f_below - f_above) / (z_below - z_above)

    # The two one-sided slopes that straddle level k.
    slope_above = (field - f_above) / (z - z_above)
    slope_below = (f_below - field) / (z_below - z)

    dz_onesided = xr.where(
        np.abs(slope_above) >= np.abs(slope_below), slope_above,
        slope_below)

    denom = np.abs(dz_onesided)
    dz_asym = xr.where(denom > 0, 1.0 - np.abs(dz_centred) / denom,
                       np.nan)

    # Opposite signs => level k is a vertical extremum => cancellation.
    prod = slope_above * slope_below
    dz_signflip = xr.where(np.isfinite(prod),
                           xr.where(prod < 0, 1.0, 0.0), np.nan)

    for nm, da in (("dz_centred", dz_centred), ("dz_onesided", dz_onesided),
                   ("dz_asym", dz_asym), ("dz_signflip", dz_signflip)):
        da.name = nm
    return {"dz_centred": dz_centred, "dz_onesided": dz_onesided,
            "dz_asym": dz_asym, "dz_signflip": dz_signflip}
