"""
depth_figures.py
----------------
Figures for the DEPTH field-validation notebooks, plus the small amount
of data shaping they need.

A note on the word "grid", because this repo uses it for two unrelated
things.  In THIS module a *grid* is the rows x columns array of panels
in a figure -- matplotlib's sense, and the same sense as the surface
module ``pipeline_grids.py``.  The model's Arakawa C-grid (tracer
centres, staggered faces, corners) is a different thing entirely and
lives in ``docs/Grid.md``, ``docs/Gradients.md`` and
``utils/native_gradient.py``.  Nothing here touches it.

Layout
------
The surface notebooks put a REGION on each row.  The depth notebooks
fix one tile and put a DEPTH LEVEL on each row instead.  Columns are
unchanged: the dependency chain, raw -> intermediate -> final.

:func:`depth_map_grid` is eight rows: the four levels over the whole
tile, then the same four zoomed to a 200 x 200 km box, whose position
is the crimson square on the whole-tile rows.

:func:`depth_pdf_grid` is four rows -- the whole tile at each level.
The zoom boxes are too small to make an honest histogram, so they are
deliberately absent.  Bins are shared down a COLUMN, so reading a
column top to bottom shows how the distribution changes with depth.

Data shaping
------------
:func:`compute_levels` reduces lazy 3D fields to the four levels, and
:func:`pack_tile_levels` turns computed channels into the
``{base: {level: (x, y, arr)}}`` mapping both figure functions consume
-- NaN'ing the tile's edge rim and masking land on the way.  Same job
``live_fields.py`` does for the surface notebooks.

Colour conventions (cmaps, labels, log scales, diverging centring, land
grey) come from the same registry and the same helpers the surface
figures use.  Nothing is hard-coded here.

Generated by LH and Claude.
"""

import dask
import matplotlib.pyplot as plt
import numpy as np

from dbof.plotting import regions as regions_mod
from dbof.plotting.global_maps import make_field_norm, plot_global_field
# ``_clean_values`` is private to pdfs.py but is the single definition of
# the NaN-drop / log10 convention; reusing it keeps the depth PDFs and
# the surface PDFs from drifting apart.
from dbof.plotting.pdfs import N_BINS, _clean_values, pdf_panel, shared_bins
from dbof.preprocessing.depth_strategies import apply_depth_strategies
from dbof.tiles.field_registry import TILE_PROPERTIES

PANEL_W = 4.2
PANEL_H = 3.2
LAND_COLOR = "0.85"
BOX_KW = {"color": "crimson", "linewidth": 1.4}

#: The four depth levels, in the order the figures use as rows.
DEPTH_LEVELS = ("sfc", "z25m", "mld", "mld_mean")

#: Row titles.
LEVEL_TITLES = {
    "sfc":      "surface (k=0)",
    "z25m":     "25 m",
    "mld":      "at MLD",
    "mld_mean": "MLD mean",
}

#: Default half-width of the zoom box, in km (so a 200 x 200 km square).
ZOOM_HALF_KM = 100.0

#: Vertical dimension names, for spotting an inherently 2D field.
_VERTICAL_DIMS = {"k", "k_l", "k_u", "k_p1", "Z", "Zl", "Zu", "Zp1"}


# ---------------------------------------------------------------------------
# Picking the tile
# ---------------------------------------------------------------------------

def region_anchor(region):
    """Return the ``(lon, lat)`` a region's tile and zoom are centred on.

    A tile SAMPLES a region, it does not cover it, so a depth notebook
    needs a point rather than a box.  We reuse the ``zoom`` anchors
    already pinned in ``regions.py`` -- the same points the surface
    notebooks zoom into -- so surface and depth look at the same water.

    Inputs
    ------
    region : str
        Key in ``regions.REGIONS`` carrying a ``zoom`` anchor.

    Outputs
    -------
    (lon, lat) : tuple[float, float]

    Raises
    ------
    ValueError
        If the region has no anchor (``global``, ``kerguelen``).

    Generated by LH and Claude.
    """
    anchor = regions_mod.REGIONS.get(region, {}).get("zoom")
    if anchor is None:
        have = sorted(k for k, v in regions_mod.REGIONS.items()
                      if v.get("zoom"))
        raise ValueError(
            f"region '{region}' has no 'zoom' anchor in regions.py, so "
            f"there is no point to centre a tile on.  Regions with one: "
            f"{have}"
        )
    return float(anchor[0]), float(anchor[1])


def edge_margin_for(bases):
    """Widest invalid rim among these fields, from the tile registry.

    A tile's xgcm grid has no face connections, so fields with a
    horizontal stencil are wrong near the boundary.  ``field_registry``
    already records how many cells that is per field (0 vertical-only,
    1 staggered interpolation, 3 gradient / Jacobian chains); this just
    takes the worst case over the chain so one rim covers the figure.

    Names the registry does not know (live intermediates such as
    ``rho_theta``) are skipped -- pass an explicit margin if one of them
    is the widest thing in your chain.

    Inputs
    ------
    bases : iterable of str
        Field base names.

    Outputs
    -------
    int
        Rim width in cells; 0 if none of the names is in the registry.

    Generated by LH and Claude.
    """
    known = [TILE_PROPERTIES[b].edge_margin for b in bases
             if b in TILE_PROPERTIES]
    return max(known) if known else 0


# ---------------------------------------------------------------------------
# Shaping the data
# ---------------------------------------------------------------------------

def tile_coords(ds_grid):
    """Return the tile's 2D ``(XC, YC)`` as plain numpy arrays.

    Inputs
    ------
    ds_grid : xr.Dataset
        Tile grid from ``tile_utils._load_grid_for_tile``.

    Outputs
    -------
    (XC, YC) : tuple[np.ndarray, np.ndarray]
        Longitude / latitude on dims ``(j, i)``, face squeezed out.

    Generated by LH and Claude.
    """
    return (ds_grid["XC"].isel(face=0).values,
            ds_grid["YC"].isel(face=0).values)


def tile_land_mask(ds_grid):
    """Boolean land mask (True = land) from the tile's surface ``hFacC``.

    The DEPTH grid store's ``hFacC`` is already collapsed to ``k=0``, and
    the production depth pipeline masks with that same surface mask, so
    this matches what the global stores contain.

    Inputs
    ------
    ds_grid : xr.Dataset
        Tile grid from ``tile_utils._load_grid_for_tile``.

    Outputs
    -------
    np.ndarray
        Boolean ``(j, i)`` array, True where the cell is land.

    Generated by LH and Claude.
    """
    hfac = ds_grid["hFacC"]
    if "k" in hfac.dims:
        hfac = hfac.isel(k=0)
    return (hfac.isel(face=0).values == 0)


def reduce_to_levels(field3d, base, ds_merge, mld, levels=DEPTH_LEVELS):
    """Reduce one lazy 3D field to the requested depth levels (still lazy).

    Fields with no vertical dimension (Eta, coriolis_f, MLD itself) pass
    straight through under ``{base}_2d``; :func:`pack_tile_levels`
    broadcasts those down the rows later.

    Inputs
    ------
    field3d : xr.DataArray
        Lazy field on the tile.
    base : str
        Channel base name, e.g. ``"rho_theta"``.
    ds_merge : xr.Dataset
        Merged tile dataset.
    mld : xr.DataArray or None
        Lazy MLD; required for the ``mld`` / ``mld_mean`` levels.
    levels : tuple[str]
        Subset of :data:`DEPTH_LEVELS`.

    Outputs
    -------
    dict[str, xr.DataArray]
        Lazy arrays keyed ``{base}_{level}`` (or ``{base}_2d``).

    Generated by LH and Claude.
    """
    if not (set(field3d.dims) & _VERTICAL_DIMS):
        return {f"{base}_2d": field3d}

    return apply_depth_strategies(
        field3d, base, ds_merge, mld=mld,
        requested={f"{base}_{lev}" for lev in levels},
    )


def compute_levels(lazy_3d, ds_merge, *, mld=None, levels=DEPTH_LEVELS,
                   verbose=True):
    """Reduce a dict of lazy fields to levels, in one ``dask.compute``.

    Use this for the chain's raw inputs and live intermediates (Theta,
    Salt, rho_theta, db_dx, ...) -- the things the global stores never
    keep but the dependency figures need.

    Inputs
    ------
    lazy_3d : dict[str, xr.DataArray]
        Base name -> lazy field on the tile.
    ds_merge : xr.Dataset
        Merged tile dataset.
    mld : xr.DataArray or None
        Lazy MLD.  Required if ``levels`` includes ``mld`` / ``mld_mean``.
    levels : tuple[str]
        Depth levels to produce.
    verbose : bool
        Print the channels produced.

    Outputs
    -------
    dict[str, xr.DataArray]
        Materialised, keyed ``{base}_{level}`` / ``{base}_2d``.

    Generated by LH and Claude.
    """
    lazy_out = {}
    for base, field in lazy_3d.items():
        lazy_out.update(
            reduce_to_levels(field, base, ds_merge, mld, levels=levels))

    keys = list(lazy_out)
    values = dask.compute(*[lazy_out[k] for k in keys], retries=10)
    out = dict(zip(keys, values))
    if verbose:
        print(f"live fields : {sorted(out)}")
    return out


def _as_2d(value):
    """Squeeze a computed channel to a 2D ``(j, i)`` numpy array.

    Inputs
    ------
    value : xr.DataArray or np.ndarray
        A computed channel; may still carry a size-1 ``face`` dim.

    Outputs
    -------
    np.ndarray

    Generated by LH and Claude.
    """
    return np.squeeze(np.asarray(getattr(value, "values", value)))


def _split_channel(name, levels):
    """Split ``"N2_mld_mean"`` into ``("N2", "mld_mean")``.

    Inputs
    ------
    name : str
        Channel name.
    levels : tuple[str]
        Level suffixes to look for.

    Outputs
    -------
    (base, level) : tuple[str, str or None]
        ``level`` is None when there is no recognised suffix.

    Generated by LH and Claude.
    """
    # Longest suffix first, so "mld_mean" wins over "mld".
    for lev in sorted(set(levels) | {"2d", "sfc"}, key=len, reverse=True):
        if name.endswith("_" + lev):
            return name[: -len(lev) - 1], lev
    return name, None


def _nan_rim(arr, margin):
    """NaN a border of *margin* cells on all four sides.

    Same convention as ``tile_utils.compute_tile_property``: the array
    keeps its full 720 x 720 shape and the unusable cells become NaN,
    rather than being trimmed away.

    Inputs
    ------
    arr : np.ndarray
        2D field (modified on a copy).
    margin : int
        Rim width in cells; 0 is a no-op.

    Outputs
    -------
    np.ndarray

    Generated by LH and Claude.
    """
    if margin <= 0:
        return arr
    out = arr.copy()
    out[:margin, :] = np.nan
    out[-margin:, :] = np.nan
    out[:, :margin] = np.nan
    out[:, -margin:] = np.nan
    return out


def pack_tile_levels(channels, XC, YC, *, edge_margin=0, land_mask=None,
                     levels=DEPTH_LEVELS, verbose=True):
    """Turn computed channels into the ``{base: {level: (x, y, arr)}}`` map.

    This is the structure both figure functions consume.  On the way it
    does the two clean-up steps every tile result needs:

    - **NaNs the edge rim**, where the local (no face connections) grid
      made horizontal stencils invalid;
    - **masks land** with the surface ``hFacC``, matching production.

    Channels with no depth suffix, and bases that only ever produce
    ``_sfc`` (Eta, gradeta2, ug, vg), are BROADCAST down the rows so the
    dependency chain still reads left-to-right at every level.  Which
    ones were broadcast is printed, and belongs in the figure caption.

    Inputs
    ------
    channels : dict[str, xr.DataArray | np.ndarray]
        Computed channels, keyed ``{base}_{level}`` / ``{base}_2d`` /
        bare (e.g. ``"mixed_layer_depth"``).
    XC, YC : np.ndarray
        Tile coordinates from :func:`tile_coords`.
    edge_margin : int
        Rim width to NaN; see :func:`edge_margin_for`.
    land_mask : np.ndarray or None
        Boolean ``(j, i)`` land mask from :func:`tile_land_mask`.
        ``None`` skips masking.
    levels : tuple[str]
        Row order.
    verbose : bool
        Print the shape and which bases were broadcast.

    Outputs
    -------
    dict[str, dict[str, tuple]]
        ``out[base][level] = (x, y, arr)``.

    Generated by LH and Claude.
    """
    def _finish(value):
        arr = _nan_rim(_as_2d(value).astype("float32"), edge_margin)
        if land_mask is not None:
            arr = np.where(land_mask, np.nan, arr)
        return (XC, YC, arr)

    grouped = {}
    for name, value in channels.items():
        base, level = _split_channel(name, levels)
        grouped.setdefault(base, {})[level or "2d"] = _finish(value)

    out, broadcast = {}, []
    for base, by_level in grouped.items():
        missing = [lev for lev in levels if lev not in by_level]
        if missing:
            # A 2D field (or a surface-only base): repeat it down the rows.
            source = by_level.get("2d") or by_level.get("sfc")
            if source is None:
                raise KeyError(
                    f"'{base}' has levels {sorted(by_level)} but none of "
                    f"{missing} and nothing to broadcast from."
                )
            broadcast.append(base)
            by_level = {lev: by_level.get(lev, source) for lev in levels}
        out[base] = {lev: by_level[lev] for lev in levels}

    if verbose:
        n_j, n_i = out[next(iter(out))][levels[0]][2].shape
        print(f"packed      : {len(out)} fields on a {n_j} x {n_i} tile, "
              f"{edge_margin}-cell rim NaN'd")
        if broadcast:
            print(f"broadcast   : {sorted(broadcast)} are 2D / surface-only "
                  "-- the same map repeats down the depth rows")
    return out


# ---------------------------------------------------------------------------
# Cropping to the zoom box
# ---------------------------------------------------------------------------

def crop_lonlat_box(x, y, arr, west, east, south, north):
    """Crop a tile to the tightest window covering a lon/lat box.

    Unlike ``regions.crop_zoom`` this makes no assumption that array
    rows are lines of constant latitude.  A tile's face-local axes can
    be rotated or mirrored relative to geographic north, so we build a
    boolean mask of cells inside the box and take its bounding box in
    ARRAY space.

    Inputs
    ------
    x, y : np.ndarray
        2D longitude / latitude of the tile.
    arr : np.ndarray
        2D field on the same mesh.
    west, east, south, north : float
        Box edges in degrees.

    Outputs
    -------
    (xz, yz, sub) : tuple[np.ndarray, np.ndarray, np.ndarray]

    Raises
    ------
    ValueError
        If no cell falls inside the box.

    Generated by LH and Claude.
    """
    # Wrap longitudes onto the box so the dateline is not a special case.
    dlon = (x - west + 180.0) % 360.0 - 180.0
    span = (east - west + 180.0) % 360.0 - 180.0
    if span <= 0:
        span += 360.0
    inside = (dlon >= 0) & (dlon <= span) & (y >= south) & (y <= north)

    if not inside.any():
        raise ValueError(
            f"no tile cells inside lon [{west}, {east}], "
            f"lat [{south}, {north}] -- is the zoom anchor on this tile?"
        )

    rows = np.where(inside.any(axis=1))[0]
    cols = np.where(inside.any(axis=0))[0]
    jsl = slice(int(rows[0]), int(rows[-1]) + 1)
    isl = slice(int(cols[0]), int(cols[-1]) + 1)
    return x[jsl, isl], y[jsl, isl], arr[jsl, isl]


def zoom_bounds(region, *, half_km=ZOOM_HALF_KM):
    """Return ``(west, east, south, north)`` of a region's zoom square.

    Thin wrapper over ``regions.zoom_box`` so this module has one place
    that knows the zoom convention.  The square is centred on the same
    anchor :func:`region_anchor` picks the tile with, so it always falls
    on the tile -- though it can sit near an edge, in which case the
    crop is clipped to whatever the tile holds.

    Inputs
    ------
    region : str
        Region key with a ``zoom`` anchor.
    half_km : float
        Half-width of the square, in km.

    Outputs
    -------
    tuple[float, float, float, float]

    Generated by LH and Claude.
    """
    (west, east), (south, north) = regions_mod.zoom_box(
        region, half_km=half_km)
    return west, east, south, north


def _draw_box(ax, bounds):
    """Draw the crimson zoom locator square on a lon/lat axis.

    Inputs
    ------
    ax : matplotlib axis
    bounds : tuple[float, float, float, float]
        ``(west, east, south, north)``.

    Outputs
    -------
    None (draws on ``ax``).

    Generated by LH and Claude.
    """
    w, e, s, n = bounds
    ax.plot([w, e, e, w, w], [s, s, n, n, s], **BOX_KW)


# ---------------------------------------------------------------------------
# Figure 1 -- maps
# ---------------------------------------------------------------------------

def depth_map_grid(chain, level_arrays, cmap_cfg, *, region,
                   levels=DEPTH_LEVELS,
                   diverging_cmaps=frozenset(),
                   log_scale_channels=frozenset(),
                   percentiles=(1, 99),
                   zoom_rows=True,
                   zoom_half_km=ZOOM_HALF_KM,
                   suptitle=None):
    """Figure 1: dependency chain across columns, depth levels down rows.

    Rows 1..N are the levels over the whole tile; rows N+1..2N repeat
    them zoomed to a ``2 * zoom_half_km`` square, whose position is
    drawn as a crimson box on the whole-tile rows.

    One colour scale per COLUMN, built from the pooled whole-tile values
    of every level and reused by that column's zoom rows -- so both the
    depth rows and the zoom rows are directly comparable.

    Inputs
    ------
    chain : list[str]
        Field base names in dependency order (the columns).  Every entry
        must be a key of ``level_arrays``.
    level_arrays : dict[str, dict[str, tuple]]
        ``level_arrays[base][level] = (x, y, arr)`` -- from
        :func:`pack_tile_levels`.
    cmap_cfg : dict[str, tuple[str, str]]
        ``field_cmaps.load_field_cmaps()`` registry: name -> (cmap, label).
    region : str
        Region key, used for the zoom anchor.
    levels : tuple[str]
        Depth levels, in row order.
    diverging_cmaps : set[str]
        Colormap NAMES to centre at zero.
    log_scale_channels : set[str]
        Field names drawn on a log colour scale.
    percentiles : tuple[float, float]
        Colour-limit percentiles.
    zoom_rows : bool
        Add the zoomed rows.  Turn off for a quick 4-row look.
    zoom_half_km : float
        Half-width of the zoom square, in km.
    suptitle : str or None
        Figure title.

    Outputs
    -------
    (fig, axes) : tuple
        ``axes`` has shape ``(n_rows, len(chain))``.

    Generated by LH and Claude.
    """
    n_lev = len(levels)
    n_rows = n_lev * 2 if zoom_rows else n_lev
    n_cols = len(chain)

    bounds = zoom_bounds(region, half_km=zoom_half_km) if zoom_rows else None

    fig, axes = plt.subplots(
        n_rows, n_cols, squeeze=False,
        figsize=(n_cols * PANEL_W, n_rows * PANEL_H),
    )

    for j, field in enumerate(chain):
        by_level = level_arrays[field]
        cmap_name, _ = cmap_cfg.get(field, ("viridis", field))

        # ONE norm per column, pooled over the whole-tile rows.  The zoom
        # rows reuse it so a feature does not change colour when you zoom.
        pooled = np.concatenate(
            [by_level[lev][2].ravel() for lev in levels])
        norm = make_field_norm(
            pooled, cmap_name,
            log=field in log_scale_channels,
            diverging_cmaps=diverging_cmaps,
            percentiles=percentiles,
        )

        im_last, label = None, field
        for i in range(n_rows):
            lev = levels[i % n_lev]
            zoomed = zoom_rows and i >= n_lev
            x, y, arr = by_level[lev]
            if zoomed:
                x, y, arr = crop_lonlat_box(x, y, arr, *bounds)

            ax = axes[i, j]
            ax.set_facecolor(LAND_COLOR)   # NaNs are not drawn -> grey land
            im, label = plot_global_field(
                ax, x, y, arr, field, cmap_cfg,
                diverging_cmaps=diverging_cmaps,
                transform=None, add_coastline=False, norm=norm,
            )
            if im is not None:
                im_last = im
            if not zoomed and zoom_rows:
                _draw_box(ax, bounds)

            ax.set_xticks([])
            ax.set_yticks([])
            if i == 0:
                ax.set_title(field, fontsize=9)
            if j == 0:
                title = LEVEL_TITLES.get(lev, lev)
                if zoomed:
                    title = f"{title}\n{2 * zoom_half_km:.0f} km zoom"
                ax.set_ylabel(title, fontsize=9)

        if im_last is not None:
            fig.colorbar(im_last, ax=axes[:, j].tolist(),
                         orientation="horizontal", fraction=0.03,
                         pad=0.02, label=label)

    if suptitle:
        fig.suptitle(suptitle, fontsize=12, y=1.005)
    return fig, axes


# ---------------------------------------------------------------------------
# Figure 2 -- PDFs
# ---------------------------------------------------------------------------

def depth_pdf_grid(chain, level_arrays, cmap_cfg, *,
                   levels=DEPTH_LEVELS,
                   log10_fields=frozenset(),
                   n_bins=N_BINS,
                   log_y=False,
                   suptitle=None):
    """Figure 2: PDFs, dependency chain across columns, levels down rows.

    Whole-tile values only.  Conventions are the surface ones
    (probability density; land and rim NaNs dropped; log10-x for the
    proportional-to-squared fields), with bins shared down a COLUMN so
    the change with depth is readable.

    Inputs
    ------
    chain : list[str]
        Field base names (the columns).
    level_arrays : dict[str, dict[str, tuple]]
        As for :func:`depth_map_grid`.
    cmap_cfg : dict[str, tuple[str, str]]
        Registry -- labels only here.
    levels : tuple[str]
        Depth levels, in row order.
    log10_fields : set[str]
        Fields binned in log10(x).
    n_bins : int
        Shared bin count per field.
    log_y : bool
        Logarithmic density axis.
    suptitle : str or None
        Figure title.

    Outputs
    -------
    (fig, axes) : tuple

    Generated by LH and Claude.
    """
    n_rows, n_cols = len(levels), len(chain)
    fig, axes = plt.subplots(
        n_rows, n_cols, squeeze=False,
        figsize=(n_cols * PANEL_W, n_rows * 2.4),
    )

    for j, field in enumerate(chain):
        log10 = field in log10_fields
        _, label = cmap_cfg.get(field, ("viridis", field))
        if log10:
            label = f"log₁₀[{label}]"

        vals = [_clean_values(level_arrays[field][lev][2], log10=log10)
                for lev in levels]
        bins = shared_bins(vals, n_bins=n_bins)

        for i, v in enumerate(vals):
            pdf_panel(axes[i, j], v, bins,
                      label=label if i == n_rows - 1 else None,
                      log_y=log_y)
            if i == 0:
                axes[i, j].set_title(field, fontsize=9)
            if j == 0:
                axes[i, j].set_ylabel(
                    LEVEL_TITLES.get(levels[i], levels[i]), fontsize=9)

    fig.text(0.005, 0.5, "probability density", rotation=90,
             va="center", fontsize=9)
    if suptitle:
        fig.suptitle(suptitle, fontsize=12, y=1.005)
    fig.tight_layout()
    return fig, axes
