"""
pipeline_grids.py
-----------------
Shared rows × columns figure scaffold for the field-validation
notebooks (plan: prompts/field_validation.md, §5 and §7).

Layout convention (both Figure 1 / maps and Figure 2 / PDFs):

- columns = a field's dependency chain, in raw → intermediate → final
  order (option (a): each field repeats its full chain);
- rows    = validation domains (``dbof.plotting.regions.REGION_ORDER``:
  global, Gulf Stream, SO Atlantic sector, eastern tropical Pacific).

Colormaps / labels / units resolve through ``field_cmaps.yaml`` and
norms through ``global_maps.make_field_norm`` — nothing here hard-codes
colors or labels.  The panel renderer is a callback so the same
scaffold serves maps (``map_panel``) and PDFs (``dbof.plotting.pdfs``).
"""

import numpy as np
import matplotlib.pyplot as plt
import cartopy.crs as ccrs

from dbof.plotting.global_maps import make_field_norm, plot_global_field
from dbof.plotting import regions as regions_mod

# Default panel size (inches); rows scale with region aspect.
PANEL_W = 5.2
PANEL_H = 3.4

# Land / no-data background colour on map panels (NaN pixels are not
# drawn by pcolormesh, so the axis facecolor shows through as land).
LAND_COLOR = "0.85"

# Region-extent boxes drawn on the global row.
BOX_KW = {"color": "crimson", "linewidth": 1.2}


def mask_wrap_cells(x, y, arr, *, lon_jump=180.0, lat_jump=30.0):
    """Mask cells whose pcolormesh quad would smear across the map.

    Generated by LH and Claude.

    On the stitched rect grid, longitudes jump by ~360 deg at the seam
    and both coordinates jump arbitrarily in the Arctic-cap rows.  With
    ``shading='nearest'`` cartopy does not always wrap/mask such quads,
    so they stretch horizontally across the projection and paint over
    land.  NaN-ing every cell adjacent to a coordinate jump prevents
    those quads from being drawn at all (the land facecolor shows
    through instead).

    Inputs
    ------
    x, y : np.ndarray
        2D lon/lat coordinate arrays of the (downsampled) global grid.
    arr : np.ndarray
        2D field aligned with ``x``/``y`` (not modified in place).
    lon_jump, lat_jump : float
        Neighbour-to-neighbour jumps (degrees) treated as artifacts.

    Outputs
    -------
    np.ndarray
        Copy of ``arr`` with artifact cells set to NaN.
    """
    bad = np.zeros(arr.shape, dtype=bool)
    for axis in (0, 1):
        jump = ((np.abs(np.diff(x, axis=axis)) > lon_jump)
                | (np.abs(np.diff(y, axis=axis)) > lat_jump))
        if axis == 0:
            bad[:-1, :] |= jump
            bad[1:, :] |= jump
        else:
            bad[:, :-1] |= jump
            bad[:, 1:] |= jump
    out = np.array(arr, dtype=float, copy=True)
    out[bad] = np.nan
    return out


def make_grid(n_rows, n_cols, row_titles, col_titles, *,
              panel_w=PANEL_W, panel_h=PANEL_H):
    """Create the shared rows × columns scaffold with titled margins.

    Generated by LH and Claude.

    Inputs
    ------
    n_rows, n_cols : int
        Grid dimensions (rows = domains, cols = dependency chain).
    row_titles, col_titles : list[str]
        Labels written on the left margin / top row of the grid.
    panel_w, panel_h : float
        Per-panel size in inches.

    Outputs
    -------
    (fig, axes) : (matplotlib.figure.Figure, np.ndarray)
        ``axes`` always has shape (n_rows, n_cols).
    """
    fig, axes = plt.subplots(
        n_rows, n_cols,
        figsize=(n_cols * panel_w, n_rows * panel_h),
        squeeze=False,
    )
    for j, title in enumerate(col_titles):
        axes[0, j].set_title(title, fontsize=9)
    for i, title in enumerate(row_titles):
        axes[i, 0].set_ylabel(title, fontsize=9)
    return fig, axes


def pipeline_map_grid(chain, region_arrays, cmap_cfg, *,
                      diverging_cmaps=frozenset(),
                      log_scale_channels=frozenset(),
                      region_order=None,
                      percentiles=(1, 99),
                      coastlines=True,
                      region_boxes=True,
                      zoom_final=True,
                      zoom_half_km=100.0,
                      suptitle=None):
    """Figure 1 of a field's validation section: the map grid.

    Generated by LH and Claude.

    Inputs
    ------
    chain : list[str]
        Channel/intermediate names in dependency order (the columns).
    region_arrays : dict[str, dict[str, tuple]]
        ``region_arrays[field][region] = (x, y, arr)`` as produced by
        ``regions.select_all_regions`` — every field in ``chain`` must
        have every region in ``region_order``.
    cmap_cfg : dict[str, tuple[str, str]]
        Registry from ``field_cmaps.load_field_cmaps()``.
    diverging_cmaps : set[str]
        Colormap names centred at zero (from the same registry).
    log_scale_channels : set[str]
        Channels drawn with a logarithmic colour scale.
    region_order : list[str] or None
        Row order; defaults to ``regions.REGION_ORDER``.
    percentiles : tuple[float, float]
        Colour-limit percentiles per panel.
    coastlines : bool
        Draw coastlines on the global (GeoAxes) row.  Requires the
        cartopy Natural Earth cache or network access.
    region_boxes : bool
        Draw the regional bounding boxes (crimson outlines) on every
        global-row panel, so Rows B–D locate themselves on Row A.
    zoom_final : bool
        Append one extra column: the FINAL field (last chain element)
        cropped to a 2·zoom_half_km square box centred on each
        region's ``zoom`` anchor (full-resolution structure — the
        regional panels alias submesoscale texture into 'sparkle' at
        figure size).  Global row is left blank in this column; the
        zoom box is outlined on each regional final-field panel.
    zoom_half_km : float
        Half-width of the zoom box in km (100 -> 200x200 km).
    suptitle : str or None
        Overall figure title.

    Outputs
    -------
    (fig, axes) : the populated scaffold; ONE norm and one horizontal
        colorbar per column, shared across all rows (regions are
        directly comparable within a column), labelled with the field's
        physical label from the registry.

    Notes
    -----
    The GLOBAL row is drawn on a cartopy GeoAxes (Robinson) with
    ``transform=PlateCarree()``, matching the proven pattern in
    ``notebooks_global/assess_generate_global_script.ipynb``.  The
    stitched rect XC/YC are non-monotonic at the longitude seam and in
    the Arctic-cap rows, so a plain-axes pcolormesh of the full grid
    smears quads across the panel; cartopy's transform handles the
    wrapping correctly.  Regional boxes are monotonic in lon/lat and
    stay on plain axes.
    """
    region_order = region_order or regions_mod.REGION_ORDER
    row_titles = [regions_mod.REGIONS[r]["short"] for r in region_order]
    n_rows = len(region_order)
    n_cols = len(chain) + (1 if zoom_final else 0)

    # Build the grid by hand: cartopy projection for global rows only.
    fig = plt.figure(figsize=(n_cols * PANEL_W, n_rows * PANEL_H))
    gs = fig.add_gridspec(n_rows, n_cols)
    axes = np.empty((n_rows, n_cols), dtype=object)
    is_global = [regions_mod.REGIONS[r]["lon"] is None
                 for r in region_order]
    for i in range(n_rows):
        for j in range(n_cols):
            if is_global[i]:
                axes[i, j] = fig.add_subplot(
                    gs[i, j], projection=ccrs.Robinson())
            else:
                axes[i, j] = fig.add_subplot(gs[i, j])

    for j, field in enumerate(chain):
        axes[0, j].set_title(chain[j], fontsize=9)
        cmap_name, label = cmap_cfg.get(field, ("viridis", field))

        # One norm per column: percentile limits over the pooled finite
        # values of ALL regions, so rows share a colour scale.
        pooled = np.concatenate([
            region_arrays[field][r][2].ravel() for r in region_order
        ])
        norm = make_field_norm(pooled, cmap_name,
                               log=field in log_scale_channels,
                               diverging_cmaps=diverging_cmaps,
                               percentiles=percentiles)

        im_last = None
        for i, region in enumerate(region_order):
            x, y, arr = region_arrays[field][region]
            if is_global[i]:
                # Drop seam/Arctic-scramble quads that would smear
                # across the projection and paint over land.
                arr = mask_wrap_cells(x, y, arr)
            # NaN (land / halo) pixels are not drawn: a gray facecolor
            # renders them as a uniform land mask on every panel.
            axes[i, j].set_facecolor(LAND_COLOR)
            im, label = plot_global_field(
                axes[i, j], x, y, arr, field, cmap_cfg,
                diverging_cmaps=diverging_cmaps,
                # Global row: geo projection handles the seam/Arctic
                # rows; regional rows are monotonic plain axes.
                transform=ccrs.PlateCarree() if is_global[i] else None,
                add_coastline=is_global[i] and coastlines,
                coastline_kw={"linewidth": 0.4, "edgecolor": "k"},
                norm=norm,
            )
            if is_global[i] and region_boxes:
                # Locate Rows B-D on the global panel.
                for other in region_order:
                    if regions_mod.REGIONS[other]["lon"] is None:
                        continue
                    lons, lats = regions_mod.region_outline(other)
                    axes[i, j].plot(lons, lats,
                                    transform=ccrs.PlateCarree(),
                                    **BOX_KW)
            if not is_global[i]:
                axes[i, j].set_xticks([])
                axes[i, j].set_yticks([])
            if j == 0:
                # ax.text works on both plain and Geo axes (set_ylabel
                # does not render on GeoAxes).
                axes[i, j].text(-0.08, 0.5, row_titles[i], fontsize=9,
                                rotation=90, va="center", ha="right",
                                transform=axes[i, j].transAxes)
            if im is not None:
                im_last = im
        if im_last is not None:
            # One shared colorbar per column, labelled with units.
            fig.colorbar(im_last, ax=axes[:, j].tolist(),
                         orientation="horizontal", fraction=0.03,
                         pad=0.02, label=label)

    if zoom_final:
        # Extra column: the FINAL field at full resolution in a
        # 2*zoom_half_km square box (regional panels alias the
        # submesoscale texture; this shows the real structure).
        jz = len(chain)
        final = chain[-1]
        cmap_name, _ = cmap_cfg.get(final, ("viridis", final))
        pooled = np.concatenate([
            region_arrays[final][r][2].ravel() for r in region_order
        ])
        # Same norm as the final column: zoom is directly comparable.
        norm_f = make_field_norm(pooled, cmap_name,
                                 log=final in log_scale_channels,
                                 diverging_cmaps=diverging_cmaps,
                                 percentiles=percentiles)
        axes[0, jz].set_title(
            f"{final} ({2 * zoom_half_km:.0f} km zoom)", fontsize=9)
        for i, region in enumerate(region_order):
            ax = axes[i, jz]
            if (is_global[i]
                    or regions_mod.REGIONS[region].get("zoom") is None):
                ax.set_axis_off()   # no zoom on the global row
                continue
            x, y, arr = region_arrays[final][region]
            xz, yz, sub = regions_mod.crop_zoom(
                x, y, arr, region, half_km=zoom_half_km)
            ax.set_facecolor(LAND_COLOR)
            plot_global_field(ax, xz, yz, sub, final, cmap_cfg,
                              diverging_cmaps=diverging_cmaps,
                              add_coastline=False, norm=norm_f)
            ax.set_xticks([])
            ax.set_yticks([])
            # Locate the zoom box on the regional final-field panel.
            (w, e), (s, n) = regions_mod.zoom_box(
                region, half_km=zoom_half_km)
            axes[i, len(chain) - 1].plot(
                [w, e, e, w, w], [s, s, n, n, s], **BOX_KW)

    if suptitle:
        fig.suptitle(suptitle, fontsize=12, y=1.005)
    return fig, axes
