"""
regions.py
----------
Named validation-region registry for the rectangular (stitched) LLC4320
lat/lon grid, plus selection helpers.

Single source of truth for the four standard domains used by every
field-validation notebook (plan: prompts/field_validation.md, §5–6):

- ``global``       — whole rect grid, downsampled ``[::12, ::12]``
- ``gulf_stream``  — Western North Atlantic, 80–40°W, 25–45°N
- ``so_atlantic``  — Atlantic sector, Southern Ocean, 20°W–20°E, 65–40°S
- ``eq_pacific``   — eastern tropical Pacific, 140–90°W, 5°S–5°N

The rect grid is the xmitgcm faces-to-latlon stitching: below the Arctic
cap, rows share (approximately) constant latitude and columns constant
longitude, so bounding boxes reduce to row/column index ranges.  All
four standard regions lie below the Arctic cap, where this holds.
"""

import numpy as np

# Row A of every validation figure: global downsampling stride.
GLOBAL_DOWNSAMPLE = 12

#: name -> dict(lon=(west, east), lat=(south, north), title=str).
#: ``lon``/``lat`` of None marks the (downsampled) global domain.
REGIONS = {
    "global": {
        "lon": None,
        "lat": None,
        "title": "Global (12x downsampled)",
        "short": "Global",
    },
    "gulf_stream": {
        "lon": (-80.0, -40.0),
        "lat": (25.0, 45.0),
        "title": "Gulf Stream (W. North Atlantic)",
        "short": "Gulf Stream",
    },
    "so_atlantic": {
        "lon": (-20.0, 20.0),
        "lat": (-65.0, -40.0),
        "title": "Southern Ocean (Atlantic sector)",
        "short": "SO Atlantic",
    },
    "eq_pacific": {
        "lon": (-140.0, -90.0),
        "lat": (-5.0, 5.0),
        "title": "Eastern tropical Pacific",
        "short": "Eq. Pacific",
    },
}

#: Standard row order for validation figures (plan §6, Rows A–D).
REGION_ORDER = ["global", "gulf_stream", "so_atlantic", "eq_pacific"]


def region_index_slices(lon, lat, name):
    """Convert a named region's bounding box to rect-grid index slices.

    Generated by LH and Claude.

    Inputs
    ------
    lon, lat : np.ndarray
        2D coordinate arrays (XC, YC) of the full rect grid, shape
        (H, W) = (12960, 17280).
    name : str
        Key into ``REGIONS``.

    Outputs
    -------
    (jsl, isl) : tuple[slice, slice]
        Row (j / latitude) and column (i / longitude) slices.  For the
        global region these are the ``GLOBAL_DOWNSAMPLE``-strided
        full-domain slices.
    """
    box = REGIONS[name]
    if box["lon"] is None:
        # Global row: whole domain, strided.
        return (slice(None, None, GLOBAL_DOWNSAMPLE),
                slice(None, None, GLOBAL_DOWNSAMPLE))

    west, east = box["lon"]
    south, north = box["lat"]

    # Representative 1D coordinates: median across the opposite axis is
    # robust to NaNs and to mild curvature of the stitched grid.
    lat_1d = np.nanmedian(lat, axis=1)   # one latitude per row
    lon_1d = np.nanmedian(lon, axis=0)   # one longitude per column

    j_idx = np.where((lat_1d >= south) & (lat_1d <= north))[0]
    i_idx = np.where((lon_1d >= west) & (lon_1d <= east))[0]
    if j_idx.size == 0 or i_idx.size == 0:
        raise ValueError(
            f"Region '{name}' selects no rect-grid points; check that "
            "the box lies below the Arctic cap."
        )
    return (slice(j_idx[0], j_idx[-1] + 1),
            slice(i_idx[0], i_idx[-1] + 1))


def select_region(arr, lon, lat, name):
    """Slice a rect-grid field (and its coords) to a named region.

    Generated by LH and Claude.

    Inputs
    ------
    arr : np.ndarray
        2D field on the full rect grid, aligned with ``lon``/``lat``.
    lon, lat : np.ndarray
        2D coordinate arrays (XC, YC) of the full rect grid.
    name : str
        Key into ``REGIONS`` ('global' returns the downsampled field).

    Outputs
    -------
    (x, y, sub) : tuple[np.ndarray, np.ndarray, np.ndarray]
        Region-sliced longitude, latitude, and field arrays, ready for
        ``dbof.plotting.global_maps.plot_global_field``.
    """
    jsl, isl = region_index_slices(lon, lat, name)
    return lon[jsl, isl], lat[jsl, isl], arr[jsl, isl]


def select_all_regions(arr, lon, lat, names=None):
    """Slice one field to every standard region in one call.

    Generated by LH and Claude.

    Inputs
    ------
    arr : np.ndarray
        2D field on the full rect grid.
    lon, lat : np.ndarray
        2D coordinate arrays of the full rect grid.
    names : list[str] or None
        Regions to select; defaults to ``REGION_ORDER``.

    Outputs
    -------
    dict[str, tuple]
        region name -> (x, y, sub) as returned by ``select_region``.
    """
    return {
        name: select_region(arr, lon, lat, name)
        for name in (names or REGION_ORDER)
    }
