"""
sparkle_grids.py
----------------
Stage-by-stage 'sparkle' diagnostic grid for the field-validation
work (prompts/field_validation.md): where along the pipeline
raw -> intermediates -> final does pixel-level speckle first appear?

Layout (one figure per final field):

- columns = the dependency chain, left (raw) to right (final);
- row 0   = STORE product, full validation region;
- row 1   = STORE product, 200x200 km zoom;
- row 2   = LIVE recomputation, full region;
- row 3   = LIVE recomputation, zoom.

Store rows show a placeholder for chain members that are never
saved (gradient / Jacobian components exist only live).  Colormaps
are strictly SEQUENTIAL -- diverging maps can hide speckle in their
white midpoint -- with one shared norm per column (store and live
panels of a stage are directly comparable).  Positive-definite
stages get a log norm (the useful dynamic range of |grad|^2 fields
spans decades); signed stages get robust percentile limits.
"""

import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import numpy as np

from dbof.plotting import regions
from dbof.plotting.pipeline_grids import LAND_COLOR

# Row titles, in fixed order.
ROW_LABELS = ("store (full)", "store (zoom)",
              "live (full)", "live (zoom)")

# Robust limits for signed fields (percent).  Deliberately NOT too
# aggressive: sparkle is extreme pixels, and clipping the top 0.1 %
# keeps it visible as saturated dots without letting one pixel set
# the whole scale.
ROBUST_PCT = (1.0, 99.9)

PANEL_W, PANEL_H = 4.4, 3.1


def _stage_norm(arrays):
    """Shared colour norm for one chain stage (column).

    Log norm when every finite value is positive (the |grad|^2
    family); robust linear limits otherwise.  Sequential colormaps
    only -- the caller never passes a diverging map.

    Inputs
    ------
    arrays : list[np.ndarray]
        Finite-or-NaN arrays pooled for this stage (store + live).

    Outputs
    -------
    matplotlib.colors.Normalize (or LogNorm)

    Generated by LH and Claude
    """
    vals = np.concatenate(
        [a[np.isfinite(a)].ravel() for a in arrays if a is not None])
    if vals.size == 0:
        return mcolors.Normalize(0.0, 1.0)
    if vals.min() > 0:
        lo = np.percentile(vals, ROBUST_PCT[0])
        hi = vals.max()               # keep the sparkle end unclipped
        if lo <= 0 or lo == hi:
            return mcolors.Normalize(vals.min(), vals.max())
        return mcolors.LogNorm(vmin=lo, vmax=hi)
    lo, hi = np.percentile(vals, ROBUST_PCT)
    if lo == hi:
        lo, hi = vals.min(), vals.max()
    return mcolors.Normalize(vmin=lo, vmax=hi)


def _panel(ax, xyz, norm, cmap):
    """Draw one pcolormesh panel (plain axes, gray land).

    Inputs
    ------
    ax : matplotlib axis.
    xyz : (x, y, arr) regional slice, or None for a placeholder.
    norm : matplotlib colour norm shared along the column.
    cmap : str -- sequential colormap name.

    Outputs
    -------
    The mappable (QuadMesh) or None for a placeholder.

    Generated by LH and Claude
    """
    ax.set_facecolor(LAND_COLOR)
    ax.set_xticks([])
    ax.set_yticks([])
    if xyz is None:
        ax.text(0.5, 0.5, "not stored\n(live only)",
                ha="center", va="center", fontsize=9,
                style="italic", transform=ax.transAxes)
        return None
    x, y, arr = xyz
    return ax.pcolormesh(x, y, arr, norm=norm, cmap=cmap,
                         shading="nearest")


def sparkle_stage_grid(chain, store_xyz, live_xyz, region, *,
                       half_km=100.0, cmap="viridis",
                       suptitle=None):
    """The 4-row (store/live x full/zoom) stage grid for one chain.

    Inputs
    ------
    chain : list[str]
        Stage names, raw -> final (columns, left to right).
    store_xyz : dict[str, tuple | None]
        stage -> (x, y, arr) full-REGION slice of the STORE product,
        or None when the stage is not a stored channel.
    live_xyz : dict[str, tuple]
        stage -> (x, y, arr) full-REGION slice of the LIVE
        recomputation (every stage must be present).
    region : str
        Region name (must define a ``zoom`` anchor in
        ``regions.REGIONS``) -- used for the zoom rows + title.
    half_km : float
        Zoom half-width in kilometres (default 200x200 km box).
    cmap : str
        Sequential colormap for every panel (NEVER diverging here:
        the white midpoint of a diverging map can hide speckle).
    suptitle : str or None
        Figure title.

    Outputs
    -------
    (fig, axes) : the populated figure and its 4 x n_stages axes.

    Generated by LH and Claude
    """
    n = len(chain)
    fig, axes = plt.subplots(
        4, n, figsize=(PANEL_W * n, PANEL_H * 4 + 0.8), squeeze=False)

    for col, stage in enumerate(chain):
        s_full = store_xyz.get(stage)
        l_full = live_xyz[stage]

        # Zoom crops (store row only when the stage is stored).
        s_zoom = (regions.crop_zoom(*s_full, region, half_km=half_km)
                  if s_full is not None else None)
        l_zoom = regions.crop_zoom(*l_full, region, half_km=half_km)

        # One shared norm per column: store and live comparable.
        norm = _stage_norm(
            [s_full[2] if s_full is not None else None, l_full[2]])

        mappable = None
        for row, xyz in enumerate((s_full, s_zoom, l_full, l_zoom)):
            pm = _panel(axes[row, col], xyz, norm, cmap)
            mappable = pm or mappable
        axes[0, col].set_title(stage, fontsize=11)

        if mappable is not None:
            fig.colorbar(mappable, ax=list(axes[:, col]),
                         orientation="horizontal", shrink=0.85,
                         pad=0.02, aspect=30)

    for row, label in enumerate(ROW_LABELS):
        axes[row, 0].set_ylabel(label, fontsize=10)

    if suptitle:
        fig.suptitle(suptitle, fontsize=13)
    return fig, axes
