"""Can xgcm exchange the corner-stencil halo across a rotated face seam?

The question
------------
``vorticity_corner`` and ``strain_shear_corner`` difference each velocity
across the OTHER axis (``d v/dx``, ``d u/dy``).  Those stencils are
currently computed with a bare ``grid.diff``, which pads each component
on its own; at a rotated connection the value that continues ``V`` is the
neighbour's ``U``, so the halo column is wrong and the rim is NaN-ed by
``face_seam_mask`` instead.

xgcm 0.10 rewrote face-connection padding and its vector path now covers
the tangential case (``_pad_face_connections`` in ``xgcm/padding.py``
reverses along the tangential dimension and flips the sign when the
component being moved is not the one being padded).  If that is correct
for our topology, the mask can shrink to the open domain edges, where
there is genuinely no neighbour.

This script decides it from data.

The test
--------
Put SOLID-BODY ROTATION on the sphere::

    u_east = OMEGA * a * cos(lat)      v_north = 0

whose relative vorticity is known exactly::

    zeta = 2 * OMEGA * sin(lat)

Rotate it onto each face's model axes with CS/SN, run the corner stencil
both ways, and compare with the analytic value at the corner latitudes
(``YG``, taken from the raw store -- the processed grid drops it).

The pass criterion is NOT agreement to machine precision.  CS/SN are
tracer-centre quantities used here at staggered points, so every cell
carries a smooth half-cell error -- and that error is far larger near
the poles than at mid latitudes, so a single global tolerance would fail
polar seam cells that are in fact perfectly healthy.

So each rim cell is compared with the *k* cells directly inward from it
on the same line: a correct halo leaves the rim comparable to its own
neighbours, a wrong one leaves it orders of magnitude above them.  The
test counts how many rim cells exceed TOL_FACTOR times their local
neighbours -- counting, not maximum, because one bad cell and ten
thousand bad cells are different answers and a maximum cannot tell them
apart.

This script's own floor at a seam is NOT the interior floor.  The halo
value is built from the neighbour face's CS/SN, which point 90 degrees
away from ours, so the two half-cell errors are independent there where
in the interior they partly cancel.  Measured on the OSN grid, a healthy
seam sits around 10x the interior median.  A threshold near 10 therefore
measures this script rather than xgcm -- hence the default of 100.  To
certify below that floor the field would have to be built without CS/SN,
from a streamfunction at the cell corners where XG/YG are exact.

Two exclusions, both principled:

- The first and last *k* cells of every edge, i.e. the FACE CORNERS.
  A halo cell diagonally off a face would have to come from a face
  ``face_connections`` never names, so no exchange scheme reaches them.
- UPPER edges are reported but do not decide the test.  With
  left-staggered ``i_g``/``j_g`` these stencils reach only the LOWER
  halo, so pairing cannot change an upper edge -- and if the upper
  numbers are identical between the two variants, that is confirmation,
  and it means ``face_seam_mask`` is masking twice the cells it needs.

What it reports
---------------
1. ``scalar``  -- the current bare ``grid.diff``.  Expected to FAIL at
   rotated seams; this is the control that proves the test can see the
   defect at all.  A pass here would mean the test is not measuring
   anything.
2. ``vector``  -- ``grid.diff({'Y': v}, 'X', other_component={'X': u})``,
   the proposed fix.  This is the result that matters.
3. Open domain edges, reported separately: no neighbour exists, so both
   variants are expected to fail there and those cells keep their NaN
   whatever the outcome above.
4. Lower vs upper edges.  With left-staggered ``i_g``/``j_g`` these
   stencils reach only the LOWER halo, so upper-edge cells may already
   be clean under ``scalar`` -- in which case ``face_seam_mask`` is
   masking twice as many cells as it needs to.

Run it from the repo root.  OSN is public; no credentials, no snapshot
data -- the grid file alone is enough::

    conda activate llcngp
    python dev/verify_corner_seam_exchange.py
    python dev/verify_corner_seam_exchange.py --tol-factor 50

Exit status is 0 when the ``vector`` variant passes on rotated seams.

Generated by LH and Claude
"""

import argparse
import sys

import numpy as np
import xarray as xr

from dbof.global_dataset_creation.data_sources import OSN_ENDPOINT
from dbof.llc4320_ingestion import get_raw_data
from dbof.llc4320_ingestion.grid import (
    face_connections,
    invalid_seam_edges,
    set_xgcm_grid,
)
from dbof.preprocessing import preproc_llc_core_data

OMEGA = 7.2921159e-5      # Earth's rotation rate [s^-1]
EARTH_RADIUS = 6.371e6    # [m]


# ---------------------------------------------------------------------------
# The analytic field
# ---------------------------------------------------------------------------

def solid_body_model_components(ds_grid):
    """Solid-body rotation, expressed on the model axes.

    ``u_east = OMEGA * a * cos(lat)``, ``v_north = 0``, rotated onto
    model axes by inverting ``rotate_vector_to_geographic``::

        u_x =  u_east * CS + v_north * SN
        v_y = -u_east * SN + v_north * CS

    CS/SN live at tracer centres and are used here at the staggered
    points, which is the source of the smooth error the tolerance
    accommodates.

    Parameters
    ----------
    ds_grid : xarray.Dataset
        Processed grid: needs ``YC``, ``CS``, ``SN``.

    Returns
    -------
    (xarray.DataArray, xarray.DataArray)
        ``u_x`` on ``i_g`` and ``v_y`` on ``j_g`` [m s^-1].

    Generated by LH and Claude
    """
    u_east = OMEGA * EARTH_RADIUS * np.cos(np.deg2rad(ds_grid['YC']))
    u_x = (u_east * ds_grid['CS']).rename({'i': 'i_g'})
    v_y = (-u_east * ds_grid['SN']).rename({'j': 'j_g'})
    return (u_x.assign_coords(i_g=ds_grid['i_g']),
            v_y.assign_coords(j_g=ds_grid['j_g']))


def corner_latitude(raw, ds_grid):
    """Latitude of the cell corners.

    ``process_llc4320_grid`` keeps only the production subset, which has
    no ``YG``, so take it from the raw store.  If that store has none
    either, fall back to the tracer latitude: the half-cell offset shifts
    the analytic vorticity by ~1e-8 s^-1, which raises the measured
    interior floor rather than biasing seams against interior, so the
    comparison stays fair -- just less sensitive.

    Parameters
    ----------
    raw : xarray.Dataset
        The grid store as loaded, before processing.
    ds_grid : xarray.Dataset
        Processed grid (used for the fallback and for the corner index
        coordinates).

    Returns
    -------
    xarray.DataArray
        Latitude on ``(face, j_g, i_g)`` [degrees].

    Generated by LH and Claude
    """
    flat = raw.reset_coords()
    if 'YG' in flat.variables:
        return flat['YG']

    print("  NOTE: no YG in the store; using YC (half-cell offset, "
          "raises the floor)")
    return (ds_grid['YC'].rename({'j': 'j_g', 'i': 'i_g'})
            .assign_coords(j_g=ds_grid['j_g'], i_g=ds_grid['i_g']))


def analytic_vorticity(lat_corner):
    """``zeta = 2 * OMEGA * sin(lat)`` at cell corners.

    Parameters
    ----------
    lat_corner : xarray.DataArray
        Corner latitude [degrees].

    Returns
    -------
    xarray.DataArray
        Corner vorticity [s^-1].

    Generated by LH and Claude
    """
    return 2 * OMEGA * np.sin(np.deg2rad(lat_corner))


# ---------------------------------------------------------------------------
# The two stencil variants
# ---------------------------------------------------------------------------

def corner_vorticity(u_x, v_y, ds_grid, grid, vector_aware):
    """Corner vorticity, with the halo taken one way or the other.

    Parameters
    ----------
    u_x, v_y : xarray.DataArray
        Staggered model-axis velocities.
    ds_grid : xarray.Dataset
        Needs ``dxC``, ``dyC``, ``rAz``.
    grid : xgcm.Grid
    vector_aware : bool
        ``True`` hands xgcm both components so a rotated connection can
        take the halo from the partner; ``False`` is the bare scalar
        diff used today.

    Returns
    -------
    xarray.DataArray
        ``momVort3`` on cell corners [s^-1].

    Generated by LH and Claude
    """
    v_dy = v_y * ds_grid['dyC']
    u_dx = u_x * ds_grid['dxC']
    if vector_aware:
        cross_v = grid.diff({'Y': v_dy}, 'X', other_component={'X': u_dx})
        cross_u = grid.diff({'X': u_dx}, 'Y', other_component={'Y': v_dy})
    else:
        cross_v = grid.diff(v_dy, 'X')
        cross_u = grid.diff(u_dx, 'Y')
    return (cross_v - cross_u) / ds_grid['rAz']


# ---------------------------------------------------------------------------
# Where to look
# ---------------------------------------------------------------------------

def classify_edges():
    """Split the invalid seam edges into rotated and open.

    Returns
    -------
    (set, set)
        ``(rotated, open_)`` of ``(face, axis, side)`` tuples.  Rotated
        edges have a neighbour reached along the other axis; open edges
        have no neighbour at all.

    Generated by LH and Claude
    """
    rotated, open_ = set(), set()
    for face, axis, side in invalid_seam_edges():
        pair = face_connections['face'][face][axis]
        link = pair[0 if side == 'lower' else 1]
        (open_ if link is None else rotated).add((face, axis, side))
    return rotated, open_


def edge_cell_mask(da, edges, width=1):
    """Boolean mask of the cells adjacent to *edges*.

    Parameters
    ----------
    da : xarray.DataArray
        Corner field with dims ``(face, j_g, i_g)``.
    edges : iterable
        ``(face, axis, side)`` tuples.
    width : int, default 1

    Returns
    -------
    xarray.DataArray
        ``True`` on the selected rim cells.

    Generated by LH and Claude
    """
    shape = (da.sizes['face'], da.sizes['j_g'], da.sizes['i_g'])
    mask = np.zeros(shape, dtype=bool)
    pos = {'Y': 1, 'X': 2}
    for face, axis, side in edges:
        sl = [slice(None)] * 3
        sl[0] = face
        sl[pos[axis]] = (slice(0, width) if side == 'lower'
                         else slice(-width, None))
        mask[tuple(sl)] = True
    return xr.DataArray(mask, dims=('face', 'j_g', 'i_g'))


def face_corner_mask(da, width=1):
    """Cells within *width* of BOTH an X and a Y face boundary.

    A halo cell diagonally off a face comes from a face that
    ``face_connections`` does not name -- the table lists edge
    neighbours, not corner ones -- so no exchange scheme can fill these,
    and on a cubed sphere three faces meet there anyway.  They are
    reported apart from the along-edge cells for that reason.

    Parameters
    ----------
    da : xarray.DataArray
        Corner field with dims ``(face, j_g, i_g)``.
    width : int, default 1

    Returns
    -------
    numpy.ndarray
        Boolean, shape ``(face, j_g, i_g)``.

    Generated by LH and Claude
    """
    nf, nj, ni = da.sizes['face'], da.sizes['j_g'], da.sizes['i_g']
    j_edge = np.zeros(nj, bool)
    j_edge[:width] = j_edge[-width:] = True
    i_edge = np.zeros(ni, bool)
    i_edge[:width] = i_edge[-width:] = True
    return np.broadcast_to(j_edge[:, None] & i_edge[None, :], (nf, nj, ni))


# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------

def summarize(err, mask, label):
    """Print max/median error over *mask* and return the max.

    Parameters
    ----------
    err : numpy.ndarray
        Absolute error field [s^-1].
    mask : numpy.ndarray
        Boolean, same shape.
    label : str

    Returns
    -------
    float
        Maximum error over the masked cells, or ``nan`` if empty.

    Generated by LH and Claude
    """
    sel = err[mask & np.isfinite(err)]
    if sel.size == 0:
        print(f"    {label:34s} (no cells)")
        return float('nan')
    print(f"    {label:34s} n={sel.size:7d}  "
          f"median {np.median(sel):.3e}  max {sel.max():.3e}")
    return float(sel.max())


def edge_vs_inward(err, edges, ref, k=8, ratio=100.0, show=6):
    """Compare each rim cell with its own inward neighbours.

    The global interior floor is not a fair yardstick: the half-cell
    CS/SN approximation is far worse near the poles than at mid
    latitudes, so a polar seam cell can exceed a global budget while
    being no worse than the cells beside it.  This compares each rim
    cell only with the *k* cells directly inward from it on the same
    line, which removes that confound entirely -- a correct halo leaves
    the rim cell comparable to its neighbours, a wrong one leaves it
    orders of magnitude above them.

    The first and last *k* positions along each edge are skipped: those
    are the face corners, whose halo would have to come diagonally off
    the face, from a neighbour ``face_connections`` never names.

    Parameters
    ----------
    err : numpy.ndarray
        Absolute error, dims ``(face, j_g, i_g)``.
    edges : iterable
        ``(face, axis, side)`` tuples.
    ref : float
        Interior median error.  Floors the denominator: on an analytic
        field the inward cells are sometimes right to machine precision,
        and dividing by ~1e-16 turns a physically perfect rim cell into a
        ratio of 1e16.  A rim cell at the interior-typical level can
        never fail.
    k : int, default 8
        Inward cells used as the local reference.
    ratio : float, default 100.0
        A rim cell fails at more than this multiple of its neighbours.
        Loose on purpose: this script's own seam floor is ~10x the
        interior, so a threshold near 10 measures the script.
    show : int, default 6
        How many of the worst offenders to list.

    Returns
    -------
    (int, int)
        Cells failing, cells tested.

    Generated by LH and Claude
    """
    n_bad = n_tested = 0
    worst = []
    for face, axis, side in sorted(edges):
        plane = err[face]
        e = np.moveaxis(plane, 0 if axis == 'Y' else 1, 0)
        rim, inward = ((e[0], e[1:1 + k]) if side == 'lower'
                       else (e[-1], e[-1 - k:-1]))
        base = np.maximum(np.nanmedian(inward, axis=0), ref)
        good = np.isfinite(rim) & np.isfinite(base)
        good[:k] = good[-k:] = False          # face corners
        r = np.where(good, rim / base, np.nan)
        bad = good & (r > ratio)
        n_bad += int(bad.sum())
        n_tested += int(good.sum())
        for idx in np.argsort(np.nan_to_num(r))[::-1][:show]:
            if bad[idx]:
                worst.append((float(r[idx]), face, axis, side, int(idx)))

    if not n_tested:
        print("      NO CELLS CHECKED -- faces are smaller than the "
              "corner exclusion (2k)")
        return 0, 0
    print(f"      above {ratio:g}x their inward neighbours: "
          f"{n_bad:6d} of {n_tested:6d}  ({100.0 * n_bad / n_tested:6.2f}%)")
    for rr, face, axis, side, idx in sorted(worst, reverse=True)[:show]:
        print(f"        face {face:2d} {axis}-{side:5s} at {idx:5d}  "
              f"{rr:9.1f}x")
    return n_bad, n_tested


def run(tol_factor=100.0, width=1):
    """Run both variants and report.

    Parameters
    ----------
    tol_factor : float, default 5.0
        A rim cell fails above this multiple of its inward neighbours.
    width : int, default 1
        Rim width in cells.

    Returns
    -------
    bool
        ``True`` when the vector-aware variant passes at rotated seams.

    Generated by LH and Claude
    """
    print("Loading the OSN grid ...")
    raw = get_raw_data.get_remote_gridfile(OSN_ENDPOINT)
    ds_grid = preproc_llc_core_data.process_llc4320_grid(raw)
    grid = set_xgcm_grid(ds_grid)

    u_x, v_y = solid_body_model_components(ds_grid)
    truth = analytic_vorticity(corner_latitude(raw, ds_grid))

    rotated, open_ = classify_edges()
    print(f"  {len(rotated)} rotated edges, {len(open_)} open edges\n")

    # Lower edges are the ones these stencils actually reach into.
    rot_lower = {e for e in rotated if e[2] == 'lower'}
    rot_upper = rotated - rot_lower

    results = {}
    for label, vector_aware in (("scalar (current)", False),
                                ("vector (proposed fix)", True)):
        zeta = corner_vorticity(u_x, v_y, ds_grid, grid, vector_aware)
        err = np.abs((zeta - truth).compute().transpose(
            'face', 'j_g', 'i_g').values)

        all_seams = np.asarray(edge_cell_mask(zeta, rotated | open_, width))
        interior = np.isfinite(err) & ~all_seams
        floor = float(np.nanpercentile(err[interior], 99.9))
        ref = float(np.median(err[interior]))

        print(f"  {label}")
        print(f"    {'interior median (the reference)':34s} {ref:.3e}")
        print(f"    {'interior 99.9th pct':34s} {floor:.3e}")
        print(f"    (signal scale: 2*OMEGA = {2 * OMEGA:.3e} s^-1)")
        summarize(err, np.asarray(edge_cell_mask(zeta, rot_lower, width)),
                  "rotated seams, lower edge")
        summarize(err, np.asarray(edge_cell_mask(zeta, rot_upper, width)),
                  "rotated seams, upper edge")
        summarize(err, np.asarray(edge_cell_mask(zeta, open_, width)),
                  "open domain edges")
        print("    local check (rim cell vs its own inward neighbours,")
        print("    face corners excluded):")
        print("      lower edges -- pairing can fix these")
        n_bad, n_tested = edge_vs_inward(err, rot_lower, ref,
                                         ratio=tol_factor)
        print("      upper edges -- these stencils never reach that halo")
        edge_vs_inward(err, rot_upper, ref, ratio=tol_factor)
        seam_med = float(np.median(
            err[np.asarray(edge_cell_mask(zeta, rot_lower, width))
                & np.isfinite(err)]))
        results[label] = (n_bad, n_tested, seam_med / ref)
        print()

    print("  seam error relative to the interior, as a median ratio:")
    for label, (_, _, rel) in results.items():
        print(f"    {label:24s} {rel:10.3e}x interior")
    rels = [r for _, _, r in results.values()]
    if rels[0] > 0 and rels[1] > 0:
        print(f"    pairing removes a factor of {rels[0] / rels[1]:.3e}\n")

    ok = True
    for label, (n_bad, n_tested, _) in results.items():
        # a correct halo leaves a handful of cells at most; allow 0.1%
        # (n_tested == 0 means the faces are smaller than the corner
        # exclusion -- nothing was checked, so nothing passed)
        passed = n_tested > 0 and n_bad <= max(1, 0.001 * n_tested)
        expect_pass = label.startswith("vector")
        flag = "PASS" if passed else "FAIL"
        note = "" if passed == expect_pass else "   <-- UNEXPECTED"
        print(f"  {label:24s} lower rotated edges {flag} "
              f"({n_bad} of {n_tested} cells bad){note}")
        if expect_pass:
            ok = passed
        elif passed:
            # the control passed: the test is not seeing the defect
            ok = False

    print()
    if ok:
        print("  => xgcm exchanges the corner halo correctly along rotated "
              "connections.\n     face_seam_mask can be reduced to the open "
              "domain edges plus the\n     face corners, where no neighbour "
              "is defined.")
    else:
        print("  => keep the mask as it is.")
    return ok


def main(argv=None):
    """Parse arguments and run.

    Parameters
    ----------
    argv : list of str, optional

    Returns
    -------
    int
        0 on pass, 1 on fail.

    Generated by LH and Claude
    """
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--tol-factor", type=float, default=100.0,
                        help="a rim cell fails above this multiple of its "
                             "inward neighbours (default 10)")
    parser.add_argument("--width", type=int, default=1,
                        help="rim width in cells (default 1)")
    args = parser.parse_args(argv)
    return 0 if run(args.tol_factor, args.width) else 1


if __name__ == "__main__":
    sys.exit(main())
