"""
Real-data spot-check: run one SURF and one DEPTH subset end-to-end.

Post-field-migration verification (prompts/field_migration.md, Phase 5
handoff): pushes ONE date through the exact production path — grid setup,
snapshot load from S3/OSN, the consolidated ``calculate_fields`` /
``calculate_fields_at_depth`` compute functions, face→latlon stitch, land
mask — and reports per-channel summary statistics instead of writing to
zarr.  Nothing here bypasses production code: the spec resolution mirrors
``cli/generate_global._resolve_subset_specs`` and the snapshot processing
is the same ``process_surface`` / ``process_depth`` used by
``generate-global``.

RUN ON THE SERVER (needs S3/OSN network access and production-scale
memory — one date of a DEPTH subset is the same workload the production
pipeline handles per date)::

    conda activate llcngp
    python dev/verify_subsets_real_data.py --date "2012-01-15 12:00:00"

Options::

    --date          ISO date string (required), e.g. "2012-01-15 12:00:00"
    --pipelines     Which pipelines to run (default: SURF DEPTH)
    --surf-subset   SURF subset (default: frontal_structure — exercises
                    the new density/buoyancy channels)
    --depth-subset  DEPTH subset (default: stratification)
    --output-dir    Where reports are written (default: .)
    --workers N     Start a local dask.distributed cluster with N workers
                    (default: 0 = default threaded scheduler)
    --save-preview  Also save each channel downsampled ::12 to an .npz
                    (handy input for the verification notebooks)

What to expect (documented, intentional changes vs pre-migration output;
see prompts/field_migration.md "Known value changes"):

- ``density`` channel is now the potential density ANOMALY sigma0
  (values ~20-30 kg/m3, not ~1020-1030).
- ``buoyancy`` channel is anomaly-based b = g*sigma0/rho0
  (values ~0.2-0.3 m/s2, not ~10).
- Buoyancy-gradient family (gradb2, log_gradb, frontogenesis_*, uB/vB/wB,
  ertel_pv_*, N2) rescaled by (9.81/1000)/(9.8/1025) per power of b
  (~x1.026 linear, ~x1.053 squared).
- Everything else (kinematics, gradtheta2/salt2/eta2, wind, MLD, Ri, Ro)
  should match pre-migration output to float precision.

Generated by LH and Claude
"""

import argparse
import logging
import sys
import time

import numpy as np

from dbof.cli.generate_global import load_snapshot, RECTANGULAR_SHAPE
from dbof.global_dataset_creation.data_sources import get_data_source
from dbof.global_dataset_creation.grid_setup import set_up_grid
from dbof.global_dataset_creation.subset_definitions import (
    expand_channels_with_suffixes,
    get_compute_fn,
    get_subset_definition,
    valid_subsets,
)
from dbof.global_dataset_creation.variable_selection import (
    required_model_variables,
)
import dbof.global_dataset_creation.process_surface as process_surface
import dbof.global_dataset_creation.process_depth as process_depth


# ---------------------------------------------------------------------------
# Spec resolution (mirrors cli/generate_global._resolve_subset_specs)
# ---------------------------------------------------------------------------

def resolve_spec(pipeline: str, subset_name: str) -> dict:
    """Build the per-subset spec exactly as the production CLI does.

    Parameters
    ----------
    pipeline : str
        ``"SURF"``, ``"OSN"``, or ``"DEPTH"``.
    subset_name : str
        A subset valid for *pipeline* (see ``valid_subsets``).

    Returns
    -------
    dict
        Keys: subset_name, compute_fn, surface_only, model_channels,
        compute_channels, channel_names, vars_needed.

    Generated by LH and Claude
    """
    defn = get_subset_definition(pipeline, subset_name)
    model_channels = list(defn["model_data_feature_channels"])
    defn_suffixes = defn.get("depth_suffixes")
    compute_channels = expand_channels_with_suffixes(
        defn["compute_features_channels"],
        depth_suffixes=defn_suffixes,
        extra_channels=defn.get("extra_channels"),
    )
    return {
        "subset_name": subset_name,
        "compute_fn": get_compute_fn(pipeline, subset_name),
        "surface_only": defn.get("surface_only", False),
        "model_channels": model_channels,
        "compute_channels": compute_channels,
        "channel_names": model_channels + compute_channels,
        "vars_needed": required_model_variables(
            model_channels, compute_channels),
    }


# ---------------------------------------------------------------------------
# Per-channel statistics
# ---------------------------------------------------------------------------

def channel_stats(data: np.ndarray, channel_names: list) -> list:
    """Summary statistics per channel of a stitched (C, H, W) array.

    Parameters
    ----------
    data : np.ndarray
        Stitched snapshot, shape (C, H, W); land pixels NaN.
    channel_names : list of str
        Channel name per leading index.

    Returns
    -------
    list of dict
        One dict per channel: name, nan_frac, min, max, mean, std,
        abs_p50, abs_p99, and the production validity-guard verdict
        (equatorial-strip sample must have >2 unique values).

    Generated by LH and Claude
    """
    rows = []
    for c, name in enumerate(channel_names):
        ch = data[c]
        finite = ch[np.isfinite(ch)]
        # Same cheap validity guard the production _generate applies.
        sample = ch[7600:8320, ::24]
        valid = (name == "SIarea") or (np.unique(sample).size > 2)
        absf = np.abs(finite)
        rows.append({
            "name": name,
            "nan_frac": 1.0 - finite.size / ch.size,
            "min": float(finite.min()) if finite.size else np.nan,
            "max": float(finite.max()) if finite.size else np.nan,
            "mean": float(finite.mean()) if finite.size else np.nan,
            "std": float(finite.std()) if finite.size else np.nan,
            "abs_p50": float(np.percentile(absf, 50)) if finite.size else np.nan,
            "abs_p99": float(np.percentile(absf, 99)) if finite.size else np.nan,
            "guard_ok": valid,
        })
    return rows


def format_report(pipeline, subset, date_str, rows, elapsed_s) -> str:
    """Fixed-width text report for one pipeline/subset run."""
    lines = [
        "=" * 100,
        f"pipeline={pipeline}  subset={subset}  date={date_str}  "
        f"elapsed={elapsed_s:.0f}s",
        "=" * 100,
        f"{'channel':<28}{'nan%':>7}{'min':>13}{'max':>13}{'mean':>13}"
        f"{'std':>13}{'|p50|':>11}{'|p99|':>11}  guard",
        "-" * 100,
    ]
    for r in rows:
        lines.append(
            f"{r['name']:<28}{100 * r['nan_frac']:>6.1f}%"
            f"{r['min']:>13.4e}{r['max']:>13.4e}{r['mean']:>13.4e}"
            f"{r['std']:>13.4e}{r['abs_p50']:>11.3e}{r['abs_p99']:>11.3e}"
            f"  {'OK' if r['guard_ok'] else 'FAIL'}")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def run_one(pipeline, subset, date_str, output_dir, save_preview) -> bool:
    """Run one pipeline/subset for one date; write report; return guard OK."""
    t0 = time.time()
    spec = resolve_spec(pipeline, subset)
    logging.info(f"[{pipeline}/{subset}] channels: {spec['channel_names']}")
    logging.info(f"[{pipeline}/{subset}] vars needed: {spec['vars_needed']}")

    data_source = get_data_source(pipeline)
    ds_grid, land_mask, grid = set_up_grid(pipeline, data_source)

    ds, ds_merge, it = load_snapshot(
        pipeline, date_str, ds_grid, spec["vars_needed"],
        spec["surface_only"], data_source,
    )

    if pipeline == "DEPTH":
        data = process_depth.process_snapshot(
            ds, ds_merge, grid,
            spec["model_channels"], spec["compute_channels"],
            spec["compute_fn"], spec["surface_only"],
        )
    else:
        data = process_surface.process_snapshot(
            ds, ds_merge, grid,
            spec["model_channels"], spec["compute_channels"],
            spec["compute_fn"],
        )

    assert data.shape[0] == len(spec["channel_names"])
    assert data.shape[1:] == RECTANGULAR_SHAPE, data.shape

    rows = channel_stats(data, spec["channel_names"])
    report = format_report(pipeline, subset, date_str, rows,
                           time.time() - t0)
    print(report)

    tag = date_str.replace(" ", "T").replace(":", "")
    rpt_path = f"{output_dir}/verify_{pipeline}_{subset}_{tag}.txt"
    with open(rpt_path, "w") as f:
        f.write(report)
    logging.info(f"report written: {rpt_path}")

    if save_preview:
        npz_path = f"{output_dir}/verify_{pipeline}_{subset}_{tag}.npz"
        np.savez_compressed(
            npz_path, channel_names=np.array(spec["channel_names"]),
            **{r["name"]: data[c, ::12, ::12]
               for c, r in enumerate(rows)})
        logging.info(f"downsampled preview written: {npz_path}")

    return all(r["guard_ok"] for r in rows)


def main(argv=None):
    p = argparse.ArgumentParser(
        description="Run one SURF and one DEPTH subset on real data and "
                    "report per-channel statistics (no zarr writes).")
    p.add_argument("--date", required=True,
                   help='ISO date string, e.g. "2012-01-15 12:00:00"')
    p.add_argument("--pipelines", nargs="+", default=["SURF", "DEPTH"],
                   choices=["SURF", "OSN", "DEPTH"])
    p.add_argument("--surf-subset", default="frontal_structure")
    p.add_argument("--depth-subset", default="stratification")
    p.add_argument("--output-dir", default=".")
    p.add_argument("--workers", type=int, default=0,
                   help="local dask.distributed workers (0 = threaded)")
    p.add_argument("--save-preview", action="store_true")
    args = p.parse_args(argv)

    logging.basicConfig(level=logging.INFO,
                        format="%(asctime)s %(levelname)s %(message)s")

    client = None
    if args.workers > 0:
        from dask.distributed import Client
        client = Client(n_workers=args.workers, threads_per_worker=2)
        logging.info(f"dask dashboard: {client.dashboard_link}")

    all_ok = True
    try:
        for pipeline in args.pipelines:
            subset = (args.depth_subset if pipeline == "DEPTH"
                      else args.surf_subset)
            if subset not in valid_subsets(pipeline):
                raise SystemExit(
                    f"subset '{subset}' not valid for {pipeline}; "
                    f"choose from {valid_subsets(pipeline)}")
            all_ok &= run_one(pipeline, subset, args.date,
                              args.output_dir, args.save_preview)
    finally:
        if client is not None:
            client.close()

    if not all_ok:
        logging.error("one or more channels FAILED the validity guard")
        sys.exit(1)
    logging.info("all channels passed the validity guard")


if __name__ == "__main__":
    main()
