"""Compare the OSN kerchunk grid with the LLC_DEPTH grid store, step by step.

Motivation
----------
The two pipelines load the SAME physical LLC4320 grid from different
stores, and they disagree about one thing: the comodo
``c_grid_axis_shift`` on ``i_g`` / ``j_g``.  ``get_remote_gridfile``
(OSN) passes through whatever the store carries; the LLC_DEPTH store
carries no comodo attributes at all, so ``get_llc_depth_gridfile``
supplies them -- which makes that literal the only record of where U and
V sit in that pipeline.

That attribute is not cosmetic.  xgcm reads it as a SIGNED direction
(``xgcm/comodo.py``): ``-0.5`` -> the staggered coordinate is at the
LEFT/WEST edge of its cell, ``+0.5`` -> the RIGHT/EAST edge.  MITgcm puts
``U`` on the west face, and xmitgcm stamps ``-0.5`` accordingly
(``xmitgcm/variables.py``).

Nothing about the FACES changes -- the stored arrays are identical, as
stage 3 confirms.  What changes is which PAIR OF CELLS each stencil
combines.  Interpolating a left-staggered ``U`` to centre ``i`` averages
``i_g[i]`` and ``i_g[i+1]``, so it reaches past the last index and needs
the UPPER halo; a right-staggered one averages ``i_g[i-1]`` and
``i_g[i]``, reaching past index 0 for the LOWER halo.  So a wrong sign
shifts every velocity-derived field one cell along the model axis, and
moves the halo-damaged column from one end of each face's index range to
the other -- which, since only some connections rotate the neighbour,
also changes WHICH faces are affected.

What this script does
---------------------
Walks both grids through the production path and compares them at every
stage, rather than trusting any single attribute:

1. ``attrs``    -- what each STORE declares, before and after the loaders
                   stamp anything.
2. ``vars``     -- inventory: variables, shapes, dtypes, chunking.
3. ``native``   -- per-face numeric comparison of every shared variable
                   on the raw face grid.
4. ``truth``    -- the decisive test, from the DATA rather than the
                   metadata: MITgcm defines ``dxC(i,j)`` as the distance
                   between tracer centres ``(i-1,j)`` and ``(i,j)``, so
                   the great-circle distance between ``XC[i-1]`` and
                   ``XC[i]`` must equal ``dxC[i]`` under the LEFT
                   convention, and ``dxC[i-1]`` under RIGHT.  Uses only
                   XC/YC/dxC/dyC, which both stores carry.
5. ``xgcm``     -- what each grid's declared attrs actually make xgcm do,
                   and which face edges become seams under each.
6. ``stitch``   -- run both through the same face->latlon stitch and
                   compare the rasters.

Run it from the repo root on the server.  OSN is public; the LLC_DEPTH
store needs dbof credentials (docs/Testing.md)::

    conda activate llcngp
    export AWS_ACCESS_KEY_ID=...
    export AWS_SECRET_ACCESS_KEY=...

    # the question at hand -- seconds, metadata + geometry only
    python dev/verify_grid_stores.py --stages attrs truth --no-figures

    # full comparison of the two stores on the native face grid
    python dev/verify_grid_stores.py --stages attrs vars native truth xgcm

    # heavy: stitches both grids to the 12960 x 17280 raster
    python dev/verify_grid_stores.py --stages stitch --stride 24

If the DEPTH store is unreachable, ``--stages attrs truth`` still reports
the OSN side on its own, which is the half that decides whether the
``+0.5`` stamp is right.

Options::

    --stages       Which stages to run (default: all but ``stitch``).
    --variables    Variables to compare numerically (default: the shared
                   horizontal set).
    --stride       Subsample stride for plotting / stitching (default 24).
    --output-dir   Where figures and the report are written (default
                   ``dev/output/grid_stores``).
    --no-figures   Skip plotting; print the numeric report only.

Exit status is non-zero if any comparison fails, so it can gate a
regeneration.

Generated by LH and Claude
"""

import argparse
import json
import sys
from pathlib import Path

import numpy as np
import xarray as xr

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

from dbof.global_dataset_creation.data_sources import (  # noqa: E402
    LLC_DEPTH_SOURCE,
    OSN_ENDPOINT,
)
from dbof.llc4320_ingestion import get_raw_data  # noqa: E402
from dbof.llc4320_ingestion.grid import (  # noqa: E402
    face_connections,
    set_xgcm_grid,
)
from dbof.preprocessing import preproc_llc_core_data  # noqa: E402

def edges_needing_a_rotated_halo(connections=None, facedim='face'):
    """Face edges whose halo cannot simply be copied from the neighbour.

    Two kinds qualify: connections that reach the neighbour along the
    OTHER axis (so a staggered component's halo would have to come from
    the neighbour's other component), and ``None`` connections (an open
    domain edge, where there is no neighbour at all).  Same-axis
    connections are copied correctly and are not listed.

    Derived from ``face_connections`` here rather than imported, so this
    diagnostic keeps working independently of the stencil code.

    Parameters
    ----------
    connections : dict, optional
        Face-connection mapping; defaults to the LLC4320 table.
    facedim : str, default 'face'
        Key of the outer connection dictionary.

    Returns
    -------
    set[tuple[int, str, str]]
        ``(face, axis, side)`` triples, ``side`` in {'lower', 'upper'}.

    Generated by LH and Claude
    """
    conn = (face_connections if connections is None else connections)[facedim]
    edges = set()
    for face, axes in conn.items():
        for axis, (lower, upper) in axes.items():
            for side, link in (('lower', lower), ('upper', upper)):
                if link is None or link[1] != axis:
                    edges.add((face, axis, side))
    return edges


#: Earth radius [m] used for the great-circle check (MITgcm's sphere).
EARTH_RADIUS_M = 6371000.0

#: Horizontal variables both stores should carry identically.
SHARED_VARS = ["XC", "YC", "dxC", "dyC", "dxG", "dyG", "rA", "rAz",
               "Depth", "hFacC", "CS", "SN"]

#: Staggered coordinate dims whose comodo attrs are the point of this script.
COORD_DIMS = ["i", "i_g", "j", "j_g"]

ALL_STAGES = ["attrs", "vars", "native", "truth", "xgcm", "stitch"]
DEFAULT_STAGES = ["attrs", "vars", "native", "truth", "xgcm"]


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------

def load_osn_grid():
    """Load the OSN kerchunk grid, raw and processed.

    Returns
    -------
    (xarray.Dataset, xarray.Dataset)
        The dataset exactly as ``get_remote_gridfile`` returns it (no
        attrs are stamped on this path), and the same after
        ``process_llc4320_grid``.

    Generated by LH and Claude
    """
    raw = get_raw_data.get_remote_gridfile(OSN_ENDPOINT)
    return raw, preproc_llc_core_data.process_llc4320_grid(raw)


def load_depth_grid(source=None):
    """Load the LLC_DEPTH grid store, raw and processed.

    Parameters
    ----------
    source : dict, optional
        ``s3_endpoint`` / ``bucket`` / ``folder``; defaults to
        ``LLC_DEPTH_SOURCE``.

    Returns
    -------
    (xarray.Dataset, xarray.Dataset)
        The dataset as ``get_llc_depth_gridfile`` returns it (comodo
        attrs already stamped by that reader) and the same after
        ``process_llc4320_3d_grid``.

    Generated by LH and Claude
    """
    src = dict(LLC_DEPTH_SOURCE if source is None else source)
    folder = src.get("grid_folder", src["folder"])
    raw = get_raw_data.get_llc_depth_gridfile(
        src["s3_endpoint"], src["bucket"], folder)
    return raw, preproc_llc_core_data.process_llc4320_3d_grid(raw)


def load_depth_store_unstamped(source=None, grid_store_name="grid.zarr"):
    """Open the DEPTH grid zarr WITHOUT the reader's attr stamping.

    ``get_llc_depth_gridfile`` overwrites ``c_grid_axis_shift`` on its way
    out, so this is the only way to see what the store itself declares.
    Mirrors that reader's URL and storage-option construction (its private
    helpers are reused deliberately -- this is a diagnostic, and the point
    is to read exactly the same object).

    Parameters
    ----------
    source : dict, optional
        As in :func:`load_depth_grid`.
    grid_store_name : str, default 'grid.zarr'
        Grid store name inside the folder.

    Returns
    -------
    xarray.Dataset or None
        The store as-is, or ``None`` if it could not be opened (the
        reason is printed).

    Generated by LH and Claude
    """
    src = dict(LLC_DEPTH_SOURCE if source is None else source)
    folder = src.get("grid_folder", src["folder"])
    try:
        url = get_raw_data._build_s3_store_url(
            src["bucket"], folder, grid_store_name)
        opts = get_raw_data._llc_depth_storage_options(src["s3_endpoint"])
        return xr.open_zarr(url, consolidated=False, storage_options=opts)
    except Exception as exc:                       # diagnostic, stay alive
        print(f"    (could not open the unstamped DEPTH store: "
              f"{type(exc).__name__}: {exc})")
        return None


# ---------------------------------------------------------------------------
# Stage 1 -- comodo attributes
# ---------------------------------------------------------------------------

def coord_attrs(ds):
    """Comodo attributes on the horizontal coordinate dims.

    Parameters
    ----------
    ds : xarray.Dataset
        Any grid dataset.

    Returns
    -------
    dict
        ``{dim: {'axis': ..., 'c_grid_axis_shift': ...}}``; a dim that is
        not a coordinate maps to ``None``.

    Generated by LH and Claude
    """
    out = {}
    for dim in COORD_DIMS:
        if dim not in ds.dims:
            out[dim] = None
        elif dim not in ds.coords:
            out[dim] = "dim only (no coordinate variable, no attrs)"
        else:
            attrs = ds.coords[dim].attrs
            out[dim] = {k: attrs.get(k) for k in
                        ("axis", "c_grid_axis_shift") if k in attrs}
    return out


def shift_to_position(shift):
    """Translate a ``c_grid_axis_shift`` into xgcm's position name.

    Parameters
    ----------
    shift : float or None
        The attribute value.

    Returns
    -------
    str
        ``'left'``, ``'right'``, or a description of what is missing.

    Generated by LH and Claude
    """
    if shift is None:
        return "MISSING"
    try:
        value = float(shift)
    except (TypeError, ValueError):
        return f"UNPARSEABLE ({shift!r})"
    if value == -0.5:
        return "left  (west/south edge -- MITgcm + xmitgcm convention)"
    if value == 0.5:
        return "right (east/north edge)"
    return f"INVALID ({value})"


def stage_attrs(osn_raw, osn_proc, dep_raw, dep_proc, dep_store):
    """Report what each store declares, before and after processing.

    Parameters
    ----------
    osn_raw, osn_proc, dep_raw, dep_proc : xarray.Dataset
        Grids at the two stages of each path.
    dep_store : xarray.Dataset or None
        The DEPTH store opened without the reader's stamping.

    Returns
    -------
    bool
        True when both paths end up on the same convention.

    Generated by LH and Claude
    """
    print("\n" + "=" * 70)
    print("STAGE 1: comodo attributes")
    print("=" * 70)
    print("xgcm reads c_grid_axis_shift as a SIGNED direction "
          "(xgcm/comodo.py):")
    print("  -0.5 -> 'left'   +0.5 -> 'right'   anything else -> error")
    print("xmitgcm stamps -0.5 on i_g/j_g (xmitgcm/variables.py).\n")

    stages = [("OSN   store  (get_remote_gridfile)", osn_raw),
              ("OSN   processed", osn_proc),
              ("DEPTH store  (raw zarr, unstamped)", dep_store),
              ("DEPTH reader (get_llc_depth_gridfile)", dep_raw),
              ("DEPTH processed", dep_proc)]
    for label, ds in stages:
        if ds is None:
            print(f"{label:38s}  (unavailable)")
            continue
        print(f"{label}")
        for dim, attrs in coord_attrs(ds).items():
            if attrs is None:
                continue
            if isinstance(attrs, str):
                print(f"    {dim:4s} {attrs}")
                continue
            shift = attrs.get("c_grid_axis_shift")
            note = (f"  -> {shift_to_position(shift)}"
                    if dim.endswith("_g") else "")
            print(f"    {dim:4s} {attrs}{note}")
        print()

    def staggered_shift(ds):
        if ds is None:
            return None
        attrs = coord_attrs(ds).get("i_g")
        if not isinstance(attrs, dict):
            return None
        return attrs.get("c_grid_axis_shift")

    osn_shift = staggered_shift(osn_proc)
    dep_shift = staggered_shift(dep_proc)
    agree = (osn_shift is not None and dep_shift is not None
             and float(osn_shift) == float(dep_shift))
    print(f"RESULT: OSN i_g = {osn_shift!r}, DEPTH i_g = {dep_shift!r}"
          f"  ->  {'AGREE' if agree else 'DISAGREE'}")
    if not agree:
        print("  The two pipelines are using different C-grid registrations."
              "\n  Stage 4 decides which one the data itself supports.")
    return agree


# ---------------------------------------------------------------------------
# Stage 2 -- inventory
# ---------------------------------------------------------------------------

def stage_vars(osn, dep):
    """Compare variable inventories, shapes and dtypes.

    Parameters
    ----------
    osn, dep : xarray.Dataset
        Processed grids.

    Returns
    -------
    bool
        True when the shared variables match in shape and dtype.

    Generated by LH and Claude
    """
    print("\n" + "=" * 70)
    print("STAGE 2: variable inventory")
    print("=" * 70)
    osn_vars, dep_vars = set(osn.data_vars), set(dep.data_vars)
    only_osn = sorted(osn_vars - dep_vars)
    only_dep = sorted(dep_vars - osn_vars)
    if only_osn:
        print(f"  only in OSN   : {only_osn}")
    if only_dep:
        print(f"  only in DEPTH : {only_dep}")

    ok = True
    print(f"\n  {'variable':10s} {'dims':22s} {'OSN shape':18s} "
          f"{'DEPTH shape':18s} dtype")
    for name in sorted(osn_vars & dep_vars):
        a, b = osn[name], dep[name]
        same = a.shape == b.shape and a.dims == b.dims
        ok &= same
        flag = "" if same else "   <-- MISMATCH"
        print(f"  {name:10s} {str(a.dims):22s} {str(a.shape):18s} "
              f"{str(b.shape):18s} {a.dtype}/{b.dtype}{flag}")
    print(f"\nRESULT: shapes and dims {'match' if ok else 'DIFFER'}")
    return ok


# ---------------------------------------------------------------------------
# Stage 3 -- native face comparison
# ---------------------------------------------------------------------------

def stage_native(osn, dep, variables, out_dir, figures=True, stride=24):
    """Per-face numeric comparison on the raw face grid.

    Parameters
    ----------
    osn, dep : xarray.Dataset
        Processed grids.
    variables : list of str
        Variables to compare.
    out_dir : pathlib.Path
        Where figures are written.
    figures : bool, default True
        Whether to draw the per-face montage.
    stride : int, default 24
        Subsampling stride for the figure only.

    Returns
    -------
    bool
        True when every compared variable is identical to float tolerance.

    Generated by LH and Claude
    """
    print("\n" + "=" * 70)
    print("STAGE 3: native (per-face) values")
    print("=" * 70)
    print("  Same physical grid from two stores -- these should be equal.\n")
    print(f"  {'variable':10s} {'max |diff|':>14s} {'max rel diff':>14s} "
          f"{'worst face':>11s}")

    ok = True
    for name in variables:
        if name not in osn or name not in dep:
            print(f"  {name:10s} (absent from one store -- skipped)")
            continue
        a, b = osn[name], dep[name]
        if a.dims != b.dims or a.shape != b.shape:
            print(f"  {name:10s} shape/dims mismatch -- skipped")
            ok = False
            continue
        diff = np.abs(a - b)
        scale = np.maximum(np.abs(a), 1e-30)
        max_abs = float(diff.max().compute())
        max_rel = float((diff / scale).max().compute())
        other = [d for d in diff.dims if d != "face"]
        per_face = diff.max(dim=other).compute()
        worst = int(per_face.argmax())
        good = max_rel < 1e-6
        ok &= good
        print(f"  {name:10s} {max_abs:14.6e} {max_rel:14.6e} "
              f"{worst:11d}{'' if good else '   <-- DIFFERS'}")

    if figures:
        _plot_face_montage(osn, dep, "XC", out_dir, stride)
    print(f"\nRESULT: native values {'match' if ok else 'DIFFER'}")
    return ok


def _plot_face_montage(osn, dep, name, out_dir, stride):
    """Draw OSN / DEPTH / difference for one variable, all 13 faces.

    Parameters
    ----------
    osn, dep : xarray.Dataset
        Processed grids.
    name : str
        Variable to draw.
    out_dir : pathlib.Path
        Output directory.
    stride : int
        Subsampling stride.

    Generated by LH and Claude
    """
    if name not in osn or name not in dep:
        return
    sub = dict(i=slice(None, None, stride), j=slice(None, None, stride))
    a = osn[name].isel(**{k: v for k, v in sub.items()
                          if k in osn[name].dims}).compute()
    b = dep[name].isel(**{k: v for k, v in sub.items()
                          if k in dep[name].dims}).compute()
    nface = a.sizes["face"]
    fig, axes = plt.subplots(3, nface, figsize=(2.0 * nface, 6.4),
                             constrained_layout=True)
    for f in range(nface):
        for row, (field, title) in enumerate(
                ((a, "OSN"), (b, "DEPTH"), (a - b, "OSN - DEPTH"))):
            ax = axes[row, f]
            cmap = "RdBu_r" if row == 2 else "viridis"
            ax.pcolormesh(field.isel(face=f).values, cmap=cmap)
            ax.set_xticks([])
            ax.set_yticks([])
            if row == 0:
                ax.set_title(f"face {f}", fontsize=8)
            if f == 0:
                ax.set_ylabel(title, fontsize=8)
    fig.suptitle(f"{name}: OSN vs LLC_DEPTH grid store "
                 f"(every {stride}th cell)", fontsize=11)
    path = out_dir / f"native_faces_{name}.png"
    fig.savefig(path, dpi=110)
    plt.close(fig)
    print(f"    figure -> {path}")


# ---------------------------------------------------------------------------
# Stage 4 -- ground truth from the data
# ---------------------------------------------------------------------------

def _haversine(lon0, lat0, lon1, lat1):
    """Great-circle distance [m] between two lon/lat arrays.

    Parameters
    ----------
    lon0, lat0, lon1, lat1 : array_like
        Degrees.

    Returns
    -------
    numpy.ndarray
        Distances in metres.

    Generated by LH and Claude
    """
    p0, p1 = np.radians(lat0), np.radians(lat1)
    dphi = p1 - p0
    dlam = np.radians(lon1 - lon0)
    h = (np.sin(dphi / 2) ** 2
         + np.cos(p0) * np.cos(p1) * np.sin(dlam / 2) ** 2)
    return 2 * EARTH_RADIUS_M * np.arcsin(np.sqrt(np.clip(h, 0, 1)))


def corner_registration(ds, face=1, sample=64):
    """Decide the registration from the CORNER coordinates, if present.

    MITgcm's ``XG``/``YG`` are the cell's south-west corner, so for cell
    ``i`` the u-point longitude ``XG[i]`` lies half a cell WEST of
    ``XC[i]``.  Testing which side ``XC[i]`` falls on is a HALF-CELL
    question (~1 km on LLC4320) and therefore immune to the sub-metre
    ambiguity that limits :func:`metric_registration`.

    Parameters
    ----------
    ds : xarray.Dataset
        Grid that still carries ``XG``/``YG`` (the raw store -- the
        ``process_llc4320_*grid`` filters drop them).
    face : int, default 1
        Face to test.
    sample : int, default 64
        Stride used when sampling rows/columns AFTER the neighbour
        differences are formed.

    Returns
    -------
    dict or None
        ``{'X': {...}, 'Y': {...}}`` with the fraction of sampled cells
        supporting each hypothesis and a verdict, or ``None`` when the
        corner coordinates are absent.

    Generated by LH and Claude
    """
    names = [(n, m) for n, m in (("XG", "XC"), ("YG", "YC"))
             if n in ds and m in ds]
    if len(names) < 1:
        return None

    out = {}
    for corner_name, centre_name, axis in (("XG", "XC", "X"),
                                           ("YG", "YC", "Y")):
        if corner_name not in ds or centre_name not in ds:
            continue
        g = np.asarray(ds[corner_name].isel(face=face))
        c = np.asarray(ds[centre_name].isel(face=face))
        # Neighbours must be taken BEFORE subsampling -- striding first
        # would compare cell i with cell i+sample.
        if axis == "X":
            g_here, g_next, centre = g[:, :-1], g[:, 1:], c[:, :-1]
        else:
            g_here, g_next, centre = g[:-1, :], g[1:, :], c[:-1, :]
        g_here = g_here[::sample, ::sample]
        g_next = g_next[::sample, ::sample]
        centre = centre[::sample, ::sample]
        # 'left'  : XG[i] <= XC[i] <= XG[i+1]  (corner i is cell i's west
        #           edge).  'right' is the mirror image.  Work with the
        #           signed offsets so a descending axis is handled too.
        step = g_next - g_here
        offset = centre - g_here
        with np.errstate(invalid="ignore", divide="ignore"):
            frac = offset / np.where(step == 0, np.nan, step)
        good = np.isfinite(frac)
        if not good.any():
            continue
        frac = frac[good]
        # frac ~ +0.5 -> centre sits between corner i and i+1 -> LEFT.
        # frac ~ -0.5 -> centre sits between corner i-1 and i -> RIGHT.
        left_votes = float(np.mean(np.abs(frac - 0.5) < 0.25))
        right_votes = float(np.mean(np.abs(frac + 0.5) < 0.25))
        out[axis] = {
            "median_fraction_of_cell": float(np.median(frac)),
            "left_support": left_votes,
            "right_support": right_votes,
            "verdict": ("left" if left_votes > right_votes else
                        "right" if right_votes > left_votes else
                        "inconclusive"),
        }
    return out or None


def metric_registration(ds, face=1):
    """Decide the registration from XC/YC and dxC/dyC.

    MITgcm defines ``dxC(i,j)`` as the distance between tracer centres
    ``(i-1,j)`` and ``(i,j)``, i.e. it sits on the WEST edge of cell
    ``(i,j)``.  Writing ``d[i] = geodesic(XC[i-1], XC[i])``:

    * LEFT  (``-0.5``): ``d[i] == dxC[i]``
    * RIGHT (``+0.5``): ``d[i] == dxC[i-1]``

    CAVEAT -- this test is only as sharp as the grid is non-uniform.
    The wrong alignment is wrong by one cell's worth of metric
    VARIATION, which on LLC4320 is well under a metre out of ~2 km, and
    our haversine is not MITgcm's own metric.  A constant bias between
    the two is therefore expected and is removed before comparing; what
    discriminates is the SCATTER.  When the two hypotheses are not
    clearly separated the verdict is ``'inconclusive'`` and
    :func:`corner_registration` should be used instead.

    Parameters
    ----------
    ds : xarray.Dataset
        Grid with ``XC``, ``YC``, ``dxC``, ``dyC``.
    face : int, default 1
        Face to test.

    Returns
    -------
    dict
        Per-axis scatter for each hypothesis, their separation ratio,
        and a verdict.

    Generated by LH and Claude
    """
    xc = np.asarray(ds["XC"].isel(face=face))
    yc = np.asarray(ds["YC"].isel(face=face))
    dxc = np.asarray(ds["dxC"].isel(face=face))
    dyc = np.asarray(ds["dyC"].isel(face=face))

    dx_between = _haversine(xc[:, :-1], yc[:, :-1], xc[:, 1:], yc[:, 1:])
    dy_between = _haversine(xc[:-1, :], yc[:-1, :], xc[1:, :], yc[1:, :])

    out = {}
    for axis, between, metric in (("X", dx_between, dxc),
                                  ("Y", dy_between, dyc)):
        if axis == "X":
            cand = {"left": metric[:, 1:], "right": metric[:, :-1]}
        else:
            cand = {"left": metric[1:, :], "right": metric[:-1, :]}
        cell = float(np.median(between))
        scatter = {}
        for name, arr in cand.items():
            residual = between - arr
            # Remove the constant haversine-vs-MITgcm bias; the
            # misalignment shows up as scatter, not offset.
            scatter[name] = float(np.std(residual - np.median(residual)))
        lo, hi = sorted(scatter.values())
        separation = (hi / lo) if lo > 0 else np.inf
        verdict = (min(scatter, key=scatter.get) if separation >= 3.0
                   else "inconclusive")
        out[axis] = {
            "cell_size_m": cell,
            "left_scatter_m": scatter["left"],
            "right_scatter_m": scatter["right"],
            "separation_ratio": separation,
            "verdict": verdict,
        }
    return out


def same_underlying_grid(a, b, face=1, names=("XC", "YC", "dxC", "dyC")):
    """Whether two stores hold numerically identical grid arrays.

    The corner test needs ``XG``/``YG``, which not every store carries.
    When the two stores demonstrably hold the SAME arrays, a verdict
    established on one transfers to the other -- the registration is a
    property of the grid, not of the store it was copied into.

    Parameters
    ----------
    a, b : xarray.Dataset
        Grids to compare.
    face : int, default 1
        Face to compare on.
    names : tuple of str
        Variables that must match.

    Returns
    -------
    (bool, dict)
        Whether every listed variable matches to float tolerance, and
        the per-variable max absolute difference.

    Generated by LH and Claude
    """
    diffs = {}
    for name in names:
        if name not in a or name not in b:
            diffs[name] = None
            continue
        va = a[name].isel(face=face)
        vb = b[name].isel(face=face)
        if va.shape != vb.shape:
            diffs[name] = np.inf
            continue
        diffs[name] = float(np.abs(np.asarray(va) - np.asarray(vb)).max())
    values = [d for d in diffs.values() if d is not None]
    return (bool(values) and all(d < 1e-6 for d in values)), diffs


def stage_truth(osn_raw, dep_raw, osn_proc, dep_proc, face=1):
    """Decide each grid's registration from the data, not the metadata.

    Runs the corner test first (sharp, half-cell scale) and falls back to
    the metric test (sub-metre, often inconclusive on a near-uniform
    grid).  A store with no corner coordinates inherits the other
    store's verdict when the two demonstrably hold the same arrays --
    otherwise a store that simply omitted ``XG``/``YG`` would escape the
    check entirely.

    Parameters
    ----------
    osn_raw, dep_raw : xarray.Dataset
        Grids as loaded, before the variable filters drop ``XG``/``YG``.
    osn_proc, dep_proc : xarray.Dataset
        The processed grids, used for the declared attributes.
    face : int, default 1
        Face to test.

    Returns
    -------
    bool
        True when every store's declared attribute matches the
        registration the data supports.

    Generated by LH and Claude
    """
    print("\n" + "=" * 70)
    print("STAGE 4: registration from the DATA (ignores all attributes)")
    print("=" * 70)

    stores = {"OSN": (osn_raw, osn_proc), "DEPTH": (dep_raw, dep_proc)}
    verdict_from_corners = {}

    # Pass 1: what can each store establish on its own?
    for label, (raw, proc) in stores.items():
        print(f"  {label} (face {face}):")
        corner = corner_registration(raw, face=face)
        if corner is None:
            print("    corner test: XG/YG absent from this store -- skipped")
        else:
            votes = []
            for axis, r in corner.items():
                print(f"    corner {axis}: centre sits "
                      f"{r['median_fraction_of_cell']:+.3f} of a cell from "
                      f"corner[i] | support left={r['left_support']:.2f} "
                      f"right={r['right_support']:.2f} "
                      f"-> {r['verdict'].upper()}")
                if r["verdict"] != "inconclusive":
                    votes.append(r["verdict"])
            if votes:
                verdict_from_corners[label] = max(set(votes), key=votes.count)

        if all(v in raw for v in ("XC", "YC", "dxC", "dyC")):
            for axis, r in metric_registration(raw, face=face).items():
                print(f"    metric {axis}: cell ~{r['cell_size_m']:.1f} m | "
                      f"scatter left={r['left_scatter_m']:.4f} m "
                      f"right={r['right_scatter_m']:.4f} m | "
                      f"separation x{r['separation_ratio']:.1f} "
                      f"-> {r['verdict'].upper()}")
        else:
            print("    metric test: XC/YC/dxC/dyC incomplete -- skipped")
        print()

    # Pass 2: transfer a verdict to any store that could not reach one,
    # provided the two stores hold the same arrays.
    identical, diffs = same_underlying_grid(osn_raw, dep_raw, face=face)
    inherited = {}
    for label in stores:
        if label in verdict_from_corners:
            continue
        donors = [d for d in verdict_from_corners if d != label]
        if identical and donors:
            donor = donors[0]
            inherited[label] = (verdict_from_corners[donor], donor)
    if inherited:
        shown = {k: (f"{v:.3e}" if isinstance(v, float) else v)
                 for k, v in diffs.items()}
        print(f"  The two stores hold identical arrays "
              f"(max |diff| {shown}),")
        print("  so a registration established on one applies to the "
              "other:")
        for label, (verdict, donor) in inherited.items():
            print(f"    {label} inherits '{verdict}' from {donor}")
        print()
    elif not identical:
        print(f"  Stores do NOT hold identical arrays (max |diff| "
              f"{diffs}); no verdict is transferred.\n")

    # Pass 3: compare each store's declared attribute with the verdict.
    ok = True
    for label, (_, proc) in stores.items():
        declared = coord_attrs(proc).get("i_g")
        declared = (declared.get("c_grid_axis_shift")
                    if isinstance(declared, dict) else None)
        expected = {-0.5: "left", 0.5: "right"}.get(
            float(declared) if declared is not None else None)
        if label in verdict_from_corners:
            data_says, how = verdict_from_corners[label], "own geometry"
        elif label in inherited:
            data_says, how = inherited[label][0], (
                f"inherited from {inherited[label][1]}")
        else:
            print(f"  {label}: declared {declared!r} -> {expected}; "
                  "data -> INCONCLUSIVE (no test could separate them)")
            continue
        agree = (expected == data_says)
        ok &= agree
        print(f"  {label}: declared {declared!r} -> {expected}; "
              f"data -> {data_says} ({how})  ==> "
              f"{'CONSISTENT' if agree else 'INCONSISTENT'}")
    print()
    print(f"RESULT: declared attributes {'match' if ok else 'CONTRADICT'} "
          "the data")
    return ok


# ---------------------------------------------------------------------------
# Stage 5 -- what xgcm actually does with each grid
# ---------------------------------------------------------------------------

def stage_xgcm(osn, dep):
    """Show the stencil consequences of each grid's declared attrs.

    Parameters
    ----------
    osn, dep : xarray.Dataset
        Processed grids.

    Returns
    -------
    bool
        True when both grids give xgcm the same axis positions.

    Generated by LH and Claude
    """
    print("\n" + "=" * 70)
    print("STAGE 5: what xgcm does with each grid")
    print("=" * 70)

    positions = {}
    for label, ds in (("OSN", osn), ("DEPTH", dep)):
        try:
            grid = set_xgcm_grid(ds, use_connections=True)
        except Exception as exc:
            print(f"  {label}: could not build xgcm Grid -- "
                  f"{type(exc).__name__}: {exc}")
            positions[label] = None
            continue
        coords = {ax: dict(grid.axes[ax].coords) for ax in ("X", "Y")
                  if ax in grid.axes}
        positions[label] = coords
        print(f"  {label}: {coords}")

        # Which halo does an interpolation to centres read, and therefore
        # which face edge becomes the seam?
        for axis in ("X", "Y"):
            entry = coords.get(axis, {})
            staggered = [p for p in entry if p != "center"]
            if not staggered:
                continue
            side = "upper" if staggered[0] == "left" else "lower"
            faces = sorted({f for f, ax, sd in edges_needing_a_rotated_halo()
                            if ax == axis and sd == side})
            print(f"      {axis}: staggered position '{staggered[0]}' -> "
                  f"reads the {side} halo -> seams on faces {faces}")

    agree = (positions.get("OSN") is not None
             and positions["OSN"] == positions.get("DEPTH"))
    print(f"\nRESULT: xgcm axis positions "
          f"{'AGREE' if agree else 'DISAGREE'} between the two pipelines")
    if not agree:
        print("  -> The faces themselves are identical (stage 3); what")
        print("     differs is which pair of cells each stencil combines.")
        print("     'left' reaches past the last index (upper halo), so the")
        print("     damaged column is a face's LAST; 'right' reaches past")
        print("     index 0 (lower halo), so it is the FIRST.  Every")
        print("     velocity-derived field is therefore shifted one cell")
        print("     along the model axis, and a different set of face edges")
        print("     is affected -- not because any face is flipped, but")
        print("     because only some connections rotate the neighbour.")
    return agree


# ---------------------------------------------------------------------------
# Stage 6 -- stitched comparison
# ---------------------------------------------------------------------------

def stage_stitch(osn, dep, variables, out_dir, figures=True, stride=24):
    """Stitch both grids to lat-lon and compare the rasters.

    Parameters
    ----------
    osn, dep : xarray.Dataset
        Processed grids.
    variables : list of str
        Scalar variables to stitch (staggered fields are skipped).
    out_dir : pathlib.Path
        Output directory.
    figures : bool, default True
        Whether to draw the comparison figure.
    stride : int, default 24
        Subsampling stride applied AFTER stitching, for plotting only.

    Returns
    -------
    bool
        True when the stitched rasters match.

    Generated by LH and Claude
    """
    from dbof.utils.faces_to_latlon import stitch_and_mask

    print("\n" + "=" * 70)
    print("STAGE 6: face -> lat-lon stitch")
    print("=" * 70)

    centre_vars = [v for v in variables
                   if v in osn and v in dep
                   and set(osn[v].dims) == {"face", "j", "i"}]
    if not centre_vars:
        print("  no cell-centred variables to stitch -- skipped")
        return True
    print(f"  stitching {centre_vars}")

    ok = True
    rasters = {}
    for label, ds in (("OSN", osn), ("DEPTH", dep)):
        arr = stitch_and_mask(ds, centre_vars, mask_dict={})
        rasters[label] = np.asarray(arr)
        print(f"    {label}: {rasters[label].shape}")

    for idx, name in enumerate(centre_vars):
        a, b = rasters["OSN"][idx], rasters["DEPTH"][idx]
        both = np.isfinite(a) & np.isfinite(b)
        max_abs = float(np.abs(a[both] - b[both]).max()) if both.any() else 0.0
        nan_mismatch = int((np.isfinite(a) ^ np.isfinite(b)).sum())
        good = max_abs < 1e-6 and nan_mismatch == 0
        ok &= good
        print(f"    {name:10s} max |diff| = {max_abs:.6e} | "
              f"NaN-pattern mismatches = {nan_mismatch}"
              f"{'' if good else '   <-- DIFFERS'}")

    if figures:
        name = centre_vars[0]
        a = rasters["OSN"][0][::stride, ::stride]
        b = rasters["DEPTH"][0][::stride, ::stride]
        fig, axes = plt.subplots(3, 1, figsize=(11, 10),
                                 constrained_layout=True)
        for ax, field, title, cmap in (
                (axes[0], a, f"{name} -- OSN", "viridis"),
                (axes[1], b, f"{name} -- LLC_DEPTH", "viridis"),
                (axes[2], a - b, f"{name} -- difference", "RdBu_r")):
            im = ax.pcolormesh(field, cmap=cmap)
            ax.set_title(title, fontsize=10)
            ax.set_xticks([])
            ax.set_yticks([])
            fig.colorbar(im, ax=ax, shrink=0.85)
        path = out_dir / f"stitched_{name}.png"
        fig.savefig(path, dpi=110)
        plt.close(fig)
        print(f"    figure -> {path}")

    print(f"\nRESULT: stitched rasters {'match' if ok else 'DIFFER'}")
    return ok


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main(argv=None):
    """Parse arguments, run the requested stages, and report.

    Parameters
    ----------
    argv : list of str, optional
        Command-line arguments; defaults to ``sys.argv[1:]``.

    Returns
    -------
    int
        0 when every stage passed, 1 otherwise.

    Generated by LH and Claude
    """
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--stages", nargs="+", choices=ALL_STAGES,
                        default=DEFAULT_STAGES)
    parser.add_argument("--variables", nargs="+", default=SHARED_VARS)
    parser.add_argument("--stride", type=int, default=24)
    parser.add_argument("--face", type=int, default=1,
                        help="face used for the stage-4 geometry test")
    parser.add_argument("--output-dir", type=Path,
                        default=Path("dev/output/grid_stores"))
    parser.add_argument("--no-figures", action="store_true")
    args = parser.parse_args(argv)

    args.output_dir.mkdir(parents=True, exist_ok=True)
    figures = not args.no_figures

    print("Loading OSN kerchunk grid ...")
    osn_raw, osn_proc = load_osn_grid()
    print("Loading LLC_DEPTH grid store ...")
    dep_raw, dep_proc = load_depth_grid()
    dep_store = (load_depth_store_unstamped()
                 if "attrs" in args.stages else None)

    results = {}
    if "attrs" in args.stages:
        results["attrs"] = stage_attrs(
            osn_raw, osn_proc, dep_raw, dep_proc, dep_store)
    if "vars" in args.stages:
        results["vars"] = stage_vars(osn_proc, dep_proc)
    if "native" in args.stages:
        results["native"] = stage_native(
            osn_proc, dep_proc, args.variables, args.output_dir,
            figures=figures, stride=args.stride)
    if "truth" in args.stages:
        results["truth"] = stage_truth(
            osn_raw, dep_raw, osn_proc, dep_proc, face=args.face)
    if "xgcm" in args.stages:
        results["xgcm"] = stage_xgcm(osn_proc, dep_proc)
    if "stitch" in args.stages:
        results["stitch"] = stage_stitch(
            osn_proc, dep_proc, args.variables, args.output_dir,
            figures=figures, stride=args.stride)

    print("\n" + "=" * 70)
    print("SUMMARY")
    print("=" * 70)
    for stage, passed in results.items():
        print(f"  {stage:8s} {'PASS' if passed else 'FAIL'}")
    report = args.output_dir / "grid_store_comparison.json"
    report.write_text(json.dumps(results, indent=2))
    print(f"\nreport -> {report}")
    return 0 if all(results.values()) else 1


if __name__ == "__main__":
    sys.exit(main())
