"""Unit tests for ``dbof.utils.native_gradient.calculate_jacobian``.

The plan for these tests is recorded in
``prompts/unit_tests.md`` (Native gradients / Jacobian).  The guiding
idea is that ``calculate_jacobian`` applies, in sequence, a rotation of
the model velocity components into geographic (zonal/meridional) axes and
a rotation of the gradient direction.  Algebraically the two rotations
compose to ``R . J_model . R^T`` -- the proper orthogonal rotation of the
2x2 velocity-gradient tensor ``J_model = [[a, b], [e, f]]`` where

    a = du/dx,  b = du/dy,  e = dv/dx,  f = dv/dy   (model basis).

Because that result is a closed form, we can build synthetic inputs whose
exact answer is known.  The synthetic grid mimics the full 13-face LLC
topology (so ``face_connections`` are exercised) but uses *uniform* metrics
(``dxC = dyC = d``) and *spatially constant* rotation coefficients so the
analytic answer holds.  Linear velocity fields on a uniform grid are
differenced and interpolated exactly, so the interior of every face matches
the analytic tensor to machine precision.  Face-edge cells are contaminated
by the (inconsistent) neighbouring-face linear fields exchanged through the
``face_connections`` halo, so a margin of cells is trimmed before comparing.

Generated by JXP and Claude
"""

import os
import tempfile

import numpy as np
import xarray as xr
import pytest

import dbof.utils.native_gradient as ng
from dbof.llc4320_ingestion.grid import set_xgcm_grid

# --- Real-grid (network) test configuration ------------------------------
# The real LLC4320 grid lives in an LLC_DEPTH-style zarr store on S3.
# ``face_connections`` needs the *face-separated* grid (face, j, i) at
# ``s3://dbof/LLC4320_RAW/DEPTH/grid.zarr`` — NOT the global 2-D mosaic
# store (``llc4320_grid.zarr``), which has no face dimension.
REAL_GRID_S3 = dict(
    s3_endpoint="https://s3-west.nrp-nautilus.io",
    bucket="dbof",
    folder="LLC4320_RAW/DEPTH",
)

# Local cache for the (small) subset of grid fields we need, so the
# multi-GB download happens at most once.  Override with the env var.
REAL_GRID_CACHE = os.environ.get(
    "LLC_TEST_GRID_CACHE",
    os.path.join(tempfile.gettempdir(), "llc4320_grid_cache.nc"))

# Real surface velocities (U, V) for Case G come from the LLC_SURF OSN
# kerchunk store, which stores a single surface level (k=0) -- so the read
# is genuinely surface-only (the LLC_DEPTH timestep stores chunk all 51
# levels together, forcing a ~50x larger read for one level).
REAL_UV_DATE = "2012-11-09 12:00:00"
REAL_UV_CACHE = os.environ.get(
    "LLC_TEST_UV_CACHE",
    os.path.join(tempfile.gettempdir(), "llc4320_caseG_UV.nc"))

# Network/slow tests are skipped unless the user opts in, so a normal
# ``pytest`` run never reaches out to S3.
RUN_NETWORK = bool(os.environ.get("RUN_LLC_NETWORK_TESTS"))

# LLC4320 has 13 faces; the synthetic grid reproduces all of them so the
# xgcm ``face_connections`` machinery is exercised by the tests.
N_FACES = 13

# Number of cells trimmed from every face edge before comparing to the
# analytic answer.  The X/Y chains each apply interp -> diff -> interp, so
# boundary fill / cross-face halo values can leak up to ~3 cells inward.
EDGE_MARGIN = 3


def make_synthetic_grid(n=16, d=2500.0, cs=1.0, sn=0.0, dy=None):
    """Build a 13-face synthetic LLC-like grid with uniform metrics.

    Parameters
    ----------
    n : int
        Number of cells per face along each horizontal dimension.  Must be
        comfortably larger than ``2 * EDGE_MARGIN`` so an interior remains.
    d : float
        Uniform grid spacing in metres for ``dxC`` (and for ``dyC`` when
        *dy* is None).
    cs, sn : float
        Spatially constant grid-rotation coefficients ``CS = cos(alpha)``
        and ``SN = sin(alpha)`` stored on tracer points.
    dy : float or None
        Uniform ``dyC`` spacing in metres.  When given and different from
        *d* the grid is **anisotropic** (dxC != dyC), which catches any
        accidental swap of the two metrics -- on an isotropic grid such a
        swap is invisible.  None (default) keeps ``dyC = d``.

    Returns
    -------
    ds : xarray.Dataset
        Grid dataset holding ``CS``, ``SN`` (tracer points ``(face, j, i)``),
        ``dxC`` (U points ``(face, j, i_g)``) and ``dyC`` (V points
        ``(face, j_g, i)``), with the comodo ``axis`` /
        ``c_grid_axis_shift`` attributes xgcm needs.
    grid : xgcm.Grid
        Grid built with the production LLC ``face_connections``.

    Generated by JXP and Claude
    """
    # 1-D index coordinates.  i_g/j_g are the staggered (cell-edge) axes;
    # the comodo attributes tell xgcm how each axis relates to the centre.
    idx = np.arange(n)
    coords = {
        "face": ("face", np.arange(N_FACES)),
        "i": ("i", idx, {"axis": "X"}),
        "i_g": ("i_g", idx, {"axis": "X", "c_grid_axis_shift": 0.5}),
        "j": ("j", idx, {"axis": "Y"}),
        "j_g": ("j_g", idx, {"axis": "Y", "c_grid_axis_shift": 0.5}),
    }

    # Rotation coefficients live on tracer points (face, j, i).
    cs_da = xr.DataArray(np.full((N_FACES, n, n), cs),
                         dims=("face", "j", "i"))
    sn_da = xr.DataArray(np.full((N_FACES, n, n), sn),
                         dims=("face", "j", "i"))

    # Cell-spacing metrics: dxC on U points, dyC on V points.  dy defaults
    # to d (isotropic); pass dy != d for an anisotropic grid.
    if dy is None:
        dy = d
    dxc = xr.DataArray(np.full((N_FACES, n, n), d),
                       dims=("face", "j", "i_g"))
    dyc = xr.DataArray(np.full((N_FACES, n, n), dy),
                       dims=("face", "j_g", "i"))

    ds = xr.Dataset(
        {"CS": cs_da, "SN": sn_da, "dxC": dxc, "dyC": dyc},
        coords=coords,
    )

    # Reuse the production grid constructor (with LLC face connections).
    grid = set_xgcm_grid(ds, use_connections=True)
    return ds, grid


def add_linear_velocity(ds, d, a, b, e, f, dy=None):
    """Add linear ``U`` and ``V`` velocity fields to the synthetic grid.

    The fields are ``u = a*x + b*y`` on U points and ``v = e*x + f*y`` on
    V points, where ``x`` / ``y`` are position in metres (index times the
    uniform spacing along each axis).  Linear fields are chosen because
    finite differences and linear interpolation reproduce them exactly, so
    the computed gradient tensor equals the analytic ``J_model = [[a, b],
    [e, f]]`` (before rotation) to machine precision.  Only slopes matter
    for the result, so any constant position offset is irrelevant.

    Parameters
    ----------
    ds : xarray.Dataset
        Synthetic grid from :func:`make_synthetic_grid`; modified in place
        to carry ``U`` and ``V``.
    d : float
        Uniform x grid spacing in metres (must match the grid's ``dxC``).
    a, b : float
        Zonal-velocity slopes du/dx and du/dy (model basis).
    e, f : float
        Meridional-velocity slopes dv/dx and dv/dy (model basis).
    dy : float or None
        Uniform y grid spacing in metres (must match the grid's ``dyC``).
        None (default) uses *d* (isotropic grid).

    Returns
    -------
    u_x : xarray.DataArray
        Zonal velocity on U points ``(face, j, i_g)``.
    v_y : xarray.DataArray
        Meridional velocity on V points ``(face, j_g, i)``.

    Generated by JXP and Claude
    """
    n = ds.sizes["i"]
    if dy is None:
        dy = d
    pos_x = np.arange(n) * d   # positions along the model-x axis
    pos_y = np.arange(n) * dy  # positions along the model-y axis

    # U on (face, j, i_g): varies as a*x along i_g and b*y along j.
    u2d = a * pos_x[None, :] + b * pos_y[:, None]      # (j, i_g)
    u3d = np.broadcast_to(u2d, (N_FACES, n, n)).copy()
    u_x = xr.DataArray(u3d, dims=("face", "j", "i_g"),
                       coords={c: ds.coords[c]
                               for c in ("face", "j", "i_g")},
                       name="U")

    # V on (face, j_g, i): varies as e*x along i and f*y along j_g.
    v2d = e * pos_x[None, :] + f * pos_y[:, None]      # (j_g, i)
    v3d = np.broadcast_to(v2d, (N_FACES, n, n)).copy()
    v_y = xr.DataArray(v3d, dims=("face", "j_g", "i"),
                       coords={c: ds.coords[c]
                               for c in ("face", "j_g", "i")},
                       name="V")

    ds["U"] = u_x
    ds["V"] = v_y
    return u_x, v_y


def interior(da, margin=EDGE_MARGIN):
    """Return the face interior, trimming ``margin`` cells from each edge.

    Edge cells are excluded because boundary fill and cross-face halo
    exchange (through ``face_connections``) inject values from inconsistent
    neighbouring linear fields, which are not part of the analytic answer.

    Parameters
    ----------
    da : xarray.DataArray
        Field on tracer points with ``i`` and ``j`` dimensions.
    margin : int
        Number of cells to drop from each edge along ``i`` and ``j``.

    Returns
    -------
    xarray.DataArray
        The trimmed interior region.

    Generated by JXP and Claude
    """
    return da.isel(i=slice(margin, -margin), j=slice(margin, -margin))


def analytic_rotated_jacobian(a, b, e, f, cs, sn):
    """Return the analytic geographic Jacobian ``R . J_model . R^T``.

    The two rotations inside ``calculate_jacobian`` compose to a single
    similarity transform of the model-basis gradient tensor
    ``J_model = [[a, b], [e, f]]`` by the orthogonal rotation
    ``R = [[CS, -SN], [SN, CS]]``.  For spatially constant ``CS, SN`` and
    linear velocity fields this transform is the exact expected interior
    result, component by component.

    Parameters
    ----------
    a, b : float
        Zonal-velocity slopes du/dx and du/dy (model basis).
    e, f : float
        Meridional-velocity slopes dv/dx and dv/dy (model basis).
    cs, sn : float
        Rotation coefficients ``CS = cos(alpha)`` and ``SN = sin(alpha)``.

    Returns
    -------
    du_lambda_dlambda, du_lambda_dphi, dv_phi_dlambda, dv_phi_dphi : float
        The four entries of ``R . J_model . R^T`` in the order returned by
        :func:`dbof.utils.native_gradient.calculate_jacobian`.

    Generated by JXP and Claude
    """
    # M = R . J_model.
    m00 = cs * a - sn * e
    m01 = cs * b - sn * f
    m10 = sn * a + cs * e
    m11 = sn * b + cs * f
    # (M . R^T) with R^T = [[CS, SN], [-SN, CS]].
    dudl = m00 * cs - m01 * sn
    dudp = m00 * sn + m01 * cs
    dvdl = m10 * cs - m11 * sn
    dvdp = m10 * sn + m11 * cs
    return dudl, dudp, dvdl, dvdp


def add_constant_velocity(ds, u0, v0):
    """Add spatially constant ``U`` and ``V`` fields to the synthetic grid.

    A constant field has zero gradient everywhere, so after any rotation
    ``calculate_jacobian`` must return zeros on every face interior.  This
    isolates the rotation machinery: any non-zero interior gradient would
    be a spurious gradient introduced by the rotation, not by the data.

    Parameters
    ----------
    ds : xarray.Dataset
        Synthetic grid from :func:`make_synthetic_grid`; modified in place.
    u0 : float
        Constant zonal-velocity value placed on U points.
    v0 : float
        Constant meridional-velocity value placed on V points.

    Returns
    -------
    u_x : xarray.DataArray
        Constant zonal velocity on U points ``(face, j, i_g)``.
    v_y : xarray.DataArray
        Constant meridional velocity on V points ``(face, j_g, i)``.

    Generated by JXP and Claude
    """
    n = ds.sizes["i"]
    # Build constant fields directly on the staggered velocity points.
    u_x = xr.DataArray(np.full((N_FACES, n, n), u0),
                       dims=("face", "j", "i_g"),
                       coords={c: ds.coords[c]
                               for c in ("face", "j", "i_g")},
                       name="U")
    v_y = xr.DataArray(np.full((N_FACES, n, n), v0),
                       dims=("face", "j_g", "i"),
                       coords={c: ds.coords[c]
                               for c in ("face", "j_g", "i")},
                       name="V")
    ds["U"] = u_x
    ds["V"] = v_y
    return u_x, v_y


def test_jacobian_no_rotation_recovers_model_gradients():
    """Test Case A: with CS=1, SN=0 the Jacobian equals the model gradients.

    When the grid rotation is the identity (``CS=1, SN=0``) the geographic
    axes coincide with the model axes, so ``R . J_model . R^T = J_model``.
    For the linear velocity fields ``u = a*x + b*y`` and ``v = e*x + f*y``
    the four returned components must therefore equal the constant slopes:

        du_lambda_dlambda = a,   du_lambda_dphi = b,
        dv_phi_dlambda    = e,   dv_phi_dphi    = f,

    everywhere in each face interior, to machine precision.  This validates
    the derivative values and the ``/dxC``, ``/dyC`` metric scaling.

    Returns
    -------
    None
        Passes by assertion; raises AssertionError on mismatch.

    Generated by JXP and Claude
    """
    # Uniform spacing and realistic O(1e-5 s^-1) velocity-gradient slopes.
    d = 2500.0
    a, b, e, f = 1.0e-5, 2.0e-5, -3.0e-5, 4.0e-5

    # Identity rotation: CS=1, SN=0.
    ds, grid = make_synthetic_grid(n=16, d=d, cs=1.0, sn=0.0)
    u_x, v_y = add_linear_velocity(ds, d, a, b, e, f)

    dudl, dudp, dvdl, dvdp = ng.calculate_jacobian(u_x, v_y, ds, grid)

    # Compare the trimmed interior of every face to the analytic constants.
    # rtol handles the ~1e-15 rounding from the multiply/divide chain.
    tol = dict(rtol=1e-9, atol=0.0)
    np.testing.assert_allclose(interior(dudl).values, a, **tol)
    np.testing.assert_allclose(interior(dudp).values, b, **tol)
    np.testing.assert_allclose(interior(dvdl).values, e, **tol)
    np.testing.assert_allclose(interior(dvdp).values, f, **tol)

    # Sanity: outputs are on tracer points (no staggered dims survive).
    for out in (dudl, dudp, dvdl, dvdp):
        assert "i_g" not in out.dims
        assert "j_g" not in out.dims
        assert set(("face", "j", "i")).issubset(out.dims)


def test_jacobian_90deg_rotation_sign_conventions():
    """Test Case B: a 90-degree grid rotation checks the sign conventions.

    With ``CS=0, SN=1`` the rotation is a quarter turn and
    ``R . J_model . R^T = [[f, -e], [-b, a]]``.  For the linear fields the
    four returned components must therefore equal, on each face interior:

        du_lambda_dlambda =  f,   du_lambda_dphi = -e,
        dv_phi_dlambda    = -b,   dv_phi_dphi    =  a.

    The flipped signs and swapped roles exercise exactly the part of the
    code most prone to a sign error in either rotation.

    Returns
    -------
    None
        Passes by assertion; raises AssertionError on mismatch.

    Generated by JXP and Claude
    """
    d = 2500.0
    a, b, e, f = 1.0e-5, 2.0e-5, -3.0e-5, 4.0e-5

    # Quarter-turn rotation: CS=0, SN=1.
    ds, grid = make_synthetic_grid(n=16, d=d, cs=0.0, sn=1.0)
    u_x, v_y = add_linear_velocity(ds, d, a, b, e, f)

    dudl, dudp, dvdl, dvdp = ng.calculate_jacobian(u_x, v_y, ds, grid)

    # Analytic targets for a 90-degree rotation: [[f, -e], [-b, a]].
    t_dudl, t_dudp, t_dvdl, t_dvdp = analytic_rotated_jacobian(
        a, b, e, f, cs=0.0, sn=1.0)

    tol = dict(rtol=1e-7, atol=1e-12)
    np.testing.assert_allclose(interior(dudl).values, t_dudl, **tol)
    np.testing.assert_allclose(interior(dudp).values, t_dudp, **tol)
    np.testing.assert_allclose(interior(dvdl).values, t_dvdl, **tol)
    np.testing.assert_allclose(interior(dvdp).values, t_dvdp, **tol)


def test_jacobian_rotation_only_constant_field_zero_gradient():
    """Test Case C: a rotated constant field has zero gradient everywhere.

    With a non-trivial rotation (45 degrees here) but a spatially constant
    velocity field, the true gradient is identically zero.  The rotation
    mixes the (constant) components but cannot manufacture spatial
    structure, so every interior component must be zero to machine
    precision.  Any non-zero interior value would reveal the rotation
    machinery injecting spurious gradients.

    Returns
    -------
    None
        Passes by assertion; raises AssertionError on mismatch.

    Generated by JXP and Claude
    """
    d = 2500.0
    alpha = np.radians(45.0)
    cs, sn = np.cos(alpha), np.sin(alpha)

    # Arbitrary non-zero constant velocities; their values must not matter.
    u0, v0 = 0.37, -0.12

    ds, grid = make_synthetic_grid(n=16, d=d, cs=cs, sn=sn)
    u_x, v_y = add_constant_velocity(ds, u0, v0)

    dudl, dudp, dvdl, dvdp = ng.calculate_jacobian(u_x, v_y, ds, grid)

    # Gradient of a constant is exactly zero on the interior.
    for out in (dudl, dudp, dvdl, dvdp):
        np.testing.assert_allclose(interior(out).values, 0.0, atol=1e-15)


@pytest.mark.parametrize("alpha_deg", [0.0, 30.0, 45.0, 90.0, 137.0])
def test_jacobian_general_angle_matches_rotation(alpha_deg):
    """Test Case D: arbitrary rotation angle matches ``R . J_model . R^T``.

    Sweeps a range of grid-rotation angles (including the Case A and Case B
    angles, which this test subsumes) and asserts that all four returned
    components equal the analytic similarity transform of the model-basis
    Jacobian, on each face interior.  This validates the full rotation
    composition for arbitrary angles, not just the special cases.

    Parameters
    ----------
    alpha_deg : float
        Grid-rotation angle in degrees (pytest-parametrized).

    Returns
    -------
    None
        Passes by assertion; raises AssertionError on mismatch.

    Generated by JXP and Claude
    """
    d = 2500.0
    a, b, e, f = 1.0e-5, 2.0e-5, -3.0e-5, 4.0e-5
    alpha = np.radians(alpha_deg)
    cs, sn = np.cos(alpha), np.sin(alpha)

    ds, grid = make_synthetic_grid(n=16, d=d, cs=cs, sn=sn)
    u_x, v_y = add_linear_velocity(ds, d, a, b, e, f)

    dudl, dudp, dvdl, dvdp = ng.calculate_jacobian(u_x, v_y, ds, grid)

    targets = analytic_rotated_jacobian(a, b, e, f, cs=cs, sn=sn)

    tol = dict(rtol=1e-7, atol=1e-12)
    for out, target in zip((dudl, dudp, dvdl, dvdp), targets):
        np.testing.assert_allclose(interior(out).values, target, **tol)


@pytest.mark.parametrize("alpha_deg", [0.0, 30.0])
def test_jacobian_anisotropic_grid_metrics(alpha_deg):
    """Anisotropic grid (dxC != dyC): the metric scaling stays correct.

    On an isotropic grid (``dxC = dyC``) an accidental swap of the two
    metrics -- dividing the x-difference by ``dyC`` or vice versa -- is
    invisible.  Here ``dyC = 2.4 * dxC``, so a swapped metric would scale
    the du/dy and dv/dy entries by 2.4 (and the x entries by 1/2.4), far
    outside tolerance.  The linear velocity fields are built with the same
    anisotropic spacings, so the interior answer is still the exact
    analytic ``R . J_model . R^T`` (identity at 0 degrees, and a generic
    angle to exercise the rotation on the anisotropic grid too).

    Parameters
    ----------
    alpha_deg : float
        Grid-rotation angle in degrees (pytest-parametrized).

    Returns
    -------
    None
        Passes by assertion; raises AssertionError on mismatch.

    Generated by JXP and Claude
    """
    d, dy = 2500.0, 6000.0        # strongly anisotropic: dy = 2.4 dx
    a, b, e, f = 1.0e-5, 2.0e-5, -3.0e-5, 4.0e-5
    alpha = np.radians(alpha_deg)
    cs, sn = np.cos(alpha), np.sin(alpha)

    ds, grid = make_synthetic_grid(n=16, d=d, cs=cs, sn=sn, dy=dy)
    u_x, v_y = add_linear_velocity(ds, d, a, b, e, f, dy=dy)

    outputs = ng.calculate_jacobian(u_x, v_y, ds, grid)
    targets = analytic_rotated_jacobian(a, b, e, f, cs=cs, sn=sn)

    tol = dict(rtol=1e-7, atol=1e-12)
    for out, target in zip(outputs, targets):
        np.testing.assert_allclose(interior(out).values, target, **tol)


def test_jacobian_output_coordinate_contract():
    """Test Case E: outputs live on tracer points with the input shape.

    Independent of the rotation, all four returned components must be on
    tracer centres (dims ``face, j, i``), must not carry the staggered
    ``i_g`` / ``j_g`` axes, and must preserve the per-face ``(n, n)`` shape
    of the input grid.  This pins down the coordinate contract the rest of
    the pipeline relies on.

    Returns
    -------
    None
        Passes by assertion; raises AssertionError on mismatch.

    Generated by JXP and Claude
    """
    d = 2500.0
    n = 16
    # Use a generic (non-identity) rotation so the contract is not tied to
    # any special angle.
    alpha = np.radians(33.0)
    ds, grid = make_synthetic_grid(n=n, d=d,
                                   cs=np.cos(alpha), sn=np.sin(alpha))
    u_x, v_y = add_linear_velocity(ds, d, 1.0e-5, 2.0e-5, -3.0e-5, 4.0e-5)

    outputs = ng.calculate_jacobian(u_x, v_y, ds, grid)

    for out in outputs:
        # On tracer points, no staggered axes survive.
        assert "i_g" not in out.dims
        assert "j_g" not in out.dims
        assert set(("face", "j", "i")).issubset(out.dims)
        # Per-face shape is preserved.
        assert out.sizes["face"] == N_FACES
        assert out.sizes["i"] == n
        assert out.sizes["j"] == n


# --------------------------------------------------------------------------
# Real LLC4320 grid (Test Case F).  Network/slow -- skipped by default.
# --------------------------------------------------------------------------

# Only the horizontal grid fields the tests need: the Jacobian inputs, the
# land mask, and the cell-centre lon/lat (XC/YC) used by the analytic
# face-consistency test in ``test_native_gradient_tracer.py``.
_REAL_GRID_VARS = ["CS", "SN", "dxC", "dyC", "hFacC", "XC", "YC"]


def load_real_llc_grid(cache_path=REAL_GRID_CACHE):
    """Load the real LLC4320 grid fields, caching a small subset locally.

    Downloads the face-separated LLC4320 grid from the LLC_DEPTH S3 store
    via :func:`get_raw_data.get_llc_depth_gridfile`, keeps only the fields
    the tests need (``CS``, ``SN``, ``dxC``, ``dyC``, plus ``hFacC`` for
    the ocean mask and ``XC``/``YC`` for lon/lat-based tests and regional
    figures), and writes them to a local NetCDF cache so the multi-GB
    download happens at most once.  Subsequent calls read the cache.  A
    cache written by an older version of this module (missing some of the
    fields) is detected and refreshed automatically.

    Parameters
    ----------
    cache_path : str
        Path to the local NetCDF cache.  Defaults to ``REAL_GRID_CACHE``
        (overridable via the ``LLC_TEST_GRID_CACHE`` env var).

    Returns
    -------
    xarray.Dataset
        Eagerly-loaded grid with ``CS``, ``SN``, ``hFacC``, ``XC``, ``YC``
        on tracer points, ``dxC`` on U points, ``dyC`` on V points, and the
        comodo ``axis`` / ``c_grid_axis_shift`` coordinate attributes.

    Generated by JXP and Claude
    """
    if os.path.exists(cache_path):
        cached = xr.open_dataset(cache_path)
        # XC/YC may be data variables or coordinates in the cache.
        present = set(cached.variables)
        if all(v in present for v in _REAL_GRID_VARS):
            return cached
        # Stale cache from an older module version: refresh it below.
        cached.close()

    # Import here so a default (no-network) test run never imports the S3
    # ingestion stack.
    from dbof.llc4320_ingestion import get_raw_data

    co = get_raw_data.get_llc_depth_gridfile(
        REAL_GRID_S3["s3_endpoint"], REAL_GRID_S3["bucket"],
        REAL_GRID_S3["folder"])
    # XC/YC are coordinates in the zarr store; promote them to variables so
    # the single-subset select below carries them along.
    co = co.reset_coords([c for c in ("XC", "YC") if c in co.coords])
    sub = co[_REAL_GRID_VARS].compute()  # eager: small subset, ~7 GB max

    # Best-effort cache; a failure here must not fail the test.
    try:
        sub.to_netcdf(cache_path)
    except OSError:
        pass
    return sub


@pytest.mark.slow
@pytest.mark.network
@pytest.mark.skipif(not RUN_NETWORK,
                    reason="needs network/S3; set RUN_LLC_NETWORK_TESTS=1")
def test_jacobian_real_grid_constant_field_zero_gradient():
    """Test Case F: a constant field has ~zero gradient on the real grid.

    Feeds a spatially constant model velocity field through
    ``calculate_jacobian`` on the *real* curvilinear LLC4320 grid (with its
    true ``CS``/``SN``, metrics and 13-face ``face_connections``) and checks
    that the returned gradient tensor is essentially zero over the ocean
    interior.

    Why a robust statistic, not the global max: the ECCO routine rotates the
    velocity into geographic axes *before* differencing, so it differentiates
    ``u_lambda = U0*CS - V0*SN``.  Where the grid rotation ``CS``/``SN`` is
    locally smooth (the overwhelming majority of ocean points) this is
    constant and its gradient is zero to machine precision.  Near grid
    singularities (the Arctic-cap face and cube-sphere face corners) the real
    term ``grad(CS)`` is large, so a constant field there legitimately
    acquires an apparent gradient.  That is physics of the grid, not a bug,
    so we assert on the median and a high percentile rather than the max:

    - median over ocean interior is at machine precision (empirically
      ~3e-17), proving the diff / interp / metric machinery introduces no
      spurious gradient for constant fields;
    - the 99th percentile is tiny (empirically ~5e-7), proving the bulk of
      the grid is unaffected by curvature.

    Returns
    -------
    None
        Passes by assertion; raises AssertionError on mismatch.

    Generated by JXP and Claude
    """
    ds = load_real_llc_grid()
    grid = set_xgcm_grid(ds.drop_vars("hFacC"), use_connections=True)

    # Arbitrary non-zero constant model velocities; values must not matter.
    u_x, v_y = add_constant_velocity(ds, u0=0.5, v0=-0.3)

    outputs = ng.calculate_jacobian(u_x, v_y, ds, grid)

    # Ocean mask (hFacC > 0), with the face-edge ring trimmed as elsewhere.
    ocean = interior(ds["hFacC"]).values > 0
    assert ocean.any()

    # Pool all four components over the ocean interior.
    pooled = np.concatenate(
        [np.abs(interior(out).values[ocean]) for out in outputs])

    assert np.all(np.isfinite(pooled))           # no NaN/inf leaked in
    # Median is machine-precision zero (huge margin over the ~3e-17 seen).
    assert np.median(pooled) < 1e-12
    # The bulk of the grid is unaffected by curvature (~5e-7 observed).
    assert np.percentile(pooled, 99.0) < 1e-5

    # Outputs honour the tracer-point coordinate contract.
    for out in outputs:
        assert "i_g" not in out.dims and "j_g" not in out.dims
        assert set(("face", "j", "i")).issubset(out.dims)


def load_real_llc_surface_velocity(cache_path=REAL_UV_CACHE):
    """Load real LLC4320 surface ``U``/``V``, caching locally.

    Reads the surface (k=0) model-frame velocity components from the
    LLC_SURF OSN kerchunk store via
    :func:`get_raw_data.get_remote_llc_data` and caches them to a local
    NetCDF.  The OSN store holds only the surface level, so this is a true
    surface-only read (~2 GB) -- unlike the LLC_DEPTH timestep stores, which
    chunk all 51 vertical levels together.

    Parameters
    ----------
    cache_path : str
        Path to the local NetCDF cache.  Defaults to ``REAL_UV_CACHE``
        (overridable via the ``LLC_TEST_UV_CACHE`` env var).

    Returns
    -------
    u_x : xarray.DataArray
        Zonal model-frame velocity on U points ``(face, j, i_g)``.
    v_y : xarray.DataArray
        Meridional model-frame velocity on V points ``(face, j_g, i)``.

    Generated by JXP and Claude
    """
    if os.path.exists(cache_path):
        uv = xr.open_dataset(cache_path)
        return uv["U"], uv["V"]

    # Import here so a default (no-network) test run never imports the OSN
    # ingestion stack.
    from dbof.llc4320_ingestion import get_raw_data
    from dbof.global_dataset_creation.data_sources import OSN_ENDPOINT
    from dbof.global_dataset_creation.iterations import osn_date_to_iteration

    it = osn_date_to_iteration(REAL_UV_DATE)
    ds = get_raw_data.get_remote_llc_data(OSN_ENDPOINT, it, range(N_FACES))
    u_x = ds["U"].astype("float32").compute()
    v_y = ds["V"].astype("float32").compute()

    try:
        xr.Dataset({"U": u_x, "V": v_y}).to_netcdf(cache_path)
    except OSError:
        pass
    return u_x, v_y


def model_frame_jacobian(u_x, v_y, ds, grid):
    """Return the Jacobian with the grid rotation forced to the identity.

    Re-runs ``calculate_jacobian`` on a copy of ``ds`` whose rotation
    coefficients are ``CS=1, SN=0`` (identity), so the four outputs are the
    *model-frame* velocity gradients -- the rotation step is a no-op.  This
    is the reference against which the geographic (real-``CS``/``SN``)
    Jacobian's trace and antisymmetric part are compared in Case G.

    Parameters
    ----------
    u_x, v_y : xarray.DataArray
        Model-frame velocity components on U / V points.
    ds : xarray.Dataset
        Real grid dataset (provides ``dxC``, ``dyC``; its ``CS``/``SN`` are
        overridden).
    grid : xgcm.Grid
        Grid object with the LLC ``face_connections``.

    Returns
    -------
    tuple of xarray.DataArray
        ``(du_dx, du_dy, dv_dx, dv_dy)`` in the model frame.

    Generated by JXP and Claude
    """
    ds_id = ds.copy()
    ds_id["CS"] = xr.ones_like(ds["CS"])
    ds_id["SN"] = xr.zeros_like(ds["SN"])
    return ng.calculate_jacobian(u_x, v_y, ds_id, grid)


@pytest.mark.slow
@pytest.mark.network
@pytest.mark.skipif(not RUN_NETWORK,
                    reason="needs network/S3; set RUN_LLC_NETWORK_TESTS=1")
def test_jacobian_real_grid_rotation_invariance_trace_curl():
    """Test Case G: trace and curl are rotation-invariant on the real grid.

    Divergence (the trace ``du_lambda_dlambda + dv_phi_dphi``) and vorticity
    (the antisymmetric part ``dv_phi_dlambda - du_lambda_dphi``) are
    invariants of the velocity-gradient tensor under an orthogonal rotation
    of the frame.  So the geographic-frame divergence/vorticity from
    ``calculate_jacobian`` (using the real ``CS``/``SN``) must match the
    model-frame divergence/vorticity (identity rotation) computed from the
    *same* real velocities -- a strong, truth-free correctness check of the
    rotation logic.

    The match is not bit-exact everywhere: because the routine differences
    the *rotated* field, spatially-varying ``CS``/``SN`` inject ``grad(CS)``
    terms near grid singularities (Arctic cap, cube-sphere corners).  These
    are real and tiny, so we assert robust statistics:

    - the signal is genuinely non-zero (model-frame divergence RMS is
      O(1e-5)), so this is not a trivial 0 == 0 comparison;
    - the median absolute difference is ~0 (bit-identical where the rotation
      is locally smooth -- the bulk of the ocean);
    - the difference RMS is < 2% of the signal RMS (empirically ~0.3%);
    - the 99th-percentile absolute difference is tiny (empirically ~2e-7).

    Returns
    -------
    None
        Passes by assertion; raises AssertionError on mismatch.

    Generated by JXP and Claude
    """
    ds = load_real_llc_grid()
    grid = set_xgcm_grid(ds.drop_vars("hFacC"), use_connections=True)

    u_x, v_y = load_real_llc_surface_velocity()
    # Align coords to the grid so xgcm pairs the staggered axes correctly.
    u_x = u_x.assign_coords(
        {c: ds.coords[c] for c in u_x.dims if c in ds.coords})
    v_y = v_y.assign_coords(
        {c: ds.coords[c] for c in v_y.dims if c in ds.coords})

    geo = ng.calculate_jacobian(u_x, v_y, ds, grid)        # real CS/SN
    mod = model_frame_jacobian(u_x, v_y, ds, grid)         # identity

    # Divergence (trace) and vorticity (antisymmetric part) in each frame.
    geo_div, mod_div = geo[0] + geo[3], mod[0] + mod[3]
    geo_vort, mod_vort = geo[2] - geo[1], mod[2] - mod[1]

    ocean = interior(ds["hFacC"]).values > 0
    for geo_inv, mod_inv in ((geo_div, mod_div), (geo_vort, mod_vort)):
        g_vals = interior(geo_inv).values[ocean]
        m_vals = interior(mod_inv).values[ocean]
        finite = np.isfinite(g_vals) & np.isfinite(m_vals)
        g_vals, m_vals = g_vals[finite], m_vals[finite]

        signal_rms = np.sqrt(np.mean(m_vals ** 2))
        diff = np.abs(g_vals - m_vals)
        diff_rms = np.sqrt(np.mean(diff ** 2))

        # Real, non-trivial signal -- not a 0 == 0 comparison.
        assert signal_rms > 1e-6
        # Bit-identical where the rotation is locally smooth.
        assert np.median(diff) < 1e-10
        # Invariant to < 2% RMS (the grad(rotation) residual is ~0.3%).
        assert diff_rms / signal_rms < 2e-2
        # The bulk of points agree to ~machine precision.
        assert np.percentile(diff, 99.0) < 1e-6
