"""Integration test: global_input against the real S3 example directory.

Requires access to the NRP S3 endpoint named in the example config.
Skips gracefully when the store is unreachable (offline / no credentials).
"""
from pathlib import Path

import pytest

from dbof.cutout_dataset_creation.config import load_config, InputConfig
from dbof.io.filesystems import create_s3_filesystems
from dbof.cutout_dataset_creation.global_input import (
    resolve_date_prefixes,
    available_channels,
    verify_feature_channels,
)

EXAMPLE_CONFIG = Path(__file__).resolve().parents[1] / "configs/cutouts/run/run_from_globals_example.yaml"
ACCESS_CONFIG = Path(__file__).resolve().parents[1] / "configs/cutouts/data_access/cutout_test_data_v1.yaml"
DATE = "20120209_120000"
ARTIFACTS_DIR = Path(__file__).resolve().parent / "output"


@pytest.fixture(scope="module")
def example_input():
    cfg = load_config(str(EXAMPLE_CONFIG))
    fs, fs_sync = create_s3_filesystems(cfg.input.s3_endpoint)
    base = f"{cfg.input.bucket.strip('/')}/{cfg.input.folder.strip('/')}"
    try:
        fs_sync.ls(base, detail=True)
    except Exception as exc:
        pytest.skip(f"input store unreachable ({base}): {exc}")
    return cfg, fs, fs_sync


def test_discovers_real_date_prefix(example_input):
    cfg, fs, fs_sync = example_input
    discover_cfg = InputConfig(
        folder=cfg.input.folder, bucket=cfg.input.bucket, s3_endpoint=cfg.input.s3_endpoint,
    )  # no date_prefixes -> force discovery
    assert DATE in resolve_date_prefixes(discover_cfg, fs_sync)


def test_available_channels_contains_known_fields(example_input):
    cfg, fs, fs_sync = example_input
    chans = available_channels(cfg.input, DATE, fs, fs_sync)
    assert {"Theta", "Salt", "Eta", "U", "V", "W"}.issubset(chans)
    assert "gradb2" in chans


def test_verify_present_and_absent(example_input):
    cfg, fs, fs_sync = example_input
    verify_feature_channels(cfg.input, DATE, ["Theta", "gradb2"], fs, fs_sync)  # present -> no raise
    # frontogenesis subset was not generated for this run, so its channels are absent.
    with pytest.raises(ValueError, match="frontogenesis_tendency"):
        verify_feature_channels(cfg.input, DATE, ["frontogenesis_tendency"], fs, fs_sync)


def test_land_mask_renders(example_input):
    """Build the stitched halo land mask from the real grid and render it.

    Mirrors set_up_grid_data_and_masks (grid reader + generate_halo_land_mask)
    without importing the CLI.  Heavy: full-grid fast-marching.
    """
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import cartopy.crs as ccrs
    import numpy as np

    from dbof.global_dataset_creation.zarr_grid_global import GlobalGridZarrReader
    from dbof.preprocessing import static_masks
    from dbof.plotting.field_cmaps import load_field_cmaps
    from dbof.plotting.global_maps import plot_global_field

    cfg, fs, fs_sync = example_input

    grid = cfg.input.grid_access
    ds_grid = GlobalGridZarrReader(
        bucket=grid.bucket, folder=grid.folder, dataset_name=grid.dataset_name, fs=fs,
    ).to_dataset_lazy()

    land_mask = static_masks.generate_halo_land_mask(
        ds_grid, cfg.output.target_km_res, stitched=True,
    )
    assert land_mask.shape == ds_grid["XC"].shape
    assert land_mask.any() and not land_mask.all()

    step = 20
    XC = np.asarray(ds_grid["XC"][::step, ::step])
    YC = np.asarray(ds_grid["YC"][::step, ::step])
    arr = land_mask[::step, ::step].astype("float32")

    cmap_cfg, diverging = load_field_cmaps()
    fig = plt.figure(figsize=(16, 8))
    ax = fig.add_subplot(1, 1, 1, projection=ccrs.Robinson())
    im, _ = plot_global_field(ax, XC, YC, arr, "land_halo_mask", cmap_cfg,
                              diverging_cmaps=diverging, transform=ccrs.PlateCarree())
    ax.set_title("Stitched halo land mask (retained = 1)")
    ARTIFACTS_DIR.mkdir(exist_ok=True)
    out = ARTIFACTS_DIR / "land_halo_mask.png"
    fig.savefig(out, dpi=120, bbox_inches="tight")
    plt.close(fig)

    assert out.exists() and out.stat().st_size > 0
    print(f"\nland mask figure written: {out}")


# Extra generated feature channels rendered to PNGs alongside Theta.  All are
# present in the SURF run's active subsets (icearea, surface_wind,
# frontal_structure, kinematic); oceQnet and geostrophic velocity (ug/vg) are
# intentionally excluded as they are not generated by this run.
RENDER_CHANNELS = ["Theta", "SIarea", "strain_mag", "relative_vorticity", "oceTAUX", "gradb2"]


def _render_global_field(cfg, fs, fs_sync, channel):
    """Read one feature channel for DATE and render it to ARTIFACTS_DIR/<channel>.png.

    Shared by the Theta smoke test and the parametrized multi-field test.
    Returns the output Path.
    """
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import cartopy.crs as ccrs
    import numpy as np

    from dbof.cutout_dataset_creation.global_input import load_snapshot_features
    from dbof.global_dataset_creation.zarr_grid_global import GlobalGridZarrReader
    from dbof.plotting.field_cmaps import load_field_cmaps
    from dbof.plotting.global_maps import plot_global_field

    ds = load_snapshot_features(cfg.input, DATE, [channel], fs, fs_sync)
    assert channel in ds.data_vars

    grid = cfg.input.grid_access
    gds = GlobalGridZarrReader(
        bucket=grid.bucket, folder=grid.folder, dataset_name=grid.dataset_name, fs=fs,
    ).to_dataset_lazy(["XC", "YC"])

    step = 20
    XC = np.asarray(gds["XC"][::step, ::step])
    YC = np.asarray(gds["YC"][::step, ::step])
    arr = np.asarray(ds[channel][::step, ::step])

    cmap_cfg, diverging = load_field_cmaps()
    fig = plt.figure(figsize=(16, 8))
    ax = fig.add_subplot(1, 1, 1, projection=ccrs.Robinson())
    im, label = plot_global_field(ax, XC, YC, arr, channel, cmap_cfg,
                                  diverging_cmaps=diverging, transform=ccrs.PlateCarree())
    plt.colorbar(im, ax=ax, fraction=0.03, pad=0.04, shrink=0.7,
                 label=label, orientation="horizontal")
    ax.set_title(channel)
    ARTIFACTS_DIR.mkdir(exist_ok=True)
    out = ARTIFACTS_DIR / f"{channel}.png"
    fig.savefig(out, dpi=120, bbox_inches="tight")
    plt.close(fig)

    assert out.exists() and out.stat().st_size > 0
    print(f"\n{channel} figure written: {out}")
    return out

@pytest.mark.parametrize("channel", RENDER_CHANNELS)
def test_feature_field_renders(example_input, channel):
    """Render each additional generated feature channel to its own PNG."""
    cfg, fs, fs_sync = example_input
    _render_global_field(cfg, fs, fs_sync, channel)


def test_ice_halo_mask_renders(example_input):
    """Build the halo ice mask from real SIarea + grid and render it.

    Mirrors process_time_snapshot's ice masking (generate_siarea_mask +
    generate_halo_ice_mask).  Heavy: full-grid fast-marching.
    """
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import cartopy.crs as ccrs
    import numpy as np

    from dbof.cutout_dataset_creation.global_input import load_snapshot_features
    from dbof.global_dataset_creation.zarr_grid_global import GlobalGridZarrReader
    from dbof.preprocessing.ice_mask import generate_siarea_mask, generate_halo_ice_mask
    from dbof.plotting.field_cmaps import load_field_cmaps
    from dbof.plotting.global_maps import plot_global_field

    cfg, fs, fs_sync = example_input

    ds = load_snapshot_features(cfg.input, DATE, ["SIarea"], fs, fs_sync)
    ice_mask = generate_siarea_mask(ds["SIarea"].values)

    grid = cfg.input.grid_access
    ds_grid = GlobalGridZarrReader(
        bucket=grid.bucket, folder=grid.folder, dataset_name=grid.dataset_name, fs=fs,
    ).to_dataset_lazy()

    halo_ice_mask = generate_halo_ice_mask(
        ds_grid, ice_mask, cfg.output.target_km_res, stitched=True,
    )
    assert halo_ice_mask.shape == ds_grid["XC"].shape
    assert halo_ice_mask.any()  # some ocean retained

    step = 20
    XC = np.asarray(ds_grid["XC"][::step, ::step])
    YC = np.asarray(ds_grid["YC"][::step, ::step])
    arr = halo_ice_mask[::step, ::step].astype("float32")

    cmap_cfg, diverging = load_field_cmaps()
    fig = plt.figure(figsize=(16, 8))
    ax = fig.add_subplot(1, 1, 1, projection=ccrs.Robinson())
    im, _ = plot_global_field(ax, XC, YC, arr, "ice_halo_mask", cmap_cfg,
                              diverging_cmaps=diverging, transform=ccrs.PlateCarree())
    ax.set_title("Halo ice mask (retained = 1)")
    ARTIFACTS_DIR.mkdir(exist_ok=True)
    out = ARTIFACTS_DIR / "ice_halo_mask.png"
    fig.savefig(out, dpi=120, bbox_inches="tight")
    plt.close(fig)

    assert out.exists() and out.stat().st_size > 0
    print(f"\nice halo mask figure written: {out}")


def test_weighted_sampling_renders(example_input):
    """Sample patch centers on real data (log10 gradb2 weighting, land+ice halo
    mask) and scatter them on a world map.  Heavy: full-grid fast-marching.
    """
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import cartopy.crs as ccrs
    import numpy as np

    from dbof.cutout_dataset_creation import processing

    cfg, fs, fs_sync = example_input

    # Exercise the same pipeline functions the CLI uses (no logic re-implemented here).
    ds_grid, land_halo = processing.set_up_grid_data_and_land_masks(cfg, fs)
    ds_merge = processing.load_snapshot(cfg, DATE, ["gradb2", "SIarea"], ds_grid, fs, fs_sync)
    merged_mask = processing.build_sampling_mask(ds_merge, land_halo, cfg.output.target_km_res)
    indices, _ = processing.sample_cutout_centers_with_loggradb(
        ds_merge, merged_mask,
        cfg.sampling.sample_points_per_snapshot, cfg.sampling.bias_to_high_gradients,
    )

    assert len(indices) == cfg.sampling.sample_points_per_snapshot
    for j, i in indices:
        assert merged_mask[j, i]  # every sample is a retained ocean point

    print("sampling done, generating visual")
    # Grid vars are single-chunk dask arrays over S3, so per-point indexing would
    # re-read the full ~900 MB chunk every iteration. Materialize XC/YC once.
    XC = np.asarray(ds_grid["XC"].values)
    YC = np.asarray(ds_grid["YC"].values)
    lats = [float(YC[j, i]) for (j, i) in indices]
    lons = [float(XC[j, i]) for (j, i) in indices]

    fig = plt.figure(figsize=(8, 4))
    ax = plt.axes(projection=ccrs.PlateCarree())
    ax.coastlines()
    ax.set_global()
    ax.scatter(lons, lats, s=10, color="red", transform=ccrs.PlateCarree())
    ax.set_title(f"Weighted sample points (n={len(indices)})")
    ARTIFACTS_DIR.mkdir(exist_ok=True)
    out = ARTIFACTS_DIR / "weighted_sample_points.png"
    fig.savefig(out, dpi=120, bbox_inches="tight")
    plt.close(fig)

    assert out.exists() and out.stat().st_size > 0
    print(f"\nweighted sample points figure written: {out}")


def test_cutout_pipeline_end_to_end(example_input):
    """Generate cutouts to S3 under a random run_id, read them back via
    load_cutout_dataset, and render 100 random cutouts to a PNG.

    Heavy: runs the real pipeline (dask, fast-marching, S3 read + write).
    """
    import uuid
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    import dbof.cutout_dataset_creation.config as cutout_config
    import dbof.cutout_dataset_creation.processing as processing
    from dbof.cutout_dataset_access.access import load_cutout_dataset, plot_random_cutouts

    cfg, fs, fs_sync = example_input  # cfg = run config; S3 confirmed reachable

    run_id = f"itest_{uuid.uuid4().hex[:8]}"
    cfg = cutout_config.JobConfig(
        run=cutout_config.RunConfig(run_id=run_id, log_dir=cfg.run.log_dir),
        input=cfg.input, sampling=cfg.sampling, output=cfg.output,
        features=cfg.features, runtime=cfg.runtime,
    )

    processing.run(cfg)  # generate the cutout dataset

    ds = load_cutout_dataset(str(ACCESS_CONFIG), run_id=run_id)
    assert ds.images.shape[0] > 0
    assert ds.channel_names
    assert ds.images.shape[0] == len(ds.metadata)
    assert ds.channel_names[-2:] == ["XC", "YC"]  # lon/lat coords appended at the end
    assert ds.images.shape[1] == len(ds.channel_names)

    fig, meta = plot_random_cutouts(ds, n=10, seed=0)
    ARTIFACTS_DIR.mkdir(exist_ok=True)
    out = ARTIFACTS_DIR / "cutout_grid_random10.png"
    fig.savefig(out, dpi=80, bbox_inches="tight")
    plt.close(fig)
    assert out.exists() and out.stat().st_size > 0
    assert len(meta) == min(10, ds.images.shape[0])

    # No S3 deletes in code -- print the cleanup command instead.
    out_bucket = cfg.output.bucket.strip("/")
    out_folder = cfg.output.folder.strip("/")
    print(f"\nTest data left at s3://{out_bucket}/{out_folder}/{run_id}/")
    print("To remove it, run:")
    print(f"  aws s3 rm s3://{out_bucket}/{out_folder}/{run_id}/ --recursive "
          f"--endpoint-url {cfg.output.s3_endpoint}")
    print(f"figure written: {out}")
