"""
Tests for ``native_gradient.calculate_grad_squared_tracer`` — the
square-BEFORE-interp |grad|^2 added for the sparkle diagnosis
(prompts/field_validation.md).

Two properties are tested on the shared synthetic LLC fixtures:

1. **Exactness on a linear field** (and agreement with the standard
   interp-then-square recipe): for s = a*x + c*y the staggered
   differences are constant, so BOTH formulations must return
   exactly a^2 + c^2 in the face interior — including on the
   synthetic fixtures' rotated (CS/SN != 1/0) grid, which also
   checks the rotation-invariance argument (the staggered form
   never rotates).

2. **The cancellation mechanism** (the sparkle): at a one-pixel
   spike the two flanking staggered differences are equal-and-
   opposite; the standard recipe's 2-point mean cancels them
   (centre |grad|^2 ~ 0 -> white speck on a log map) while the
   staggered form retains the full gradient variance.

Generated by LH and Claude
"""

import numpy as np
import xarray as xr

import synthetic_llc
import dbof.utils.native_gradient as ng

# Face-edge cells contaminated by halo/boundary effects (see
# tests/synthetic_llc.py).
M = synthetic_llc.EDGE_MARGIN
D = synthetic_llc.D
N = synthetic_llc.N


def _interior(da):
    """Face-0 interior of a (face, j, i) array (trim edge margin)."""
    return da.isel(face=0, j=slice(M, N - M), i=slice(M, N - M))


def _linear_field(a=2.0e-4, c=-1.0e-4):
    """s = a*x + c*y [per metre] on the synthetic index grid."""
    idx = np.arange(N, dtype=float) * D
    s = (a * idx[None, None, :] + c * idx[None, :, None]
         + 0.0 * np.arange(synthetic_llc.N_FACES)[:, None, None])
    return xr.DataArray(
        np.broadcast_to(s, (synthetic_llc.N_FACES, N, N)).copy(),
        dims=("face", "j", "i"))


def test_linear_field_both_forms_exact(ds2d, grid2d):
    """Linear field: both forms == a^2 + c^2 exactly (interior)."""
    a, c = 2.0e-4, -1.0e-4
    s = _linear_field(a, c)

    # Legacy ECCO recipe (interp -> rotate -> square), inline:
    # the pointwise grad_squared function was deleted.
    gx, gy = ng.calculate_native_gradient_tracer(s, ds2d, grid2d)
    std = gx ** 2 + gy ** 2

    # Square-before-interp (never rotates).
    stag = ng.calculate_grad_squared_tracer(s, ds2d, grid2d)

    expected = a**2 + c**2
    np.testing.assert_allclose(_interior(std).values, expected,
                               rtol=1e-12)
    np.testing.assert_allclose(_interior(stag).values, expected,
                               rtol=1e-12)


def test_spike_cancellation_mechanism(ds2d, grid2d):
    """One-pixel spike: standard form cancels AT the spike, the
    staggered form retains the gradient variance there."""
    j0 = i0 = N // 2
    delta = 1.0
    s = _linear_field()
    s[dict(face=0, j=j0, i=i0)] += delta

    gx, gy = ng.calculate_native_gradient_tracer(s, ds2d, grid2d)
    std = (gx ** 2 + gy ** 2).isel(face=0).values
    stag = ng.calculate_grad_squared_tracer(s, ds2d, grid2d) \
        .isel(face=0).values

    base = (2.0e-4) ** 2 + (1.0e-4) ** 2   # background |grad|^2
    spike2 = (delta / D) ** 2               # one-sided gradient^2

    # Standard recipe at the spike: the +-delta/D flanking
    # differences cancel in the 2-point mean -> |grad|^2 stays at
    # the background level (the white 'sparkle' on a log map, since
    # neighbours are ~spike2 ~ 7 orders larger).
    assert std[j0, i0] < 10.0 * base

    # Staggered form at the spike: mean of two POSITIVE squares
    # -> the full (delta/D)^2 is retained.
    assert stag[j0, i0] > 0.5 * spike2

    # The spike is visible SOMEWHERE in the 3x3 ring in both forms
    # (exact placement depends on the stagger convention).
    ring = (slice(j0 - 1, j0 + 2), slice(i0 - 1, i0 + 2))
    assert np.nanmax(std[ring]) > 0.1 * spike2
    assert np.nanmax(stag[ring]) > 0.1 * spike2


def test_smooth_field_forms_agree(ds2d, grid2d):
    """On the smooth synthetic Theta the two forms agree to the
    expected O((k*dx)^2) discretization difference (they are the
    same continuum quantity)."""
    s = ds2d["Theta"]
    gx, gy = ng.calculate_native_gradient_tracer(s, ds2d, grid2d)
    std = _interior(gx ** 2 + gy ** 2).values
    stag = _interior(
        ng.calculate_grad_squared_tracer(s, ds2d, grid2d)).values

    # Compare medians (pointwise ratios blow up near critical
    # points — that IS the sparkle mechanism).
    ratio = np.median(stag) / np.median(std)
    assert 0.5 < ratio < 2.0
