"""Unit tests for ``dbof.preprocessing.vertical_helpers``.

These helpers manage the *vertical* axis of LLC4320 depth diagnostics:
identifying the vertical dimension, converting the MITgcm
negative-upward ``Z`` to a positive-downward depth, choosing the right
layer-thickness variable, and the depth reductions built on top of those
(vertical derivative, select-at-depth, extract-at-MLD, W->tracer
interpolation, mixed-layer mean).

Two things are easy to get wrong and are tested explicitly:

* **Sign convention.** MITgcm stores ``Z`` negative-upward (``Z < 0`` below
  the surface).  ``_get_depth_coord`` must return a *positive-downward*
  depth (0 at surface, increasing downward).  A missed flip would silently
  invert every depth comparison (MLD masks, nearest-k, derivative spacing).
* **Vertical spacing.** Tracer levels (``k``) use ``drF``; W levels
  (``k_l``) use ``drC`` (falling back to a finite difference of the depth
  coordinate).  Using the wrong thickness mis-weights every mixed-layer
  mean.

The tests are a mix of **offline** synthetic fixtures (uniform/known
spacing, answers exact) and **online** checks against the *real* LLC4320
vertical coordinates (the genuine non-uniform 51-level ``Z``/``Zl``/``drF``,
fetched once from S3 and cached).  The online tests reuse the network gate
from ``test_jacobian`` and are skipped by default.

Generated by JXP and Claude
"""

import os
import tempfile
import warnings

import numpy as np
import xarray as xr
import pytest

import dbof.preprocessing.vertical_helpers as vh

# Reuse the real-grid S3 config + network gate from the Jacobian tests.
from test_jacobian import REAL_GRID_S3, RUN_NETWORK

# Cache for the (tiny, ~16 KB) real LLC4320 1-D vertical coordinates.
REAL_VERTICAL_CACHE = os.environ.get(
    "LLC_TEST_VERTICAL_CACHE",
    os.path.join(tempfile.gettempdir(), "llc4320_vertical.nc"))

# Variables read from the real grid store for the online vertical tests.
_REAL_VERTICAL_VARS = ["Z", "Zl", "Zu", "Zp1", "drF"]


# --------------------------------------------------------------------------
# Synthetic fixtures
# --------------------------------------------------------------------------

def make_synthetic_vertical(nk=10, dz=10.0, nspace=4, drf=None):
    """Build a small synthetic dataset mimicking the LLC vertical grid.

    The depth coordinate ``Z`` is stored MITgcm-style (negative-upward).
    Tracer-cell centres sit at the middle of each layer; ``drF`` is the
    layer thickness.  A dummy ``Theta`` is included so helpers that infer
    the vertical dimension from ``ds.Theta`` work.

    Parameters
    ----------
    nk : int
        Number of tracer levels.
    dz : float
        Uniform layer thickness (m) when *drf* is None.
    nspace : int
        Size of each (square) horizontal dimension of the dummy field.
    drf : array_like or None
        Optional per-level thicknesses (m); overrides the uniform *dz* and
        produces a non-uniform grid.

    Returns
    -------
    ds : xarray.Dataset
        Dataset with ``Z`` (k, negative-upward), ``Zl`` (k_l), ``drF`` (k)
        and a zero ``Theta`` (k, j, i).
    z_pos : numpy.ndarray
        The positive-downward centre depths (m), for building test fields.

    Generated by JXP and Claude
    """
    thick = np.full(nk, dz, float) if drf is None else np.asarray(drf, float)
    # Interfaces (positive-down): 0, thick0, thick0+thick1, ...
    iface = np.concatenate([[0.0], np.cumsum(thick)])     # length nk+1
    z_pos = 0.5 * (iface[:-1] + iface[1:])                # centre depths
    ds = xr.Dataset({
        # MITgcm convention: negative-upward.
        "Z": xr.DataArray(-z_pos, dims=("k",)),
        "Zl": xr.DataArray(-iface[:-1], dims=("k_l",)),
        "drF": xr.DataArray(thick, dims=("k",)),
        "Theta": xr.DataArray(np.zeros((nk, nspace, nspace)),
                              dims=("k", "j", "i")),
    })
    return ds, z_pos


def vertical_field(values_1d, nspace=4):
    """Broadcast a 1-D vertical profile to a ``(k, j, i)`` field.

    Parameters
    ----------
    values_1d : array_like
        Per-level values defining the profile along ``k``.
    nspace : int
        Size of each horizontal dimension.

    Returns
    -------
    xarray.DataArray
        Field on ``(k, j, i)`` constant across the horizontal.

    Generated by JXP and Claude
    """
    v = np.asarray(values_1d, float)
    arr = v[:, None, None] * np.ones((1, nspace, nspace))
    return xr.DataArray(arr, dims=("k", "j", "i"))


# ==========================================================================
# Offline tests -- always run
# ==========================================================================

def test_get_vertical_dim_detection():
    """``_get_vertical_dim`` finds each known vertical axis, else raises.

    Generated by JXP and Claude
    """
    for dim in ("k", "k_l", "k_u", "k_p1", "Z", "Zl", "Zu", "Zp1",
                "depth", "lev"):
        da = xr.DataArray(np.zeros(3), dims=(dim,))
        assert vh._get_vertical_dim(da) == dim

    # First-listed vertical dim wins when several are present.
    da2 = xr.DataArray(np.zeros((2, 3)), dims=("k", "k_l"))
    assert vh._get_vertical_dim(da2) == "k"

    # No vertical dimension -> ValueError.
    horiz = xr.DataArray(np.zeros((2, 2)), dims=("j", "i"))
    with pytest.raises(ValueError):
        vh._get_vertical_dim(horiz)


def test_depth_coord_sign_conversion():
    """Negative-upward ``Z`` becomes positive-downward depth.

    Generated by JXP and Claude
    """
    ds, z_pos = make_synthetic_vertical(nk=8, dz=5.0)
    depth = vh._get_depth_coord(ds, zdim="k")

    # All non-negative, strictly increasing with k, equal to -Z.
    assert np.all(depth.values >= 0)
    assert np.all(np.diff(depth.values) > 0)
    np.testing.assert_allclose(depth.values, z_pos)
    np.testing.assert_allclose(depth.values, -ds["Z"].values)


def test_depth_coord_flip_emits_warning():
    """Flipping MITgcm negative-up ``Z`` emits a loud ``UserWarning``.

    The sign flip inverts the native MITgcm/ECCO convention, which can
    silently wrong-foot users of other ECCO tooling -- so the helper must
    announce it.  An already-positive coordinate must NOT warn (no flip
    happens, so there is nothing to announce).

    Generated by JXP and Claude
    """
    ds, z_pos = make_synthetic_vertical(nk=6, dz=10.0)

    # Native negative-up Z: the flip fires and must warn.
    with pytest.warns(UserWarning, match="POSITIVE-DOWNWARD"):
        depth = vh._get_depth_coord(ds, zdim="k")
    np.testing.assert_allclose(depth.values, z_pos)

    # Already positive-down: no flip, no warning.
    ds["Z"] = xr.DataArray(z_pos, dims=("k",))
    with warnings.catch_warnings():
        warnings.simplefilter("error")           # any warning -> failure
        vh._get_depth_coord(ds, zdim="k")


def test_depth_coord_already_positive_is_unchanged():
    """A positive-downward ``Z`` is returned as-is (no double flip).

    Generated by JXP and Claude
    """
    ds, z_pos = make_synthetic_vertical(nk=6, dz=10.0)
    ds["Z"] = xr.DataArray(z_pos, dims=("k",))   # already positive-down
    depth = vh._get_depth_coord(ds, zdim="k")
    np.testing.assert_allclose(depth.values, z_pos)


def test_depth_coord_renames_Z_dimension():
    """A ``Z`` coordinate stored on dim ``'Z'`` is renamed to ``'k'``.

    Generated by JXP and Claude
    """
    nk = 5
    z_pos = (np.arange(nk) + 0.5) * 8.0
    # Build directly so Z lives on its own 'Z' dim (as xmitgcm sometimes
    # does) while data variables use 'k'.
    ds = xr.Dataset({
        "Z": xr.DataArray(-z_pos, dims=("Z",)),
        "Theta": xr.DataArray(np.zeros((nk, 2, 2)), dims=("k", "j", "i")),
    })
    depth = vh._get_depth_coord(ds, zdim="k")
    assert depth.dims == ("k",)
    np.testing.assert_allclose(depth.values, z_pos)


def test_depth_coord_kl_uses_Zl():
    """For ``zdim='k_l'`` the depth comes from ``Zl``.

    Generated by JXP and Claude
    """
    ds, _ = make_synthetic_vertical(nk=7, dz=10.0)
    depth_l = vh._get_depth_coord(ds, zdim="k_l")
    assert depth_l.dims == ("k_l",)
    np.testing.assert_allclose(depth_l.values, -ds["Zl"].values)


def test_vertical_spacing_uses_drF_for_tracer_levels():
    """Tracer-level spacing returns ``drF`` unchanged.

    Generated by JXP and Claude
    """
    ds, _ = make_synthetic_vertical(nk=9, dz=12.5)
    dz = vh._get_vertical_spacing(ds, zdim="k")
    assert dz.dims == ("k",)
    np.testing.assert_allclose(dz.values, 12.5)


def test_vertical_spacing_fallback_to_gradient():
    """Without a spacing variable, spacing falls back to ``np.gradient``.

    Generated by JXP and Claude
    """
    # Non-uniform layers so the gradient fallback is non-trivial.
    drf = [2.0, 4.0, 8.0, 16.0, 32.0]
    ds, z_pos = make_synthetic_vertical(nk=5, drf=drf)
    ds = ds.drop_vars("drF")                      # force the fallback
    dz = vh._get_vertical_spacing(ds, zdim="k")
    np.testing.assert_allclose(dz.values, np.gradient(z_pos))


def test_nearest_k_to_depth():
    """Nearest-k indexing picks the closest level (ties -> lower index).

    Generated by JXP and Claude
    """
    z_vals = np.array([5.0, 15.0, 25.0, 35.0])
    assert vh._nearest_k_to_depth(z_vals, 0.0) == 0
    assert vh._nearest_k_to_depth(z_vals, 16.0) == 1
    assert vh._nearest_k_to_depth(z_vals, 24.0) == 2
    assert vh._nearest_k_to_depth(z_vals, 100.0) == 3
    # Exactly halfway -> argmin returns the first (lower) index.
    assert vh._nearest_k_to_depth(z_vals, 10.0) == 0


def test_select_at_depth_targets_cell_centres():
    """Depth selection lands on tracer-cell CENTRES, not interfaces.

    Uses a deliberately non-uniform grid (thicknesses 2, 4, 8, 16, 32 m,
    so centres sit at 1, 4, 10, 22, 46 m and interfaces at 0, 2, 6, 14,
    30, 62 m) and checks, for every cell:

    * a target exactly at the cell centre returns that cell's value --
      "if you're trying to get to the middle of the cell you actually
      end up there";
    * a target at an *interface* does NOT accidentally read the wrong
      side: it resolves to whichever centre is nearer, and never to a
      value from two cells away.

    Also documents the nearest-CENTRE semantics of ``_select_at_depth``:
    on a non-uniform grid a target inside a thick cell but close to its
    upper interface can legitimately resolve to the thin cell above,
    because that cell's centre is nearer (e.g. 15 m lies inside the
    14-30 m cell, but is closer to the 10 m centre than to 22 m).

    Generated by JXP and Claude
    """
    drf = [2.0, 4.0, 8.0, 16.0, 32.0]
    ds, z_pos = make_synthetic_vertical(nk=5, drf=drf)
    np.testing.assert_allclose(z_pos, [1.0, 4.0, 10.0, 22.0, 46.0])
    field = vertical_field(z_pos)                 # value encodes its depth

    # Dead-centre targets must return exactly that cell, every cell.
    for k, zc in enumerate(z_pos):
        out = vh._select_at_depth(field, float(zc), ds)
        np.testing.assert_allclose(out.values, z_pos[k])

    # Nearest-centre semantics near an interface of a non-uniform grid:
    # 15 m is inside cell k=3 (14-30 m) but nearer the k=2 centre (10 m).
    out = vh._select_at_depth(field, 15.0, ds)
    np.testing.assert_allclose(out.values, z_pos[2])
    # 21 m is inside the same cell and nearer its own centre (22 m).
    out = vh._select_at_depth(field, 21.0, ds)
    np.testing.assert_allclose(out.values, z_pos[3])


def test_vertical_derivative_linear_is_exact():
    """d/dz of a linear profile equals its slope at every level.

    Centered/forward/backward differences are all exact for a linear
    field, so every level (including the boundaries) returns the slope.

    Generated by JXP and Claude
    """
    ds, z_pos = make_synthetic_vertical(nk=12, dz=10.0)
    slope = 0.3
    field = vertical_field(slope * z_pos)         # f = slope * depth
    deriv = vh._vertical_derivative(field, ds)
    np.testing.assert_allclose(deriv.values, slope, rtol=1e-9, atol=1e-12)


def test_vertical_derivative_sign_decreasing_with_depth():
    """A profile that decreases with depth has a negative d/dz.

    With z positive-downward, temperature falling with depth must give
    dθ/dz < 0 -- the sign that matters physically.

    Generated by JXP and Claude
    """
    ds, z_pos = make_synthetic_vertical(nk=10, dz=10.0)
    theta = vertical_field(20.0 - 0.05 * z_pos)   # warm surface, cooler deep
    deriv = vh._vertical_derivative(theta, ds)
    assert np.all(deriv.values < 0)
    np.testing.assert_allclose(deriv.values, -0.05, rtol=1e-9, atol=1e-12)


def test_select_at_depth_picks_nearest_level():
    """``_select_at_depth`` returns the value at the nearest model level.

    Generated by JXP and Claude
    """
    ds, z_pos = make_synthetic_vertical(nk=10, dz=10.0)
    field = vertical_field(z_pos)                 # value encodes its depth
    out = vh._select_at_depth(field, 47.0, ds)    # nearest centre is 45 m
    assert "k" not in out.dims
    np.testing.assert_allclose(out.values, z_pos[np.abs(z_pos - 47).argmin()])


def test_extract_at_mld_per_column():
    """``_extract_at_mld`` extracts the nearest-k value per column.

    Generated by JXP and Claude
    """
    ds, z_pos = make_synthetic_vertical(nk=10, dz=10.0, nspace=3)
    field = vertical_field(z_pos, nspace=3)       # value == depth
    # Distinct MLD per column.
    mld_vals = np.array([[5.0, 25.0, 95.0],
                         [15.0, 55.0, 5.0],
                         [85.0, 35.0, 45.0]])
    mld = xr.DataArray(mld_vals, dims=("j", "i"))
    out = vh._extract_at_mld(field, mld, ds)
    expected = z_pos[np.abs(z_pos[None, None, :]
                            - mld_vals[..., None]).argmin(axis=-1)]
    assert out.dims == ("j", "i")
    np.testing.assert_allclose(out.values, expected)


def test_interp_w_to_tracer_levels_averages_interfaces():
    """W at interfaces interpolates to centres as the adjacent average.

    Generated by JXP and Claude
    """
    nk = 10
    # W lives on k_l with nk+1 interface levels (one more than the nk
    # tracer levels); build directly to avoid a k_l size clash with Zl.
    w_vals = np.arange(nk + 1, dtype=float)
    ds = xr.Dataset({
        "Theta": xr.DataArray(np.zeros((nk, 4, 4)), dims=("k", "j", "i")),
        "W": xr.DataArray(w_vals[:, None, None] * np.ones((1, 4, 4)),
                          dims=("k_l", "j", "i")),
    })
    w_tracer = vh._interp_w_to_tracer_levels(ds)
    expected = 0.5 * (w_vals[:nk] + w_vals[1:nk + 1])
    assert w_tracer.sizes["k"] == nk
    np.testing.assert_allclose(w_tracer.isel(j=0, i=0).values, expected)


def test_masked_ml_mean_constant_field():
    """Thickness-weighted ML mean of a constant field is that constant.

    Generated by JXP and Claude
    """
    ds, _ = make_synthetic_vertical(nk=10, dz=10.0, nspace=2)
    field = vertical_field(np.full(10, 7.0), nspace=2)
    mld = xr.DataArray(np.full((2, 2), 45.0), dims=("j", "i"))
    out = vh._masked_ml_mean(field, mld, ds)
    assert out.dims == ("j", "i")
    np.testing.assert_allclose(out.values, 7.0)


def test_masked_ml_mean_thickness_weighted():
    """ML mean matches an explicit thickness-weighted average over z<=MLD.

    Generated by JXP and Claude
    """
    ds, z_pos = make_synthetic_vertical(nk=10, dz=10.0, nspace=1)
    prof = 2.0 * z_pos                             # arbitrary linear profile
    field = vertical_field(prof, nspace=1)
    mld_depth = 55.0
    mld = xr.DataArray(np.full((1, 1), mld_depth), dims=("j", "i"))
    out = vh._masked_ml_mean(field, mld, ds)

    mask = z_pos <= mld_depth
    dz = ds["drF"].values
    expected = np.sum(prof[mask] * dz[mask]) / np.sum(dz[mask])
    np.testing.assert_allclose(out.values, expected)


# ==========================================================================
# Online (real-grid) tests -- network/slow, skipped by default
# ==========================================================================

def load_real_llc_vertical(cache_path=REAL_VERTICAL_CACHE):
    """Load the real LLC4320 1-D vertical coordinates, caching locally.

    Fetches ``Z``, ``Zl``, ``Zu``, ``Zp1`` and ``drF`` from the LLC4320
    grid store via :func:`get_raw_data.get_llc_depth_gridfile` (these are
    tiny 1-D arrays, ~51 elements) and caches them to NetCDF.

    Parameters
    ----------
    cache_path : str
        Local NetCDF cache path (overridable via ``LLC_TEST_VERTICAL_CACHE``).

    Returns
    -------
    xarray.Dataset
        Dataset of the real vertical coordinates (MITgcm negative-upward).

    Generated by JXP and Claude
    """
    if os.path.exists(cache_path):
        return xr.open_dataset(cache_path)

    from dbof.llc4320_ingestion import get_raw_data
    co = get_raw_data.get_llc_depth_gridfile(
        REAL_GRID_S3["s3_endpoint"], REAL_GRID_S3["bucket"],
        REAL_GRID_S3["folder"])

    out = {}
    for name in _REAL_VERTICAL_VARS:
        if name in co:
            out[name] = co[name].compute()
        elif name in co.coords:
            out[name] = co.coords[name].compute()
    ds = xr.Dataset(out)
    try:
        ds.to_netcdf(cache_path)
    except OSError:
        pass
    return ds


@pytest.mark.slow
@pytest.mark.network
@pytest.mark.skipif(not RUN_NETWORK,
                    reason="needs network/S3; set RUN_LLC_NETWORK_TESTS=1")
def test_real_depth_coord_sign_and_monotonic():
    """Real ``Z`` (negative-upward) converts to monotonic positive depth.

    The genuine LLC4320 ``Z`` runs from ~-0.5 m to ~-945 m.  The helper must
    return a strictly increasing positive-downward depth starting near the
    surface, equal to ``-Z``.

    Generated by JXP and Claude
    """
    ds = load_real_llc_vertical()
    assert np.nanmean(ds["Z"].values) < 0           # really negative-upward

    depth = vh._get_depth_coord(ds, zdim="k")
    assert depth.dims == ("k",)
    assert np.all(depth.values >= 0)
    assert np.all(np.diff(depth.values) > 0)         # strictly increasing
    assert depth.values[0] < 2.0                     # surface near 0
    assert depth.values[-1] > 500.0                  # deepest level deep
    np.testing.assert_allclose(depth.values, -ds["Z"].values)


@pytest.mark.slow
@pytest.mark.network
@pytest.mark.skipif(not RUN_NETWORK,
                    reason="needs network/S3; set RUN_LLC_NETWORK_TESTS=1")
def test_real_vertical_spacing_drF_consistent():
    """Real ``drF`` is positive and spans the full depth range.

    The tracer-level thicknesses must be positive, increase with depth
    (LLC4320 refines toward the surface), and sum to the total depth range
    spanned by the cell interfaces ``Zp1``.

    Generated by JXP and Claude
    """
    ds = load_real_llc_vertical()
    dz = vh._get_vertical_spacing(ds, zdim="k")

    assert dz.dims == ("k",)
    assert np.all(dz.values > 0)
    assert dz.values[0] < dz.values[-1]              # refines near surface
    if "Zp1" in ds:
        span = float(np.abs(ds["Zp1"].values[-1] - ds["Zp1"].values[0]))
        np.testing.assert_allclose(dz.values.sum(), span, rtol=1e-4)


@pytest.mark.slow
@pytest.mark.network
@pytest.mark.skipif(not RUN_NETWORK,
                    reason="needs network/S3; set RUN_LLC_NETWORK_TESTS=1")
def test_real_vertical_derivative_linear_exact():
    """d/dz of a linear profile is exact on the *real* non-uniform levels.

    Centered/forward/backward differences are exact for a linear field even
    on the genuine non-uniform LLC4320 ``Z`` spacing, so a profile
    ``f = slope * depth`` recovers ``slope`` at every level.

    Generated by JXP and Claude
    """
    ds = load_real_llc_vertical()
    depth = vh._get_depth_coord(ds, zdim="k").values
    slope = 0.123
    field = vertical_field(slope * depth)
    deriv = vh._vertical_derivative(field, ds)
    np.testing.assert_allclose(deriv.values, slope, rtol=1e-6, atol=1e-9)
