"""Unit tests for ``dbof.utils.native_gradient.calculate_native_gradient_tracer``.

This is the scalar-tracer companion to ``test_jacobian.py``.  Where the
Jacobian rotates a velocity *tensor*, ``calculate_native_gradient_tracer``
computes the gradient *vector* of a scalar tracer ``s`` on the native LLC
grid: it takes model-x / model-y finite differences (``grid.diff / dxC``,
``grid.diff / dyC``), interpolates them to tracer centres, then rotates the
gradient vector into geographic (zonal/meridional) axes with
``R = [[CS, -SN], [SN, CS]]``:

    grad_lambda = gx*CS - gy*SN,   grad_phi = gx*SN + gy*CS

where ``gx = ds/dx`` and ``gy = ds/dy`` are the model-basis gradients.

Two facts drive the tests:

* For a **linear** tracer ``s = slope_x*x + slope_y*y`` on a uniform grid
  the model gradients are exactly ``(slope_x, slope_y)``, so the rotated
  result is the closed form ``(slope_x*CS - slope_y*SN,
  slope_x*SN + slope_y*CS)`` -- an analytic target.  (``slope_x`` /
  ``slope_y`` are prescribed tracer slopes, in tracer units per metre --
  nothing to do with pressure.)
* The rotation is applied to the **already-differenced** gradient, so
  (unlike the velocity Jacobian) a **constant tracer gives an exactly zero
  gradient even on the real curvilinear grid**, and the **gradient
  magnitude is exactly rotation-invariant** (``|R g| = |g|`` pointwise,
  since ``CS^2 + SN^2 = 1``).  Both hold to machine precision regardless of
  how ``CS``/``SN`` vary.

Synthetic fixtures (13-face topology, uniform metrics, constant rotation)
and the real-grid loader are reused from ``test_jacobian`` so the two test
modules stay consistent.

Generated by JXP and Claude
"""

import os
import tempfile

import numpy as np
import xarray as xr
import pytest

import dbof.utils.native_gradient as ng
from dbof.llc4320_ingestion.grid import set_xgcm_grid

# Reuse the Jacobian test fixtures: synthetic 13-face grid builder, the
# face-interior trimmer, the cached real-grid loader, and the network gate.
from test_jacobian import (
    make_synthetic_grid,
    interior,
    load_real_llc_grid,
    N_FACES,
    EDGE_MARGIN,
    RUN_NETWORK,
    REAL_UV_DATE,
)

# Real surface tracer (sea-surface temperature, Theta) for the online tests,
# read once from the LLC_SURF OSN kerchunk store (surface-only) and cached.
REAL_TRACER_VAR = "Theta"
REAL_TRACER_CACHE = os.environ.get(
    "LLC_TEST_TRACER_CACHE",
    os.path.join(tempfile.gettempdir(), "llc4320_tracer_Theta.nc"))


def add_linear_tracer(ds, d, slope_x, slope_y, dy=None):
    """Add a linear tracer ``s = slope_x*x + slope_y*y`` on tracer centres.

    Linear fields are differenced and interpolated exactly on a uniform
    grid, so the model-basis gradient is exactly ``(slope_x, slope_y)`` and
    the rotated result is analytic.  Only the slopes matter, so any
    constant offset is irrelevant.  (The slopes are prescribed synthetic
    constants in tracer units per metre -- not pressure or any other
    physical field.)

    Parameters
    ----------
    ds : xarray.Dataset
        Synthetic grid from :func:`make_synthetic_grid`; provides the
        ``face``/``j``/``i`` centre coordinates.
    d : float
        Uniform x grid spacing in metres (matches the grid's ``dxC``).
    slope_x, slope_y : float
        Tracer slopes ds/dx and ds/dy (model basis).
    dy : float or None
        Uniform y grid spacing in metres (matches the grid's ``dyC``).
        None (default) uses *d* (isotropic grid).

    Returns
    -------
    xarray.DataArray
        Tracer on centre points ``(face, j, i)``.

    Generated by JXP and Claude
    """
    n = ds.sizes["i"]
    if dy is None:
        dy = d
    pos_x = np.arange(n) * d
    pos_y = np.arange(n) * dy
    s2d = slope_x * pos_x[None, :] + slope_y * pos_y[:, None]   # (j, i)
    s3d = np.broadcast_to(s2d, (N_FACES, n, n)).copy()
    return xr.DataArray(s3d, dims=("face", "j", "i"),
                        coords={c: ds.coords[c]
                                for c in ("face", "j", "i")},
                        name="S")


def analytic_rotated_gradient(slope_x, slope_y, cs, sn):
    """Return the analytic geographic gradient ``R . (slope_x, slope_y)``.

    Parameters
    ----------
    slope_x, slope_y : float
        Model-basis tracer gradients ds/dx and ds/dy.
    cs, sn : float
        Rotation coefficients ``CS = cos(alpha)`` and ``SN = sin(alpha)``.

    Returns
    -------
    grad_lambda, grad_phi : float
        Zonal and meridional gradient components, in the order returned by
        ``calculate_native_gradient_tracer``.

    Generated by JXP and Claude
    """
    return slope_x * cs - slope_y * sn, slope_x * sn + slope_y * cs


def model_frame_gradient(s, ds, grid):
    """Return the tracer gradient with the rotation forced to the identity.

    Re-runs ``calculate_native_gradient_tracer`` on a copy of ``ds`` whose
    rotation coefficients are ``CS=1, SN=0``, giving the *model-frame*
    gradient components ``(ds/dx, ds/dy)`` at centres -- the reference for
    the magnitude-invariance check.

    Parameters
    ----------
    s : xarray.DataArray
        Tracer on centre points.
    ds : xarray.Dataset
        Grid dataset (its ``CS``/``SN`` are overridden; ``dxC``/``dyC`` kept).
    grid : xgcm.Grid
        Grid object with the LLC ``face_connections``.

    Returns
    -------
    tuple of xarray.DataArray
        ``(ds/dx, ds/dy)`` in the model frame.

    Generated by JXP and Claude
    """
    ds_id = ds.copy()
    ds_id["CS"] = xr.ones_like(ds["CS"])
    ds_id["SN"] = xr.zeros_like(ds["SN"])
    return ng.calculate_native_gradient_tracer(s, ds_id, grid)


# --------------------------------------------------------------------------
# Offline (synthetic) tests -- always run.
# --------------------------------------------------------------------------

def test_tracer_no_rotation_recovers_model_gradient():
    """No rotation (CS=1, SN=0): gradient equals the prescribed slopes.

    With the identity rotation the geographic axes coincide with the model
    axes, so for ``s = slope_x*x + slope_y*y`` the two returned components
    must equal the constant slopes over every face interior, validating
    the derivative values and the ``/dxC``, ``/dyC`` scaling.

    Returns
    -------
    None
        Passes by assertion.

    Generated by JXP and Claude
    """
    d = 2500.0
    slope_x, slope_y = 1.0e-4, -3.0e-4
    ds, grid = make_synthetic_grid(n=16, d=d, cs=1.0, sn=0.0)
    s = add_linear_tracer(ds, d, slope_x, slope_y)

    grad_lambda, grad_phi = ng.calculate_native_gradient_tracer(s, ds, grid)

    tol = dict(rtol=1e-9, atol=0.0)
    np.testing.assert_allclose(interior(grad_lambda).values, slope_x, **tol)
    np.testing.assert_allclose(interior(grad_phi).values, slope_y, **tol)

    for out in (grad_lambda, grad_phi):
        assert "i_g" not in out.dims and "j_g" not in out.dims
        assert set(("face", "j", "i")).issubset(out.dims)


def test_tracer_90deg_rotation_sign_conventions():
    """90-degree rotation (CS=0, SN=1): the gradient components swap signs.

    ``R(90) . (slope_x, slope_y) = (-slope_y, slope_x)``.  The flipped
    signs and swapped roles exercise the sign conventions of the
    gradient-vector rotation -- the part most prone to error.

    Returns
    -------
    None
        Passes by assertion.

    Generated by JXP and Claude
    """
    d = 2500.0
    slope_x, slope_y = 1.0e-4, -3.0e-4
    ds, grid = make_synthetic_grid(n=16, d=d, cs=0.0, sn=1.0)
    s = add_linear_tracer(ds, d, slope_x, slope_y)

    grad_lambda, grad_phi = ng.calculate_native_gradient_tracer(s, ds, grid)

    t_lambda, t_phi = analytic_rotated_gradient(slope_x, slope_y,
                                                cs=0.0, sn=1.0)
    tol = dict(rtol=1e-7, atol=1e-12)
    np.testing.assert_allclose(interior(grad_lambda).values, t_lambda, **tol)
    np.testing.assert_allclose(interior(grad_phi).values, t_phi, **tol)


def test_tracer_constant_field_zero_gradient():
    """A constant tracer has zero gradient under any rotation.

    The gradient of a constant is identically zero; the rotation of the
    zero vector is zero.  With a non-trivial 45-degree rotation, every
    interior component must be zero to machine precision -- confirming the
    machinery introduces no spurious gradient.

    Returns
    -------
    None
        Passes by assertion.

    Generated by JXP and Claude
    """
    d = 2500.0
    alpha = np.radians(45.0)
    ds, grid = make_synthetic_grid(n=16, d=d,
                                   cs=np.cos(alpha), sn=np.sin(alpha))
    # Constant tracer: zero slopes plus an arbitrary offset.
    s = add_linear_tracer(ds, d, 0.0, 0.0) + 7.0

    grad_lambda, grad_phi = ng.calculate_native_gradient_tracer(s, ds, grid)

    for out in (grad_lambda, grad_phi):
        np.testing.assert_allclose(interior(out).values, 0.0, atol=1e-15)


@pytest.mark.parametrize("alpha_deg", [0.0, 30.0, 45.0, 90.0, 137.0])
def test_tracer_general_angle_matches_rotation(alpha_deg):
    """Arbitrary rotation angle matches the analytic rotated gradient.

    Sweeps several grid-rotation angles (subsuming the no-rotation and
    90-degree special cases) and asserts both gradient components equal the
    analytic ``R . (slope_x, slope_y)`` over each face interior.

    Parameters
    ----------
    alpha_deg : float
        Grid-rotation angle in degrees (pytest-parametrized).

    Returns
    -------
    None
        Passes by assertion.

    Generated by JXP and Claude
    """
    d = 2500.0
    slope_x, slope_y = 1.0e-4, -3.0e-4
    alpha = np.radians(alpha_deg)
    cs, sn = np.cos(alpha), np.sin(alpha)

    ds, grid = make_synthetic_grid(n=16, d=d, cs=cs, sn=sn)
    s = add_linear_tracer(ds, d, slope_x, slope_y)

    grad_lambda, grad_phi = ng.calculate_native_gradient_tracer(s, ds, grid)
    t_lambda, t_phi = analytic_rotated_gradient(slope_x, slope_y,
                                                cs=cs, sn=sn)

    tol = dict(rtol=1e-7, atol=1e-12)
    np.testing.assert_allclose(interior(grad_lambda).values, t_lambda, **tol)
    np.testing.assert_allclose(interior(grad_phi).values, t_phi, **tol)


@pytest.mark.parametrize("alpha_deg", [0.0, 30.0])
def test_tracer_anisotropic_grid_metrics(alpha_deg):
    """Anisotropic grid (dxC != dyC): the metric scaling stays correct.

    On an isotropic grid an accidental swap of ``dxC`` and ``dyC`` -- e.g.
    dividing the x-difference by ``dyC`` -- is invisible.  Here
    ``dyC = 2.4 * dxC``, so a swapped metric would scale the two gradient
    components by 2.4 (or 1/2.4), far outside tolerance.  The linear
    tracer is built with the same anisotropic spacings, so the interior
    answer is still the exact analytic ``R . (slope_x, slope_y)``.

    Parameters
    ----------
    alpha_deg : float
        Grid-rotation angle in degrees (pytest-parametrized).

    Returns
    -------
    None
        Passes by assertion.

    Generated by JXP and Claude
    """
    d, dy = 2500.0, 6000.0        # strongly anisotropic: dy = 2.4 dx
    slope_x, slope_y = 1.0e-4, -3.0e-4
    alpha = np.radians(alpha_deg)
    cs, sn = np.cos(alpha), np.sin(alpha)

    ds, grid = make_synthetic_grid(n=16, d=d, cs=cs, sn=sn, dy=dy)
    s = add_linear_tracer(ds, d, slope_x, slope_y, dy=dy)

    grad_lambda, grad_phi = ng.calculate_native_gradient_tracer(s, ds, grid)
    t_lambda, t_phi = analytic_rotated_gradient(slope_x, slope_y,
                                                cs=cs, sn=sn)

    tol = dict(rtol=1e-7, atol=1e-12)
    np.testing.assert_allclose(interior(grad_lambda).values, t_lambda, **tol)
    np.testing.assert_allclose(interior(grad_phi).values, t_phi, **tol)


def test_tracer_output_coordinate_contract():
    """Outputs live on tracer points with the input shape.

    Independent of rotation, both gradient components must be on tracer
    centres (dims ``face, j, i``), carry no staggered ``i_g``/``j_g`` axes,
    and preserve the per-face ``(n, n)`` shape.

    Returns
    -------
    None
        Passes by assertion.

    Generated by JXP and Claude
    """
    d = 2500.0
    n = 16
    alpha = np.radians(33.0)
    ds, grid = make_synthetic_grid(n=n, d=d,
                                   cs=np.cos(alpha), sn=np.sin(alpha))
    s = add_linear_tracer(ds, d, 1.0e-4, -3.0e-4)

    outputs = ng.calculate_native_gradient_tracer(s, ds, grid)
    for out in outputs:
        assert "i_g" not in out.dims and "j_g" not in out.dims
        assert set(("face", "j", "i")).issubset(out.dims)
        assert out.sizes["face"] == N_FACES
        assert out.sizes["i"] == n
        assert out.sizes["j"] == n


# --------------------------------------------------------------------------
# Online (real-grid) tests -- network/slow, skipped by default.
# --------------------------------------------------------------------------

def load_real_llc_surface_tracer(var=REAL_TRACER_VAR,
                                 cache_path=REAL_TRACER_CACHE):
    """Load a real LLC4320 surface tracer, caching locally.

    Reads the surface (k=0) tracer from the LLC_SURF OSN kerchunk store via
    :func:`get_raw_data.get_remote_llc_data` (a true surface-only read) and
    caches it to a local NetCDF.

    Parameters
    ----------
    var : str
        Tracer variable name (default ``'Theta'``, sea-surface temperature).
    cache_path : str
        Local NetCDF cache path (overridable via ``LLC_TEST_TRACER_CACHE``).

    Returns
    -------
    xarray.DataArray
        Tracer on centre points ``(face, j, i)``.

    Generated by JXP and Claude
    """
    if os.path.exists(cache_path):
        return xr.open_dataset(cache_path)[var]

    from dbof.llc4320_ingestion import get_raw_data
    from dbof.global_dataset_creation.data_sources import OSN_ENDPOINT
    from dbof.global_dataset_creation.iterations import osn_date_to_iteration

    it = osn_date_to_iteration(REAL_UV_DATE)
    ds = get_raw_data.get_remote_llc_data(OSN_ENDPOINT, it, range(N_FACES))
    tracer = ds[var].astype("float32").compute()
    try:
        xr.Dataset({var: tracer}).to_netcdf(cache_path)
    except OSError:
        pass
    return tracer


@pytest.mark.slow
@pytest.mark.network
@pytest.mark.skipif(not RUN_NETWORK,
                    reason="needs network/S3; set RUN_LLC_NETWORK_TESTS=1")
def test_tracer_real_grid_constant_field_zero_gradient():
    """Constant tracer -> exactly zero gradient on the real grid.

    Because ``calculate_native_gradient_tracer`` differences the tracer
    *before* rotating the gradient, a constant tracer yields an exactly zero
    gradient everywhere -- even at grid singularities where ``CS``/``SN``
    vary rapidly (no ``grad(CS)`` term can appear, unlike the velocity
    Jacobian).  Asserted to machine precision over the ocean interior.

    Returns
    -------
    None
        Passes by assertion.

    Generated by JXP and Claude
    """
    ds = load_real_llc_grid()
    grid = set_xgcm_grid(ds.drop_vars("hFacC"), use_connections=True)

    # A spatially constant tracer on tracer centres.
    s = xr.full_like(ds["CS"], 10.0)

    grad_lambda, grad_phi = ng.calculate_native_gradient_tracer(s, ds, grid)

    ocean = interior(ds["hFacC"]).values > 0
    assert ocean.any()
    for out in (grad_lambda, grad_phi):
        vals = interior(out).values[ocean]
        vals = vals[np.isfinite(vals)]
        assert np.max(np.abs(vals)) < 1e-12


# Sphere radius used by the analytic lon/lat targets.  MITgcm/ECCO treat
# the Earth as a sphere of ~6370-6371 km; the two conventions differ by
# 0.02%, far inside the test tolerances, so the exact choice is immaterial.
R_SPHERE = 6.371e6


def analytic_geographic_gradient(kind, lon_deg, lat_deg):
    """Closed-form geographic gradient of an analytic lon/lat tracer.

    Two globally smooth tracers with known gradients (lambda = longitude,
    phi = latitude, R = sphere radius):

    * ``'sin_lat'``: ``s = sin(phi)``.  Zonal gradient 0; meridional
      gradient ``cos(phi) / R``.
    * ``'sin_lon_cos_lat'``: ``s = sin(lambda) cos(phi)`` (the Cartesian
      y-coordinate of the unit sphere, so it is smooth across the
      dateline and the poles).  Zonal gradient ``cos(lambda) / R``;
      meridional gradient ``-sin(lambda) sin(phi) / R``.

    Parameters
    ----------
    kind : str
        ``'sin_lat'`` or ``'sin_lon_cos_lat'``.
    lon_deg, lat_deg : numpy.ndarray
        Longitude / latitude in degrees (any matching shape).

    Returns
    -------
    s : numpy.ndarray
        The tracer values.
    g_zonal, g_merid : numpy.ndarray
        Analytic zonal and meridional gradient components (1/m).

    Generated by JXP and Claude
    """
    lon = np.deg2rad(lon_deg.astype("float64"))
    lat = np.deg2rad(lat_deg.astype("float64"))
    if kind == "sin_lat":
        s = np.sin(lat)
        g_zonal = np.zeros_like(s)
        g_merid = np.cos(lat) / R_SPHERE
    elif kind == "sin_lon_cos_lat":
        s = np.sin(lon) * np.cos(lat)
        g_zonal = np.cos(lon) / R_SPHERE
        g_merid = -np.sin(lon) * np.sin(lat) / R_SPHERE
    else:
        raise ValueError(f"unknown analytic tracer kind: {kind}")
    return s, g_zonal, g_merid


@pytest.mark.slow
@pytest.mark.network
@pytest.mark.skipif(not RUN_NETWORK,
                    reason="needs network/S3; set RUN_LLC_NETWORK_TESTS=1")
@pytest.mark.parametrize("kind", ["sin_lat", "sin_lon_cos_lat"])
def test_tracer_real_grid_face_consistency_analytic_field(kind):
    """Every face reproduces the analytic gradient of a lon/lat tracer.

    Builds a globally smooth tracer directly from the real grid's cell-
    centre longitude/latitude (``XC``/``YC``) whose geographic gradient is
    known in closed form, then asserts the computed (zonal, meridional)
    components match the analytic ones **on every face separately**.

    This is the reviewer-requested check that "the faces are doing what
    they should": a staggering mistake (e.g. ending on the U point on some
    faces and the V point on others), a per-face sign flip, or a swapped
    component would show up as an O(1) relative error on the affected
    face, while the discretisation error of the smooth field is orders of
    magnitude smaller.  Because the tracer is consistent across face
    boundaries, this also exercises the ``face_connections`` halo with a
    field whose truth is known (unlike the synthetic per-face linear
    fields, which are deliberately inconsistent at the seams).

    The comparison is restricted to **ocean** points (``hFacC > 0``):
    over land the grid stores fill values ``CS = SN = 0``, so the rotated
    gradient is identically zero there and the analytic target cannot be
    reproduced -- a property of the grid files, not of the code under
    test.  Errors are normalised by the gradient scale ``1/R`` so the
    thresholds are dimensionless: per-face median < 1e-3 and 95th
    percentile < 5e-3 (observed: medians ~1e-4, p95 ~5e-4).  The floor is set by float32 ``XC``/``YC``
    quantisation (~0.4 m position noise over ~1-2 km cells), not by the
    numerics under test.

    Parameters
    ----------
    kind : str
        Analytic tracer kind (pytest-parametrized; see
        :func:`analytic_geographic_gradient`).

    Returns
    -------
    None
        Passes by assertion.

    Generated by JXP and Claude
    """
    ds = load_real_llc_grid()
    grid = set_xgcm_grid(ds.drop_vars("hFacC"), use_connections=True)

    s_np, gz_np, gm_np = analytic_geographic_gradient(
        kind, ds["XC"].values, ds["YC"].values)
    s = xr.DataArray(s_np, dims=("face", "j", "i"),
                     coords={c: ds.coords[c] for c in ("face", "j", "i")},
                     name="S")

    grad_lambda, grad_phi = ng.calculate_native_gradient_tracer(s, ds, grid)

    # Dimensionless error: (computed - analytic) / (1/R).
    err_z = (interior(grad_lambda).values
             - interior(xr.DataArray(gz_np, dims=("face", "j", "i"))).values
             ) * R_SPHERE
    err_m = (interior(grad_phi).values
             - interior(xr.DataArray(gm_np, dims=("face", "j", "i"))).values
             ) * R_SPHERE

    # Ocean only: over land CS = SN = 0 (fill), so the rotation zeroes the
    # gradient by construction and no comparison is meaningful there.
    ocean = interior(ds["hFacC"]).values > 0

    for face in range(N_FACES):
        mask = ocean[face]
        pooled = np.concatenate(
            [np.abs(err_z[face][mask]).ravel(),
             np.abs(err_m[face][mask]).ravel()])
        pooled = pooled[np.isfinite(pooled)]
        assert pooled.size > 0
        med = np.median(pooled)
        p95 = np.percentile(pooled, 95.0)
        assert med < 1e-3, f"face {face} ({kind}): median {med:.2e}"
        assert p95 < 5e-3, f"face {face} ({kind}): 95th pct {p95:.2e}"


@pytest.mark.slow
@pytest.mark.network
@pytest.mark.skipif(not RUN_NETWORK,
                    reason="needs network/S3; set RUN_LLC_NETWORK_TESTS=1")
def test_tracer_real_grid_gradient_magnitude_invariance():
    """Gradient magnitude is rotation-invariant on the real grid.

    The rotation acts on the already-computed gradient vector, so
    ``|grad_geographic| = |grad_model|`` exactly (``CS^2 + SN^2 = 1``),
    independent of how ``CS``/``SN`` vary.  Feeds a real surface tracer
    (Theta) and compares the geographic-frame gradient magnitude to the
    model-frame magnitude (identity rotation) computed from the same tracer.

    Asserts robust statistics: the signal is genuinely non-zero (not a
    trivial 0 == 0), the median difference is ~0, and the relative RMS
    difference is at machine precision (empirically ~3e-8 in float32).

    Returns
    -------
    None
        Passes by assertion.

    Generated by JXP and Claude
    """
    ds = load_real_llc_grid()
    grid = set_xgcm_grid(ds.drop_vars("hFacC"), use_connections=True)

    tracer = load_real_llc_surface_tracer()
    tracer = tracer.assign_coords(
        {c: ds.coords[c] for c in tracer.dims if c in ds.coords})

    gx_geo, gy_geo = ng.calculate_native_gradient_tracer(tracer, ds, grid)
    gx_mod, gy_mod = model_frame_gradient(tracer, ds, grid)

    mag_geo = np.sqrt(gx_geo ** 2 + gy_geo ** 2)
    mag_mod = np.sqrt(gx_mod ** 2 + gy_mod ** 2)

    ocean = interior(ds["hFacC"]).values > 0
    g = interior(mag_geo).values[ocean]
    m = interior(mag_mod).values[ocean]
    finite = np.isfinite(g) & np.isfinite(m)
    g, m = g[finite], m[finite]

    signal_rms = np.sqrt(np.mean(m ** 2))
    diff = np.abs(g - m)
    diff_rms = np.sqrt(np.mean(diff ** 2))

    assert signal_rms > 1e-6                 # real, non-trivial signal
    assert np.median(diff) < 1e-12           # bit-identical for most points
    assert diff_rms / signal_rms < 1e-5      # machine precision (~3e-8)
    assert np.percentile(diff, 99.0) < 1e-9
