"""Staggered vector pairs crossing an LLC face connection.

Some face connections reach the neighbour along the other axis, so a
staggered component's halo has to come from its partner.  Pairs that are
rotated afterwards (U/V, the Jacobian, tracer-gradient components) carry
the error into the output; the corner stencils cannot be exchanged at
all and are masked.  See docs/Gradients.md.

Generated by LH and Claude
"""

import numpy as np
import pytest
import xarray as xr

import dbof.utils.native_gradient as ng
from dbof.llc4320_ingestion.grid import (
    face_connections,
    face_seam_mask,
    invalid_seam_edges,
    set_xgcm_grid,
)
from dbof.utils.native_gradient import (diff_pair_along_own_axis,
                                        interp_pair_to_center)

#: Faces whose X-upper connection is rotated (left-staggered U reads the
#: upper halo), e.g. face 5 -> face 7 via 'Y'.
ROTATED_X_UPPER = {3, 4, 5}


def test_invalid_seam_edges_lists_rotated_and_open_edges():
    edges = invalid_seam_edges()
    assert (5, 'X', 'upper') in edges       # rotated: -> face 7 via 'Y'
    assert (9, 'X', 'upper') in edges       # open: -> None
    assert (5, 'X', 'lower') not in edges   # same axis: -> face 2 via 'X'

    conn = face_connections['face']
    for face, axis, side in edges:
        link = conn[face][axis][0 if side == 'lower' else 1]
        assert link is None or link[1] != axis


def test_face_seam_mask_touches_only_the_rim(ds2d, grid2d):
    masked = face_seam_mask(xr.ones_like(ds2d['CS']), grid2d)
    assert bool(np.isnan(masked).any())
    assert not bool(np.isnan(
        masked.isel(i=slice(2, -2), j=slice(2, -2))).any())


def test_paired_interp_differs_from_scalar_only_at_rotated_seams(ds2d, grid2d):
    """The exchange changes the old scalar answer, and only at the seams."""
    paired, _ = interp_pair_to_center(ds2d.U, ds2d.V, grid2d)
    scalar = grid2d.interp(ds2d.U, 'X', padding='fill')
    differs = (np.abs(paired - scalar) > 0).compute()

    n = ds2d.sizes['i']
    for face in range(differs.sizes['face']):
        cols = set(np.flatnonzero(differs.isel(face=face).any('j').values))
        assert cols == ({n - 1} if face in ROTATED_X_UPPER else set()), (
            f"face {face} differs at columns {cols}")


def test_paired_interp_leaves_no_nans(ds2d, grid2d):
    u_c, v_c = interp_pair_to_center(ds2d.U, ds2d.V, grid2d)
    assert not bool(np.isnan(u_c).any().compute())
    assert not bool(np.isnan(v_c).any().compute())


@pytest.mark.parametrize("call", [
    lambda ds, g: ng.rotate_vector_to_geographic(ds.U, ds.V, ds, g),
    lambda ds, g: ng.calculate_jacobian(ds.U, ds.V, ds, g),
    lambda ds, g: ng.calculate_native_gradient_tracer(ds.Theta, ds, g),
], ids=["rotate_vector", "jacobian", "tracer_gradient"])
def test_rotated_paths_use_the_paired_exchange(ds2d, grid2d, call, monkeypatch):
    """Every rotated path must route its pair through the exchange."""
    calls = []
    real = ng.interp_pair_to_center
    monkeypatch.setattr(ng, "interp_pair_to_center",
                        lambda x, y, g: (calls.append(1), real(x, y, g))[1])
    call(ds2d, grid2d)
    assert calls, "this path interpolates its pair one component at a time"


def test_centre_pair_uses_the_paired_difference(ds2d, grid2d):
    out = ng.calculate_native_strain_vorticity(ds2d.U, ds2d.V, ds2d, grid2d)
    dx, dy = diff_pair_along_own_axis(ds2d.U * ds2d.dyG,
                                      ds2d.V * ds2d.dxG, grid2d)
    xr.testing.assert_allclose(out['strain_normal_center'],
                               (dx - dy) / ds2d.rA)


def test_corner_pair_is_masked_at_the_seams(ds2d, grid2d):
    out = ng.calculate_native_strain_vorticity(ds2d.U, ds2d.V, ds2d, grid2d)
    for key in ('vorticity_corner', 'strain_shear_corner'):
        da = out[key].compute()
        assert bool(np.isnan(da).any()), f"{key} was not masked"
        assert not bool(np.isnan(
            da.isel(i_g=slice(2, -2), j_g=slice(2, -2))).any())
    assert bool(np.isnan(out['vorticity_corner'].isel(face=5, i_g=-1)).all())


def test_seam_nan_reaches_okubo_weiss(ds2d, grid2d):
    out = ng.calculate_native_strain_vorticity(ds2d.U, ds2d.V, ds2d, grid2d)
    okubo = (out['strain_normal_center'] ** 2
             + ng.interp_corner_squared(out['strain_shear_corner'] ** 2, grid2d)
             - ng.interp_corner_squared(out['vorticity_corner'] ** 2, grid2d))
    okubo = okubo.compute()
    assert bool(np.isnan(okubo.isel(face=5, i=-1)).all())
    assert not bool(np.isnan(
        okubo.isel(i=slice(3, -3), j=slice(3, -3))).any())


def test_grad_squared_is_unchanged(ds2d, grid2d):
    """The rotation-free path is left alone; gradb2 must not move."""
    got = ng.calculate_grad_squared_tracer(ds2d.Theta, ds2d, grid2d)
    expected = (grid2d.interp((grid2d.diff(ds2d.Theta, 'X')
                               / ds2d.dxC) ** 2, 'X', padding='fill')
                + grid2d.interp((grid2d.diff(ds2d.Theta, 'Y')
                                 / ds2d.dyC) ** 2, 'Y', padding='fill'))
    xr.testing.assert_allclose(got, expected)


def test_tile_grid_is_untouched(ds2d):
    """A single-face tile grid has no seams: plain stencils, no mask."""
    tile = ds2d.isel(face=slice(5, 6))
    tile_grid = set_xgcm_grid(tile, use_connections=False)
    xr.testing.assert_identical(
        face_seam_mask(tile.CS, tile_grid), tile.CS)

    out = ng.calculate_native_strain_vorticity(tile.U, tile.V, tile, tile_grid)
    assert not bool(np.isnan(out['vorticity_corner']).any())
    u_c, _ = interp_pair_to_center(tile.U, tile.V, tile_grid)
    xr.testing.assert_allclose(
        u_c, tile_grid.interp(tile.U, 'X', padding='fill'))
