run:
  run_id: "year_4x150"
  log_dir: "../test_logs/"

data: # info on these configs can be found in docs/Accessing_Raw_LLC4320_Data.md
  sampling_step: 2190 # Stride in hours. This will give us 4 evenly spaced samples in a years worth of data
  start_record: 1180 # This is the first record with wind forcing
  timestep_hours: 8760 # this is one year worth of time snapshots (simply in hours)

sampling: # info on these configs can be found in docs/Sampling_With_GradB2.md
  bias_to_high_gradients: 1.3
  sample_points_per_snapshot: 150

output:
  target_km_res: 150
  down_sample_res: 64
  s3_endpoint: "https://s3-west.nrp-nautilus.io"
  bucket: "dbof/"
  folder: "native_grid_dbof_training_data/"
  dataset_name: "cutout_dataset_creation.zarr"

features:
  model_data_feature_channels: # These can only be features present in the LLC4320 model
    - Eta
    - Salt
    - Theta
    - U
    - V
    - W
  compute_features_channels: # These can only be features calculated by our code. log_gradb is currently not optional
    - relative_vorticity
    # - log_gradb is added to the list automatically. This is currently not an optional feature

runtime:
  zarr_async_concurrency: 128
