"""Build all 6 surface field-validation notebooks.

Canonical generator: edit the templates/specs here and re-run
(from the repo root: ``python dev/build_field_validation_notebooks.py``)
to regenerate every notebook consistently.

v2: component-level intermediates plotted in the dependency chains
(gradient components, Jacobian components) per supervisor request;
live cells batch-stitch and slice immediately (bounded memory).

Generated by LH and Claude
"""
import json
import uuid

from pathlib import Path

OUT_DIR = str(Path(__file__).resolve().parents[1]
              / "notebooks" / "notebooks_field_validation"
              / "surface_fields") + "/"


def md(cells, src):
    cells.append({"cell_type": "markdown", "id": uuid.uuid4().hex[:8],
                  "metadata": {}, "source": src})


def code(cells, src):
    cells.append({"cell_type": "code", "id": uuid.uuid4().hex[:8],
                  "metadata": {}, "execution_count": None,
                  "outputs": [], "source": src})


# ─────────────────────────────────────────────────────────────────────
# Shared cell templates
# ─────────────────────────────────────────────────────────────────────

RUN_MD = """\
## Section 1 — RUN the SURF pipeline for this subset + timestep

One cell (pattern from
`notebooks/notebooks_global/running_generate_global_script.ipynb`).
Existing stores for this date are skipped unless `--clobber` is added,
so re-running is a cheap no-op.{run_note}\
"""

RUN_CELL = """\
# Section 1: run the SURF pipeline for this subset and timestep.
SUBSET   = "{subset}"
PIPELINE = "SURF"
RUN_ID   = "field_validation_v1"
DATE     = "2012-11-09 12:00:00"   # single validation timestep

!generate-global \\
    --config ../../../configs/global/run/field_validation_surface.yaml \\
    --pipeline $PIPELINE \\
    --subset $SUBSET \\
    --run_id $RUN_ID\
"""

LOAD_MD = """\
## Section 2 — LOAD the data generated in Section 1

One cell (pattern from
`notebooks/notebooks_global/assess_generate_global_script.ipynb`):
product reader + grid reader, with shape/date confirmation printout.\
"""

LOAD_CELL = """\
# Section 2: load the store written in Section 1 + the shared grid.
import numpy as np
import matplotlib.pyplot as plt

import dbof.io.filesystems as filesystems
import dbof.global_dataset_creation.zarr_dataset_global as zarr_dataset
import dbof.global_dataset_creation.zarr_grid_global as zarr_grid
from dbof.global_dataset_creation.subset_definitions import (
    get_subset_definition,
)

S3_ENDPOINT = "https://s3-west.nrp-nautilus.io"
BUCKET      = "dbof"
FOLDER      = "surface_fields"       # SURF output folder
DATE_PREFIX = "20121109_120000"      # matches DATE in Section 1

defn = get_subset_definition(PIPELINE, SUBSET)
# get_subset_definition already folds per-pipeline extras (e.g.
# oceQnet for SURF) into model_data_feature_channels.
CHANNELS = (list(defn["model_data_feature_channels"])
            + list(defn["compute_features_channels"]))

fs, _ = filesystems.create_s3_filesystems(S3_ENDPOINT)
reader = zarr_dataset.GlobalZarrDatasetReader(
    bucket=BUCKET, folder=FOLDER, run_id=RUN_ID,
    dataset_name=defn["dataset_name"], date_prefix=DATE_PREFIX, fs=fs,
)

fs_grid, _ = filesystems.create_s3_filesystems(S3_ENDPOINT)
grid_reader = zarr_grid.GlobalGridZarrReader(
    bucket=BUCKET, folder="LLC4320_GRID_2D",
    dataset_name="llc4320_grid.zarr", fs=fs_grid,
)
XC, YC = grid_reader.lon, grid_reader.lat

print(reader)
print(f"channels  : {reader.channel_names}")
print(f"shape     : {reader.shape}  (C, H, W)")
print(f"iteration : {reader.iteration}")
print(f"grid      : XC {XC.shape}, "
      f"lon [{XC.min():.1f}, {XC.max():.1f}], "
      f"lat [{YC.min():.1f}, {YC.max():.1f}]")\
"""

GUARD_CELL = """\
# Section 3: guard — store channels must match the code definition.
print(f"subset '{SUBSET}': {len(CHANNELS)} channels")
for ch in CHANNELS:
    print(f"  - {ch}")
assert set(reader.channel_names) == set(CHANNELS), (
    "store channels differ from subset_definitions — regenerate the "
    "store (Section 1, --clobber) or check the code definition")
print("OK: store channel set matches subset_definitions")\
"""

# Batch stitch+slice tail appended to live cells that build live_map.
LIVE_TAIL = """\

# Batch-stitch the live fields and slice to the validation domains
# (shared plumbing: dbof.plotting.live_fields; at most `batch`
# full-res arrays alive at once).
from dbof.plotting import regions
from dbof.plotting.live_fields import stitch_and_slice

SLICE_REGIONS = (regions.REGION_ORDER
                 + globals().get("EXTRA_REGIONS", []))
region_arrays = globals().get("region_arrays", {})
region_arrays.update(stitch_and_slice(
    live_map, ds_raw, ds_merge, XC, YC, SLICE_REGIONS, batch=4))
print(f"live fields ready: {list(live_map)}")\
"""

HELPERS_CELL = """\
# Section 5 helpers: one call per figure, shared by all fields.
from pathlib import Path

import cartopy.crs as ccrs

from dbof.plotting.global_maps import plot_global_field
from dbof.plotting.pipeline_grids import (
    pipeline_map_grid, mask_wrap_cells, LAND_COLOR,
)
from dbof.plotting.pdfs import pipeline_pdf_grid
from dbof.plotting.literature_comparison import side_by_side

# Flat literature directory; files named
# {{field}}_{{Citation}}_{{description}}.png
LIT_DIR = Path("../literature_figures")

# Full dependency chain per field (columns of Figures 1-2), including
# component-level intermediates (gradient / Jacobian components).
CHAINS = {chains}

# f-normalised fields: |lat|>2 deg filter on the Eq. Pacific row of
# the PDFs only (maps annotated instead) — plan Clarification 8.
F_NORM = {f_norm}

# Fields drawn/binned on log scales (∝-squared fields).
LOG_FIELDS = {log_fields}

PDF_NOTE = ("PDFs: density; land+rim NaNs removed; shared bins "
            "across domains; log10-x for \\u221d-squared fields")


# Shared figure toolkit (extracted to dbof.plotting.validation_figures
# — one implementation for all six notebooks); methods bound to the
# historical cell-level names used by the Section 5/6 cells below.
from dbof.plotting.validation_figures import ValidationFigures

_figs = ValidationFigures(
    chains=CHAINS, region_arrays=region_arrays,
    cmap_cfg=CMAP_CFG, diverging=DIVERGING,
    log_fields=LOG_FIELDS, f_norm=F_NORM, lit_dir=LIT_DIR,
)
figure1_maps = _figs.maps
figure2_pdfs = _figs.pdfs
figure3_literature = _figs.literature\
"""

SLICE_HEAD = """\
# Slice the STORE channels to the validation domains (live fields,
# if any, were sliced in the previous cell) via the shared plumbing
# in dbof.plotting.live_fields.
from dbof.plotting import regions
from dbof.plotting.field_cmaps import load_field_cmaps
from dbof.plotting.live_fields import (
    slice_store, print_region_summary,
)

CMAP_CFG, DIVERGING = load_field_cmaps()

# region_arrays[field][region] = (x, y, arr)
region_arrays = globals().get("region_arrays", {})
SLICE_REGIONS = (regions.REGION_ORDER
                 + globals().get("EXTRA_REGIONS", []))
"""

SLICE_TAIL = """\
region_arrays.update(
    slice_store(reader, CHANNELS, XC, YC, SLICE_REGIONS))
print_region_summary(region_arrays)\
"""

SUMMARY_MD = """\
## Summary — guard-style checks

Pass/fail checklist mirroring `dev/verify_subsets_real_data.py`:
finite fraction, plausible range, and channel-uniqueness guard on the
Gulf Stream domain.\
"""

SUMMARY_CELL = """\
# Summary: quick stats + uniqueness guard (Gulf Stream domain).
seen = {}
print(f"{'field':24s} {'finite%':>8s} {'min':>11s} "
      f"{'max':>11s} {'unique':>7s}")
for ch in CHANNELS:
    sub = region_arrays[ch]["gulf_stream"][2]
    finite = np.isfinite(sub)
    frac = 100.0 * finite.mean()
    key = hash(sub[finite][::997].tobytes()) if finite.any() else ch
    dup = seen.get(key)
    seen[key] = ch
    print(f"{ch:24s} {frac:7.1f}% {np.nanmin(sub):11.3g} "
          f"{np.nanmax(sub):11.3g} {'DUP!' if dup else 'ok':>7s}")
    assert dup is None, f"{ch} identical to {dup}"
print("\\nAll checks passed.")\
"""

SEC5_MD = """\
## Section 5 — Per-field validation

- **Figure 1 — maps**: columns = the field's full dependency chain
  (raw → components → final; every computed step is shown), rows =
  validation domains.  One shared colour scale per column; land/halo
  NaNs gray; regional boxes on the global row.
- **Figure 2 — PDFs**: same grid.  Probability density; land +
  halo-rim NaNs removed; bins shared per field across domains;
  Eq. Pacific row |lat|>2° filtered for f-normalised fields.
- **Literature comparisons** live in Section 6 at the end of the
  notebook — one subsection PER REFERENCE (a reference may validate
  several fields at once), only where a reference exists.  Images in
  `../literature_figures/`, named
  `{field(s)}_{Citation}_{description}.png`.\
"""

TURNER_FIG3 = """\
# Whalen & Drushka comparison: Pacific-centred Robinson and THEIR
# colour convention (turbo-like, fixed -90..+90) so the panels read
# side by side.


def _tu_wd_panel(ax):
    \"\"\"Our global Tu in the W&D display convention.
    Inputs: ax (cartopy axis).  Outputs: draws on ax.
    Generated by LH and Claude
    \"\"\"
    x, y, arr = region_arrays["turner_angle"]["global"]
    arr = mask_wrap_cells(x, y, arr)
    ax.set_facecolor(LAND_COLOR)
    im = ax.pcolormesh(x, y, arr, cmap="turbo",
                       vmin=-90, vmax=90,
                       transform=ccrs.PlateCarree())
    ax.coastlines(linewidth=0.4)
    plt.colorbar(im, ax=ax, orientation="horizontal",
                 fraction=0.04, pad=0.04,
                 label="Turner angle (deg)")


side_by_side(
    _tu_wd_panel,
    LIT_DIR / ("turner-angle_Whalen&Drushka(2024)_"
               "World-Ocean-Atlas-climatology.png"),
    projection=ccrs.Robinson(central_longitude=180),
    caption=("Compare with Whalen & Drushka (2025), World Ocean "
             "Atlas climatology.  Our panel uses their display "
             "convention (Pacific-centred, turbo, \\u00b190\\u00b0). "
             "Note: WOA is a coarse multi-decade "
             "climatology vs one LLC4320 snapshot \\u2014 expect "
             "agreement in the large-scale Tu pattern (T- vs "
             "S-controlled regimes), not in mesoscale detail.\\n"
             "Whalen, C. B., and K. Drushka, 2025: Global "
             "Distribution and Governing Dynamics of "
             "Submesoscale Density Fronts. J. Phys. Oceanogr., "
             "55, 1831\\u20131845, "
             "https://doi.org/10.1175/JPO-D-24-0119.1."),
)\
"""




# One cell at the end: store-vs-live consistency (plumbing test).
CONSISTENCY_CELL = """\
# Store-vs-live consistency: each final channel (store) must equal
# the function of its live-computed dependencies (Gulf Stream domain;
# land + halo-rim NaNs excluded).  This turns the two-path design
# (finals via RUN->store->LOAD, dependencies via live compute) into
# an explicit pass/fail test of the pipeline plumbing.
from dbof.preprocessing.physical_constants import (
    G, RHO0_REFERENCE, ALPHA, BETA,
)


def _gs(field):
    \"\"\"Gulf Stream slice of one field.

    Inputs: field (str).  Outputs: 2D np.ndarray.
    Generated by LH and Claude
    \"\"\"
    return region_arrays[field]["gulf_stream"][2]


CHECKS = {{
{checks}
}}

# Shared pass/fail loop (dbof.plotting.validation_figures);
# rel_tol=1e-4 — float32 store vs float64 live recompute.
from dbof.plotting.validation_figures import run_consistency_checks

run_consistency_checks(CHECKS)\
"""

CHECKS_SRC = {}

CHECKS_SRC["frontal_structure"] = """\
    # grad*2 are square-BEFORE-interp (sparkle fix, 2026-08-05):
    # NOT reproducible from the centred components — compare the
    # store against the live canonical function instead.
    "gradtheta2 (store) = grad_theta2 (live sq-first)":
        (_gs("gradtheta2"), _gs("gradtheta2_live")),
    "gradsalt2 (store) = grad_salt2 (live sq-first)":
        (_gs("gradsalt2"), _gs("gradsalt2_live")),
    "gradeta2 (store) = grad_eta2 (live sq-first)":
        (_gs("gradeta2"), _gs("gradeta2_live")),
    "gradrho2 (store) = grad_rho2 (live sq-first)":
        (_gs("gradrho2"), _gs("gradrho2_live")),
    "gradb2 (store) = grad_b2 (live sq-first)":
        (_gs("gradb2"), _gs("gradb2_live")),
    "density = rho_theta - RHO0":
        (_gs("density"), _gs("rho_theta") - RHO0_REFERENCE),
    "buoyancy = G*density/RHO0":
        (_gs("buoyancy"), G * _gs("density") / RHO0_REFERENCE),
    # turner_angle is the projection form (Johnson et al. 2012,
    # plan 2026-08-06): built from measured-grad(rho) dot products,
    # NOT from the grad² channels — compare store vs live canonical.
    "turner_angle (store) = turner_angle (live, projection)":
        (_gs("turner_angle"), _gs("turner_angle_live")),\
"""

CHECKS_SRC["kinematic"] = """\
    "relative_vorticity = dv_dx - du_dy":
        (_gs("relative_vorticity"), _gs("dv_dx") - _gs("du_dy")),
    "strain_n = du_dx - dv_dy":
        (_gs("strain_n"), _gs("du_dx") - _gs("dv_dy")),
    "strain_s = dv_dx + du_dy":
        (_gs("strain_s"), _gs("dv_dx") + _gs("du_dy")),
    "divergence = du_dx + dv_dy":
        (_gs("divergence"), _gs("du_dx") + _gs("dv_dy")),
    # strain_mag and okubo_weiss are square-first from the
    # C-grid-native invariants (sparkle fix, 2026-08-05):
    # deliberately NOT equal to combinations of the centred signed
    # channels — compare against the live canonical functions.
    "strain_mag (store) = strain mag (live sq-first)":
        (_gs("strain_mag"), _gs("strain_mag_live")),
    "okubo_weiss (store) = okubo_weiss (live sq-first)":
        (_gs("okubo_weiss"), _gs("okubo_weiss_live")),
    "rossby_number = vorticity / f":
        (_gs("rossby_number"),
         _gs("relative_vorticity") / _gs("coriolis_f")),\
"""

CHECKS_SRC["frontogenesis"] = """\
    "ug = -(G/f) * dEta_dy":
        (_gs("ug"), -(G / _gs("coriolis_f")) * _gs("dEta_dy")),
    "vg = +(G/f) * dEta_dx":
        (_gs("vg"), (G / _gs("coriolis_f")) * _gs("dEta_dx")),
    "frontogenesis_ageo = tendency - geo":
        (_gs("frontogenesis_ageo"),
         _gs("frontogenesis_tendency") - _gs("frontogenesis_geo")),\
"""

CHECKS_SRC["surface_wind"] = """\
    "ekman_pumping = curl / (RHO0 * f)":
        (_gs("ekman_pumping"),
         _gs("wind_stress_curl")
         / (RHO0_REFERENCE * _gs("coriolis_f"))),
    "u_ekman = tau_north / (RHO0 * f)":
        (_gs("u_ekman"),
         _gs("oceTAUY") / (RHO0_REFERENCE * _gs("coriolis_f"))),
    "v_ekman = -tau_east / (RHO0 * f)":
        (_gs("v_ekman"),
         -_gs("oceTAUX") / (RHO0_REFERENCE * _gs("coriolis_f"))),\
"""




# ── Section 6 literature cells (per-reference) ───────────────────────

BACHMAN_MAPS_MD = """\
### 6.1 Bachman et al. (2021) — W*, F, |∇b| over the Kerguelen Plateau

Reference region: 60–85°E, 50–38°S (``regions.REGIONS['kerguelen']``,
sliced in the live cell via ``EXTRA_REGIONS``).  Left column: our
snapshot (2012-11-09); right: Bachman et al. (2021) maps.  Note the
reference shows a sub-window (~74–85°E) of the region and a different
model/date — compare structure and magnitudes, not features.\
"""

BACHMAN_MAPS_CELL = """\
# Bachman et al. (2021) Fig-1-style comparison: stacked maps of
# Wstar, F (their Eq. 38), |grad b| over the Kerguelen Plateau,
# with COLOUR SCALES PINNED TO THE REFERENCE FIGURE.
import matplotlib.colors as mcolors

from dbof.plotting.literature_comparison import stacked_side_by_side

KREG = "kerguelen"


def _kerg(field):
    \"\"\"Kerguelen slice of one field.  Generated by LH and Claude.\"\"\"
    return region_arrays[field][KREG]


_xk, _yk, _dbx = _kerg("db_dx")
_dby = _kerg("db_dy")[2]
gradb_mag_kerg = np.hypot(_dbx, _dby)

# Bachman et al. (2021) Eq. 38: F = 2 Q.grad(b)/|grad(b)| [s-3].
# Our store channel frontogenesis_tendency IS Q.grad(b) (expand the
# dot product to see it equals _frontogenesis_formula), so their F
# is exactly 2*ours/|grad b|.
_F_store = _kerg("frontogenesis_tendency")[2]
F_b38 = np.where(gradb_mag_kerg > 0,
                 2.0 * _F_store / gradb_mag_kerg, np.nan)
_v = np.abs(F_b38[np.isfinite(F_b38)])
print("F (Eq. 38) |value| percentiles [s-3]: "
      + ", ".join(f"p{p}={np.percentile(_v, p):.2e}"
                  for p in (50, 90, 99)))
print("reference map scale: +/-5e-15")


def _kerg_panel(arr, cmap_field, norm, label):
    \"\"\"Renderer with an explicit (literature-pinned) norm.

    Inputs: arr (2D); cmap_field (str, field_cmaps key for the
    colormap); norm (matplotlib Normalize); label (str).
    Outputs: callable(ax).  Generated by LH and Claude
    \"\"\"
    def _render(ax):
        ax.set_facecolor(LAND_COLOR)
        im, _ = plot_global_field(
            ax, _xk, _yk, arr, cmap_field, CMAP_CFG,
            diverging_cmaps=DIVERGING, add_coastline=False,
            norm=norm)
        if im is not None:
            plt.colorbar(im, ax=ax, label=label, fraction=0.04,
                         extend="both")
        ax.set_xticks([])
        ax.set_yticks([])
    return _render


stacked_side_by_side(
    [_kerg_panel(_kerg("Wstar")[2], "Wstar",
                 mcolors.TwoSlopeNorm(vcenter=0, vmin=-1e-7,
                                      vmax=1e-7),
                 "W* (s\u207b\u00b2)  [ref scale \u00b11e-7]"),
     _kerg_panel(F_b38,
                 "frontogenesis_tendency",
                 mcolors.TwoSlopeNorm(vcenter=0, vmin=-5e-15,
                                      vmax=5e-15),
                 "F = 2Q\u00b7\u2207b/|\u2207b| (s\u207b\u00b3) "
                 "[ref scale \u00b15e-15]"),
     _kerg_panel(gradb_mag_kerg, "gradb_mag",
                 mcolors.Normalize(vmin=0, vmax=5e-7),
                 "|\u2207b| (s\u207b\u00b2)  [ref scale "
                 "0\u20135e-7]")],
    LIT_DIR / ("frontogenesis_F-gradB-W*_mapss_Kerguelen_"
               "MITgcm_Bachman(2021).png"),
    our_titles=["Wstar", "F (Bachman Eq. 38)", "|\u2207b|"],
    caption=("Colour scales pinned to Bachman et al. (2021).  W* and "
             "|\u2207b| compare directly.  F computed per their "
             "Eq. 38: F = 2Q\u00b7\u2207b/|\u2207b| [s\u207b"
             "\u00b3] = 2\u00d7(our Q\u00b7\u2207b channel)/"
             "|\u2207b|.  Reference fields are from an IDEALISED "
             "channel simulation (their year 5, day 100), not "
             "LLC4320 \u2014 compare morphology; residual "
             "magnitude offsets may be model/seasonal.\\n"
             "Bachman, S. D., 2021: An Eulerian Scheme for "
             "Identifying Fronts and Vortices in Quasi-Balanced "
             "Flows. J. Phys. Oceanogr., 51, 3279\u20133296, "
             "https://doi.org/10.1175/JPO-D-21-0037.1."),
)
plt.show()\
"""

BACHMAN_PDFS_MD = """\
### 6.3 Bachman et al. (2021) — log-magnitude PDFs, same region

Occurrence histograms of log₁₀|W*|, log₁₀|F|, log₁₀|∇b| over the
Kerguelen box, mimicking the reference's Figure 2 (F sits many
decades below W* and |∇b| by construction of its units).\
"""

BACHMAN_PDFS_CELL = """\
# Bachman et al. (2021) Fig-2-style comparison: overlaid log10
# magnitude histograms (occurrences) over the Kerguelen box.
def _bachman_pdfs(ax):
    \"\"\"Overlaid log10-magnitude histograms (Bachman Fig 2 style).

    Inputs: ax (matplotlib axis).  Outputs: draws on ax.
    Generated by LH and Claude
    \"\"\"
    panels = [
        ("log\u2081\u2080 |W*|", np.abs(_kerg("Wstar")[2]),
         "indianred"),
        ("log\u2081\u2080 |F| (Eq. 38)",
         np.abs(F_b38), "steelblue"),
        ("log\u2081\u2080 |\u2207b|", gradb_mag_kerg,
         "yellowgreen"),
    ]
    for name, vals, color in panels:
        v = vals[np.isfinite(vals)]
        v = np.log10(v[v > 0])
        ax.hist(v, bins=120, alpha=0.6, color=color, label=name)
    ax.set_ylabel("occurrences")
    ax.legend()


side_by_side(
    _bachman_pdfs,
    LIT_DIR / ("frontogenesis_F-gradB-W*_PDFs_Kerguelen_"
               "MITgcm_Bachman(2021).png"),
    caption=("Compare modal positions and widths with Bachman et "
             "al. (2021) Fig 2.  |W*| and |\u2207b| compare "
             "directly; F uses their Eq. 38 (2Q\u00b7\u2207b/"
             "|\u2207b|, s\u207b\u00b3).  Their fields are from "
             "an idealised channel run \u2014 expect lognormal "
             "SHAPES to match; modal offsets may be model/regime.\\n"
             "Bachman, S. D., 2021: An Eulerian Scheme for "
             "Identifying Fronts and Vortices in Quasi-Balanced "
             "Flows. J. Phys. Oceanogr., 51, 3279\u20133296, "
             "https://doi.org/10.1175/JPO-D-21-0037.1."),
)
plt.show()\
"""

TURNER_LIT_MD = """\
### 6.1 Whalen & Drushka (2025) — Turner angle, global

Global World Ocean Atlas climatology (image filename says 2024; the
published paper is 2025) vs our single LLC4320 snapshot:
expect agreement in the large-scale Tu regimes, not mesoscale
detail.\
"""



KIN_BACHMAN_MD = """\
### 6.1 Bachman et al. (2021) — ζ (ω) and W over the Kerguelen Plateau

Reference figure shows b, ω, W, W* (60–85°E, 50–38°S).  This subset
can reproduce the ζ (their ω) and W (okubo_weiss) panels; b is
validated in `frontal_structure.ipynb` and W* in
`frontogenesis.ipynb` (cross-reference rule).  Different model/date —
compare structure and magnitudes, not features.\
"""

KIN_BACHMAN_CELL = """\
# Bachman et al. (2021) comparison: stacked maps of zeta and
# okubo_weiss over the Kerguelen Plateau.
from dbof.plotting.literature_comparison import stacked_side_by_side

KREG = "kerguelen"


def _kerg(field):
    \"\"\"Kerguelen slice of one field.  Generated by LH and Claude.\"\"\"
    return region_arrays[field][KREG]


def _kerg_panel(field):
    \"\"\"Renderer for one Kerguelen map panel.

    Inputs: field (str) — field_cmaps key present in region_arrays.
    Outputs: callable(ax).  Generated by LH and Claude
    \"\"\"
    x, y, arr = _kerg(field)

    def _render(ax):
        ax.set_facecolor(LAND_COLOR)
        im, label = plot_global_field(
            ax, x, y, arr, field, CMAP_CFG,
            diverging_cmaps=DIVERGING, add_coastline=False)
        if im is not None:
            plt.colorbar(im, ax=ax, label=label, fraction=0.04)
        ax.set_xticks([])
        ax.set_yticks([])
    return _render


stacked_side_by_side(
    [_kerg_panel("relative_vorticity"),
     _kerg_panel("okubo_weiss")],
    LIT_DIR / ("kinematic_B-omega-W-W*_maps_Kerguelen_"
               "MITgcm_Bachman(2021).png"),
    our_titles=["relative_vorticity (\u03c9)", "okubo_weiss (W)"],
    caption=("Bachman et al. (2021) panels b (\u03c9) and c (W).  "
             "Expect eddy cores (W<0) ringed by strain (W>0); "
             "b \u2192 frontal_structure.ipynb, "
             "W* \u2192 frontogenesis.ipynb.\\n"
             "Bachman, S. D., 2021: An Eulerian Scheme for "
             "Identifying Fronts and Vortices in Quasi-Balanced "
             "Flows. J. Phys. Oceanogr., 51, 3279\u20133296, "
             "https://doi.org/10.1175/JPO-D-21-0037.1."),
)
plt.show()\
"""

KIN_JPDF_MD = """\
### 6.2 Balwada et al. (2021) — vorticity–strain joint PDFs

Reference setup: an IDEALISED ACC-like channel (2000 km × 2000 km ×
3 km, β-plane centred at 35°S, meridional Gaussian ridge 1 km high /
150 km wide), with f₀ = f(35°S) < 0.  Our Kerguelen box is a
reasonable real-ocean analog: comparable size (~1900 × 1330 km) and
a real topographic ridge in the ACC.

SIGN CONVENTION (matters in the SH): ζ is normalised by SIGNED f₀
(regional mean f, negative here), σ and Δ by |f₀| — so CYCLONIC
vorticity (ζ < 0 in the SH) maps to POSITIVE ζ/f₀, as in the
reference.  Normalising by |f| instead mirrors the plots left-right.

Panels: occurrence JPDF, conditional-mean divergence Δ̄/|f₀|, and
conditional-mean |∇b| (computed live from Theta/Salt via
``compute_buoyancy_gradients``).  ``dbof.plotting.jpdfs`` is a fresh
implementation — reconcile against
``fronts/properties/analysis/jpdf.py``.\
"""

KIN_JPDF_CELL = """\
# Balwada et al. (2021)-style joint PDFs over the Kerguelen box.
from dbof.plotting.jpdfs import (
    plot_jpdf_occurrence, plot_jpdf_conditional,
    plot_jpdf_conditional_log,
)

_zeta = _kerg("relative_vorticity")[2]
_sig = _kerg("strain_mag")[2]
_div = _kerg("divergence")[2]
_gb = _kerg("gradb_mag")[2]

# SIGNED f0 (Balwada: f0 = f(35S) < 0).  Cyclones (zeta<0 in the
# SH) then map to POSITIVE zeta/f0; using |f| mirrors the plots.
f0 = np.nanmean(_kerg("coriolis_f")[2])
print(f"f0 (signed regional mean f) = {f0:.3e} s-1")

_m = (np.isfinite(_zeta) & np.isfinite(_sig)
      & np.isfinite(_div) & np.isfinite(_gb))
zf = _zeta[_m] / f0
sf = _sig[_m] / np.abs(f0)
dv = _div[_m] / np.abs(f0)
gb = _gb[_m]


def _occ(ax):
    plot_jpdf_occurrence(ax, zf, sf)


side_by_side(
    _occ,
    LIT_DIR / ("kinematic_strain-vorticity-JPDF_"
               "Balwada-et-al(2021).png"),
    caption=("Occurrence JPDF, signed-f0 convention: expect the "
             "Balwada et al. (2021) shape \u2014 mode near the "
             "origin, cyclonic (right) tail along the \u03c3 = "
             "\u03b6 separatrix.  Reference is an idealised ACC "
             "channel at ~1 km resolution; compare shape and "
             "regime occupation.\\n"
             "Balwada, D., Q. Xiao, S. Smith, R. Abernathey, and "
             "A. R. Gray, 2021: Vertical Fluxes Conditioned on "
             "Vorticity and Strain Reveal Submesoscale "
             "Ventilation. J. Phys. Oceanogr., 51, "
             "2883\u20132901, "
             "https://doi.org/10.1175/JPO-D-21-0016.1."),
)
plt.show()


def _cond(ax):
    plot_jpdf_conditional(ax, zf, sf, dv,
                          clabel=r"$\\overline{\\Delta}/|f_0|$")


side_by_side(
    _cond,
    LIT_DIR / ("kinematic_divergence-conditional-JPDF_"
               "Balwada-et-al(2021).png"),
    caption=("Conditional-mean divergence: expect convergence "
             "(negative, blue) concentrated along the cyclonic "
             "strain ridge.\\n"
             "Balwada, D., Q. Xiao, S. Smith, R. Abernathey, and "
             "A. R. Gray, 2021: Vertical Fluxes Conditioned on "
             "Vorticity and Strain Reveal Submesoscale "
             "Ventilation. J. Phys. Oceanogr., 51, "
             "2883\u20132901, "
             "https://doi.org/10.1175/JPO-D-21-0016.1."),
)
plt.show()


def _condgb(ax):
    plot_jpdf_conditional_log(
        ax, zf, sf, gb,
        clabel=r"$\\overline{|\\nabla b|}$ (s$^{-2}$)")


side_by_side(
    _condgb,
    LIT_DIR / ("kinematic_gradb-conditional-JPDF_"
               "Balwada-et-al(2021).png"),
    caption=("Conditional-mean |\u2207b| (log scale, 1e-8\u2013"
             "1e-6): expect the tightest buoyancy gradients along "
             "the cyclonic-strain ridge, weakest in the AVD "
             "interior.\\n"
             "Balwada, D., Q. Xiao, S. Smith, R. Abernathey, and "
             "A. R. Gray, 2021: Vertical Fluxes Conditioned on "
             "Vorticity and Strain Reveal Submesoscale "
             "Ventilation. J. Phys. Oceanogr., 51, "
             "2883\u20132901, "
             "https://doi.org/10.1175/JPO-D-21-0016.1."),
)
plt.show()\
"""


F_DEF_MD = """\
### 6.2 The two F definitions side by side (same numerator)

Our product channel is **F = Q·∇b** [s⁻⁵] (unnormalised — this is
and remains the pipeline definition).  Bachman et al. (2021) Eq. 38
uses **F₃₈ = 2Q·∇b/|∇b|** [s⁻³] (Hoskins 1982).  Same numerator,
different normalisation: F emphasises sharpening where |∇b| is
already strong (|∇b|² weighting); F₃₈ measures the rate of change of
|∇b| itself.  Shown side by side over the Kerguelen box, each on its
own percentile scale.\
"""

F_DEF_CELL = """\
# Our F (store channel, unchanged) vs Bachman Eq. 38 — same
# numerator Q.grad(b), different normalisation.
fig, _axes = plt.subplots(1, 2, figsize=(15, 5.5))
for _ax, _arr, _ttl in [
    (_axes[0], _F_store,
     "ours: F = Q\u00b7\u2207b  (s\u207b\u2075)"),
    (_axes[1], F_b38,
     "Bachman Eq. 38: F\u2083\u2088 = 2Q\u00b7\u2207b/"
     "|\u2207b|  (s\u207b\u00b3)"),
]:
    _ax.set_facecolor(LAND_COLOR)
    _im, _ = plot_global_field(
        _ax, _xk, _yk, _arr, "frontogenesis_tendency", CMAP_CFG,
        diverging_cmaps=DIVERGING, add_coastline=False)
    if _im is not None:
        plt.colorbar(_im, ax=_ax, fraction=0.04)
    _ax.set_title(_ttl, fontsize=11)
    _ax.set_xticks([])
    _ax.set_yticks([])
fig.suptitle("Frontogenesis definitions \u2014 identical frontal "
             "morphology, different weighting/units", fontsize=12)
plt.tight_layout()
plt.show()\
"""



YU_MD = """\
### 6.1 Yu et al. (2021) — global Eta and U (LLC4320 itself)

Strongest possible reference: the SAME model.  Their snapshot is
2011-11-24; ours is 2012-11-09 — large-scale structure (gyres, ACC
SSH gradient, equatorial current system) should match closely;
mesoscale eddies will differ in phase.\
"""

YU_CELL = """\
# Yu et al. (2021) comparison: global Eta and U maps (LLC4320,
# their 2011-11-24 vs our 2012-11-09 snapshot).  Both panels use
# the 'balance' diverging colormap (per-cell override of Eta's
# registry entry).
import cartopy.crs as ccrs

from dbof.plotting.literature_comparison import side_by_side

YU_CMAP_CFG = {
    **CMAP_CFG,
    "Eta": ("balance", CMAP_CFG["Eta"][1]),
    "U": ("balance", CMAP_CFG["U"][1]),
}

CIT_YU = ("Yu, X., Ponte, A. L., Lahaye, N., Caspar-Cohen, Z., & "
          "Menemenlis, D. (2021). Geostrophy assessment and "
          "momentum balance of the global oceans in a tide- and "
          "eddy-resolving model. J. Geophys. Res.: Oceans, 126, "
          "e2021JC017422. https://doi.org/10.1029/2021JC017422.")

CAPTIONS = {
    "Eta": ("Global Eta vs Yu et al. (2021), 2011-11-24 — SAME "
            "model, different date AND tidal phase.  LLC4320 is "
            "tide-forced: a single Eta snapshot = dynamic "
            "topography + instantaneous barotropic tide, and the "
            "tidal contribution differs between snapshots by "
            "construction.  Compare the standing dynamic-"
            "topography pattern (subtropical highs, ACC gradient, "
            "~2.5 m global range); pointwise sign/offset "
            "differences at large scale are expected tidal-phase "
            "effects, not pipeline errors.\\n" + CIT_YU),
    "U": ("Global U vs Yu et al. (2021), 2011-11-24 — SAME "
          "model, different date.  The quasi-steady circulation "
          "(equatorial current system, WBC extensions, ACC) should "
          "match in position and sign; tidal and internal-wave "
          "currents differ in phase, and mesoscale eddies in "
          "position.  A systematic reversal or rotation of the "
          "jets WOULD indicate a pipeline (rotation) error — "
          "phase-type differences do not.\\n" + CIT_YU),
}


def _global_panel(field):
    \"\"\"Renderer for one global Robinson panel.

    Inputs: field (str) — store channel name.
    Outputs: callable(ax).  Generated by LH and Claude
    \"\"\"
    x, y, arr = region_arrays[field]["global"]
    arr = mask_wrap_cells(x, y, arr)   # seam/Arctic handling

    def _render(ax):
        ax.set_facecolor(LAND_COLOR)
        im, label = plot_global_field(
            ax, x, y, arr, field, YU_CMAP_CFG,
            diverging_cmaps=DIVERGING,
            transform=ccrs.PlateCarree(), add_coastline=True,
            coastline_kw={"linewidth": 0.4, "edgecolor": "k"})
        if im is not None:
            plt.colorbar(im, ax=ax, orientation="horizontal",
                         fraction=0.04, pad=0.04, label=label)
    return _render


for _field, _png in [
    ("Eta", "native-fields_eta_LLC4320_global_24NOV2011_"
            "Yu-et-al(2021).png"),
    ("U", "native-fields_u-ug_LLC4320_global_24NOV2011_"
          "Yu-et-al(2021).png"),
]:
    side_by_side(
        _global_panel(_field), LIT_DIR / _png,
        projection=ccrs.Robinson(),
        caption=CAPTIONS[_field],
    )
    plt.show()\
"""



FS_GRADB_MD = """\
### 6.2 Global |∇b| snapshot comparison

|∇b| = √(bₓ² + b_y²) from the live gradient components, global view,
colour scale pinned to the reference (0–1.1e-6 s⁻²).  Rename the
``PNG_NAME`` below to match the saved reference image / citation.\
"""

FS_GRADB_CELL = """\
# Global |grad b| = hypot(db_dx, db_dy) vs literature global map.
import cartopy.crs as ccrs

from dbof.plotting.literature_comparison import side_by_side

PNG_NAME = ("frontal-structure_gradb_global_LLC4320_"
            "Bodner-et-al(2025).png")

_xg, _yg, _dbx = region_arrays["db_dx"]["global"]
_dby = region_arrays["db_dy"]["global"][2]
gradb_glob = mask_wrap_cells(_xg, _yg, np.hypot(_dbx, _dby))


def _gradb_panel(ax):
    \"\"\"Global |grad b| on the reference colour scale.

    Inputs: ax (cartopy GeoAxes).  Outputs: draws on ax.
    Generated by LH and Claude
    \"\"\"
    ax.set_facecolor("black")     # reference uses black land/bg
    im = ax.pcolormesh(_xg, _yg, gradb_glob,
                       transform=ccrs.PlateCarree(),
                       cmap="magma", vmin=0.0, vmax=1.1e-6,
                       shading="nearest")
    ax.coastlines(linewidth=0.3, color="gray")
    plt.colorbar(im, ax=ax, orientation="horizontal",
                 fraction=0.04, pad=0.04, extend="max",
                 label="|\u2207b| (s\u207b\u00b2) "
                       "[ref scale 0\u20131.1e-6]")


side_by_side(
    _gradb_panel, LIT_DIR / PNG_NAME,
    projection=ccrs.Robinson(),
    caption=("Global surface |\u2207b| = \u221a(b\u2093\u00b2 + "
             "b\u1d67\u00b2), colour scale pinned to the "
             "reference.  Expect WBC extensions, ACC, and "
             "equatorial fronts bright; gyre interiors dark.\\n"
             "Bodner, A., Balwada, D., & Zanna, L. (2025). A "
             "data-driven approach for parameterizing ocean "
             "submesoscale buoyancy fluxes. J. Adv. Model. "
             "Earth Syst., 17, e2025MS004991. "
             "https://doi.org/10.1029/2025MS004991."),
)
plt.show()\
"""

FS_PGF_MD = """\
### 6.3 Pressure-gradient force g·|∇η| comparison

g·√(gradeta2) from the STORE channel (validates the product
directly), colour scale pinned to the reference (0–8e-5 m s⁻²).
NOTE: the reference is a time-RMS ⟨g∇η⟩_rms (internal-tide beams
smoothed/emphasised); ours is ONE snapshot — expect the same
large-scale pattern but streakier instantaneous detail.  Rename
``PNG_NAME`` to match the saved reference image / citation.\
"""

FS_PGF_CELL = """\
# Global pressure-gradient force g*|grad eta| vs literature RMS map.
from dbof.preprocessing.physical_constants import G

PNG_NAME = ("frontal-structure_gradEta_globalLLC4320_"
            "Yu-et-al(2021).png")

_xg2, _yg2, _ge2 = region_arrays["gradeta2"]["global"]
pgf_glob = mask_wrap_cells(_xg2, _yg2, G * np.sqrt(_ge2))


def _pgf_panel(ax):
    \"\"\"Global g|grad eta| on the reference colour scale.

    Inputs: ax (cartopy GeoAxes).  Outputs: draws on ax.
    Generated by LH and Claude
    \"\"\"
    ax.set_facecolor(LAND_COLOR)
    im = ax.pcolormesh(_xg2, _yg2, pgf_glob,
                       transform=ccrs.PlateCarree(),
                       cmap="OrRd", vmin=0.0, vmax=8e-5,
                       shading="nearest")
    ax.coastlines(linewidth=0.3, color="k")
    plt.colorbar(im, ax=ax, orientation="horizontal",
                 fraction=0.04, pad=0.04, extend="max",
                 label="g\u00b7|\u2207\u03b7| (m s\u207b\u00b2) "
                       "[ref scale 0\u20138e-5]")


side_by_side(
    _pgf_panel, LIT_DIR / PNG_NAME,
    projection=ccrs.Robinson(),
    caption=("Instantaneous g\u00b7|\u2207\u03b7| from the "
             "gradeta2 store channel vs the reference time-RMS "
             "\u27e8g\u2207\u03b7\u27e9: same large-scale "
             "pattern (WBCs, ACC, internal-tide generation "
             "sites); a single snapshot is streakier than the "
             "RMS.\\n"
             "Yu, X., Ponte, A. L., Lahaye, N., Caspar-Cohen, Z., "
             "& Menemenlis, D. (2021). Geostrophy assessment and "
             "momentum balance of the global oceans in a tide- and "
             "eddy-resolving model. J. Geophys. Res.: Oceans, 126, "
             "e2021JC017422. "
             "https://doi.org/10.1029/2021JC017422."),
)
plt.show()\
"""




FG_UG_MD = """\
### 6.4 Yu et al. (2021) — geostrophic u_g, global

Global ug vs the reference (their 2011-11-24 LLC4320 snapshot,
±2 m s⁻¹, equatorial band |lat|<10° masked white).  Same model —
large-scale structure should match closely.\
"""

FG_UG_CELL = """\
# Yu et al. (2021) comparison: global geostrophic u_g (ref scale
# +/-2 m/s; |lat|<10 deg masked as in the reference figure).
import cartopy.crs as ccrs
import matplotlib.colors as _mcolors

_xu, _yu, _ug = region_arrays["ug"]["global"]
_ugm = mask_wrap_cells(_xu, _yu, _ug)
_ugm = np.where(np.abs(_yu) > 10.0, _ugm, np.nan)


def _ug_panel(ax):
    \"\"\"Global ug on the reference colour scale.

    Inputs: ax (cartopy GeoAxes).  Outputs: draws on ax.
    Generated by LH and Claude
    \"\"\"
    ax.set_facecolor(LAND_COLOR)
    im, _ = plot_global_field(
        ax, _xu, _yu, _ugm, "ug", CMAP_CFG,
        diverging_cmaps=DIVERGING,
        transform=ccrs.PlateCarree(), add_coastline=True,
        coastline_kw={"linewidth": 0.4, "edgecolor": "k"},
        norm=_mcolors.TwoSlopeNorm(vcenter=0, vmin=-2.0, vmax=2.0))
    if im is not None:
        plt.colorbar(im, ax=ax, orientation="horizontal",
                     fraction=0.04, pad=0.04,
                     label="u_g (m s⁻¹) "
                           "[ref scale ±2]")


side_by_side(
    _ug_panel,
    LIT_DIR / ("frontogenesis_ug_globalLLC4320_24NOV2011_"
               "Yu-et-al(2021).png"),
    projection=ccrs.Robinson(),
    caption=("Global geostrophic u_g vs Yu et al. (2021) "
             "(2011-11-24; equatorial band |lat|<10° masked "
             "as in the reference).  SAME model — large-scale "
             "structure should match closely; mesoscale differs "
             "in phase.\\n"
             "Yu, X., Ponte, A. L., Lahaye, N., Caspar-Cohen, Z., "
             "& Menemenlis, D. (2021). Geostrophy assessment and "
             "momentum balance of the global oceans in a tide- "
             "and eddy-resolving model. J. Geophys. Res.: Oceans, "
             "126, e2021JC017422. "
             "https://doi.org/10.1029/2021JC017422."),
)
plt.show()\
"""




NATIVE_CIRC_MD = """\
### 6.2 Global circulation schematic — U and V direction check

Our instantaneous U (eastward) and V (northward) beside the
textbook map of major surface currents: a comprehensive sign/
direction check on the CS/SN rotation.  The schematic is a
time-mean; the snapshot overlays mesoscale eddies and tides —
compare the persistent structures.\
"""

NATIVE_CIRC_CELL = """\
# Global circulation schematic comparison: U and V direction check
# (colour scale pinned to +/-0.5 m/s so the mean jets stand out).
import cartopy.crs as ccrs
import matplotlib.colors as _mcolors

from dbof.plotting.literature_comparison import stacked_side_by_side

PNG_NAME = "native-fields_u-v_global-circulation-schematic.png"


def _vel_panel(field):
    \"\"\"Renderer for one velocity panel on a +/-0.5 m/s scale.

    Inputs: field (str) — 'U' or 'V'.
    Outputs: callable(ax).  Generated by LH and Claude
    \"\"\"
    x, y, arr = region_arrays[field]["global"]
    arr = mask_wrap_cells(x, y, arr)

    def _render(ax):
        ax.set_facecolor(LAND_COLOR)
        im, label = plot_global_field(
            ax, x, y, arr, field,
            {**CMAP_CFG, field: ("balance", CMAP_CFG[field][1])},
            diverging_cmaps=DIVERGING,
            transform=ccrs.PlateCarree(), add_coastline=True,
            coastline_kw={"linewidth": 0.4, "edgecolor": "k"},
            norm=_mcolors.TwoSlopeNorm(vcenter=0, vmin=-0.5,
                                       vmax=0.5))
        if im is not None:
            plt.colorbar(im, ax=ax, orientation="horizontal",
                         fraction=0.04, pad=0.04,
                         label=label + "  [±0.5 m/s]")
    return _render


stacked_side_by_side(
    [_vel_panel("U"), _vel_panel("V")],
    LIT_DIR / PNG_NAME,
    our_titles=["U (eastward)", "V (northward)"],
    projection=ccrs.Robinson(),
    caption=("Direction checklist against the schematic — "
             "U: eastward ACC and WBC extensions (red), westward "
             "N/S equatorial currents flanking the eastward "
             "counter-current; V: poleward western boundary "
             "currents (Gulf Stream/Kuroshio V>0; Brazil/Agulhas/"
             "E. Australia V<0), equatorward eastern boundary "
             "currents (California/Canary V<0; Peru/Benguela "
             "V>0).  The schematic is a TIME-MEAN cartoon; the "
             "snapshot adds eddies and tides — any systematic "
             "reversal of these persistent features would indicate "
             "a rotation error.  Schematic of major ocean surface "
             "currents (public-domain textbook map; add specific "
             "attribution if required)."),
)
plt.show()\
"""


# ─────────────────────────────────────────────────────────────────────
# Per-subset specifications
# ─────────────────────────────────────────────────────────────────────

SPECS = {}

SPECS["frontal_structure"] = dict(
    header_extra=(
        "Every computed step is shown: gradient COMPONENTS "
        "(tracer-point, CS/SN-rotated east/north derivatives from "
        "`native_gradient.calculate_native_gradient_tracer`) appear "
        "as their own chain columns before the squared magnitudes."),
    run_note="",
    section3_md=(
        "## Section 3 — SUBSET: `frontal_structure`\n\n"
        "Channels (verbatim from `subset_definitions."
        "SURFACE_SUBSETS`; no raw model channels — every channel is "
        "computed):\n\n"
        "`gradb2`, `gradsalt2`, `gradtheta2`, `gradeta2`, `gradrho2`, "
        "`turner_angle`, `density`, `buoyancy`"),
    dep_table="""\
## Section 4 — Field & dependency table

| FIELD NAME | UNITS | EQUATION | DEPENDENCIES | LOCATION OF CALC IN CODE |
|---|---|---|---|---|
| density (σ₀) | kg m⁻³ | σ₀ = ρ_JMD95(S, Θ, p=0) − 1000 | Theta, Salt → rho_theta | `calculate_fields.potential_density_anomaly` |
| buoyancy (b) | m s⁻² | b = g·σ₀/ρ₀ | density (← Theta, Salt) | `calculate_fields.buoyancy_of_field` |
| gradtheta2 | °C² m⁻² | \\|∇Θ\\|² = Θₓ² + Θᵧ² | dTheta_dx, dTheta_dy (← Theta) | `calculate_fields.grad_theta2` → `native_gradient` |
| gradsalt2 | psu² m⁻² | \\|∇S\\|² | dSalt_dx, dSalt_dy (← Salt) | `calculate_fields.grad_salt2` → `native_gradient` |
| gradeta2 | m² m⁻² | \\|∇η\\|² | dEta_dx, dEta_dy (← Eta) | `calculate_fields.grad_eta2` → `native_gradient` |
| gradrho2 | kg² m⁻⁸ | \\|∇ρθ\\|² | drho_dx, drho_dy (← rho_theta ← Theta, Salt) | `calculate_fields.grad_rho2` → `native_gradient` |
| gradb2 | s⁻⁴ | \\|∇b\\|² | db_dx, db_dy (← buoyancy) | `calculate_fields.grad_b2` → `native_gradient` |
| turner_angle | ° | Tu = arctan[∇ρ·(α∇T + β∇S) / ∇ρ·(α∇T − β∇S)] — projection form, Johnson et al. (2012) / Whalen & Drushka (2025); measured ∇ρ; co-located staggered dot products (`ng.calculate_grad_dot_tracer`); independent of the grad² channels | Theta, Salt → rho_theta | `calculate_fields.turner_angle` |

Non-channel intermediates (computed LIVE below with the same
production code, plotted as chain columns):

| INTERMEDIATE | UNITS | EQUATION | LOCATION |
|---|---|---|---|
| rho_theta | kg m⁻³ | ρ_JMD95(S, Θ, p=0) | `calculate_fields.potential_density` |

**Stencil note (sparkle fix, 2026-08-05)** — the squared magnitudes (all five grad*2) are built SQUARE-BEFORE-INTERP from the native staggered differences (`ng.calculate_grad_squared_tracer`); the displayed gradient components are the geographic (centre-interpolated) vectors — physically the same chain, but the finals are NOT pixelwise combinations of them (see docs/Fields.md).

| d{X}_dx, d{X}_dy for X ∈ Θ, S, η, ρθ, b | per field / m | native tracer gradient + CS/SN rotation | `native_gradient.calculate_native_gradient_tracer` |

Processing operations: land masking (`hFacC == 0`, NaN); native-grid
tracer differentiation with CS/SN rotation (NaN halo rim at face
edges); **no** staggered→tracer interpolation; face→lat-lon
stitching; global row downsampled `[::12, ::12]`.  Conventions:
σ₀ = ρ − 1000; b = g·σ₀/ρ₀ (anomaly-based).\
""",
    live_md=(
        "### Raw inputs & live intermediates\n\n"
        "The store holds only the 8 output channels.  Raw inputs, "
        "rho_theta, and ALL gradient components are computed live "
        "from the same OSN snapshot with the same code, batch-"
        "stitched, and sliced to the validation domains."),
    live_cell="""\
# Live raw + intermediate fields (same loaders as the pipeline).
import dbof.preprocessing.calculate_fields as calculate_fields
import dbof.utils.native_gradient as ng
from dbof.cli.generate_global import load_snapshot
from dbof.global_dataset_creation.data_sources import get_data_source
from dbof.global_dataset_creation.grid_setup import set_up_grid
from dbof.utils.faces_to_latlon import stitch_and_mask

# Grid + snapshot exactly as generate-global does for SURF.
ds_grid, land_mask, xgrid = set_up_grid(PIPELINE, None)
ds_raw, ds_merge, it = load_snapshot(
    PIPELINE, DATE, ds_grid, ["Theta", "Salt", "Eta"],
    surface_only=False, data_source=get_data_source(PIPELINE),
)
print(f"OSN iteration {it}  (store iteration {reader.iteration})")
for _v in ds_merge.data_vars:
    if ds_merge[_v].ndim >= 2:
        print(f"  raw {_v}: {ds_merge[_v].dtype}")

# Lazy live fields: raw, rho_theta, and every gradient component
# (tracer-point, CS/SN-rotated) — the exact code under validation.
rho = calculate_fields.potential_density(ds_merge)
b = calculate_fields.buoyancy_of_field(ds_merge)
gTh = ng.calculate_native_gradient_tracer(
    ds_merge.Theta, ds_merge, grid=xgrid)
gS = ng.calculate_native_gradient_tracer(
    ds_merge.Salt, ds_merge, grid=xgrid)
gE = ng.calculate_native_gradient_tracer(
    ds_merge.Eta, ds_merge, grid=xgrid)
gR = ng.calculate_native_gradient_tracer(rho, ds_merge, grid=xgrid)
gB = ng.calculate_native_gradient_tracer(b, ds_merge, grid=xgrid)

live_map = {
    "Theta": ds_merge["Theta"], "Salt": ds_merge["Salt"],
    "Eta": ds_merge["Eta"], "rho_theta": rho,
    "dTheta_dx": gTh[0], "dTheta_dy": gTh[1],
    "dSalt_dx": gS[0], "dSalt_dy": gS[1],
    "dEta_dx": gE[0], "dEta_dy": gE[1],
    "drho_dx": gR[0], "drho_dy": gR[1],
    "db_dx": gB[0], "db_dy": gB[1],
    # Live finals via the canonical (square-before-interp)
    # functions — consumed by the consistency checks; the store
    # finals CANNOT be reproduced from the centred components
    # (different stencils; see docs/Fields.md).
    "gradtheta2_live": calculate_fields.grad_theta2(ds_merge, xgrid),
    "gradsalt2_live": calculate_fields.grad_salt2(ds_merge, xgrid),
    "gradeta2_live": calculate_fields.grad_eta2(ds_merge, xgrid),
    "gradrho2_live": calculate_fields.grad_rho2(ds_merge, xgrid),
    "gradb2_live": calculate_fields.grad_b2(ds_merge, xgrid),
    "turner_angle_live": calculate_fields.turner_angle(
        ds_merge, xgrid),
}\
""" + LIVE_TAIL,
    chains={
        "density":      ["Theta", "Salt", "rho_theta", "density"],
        "buoyancy":     ["Theta", "Salt", "rho_theta", "density",
                         "buoyancy"],
        "gradtheta2":   ["Theta", "dTheta_dx", "dTheta_dy",
                         "gradtheta2"],
        "gradsalt2":    ["Salt", "dSalt_dx", "dSalt_dy", "gradsalt2"],
        "gradeta2":     ["Eta", "dEta_dx", "dEta_dy", "gradeta2"],
        "gradrho2":     ["rho_theta", "drho_dx", "drho_dy",
                         "gradrho2"],
        "gradb2":       ["buoyancy", "db_dx", "db_dy", "gradb2"],
        "turner_angle": ["gradtheta2", "gradsalt2", "gradrho2",
                         "turner_angle"],
    },
    f_norm=set(),
    log_fields={"gradb2", "gradsalt2", "gradtheta2", "gradeta2",
                "gradrho2"},
    fields=[
        ("density", "5.1 density (σ₀)",
         "Theta, Salt → rho_theta (JMD95 at p=0) → σ₀ = ρθ − 1000 "
         "(`calculate_fields.potential_density_anomaly`)."),
        ("buoyancy", "5.2 buoyancy (b)",
         "σ₀ → b = g·σ₀/ρ₀ [m s⁻²] "
         "(`calculate_fields.buoyancy_of_field`)."),
        ("gradtheta2", "5.3 gradtheta2 (|∇Θ|²)",
         "Theta → (∂Θ/∂x, ∂Θ/∂y) via native tracer gradient + CS/SN "
         "rotation → sum of squares "
         "(`calculate_fields.grad_theta2`).  Components should be "
         "diverging around 0 with frontal banding."),
        ("gradsalt2", "5.4 gradsalt2 (|∇S|²)",
         "Salt → (∂S/∂x, ∂S/∂y) → |∇S|² "
         "(`calculate_fields.grad_salt2`)."),
        ("gradeta2", "5.5 gradeta2 (|∇η|²)",
         "Eta → (∂η/∂x, ∂η/∂y) → |∇η|² "
         "(`calculate_fields.grad_eta2`).  Geostrophic KE proxy."),
        ("gradrho2", "5.6 gradrho2 (|∇ρ|²)",
         "rho_theta → (∂ρ/∂x, ∂ρ/∂y) → |∇ρθ|² "
         "(`calculate_fields.grad_rho2`)."),
        ("gradb2", "5.7 gradb2 (|∇b|²)",
         "buoyancy → (∂b/∂x, ∂b/∂y) → |∇b|² "
         "(`calculate_fields.grad_b2`).  Structure = gradrho2 scaled "
         "by (g/ρ₀)²."),
        ("turner_angle", "5.8 turner_angle (Tu)",
         "gradtheta2, gradsalt2, gradrho2 → "
         "Tu = arctan[ρ₀(β²|∇S|² − α²|∇Θ|²)/(−|∇ρ|²/ρ₀)] [°] "
         "(`calculate_fields.turner_angle`).  Masked where |∇ρ| = 0.",
         TURNER_FIG3),
    ],
    lit_cells=[(TURNER_LIT_MD, TURNER_FIG3),
               (FS_GRADB_MD, FS_GRADB_CELL),
               (FS_PGF_MD, FS_PGF_CELL)],
    crossref=(
        "**Cross-references** — σ₀ and b are validated here; sibling "
        "notebooks (`kinematic`, `frontogenesis`, DEPTH "
        "`stratification`, ...) reference these sections for the "
        "shared density/buoyancy machinery rather than "
        "re-validating it."),
)

SPECS["native_fields"] = dict(
    header_extra=(
        "Raw model channels are validated directly; U/V are the only "
        "computed channels (staggered→tracer interpolation + CS/SN "
        "rotation).  The rotation machinery itself is exercised "
        "further in `kinematic.ipynb` (Jacobian) and referenced from "
        "there."),
    run_note="",
    section3_md=(
        "## Section 3 — SUBSET: `native_fields`\n\n"
        "Channels (verbatim from `subset_definitions."
        "SURFACE_SUBSETS`):\n\n"
        "raw — `Theta`, `Salt`, `Eta`, `W`; computed — `U`, `V`"),
    dep_table="""\
## Section 4 — Field & dependency table

| FIELD NAME | UNITS | EQUATION | DEPENDENCIES | LOCATION OF CALC IN CODE |
|---|---|---|---|---|
| Theta | °C | model output | — | OSN llc_surf kerchunk |
| Salt | psu | model output | — | OSN llc_surf kerchunk |
| Eta | m | model output | — | OSN llc_surf kerchunk |
| W | m s⁻¹ | model output (top interface, k_l=0 — ≈0 by construction; noted) | — | OSN llc_surf kerchunk |
| U | m s⁻¹ | staggered U,V → interp to tracer pts → CS/SN rotation → eastward | raw U, V; CS, SN | `calculate_fields.geographic_velocity` → `native_gradient.rotate_vector_to_geographic` |
| V | m s⁻¹ | same → northward | raw U, V; CS, SN | `calculate_fields.geographic_velocity` |

Processing operations: land masking (`hFacC == 0`, NaN);
staggered→tracer interpolation (U at i_g, V at j_g) for U/V only;
CS/SN rotation; **no** differentiation; face→lat-lon stitching;
global row downsampled `[::12, ::12]`.  Raw staggered U/V cannot be
stitched (staggered dims) — the rotation step is validated via the
table and the Jacobian chains in `kinematic.ipynb`.\
""",
    live_md=None, live_cell=None,
    chains={
        "Theta": ["Theta"], "Salt": ["Salt"], "Eta": ["Eta"],
        "W": ["W"], "U": ["U"], "V": ["V"],
    },
    f_norm=set(), log_fields=set(),
    fields=[
        ("Theta", "5.1 Theta (raw)",
         "Model potential temperature, validated as loaded."),
        ("Salt", "5.2 Salt (raw)",
         "Model salinity.  Subtropical maxima, fresh ITCZ/plumes."),
        ("Eta", "5.3 Eta (raw)",
         "Sea-surface height anomaly.  Gyres, ACC gradient."),
        ("W", "5.4 W (raw)",
         "Vertical velocity at the top interface (k_l = 0) — ≈0 by "
         "construction; internal-wave signals dominate."),
        ("U", "5.5 U (computed: eastward)",
         "Staggered U,V interpolated to tracer points and rotated "
         "to geographic east via CS/SN."),
        ("V", "5.6 V (computed: northward)",
         "Same rotation, northward component."),
    ],
    lit_cells=[(YU_MD, YU_CELL),
               (NATIVE_CIRC_MD, NATIVE_CIRC_CELL)],
    crossref=(
        "**Cross-references** — the interp+rotation machinery used "
        "here is exercised on derived fields in `kinematic.ipynb` "
        "(Jacobian) and `frontogenesis.ipynb`; raw Theta/Salt/Eta "
        "feed `frontal_structure.ipynb` gradients."),
)

SPECS["surface_wind"] = dict(
    header_extra=(
        "Wind-stress diagnostics.  τ comes from the LLC_SURF S3 "
        "forcing stores at this date (OSN llc_wind kerchunk ends "
        "2012-07-15); the 20121109T12 LLC_SURF raw data is "
        "transferred and available."),
    run_note=(
        "\n\nNote: at 2012-11-09 the wind variables come from the "
        "LLC_SURF S3 stores (outside the OSN llc_wind window).  The "
        "20121109T12 LLC_SURF raw data has been TRANSFERRED (plan §9 "
        "item resolved 2026-07-31), so no OSN wind data is needed."),
    section3_md=(
        "## Section 3 — SUBSET: `surface_wind`\n\n"
        "Channels (verbatim from `subset_definitions."
        "SURFACE_SUBSETS`):\n\n"
        "raw (SURF only) — `oceQnet`; computed — `oceTAUX`, "
        "`oceTAUY`, `wind_stress_curl`, `ekman_pumping`, `u_ekman`, "
        "`v_ekman`"),
    dep_table="""\
## Section 4 — Field & dependency table

| FIELD NAME | UNITS | EQUATION | DEPENDENCIES | LOCATION OF CALC IN CODE |
|---|---|---|---|---|
| oceTAUX | N m⁻² | staggered τ → interp + CS/SN rotation → eastward | raw oceTAUX, oceTAUY; CS, SN | `calculate_fields.geographic_wind_stress` |
| oceTAUY | N m⁻² | same → northward | raw oceTAUX, oceTAUY; CS, SN | `calculate_fields.geographic_wind_stress` |
| wind_stress_curl | N m⁻³ | ∇×τ (native gradients of rotated τ) | oceTAUX, oceTAUY; grid metrics | `calculate_fields.wind_stress_curl` |
| ekman_pumping | m s⁻¹ | w_E = curl(τ)/(ρ₀ f); NaN at equator | wind_stress_curl, f | `calculate_fields.ekman_pumping` |
| u_ekman | m² s⁻¹ | Ekman transport (τ/ρ₀f, 90° right of τ in NH) | oceTAUX, oceTAUY, f | `calculate_fields.ekman_transport` |
| v_ekman | m² s⁻¹ | same, meridional component | oceTAUX, oceTAUY, f | `calculate_fields.ekman_transport` |
| oceQnet | W m⁻² | model output (SURF pipeline only) | — | LLC_SURF store |

Intermediate plotted in dependency columns: `coriolis_f`
(f = 2Ω·sin lat), recomputed in-notebook on the rect grid — an
independent check on the pipeline's
`calculate_fields.coriolis_parameter`.

Processing operations: land masking; staggered→tracer interpolation +
CS/SN rotation (τ); native-grid differentiation (curl; halo rim);
f-division (ekman fields — equatorial NaNs expected); face→lat-lon
stitching; global downsampling.\
""",
    live_md=(
        "### In-notebook extras: coriolis_f + surface currents\n\n"
        "`coriolis_f` is recomputed on the rect grid (same equation "
        "as `calculate_fields.coriolis_parameter`; independent "
        "cross-check), masked to ocean pixels.  Surface currents "
        "`U`, `V` are loaded from the **native_fields store of the "
        "same run/date** as COMPANION columns for the rotated wind "
        "stress (not dependencies): expect broad stress/current "
        "alignment under the trades and westerlies with Ekman "
        "deflection, and WBC jets that are NOT wind-aligned.  Run "
        "native_fields.ipynb Section 1 first if that store is "
        "missing."),
    live_cell="""\
# coriolis_f on the rect grid (same equation as
# calculate_fields.coriolis_parameter), ocean-masked via oceTAUX.
from dbof.plotting import regions
from dbof.preprocessing.physical_constants import OMEGA_EARTH

f_rect = (2.0 * OMEGA_EARTH
          * np.sin(np.radians(YC))).astype("float32")
_tau = reader.get_channel_snapshot("oceTAUX")
f_rect = np.where(np.isfinite(_tau), f_rect, np.nan)
del _tau

region_arrays = {}
region_arrays["coriolis_f"] = regions.select_all_regions(
    f_rect, XC, YC)
del f_rect
print("coriolis_f ready (rect-grid cross-check)")

# Surface currents U, V from the native_fields store of the SAME
# run/date — companion columns for the rotated wind stress (NOT
# dependencies; cross-subset physical comparison).  Requires the
# native_fields store for this run_id/date (generated by
# native_fields.ipynb).
defn_nf = get_subset_definition(PIPELINE, "native_fields")
reader_nf = zarr_dataset.GlobalZarrDatasetReader(
    bucket=BUCKET, folder=FOLDER, run_id=RUN_ID,
    dataset_name=defn_nf["dataset_name"], date_prefix=DATE_PREFIX,
    fs=fs,
)
for _ch in ["U", "V"]:
    _arr = reader_nf.get_channel_snapshot(_ch)
    region_arrays[_ch] = regions.select_all_regions(_arr, XC, YC)
    del _arr
print("U, V loaded from native_fields store (same run/date)")\
""",
    chains={
        "oceTAUX": ["U", "oceTAUX"],
        "oceTAUY": ["V", "oceTAUY"],
        "wind_stress_curl": ["oceTAUX", "oceTAUY",
                             "wind_stress_curl"],
        "ekman_pumping": ["wind_stress_curl", "coriolis_f",
                          "ekman_pumping"],
        "u_ekman": ["oceTAUX", "oceTAUY", "coriolis_f", "u_ekman"],
        "v_ekman": ["oceTAUX", "oceTAUY", "coriolis_f", "v_ekman"],
        "oceQnet": ["oceQnet"],
    },
    f_norm={"ekman_pumping", "u_ekman", "v_ekman"},
    log_fields=set(),
    fields=[
        ("oceTAUX", "5.1 oceTAUX (eastward wind stress)",
         "Rotated τ east: trades (negative), westerlies (positive).  "
         "Companion column U (surface current, native_fields store, "
         "same run/date): broadly aligned in wind-driven regimes; "
         "WBC jets stand out as NOT wind-aligned."),
        ("oceTAUY", "5.2 oceTAUY (northward wind stress)",
         "Rotated τ north: monsoon/storm-track structure.  "
         "Companion column V (surface current): same comparison as "
         "U/oceTAUX."),
        ("wind_stress_curl", "5.3 wind_stress_curl",
         "∇×τ from native gradients of the rotated stress; gyre-"
         "scale sign structure."),
        ("ekman_pumping", "5.4 ekman_pumping",
         "w_E = curl(τ)/(ρ₀f); equatorial extremes expected (f→0; "
         "PDF row filtered)."),
        ("u_ekman", "5.5 u_ekman",
         "Zonal Ekman transport — 90° right of τ in NH, left in SH."),
        ("v_ekman", "5.6 v_ekman",
         "Meridional Ekman transport: equatorward under westerlies, "
         "poleward under trades."),
        ("oceQnet", "5.7 oceQnet (raw, SURF only)",
         "Net surface heat flux (LLC_SURF store), validated as "
         "loaded; ocean heat loss over WBCs in November."),
    ],
    crossref=(
        "**Cross-references** — the DEPTH-pipeline `surface_wind` "
        "subset is surface_only and identical in content; it "
        "references THIS notebook.  coriolis_f as an output channel "
        "is validated in `kinematic.ipynb`."),
)

SPECS["icearea"] = dict(
    header_extra=(
        "Minimal notebook (one raw channel; plan Clarification 6: "
        "standalone).  SIarea comes from the LLC_SURF store at this "
        "date (transferred; outside the OSN llc_wind window)."),
    run_note=(
        "\n\nNote: SIarea at 2012-11-09 comes from the LLC_SURF S3 "
        "store (OSN llc_wind ends 2012-07-15); the 20121109T12 raw "
        "data is transferred and available."),
    section3_md=(
        "## Section 3 — SUBSET: `icearea`\n\n"
        "Channels (verbatim from `subset_definitions."
        "SURFACE_SUBSETS`):\n\nraw — `SIarea` (no computed channels)"),
    dep_table="""\
## Section 4 — Field & dependency table

| FIELD NAME | UNITS | EQUATION | DEPENDENCIES | LOCATION OF CALC IN CODE |
|---|---|---|---|---|
| SIarea | 0–1 | model output (sea-ice area fraction) | — | LLC_SURF store |

Processing operations: land masking; face→lat-lon stitching; global
downsampling.  No computation, interpolation, rotation, or
differentiation.  Note: mid/low-latitude validation domains are
ice-free — the PDF is a delta at 0 there; the global and SO Atlantic
rows carry the signal (Nov = austral spring: Antarctic ice edge
within the SO Atlantic box).\
""",
    live_md=None, live_cell=None,
    chains={"SIarea": ["SIarea"]},
    f_norm=set(), log_fields=set(),
    fields=[
        ("SIarea", "5.1 SIarea (raw)",
         "Sea-ice area fraction, validated as loaded.  November: "
         "Antarctic ice edge in the SO Atlantic box; Arctic cap on "
         "the global row.  Open-ocean zeros dominate the PDFs "
         "(documented)."),
    ],
    crossref=(
        "**Cross-references** — none; DEPTH `icearea` is "
        "surface_only and references this notebook."),
)

SPECS["kinematic"] = dict(
    header_extra=(
        "Velocity-gradient diagnostics.  Every computed step is "
        "shown: the four Jacobian components (du_dx, du_dy, dv_dx, "
        "dv_dy — tracer-point, tensor-rotated) are computed live and "
        "plotted as chain columns feeding each final field."),
    run_note="",
    section3_md=(
        "## Section 3 — SUBSET: `kinematic`\n\n"
        "Channels (verbatim from `subset_definitions."
        "SURFACE_SUBSETS`):\n\n"
        "computed — `relative_vorticity`, `strain_n`, `strain_s`, "
        "`strain_mag`, `divergence`, `coriolis_f`, `rossby_number`, "
        "`okubo_weiss`"),
    dep_table="""\
## Section 4 — Field & dependency table

| FIELD NAME | UNITS | EQUATION | DEPENDENCIES | LOCATION OF CALC IN CODE |
|---|---|---|---|---|
| relative_vorticity | s⁻¹ | ζ = ∂v/∂x − ∂u/∂y | dv_dx, du_dy (← J ← raw U, V) | `calculate_fields.relative_vorticity` → `native_gradient.calculate_jacobian` |
| strain_n | s⁻¹ | σₙ = ∂u/∂x − ∂v/∂y | du_dx, dv_dy | `calculate_fields.strain` |
| strain_s | s⁻¹ | σₛ = ∂v/∂x + ∂u/∂y | dv_dx, du_dy | `calculate_fields.strain` |
| strain_mag | s⁻¹ | σ = √(σₙ² + σₛ²) | strain_n, strain_s | `calculate_fields.strain` |
| divergence | s⁻¹ | δ = ∂u/∂x + ∂v/∂y | du_dx, dv_dy | `calculate_fields.divergence` |
| coriolis_f | s⁻¹ | f = 2Ω sin(lat) | YC | `calculate_fields.coriolis_parameter` |
| rossby_number | — | Ro = ζ/f | relative_vorticity, coriolis_f | `calculate_fields.rossby_number` |
| okubo_weiss | s⁻² | W = σₙ² + σₛ² − ζ² | strain_mag, relative_vorticity | `calculate_fields.okubo_weiss_parameter` |

**Stencil note (sparkle fix, 2026-08-05)** — the squared magnitudes (strain_mag, okubo_weiss) are built SQUARE-BEFORE-INTERP from the native staggered differences (`ng.calculate_grad_squared_tracer`, `ng.calculate_native_strain_vorticity` — ζ², σₛ² on the corner (momVort3) points); the displayed gradient components are the geographic (centre-interpolated) vectors — physically the same chain, but the finals are NOT pixelwise combinations of them (see docs/Fields.md).


Live-plotted intermediates: rotated tracer-point `U`, `V`
(`calculate_fields.geographic_velocity`) and the Jacobian components
`du_dx`, `du_dy`, `dv_dx`, `dv_dy`
(`calculate_fields.compute_velocity_jacobian` →
`native_gradient.calculate_jacobian`).

Processing operations: land masking; staggered→tracer interpolation;
CS/SN tensor rotation of J; native-grid differentiation (halo rim);
f-division (Ro — equatorial extremes expected); face→lat-lon
stitching; global downsampling.\
""",
    live_md=(
        "### Raw inputs & Jacobian components computed live\n\n"
        "The store holds only derived channels; the chains start "
        "from the rotated tracer-point velocities and the four "
        "Jacobian components, computed here from the same OSN "
        "snapshot with the same code and batch-stitched."),
    live_cell="""\
# Live raw inputs + Jacobian components (pipeline loaders/code).
import dbof.preprocessing.calculate_fields as calculate_fields
from dbof.cli.generate_global import load_snapshot
from dbof.global_dataset_creation.data_sources import get_data_source
from dbof.global_dataset_creation.grid_setup import set_up_grid
from dbof.utils.faces_to_latlon import stitch_and_mask

ds_grid, land_mask, xgrid = set_up_grid(PIPELINE, None)
ds_raw, ds_merge, it = load_snapshot(
    PIPELINE, DATE, ds_grid, ["U", "V", "Theta", "Salt"],
    surface_only=False, data_source=get_data_source(PIPELINE),
)
print(f"OSN iteration {it}  (store iteration {reader.iteration})")
for _v in ds_merge.data_vars:
    if ds_merge[_v].ndim >= 2:
        print(f"  raw {_v}: {ds_merge[_v].dtype}")

u_east, v_north = calculate_fields.geographic_velocity(
    ds_merge, xgrid)
J = calculate_fields.compute_velocity_jacobian(ds_merge, xgrid)

# |grad b| for the Balwada gradb-conditioned JPDF (Section 6).
bg = calculate_fields.compute_buoyancy_gradients(ds_merge, xgrid)

# Extra slice region for the Bachman/Balwada comparisons.
EXTRA_REGIONS = ["kerguelen"]

s_mag_live, _, _ = calculate_fields.strain(
    ds_merge, xgrid, jacobian=J)

live_map = {
    "U": u_east, "V": v_north,
    "du_dx": J.du_dx, "du_dy": J.du_dy,
    "dv_dx": J.dv_dx, "dv_dy": J.dv_dy,
    "gradb_mag": (bg.zonal**2 + bg.merid**2) ** 0.5,
    # Live finals via the canonical square-first functions —
    # consumed by the consistency checks (strain_mag and
    # okubo_weiss are NOT reproducible from the centred
    # components; see docs/Fields.md).
    "strain_mag_live": s_mag_live,
    "okubo_weiss_live": calculate_fields.okubo_weiss_parameter(
        ds_merge, xgrid),
}\
""" + LIVE_TAIL,
    chains={
        "relative_vorticity": ["U", "V", "dv_dx", "du_dy",
                               "relative_vorticity"],
        "strain_n": ["U", "V", "du_dx", "dv_dy", "strain_n"],
        "strain_s": ["U", "V", "dv_dx", "du_dy", "strain_s"],
        "strain_mag": ["strain_n", "strain_s", "strain_mag"],
        "divergence": ["U", "V", "du_dx", "dv_dy", "divergence"],
        "coriolis_f": ["coriolis_f"],
        "rossby_number": ["relative_vorticity", "coriolis_f",
                          "rossby_number"],
        "okubo_weiss": ["strain_mag", "relative_vorticity",
                        "okubo_weiss"],
    },
    f_norm={"rossby_number"},
    log_fields=set(),
    fields=[
        ("relative_vorticity", "5.1 relative_vorticity (ζ)",
         "ζ = dv_dx − du_dy.  Submesoscale cyclonic filaments "
         "(positive-skewed NH), eddy cores; halo rim NaN."),
        ("strain_n", "5.2 strain_n (σₙ)",
         "σₙ = du_dx − dv_dy: frontal confluence zones."),
        ("strain_s", "5.3 strain_s (σₛ)",
         "σₛ = dv_dx + du_dy: jet flanks."),
        ("strain_mag", "5.4 strain_mag (σ)",
         "σ = √(σₙ²+σₛ²) — positive-definite; fronts and eddy "
         "peripheries."),
        ("divergence", "5.5 divergence (δ)",
         "δ = du_dx + dv_dy: frontal convergence filaments; "
         "magnitudes ≪ ζ at mesoscale."),
        ("coriolis_f", "5.6 coriolis_f",
         "f = 2Ω sin(lat) — analytic; validates the YC → f path."),
        ("rossby_number", "5.7 rossby_number (Ro = ζ/f)",
         "O(0.1–1) in energetic regions; equatorial blow-up "
         "expected (f→0; PDF row filtered)."),
        ("okubo_weiss", "5.8 okubo_weiss (W)",
         "W = σ² − ζ²: negative eddy cores, positive strain "
         "peripheries."),
    ],
    lit_cells=[(KIN_BACHMAN_MD, KIN_BACHMAN_CELL),
               (KIN_JPDF_MD, KIN_JPDF_CELL)],
    crossref=(
        "**Cross-references** — rotation/Jacobian machinery is "
        "validated HERE (sibling notebooks reference this one); "
        "rotated U/V as output channels → `native_fields.ipynb`; "
        "W* (∇b-modified Okubo-Weiss) → `frontogenesis.ipynb`."),
)

SPECS["frontogenesis"] = dict(
    header_extra=(
        "Frontogenesis-function diagnostics.  Every computed step is "
        "shown: buoyancy-gradient components (db_dx, db_dy) and SSH-"
        "gradient components (dEta_dx, dEta_dy) are computed live "
        "and plotted; the velocity-Jacobian components feeding "
        "F(u,v) are identical to the ones validated in "
        "`kinematic.ipynb` (referenced, not re-plotted)."),
    run_note="",
    section3_md=(
        "## Section 3 — SUBSET: `frontogenesis`\n\n"
        "Channels (verbatim from `subset_definitions."
        "SURFACE_SUBSETS`):\n\n"
        "computed — `frontogenesis_tendency`, `ug`, `vg`, "
        "`frontogenesis_geo`, `frontogenesis_ageo`, `Wstar`"),
    dep_table="""\
## Section 4 — Field & dependency table

| FIELD NAME | UNITS | EQUATION | DEPENDENCIES | LOCATION OF CALC IN CODE |
|---|---|---|---|---|
| frontogenesis_tendency | s⁻⁵ | F(u,v) = −[uₓ·bₓ² + (u_y + vₓ)·bₓ·b_y + v_y·b_y²] | J (U, V); db_dx, db_dy (← b ← Theta, Salt) | `calculate_fields.frontogenesis_tendency` (`_frontogenesis_formula`) |
| ug | m s⁻¹ | −(g/f)·∂η/∂y | dEta_dy, coriolis_f | `calculate_fields.geostrophic_velocity` |
| vg | m s⁻¹ | +(g/f)·∂η/∂x | dEta_dx, coriolis_f | `calculate_fields.geostrophic_velocity` |
| frontogenesis_geo | s⁻⁵ | F(ug,vg) — same formula with geostrophic velocity gradients | ug, vg gradients; db_dx, db_dy | `calculate_fields.frontogenesis_geo` |
| frontogenesis_ageo | s⁻⁵ | F(u,v) − F(ug,vg) | both tendencies | `surface_subsets.compute_frontogenesis` (inline) |
| Wstar | s⁻² | W* = 4·sgn(λ₂)·√(λ₁² + λ₂²); λ₂ = W/4 with W = σₙ² + σₛ² − ζ²; λ₁ = λ₂/2 + √(λ₂² + \|Q\|²/f²)/2; Q = −(uₓbₓ + vₓb_y, u_ybₓ + v_yb_y) (Bachman 2021) | J; db_dx, db_dy; f | `calculate_fields.modified_okubo_weiss` |

Live-plotted intermediates: raw `Eta`, rotated `U`/`V`, `buoyancy`,
`db_dx`/`db_dy` (`calculate_fields.compute_buoyancy_gradients`),
`dEta_dx`/`dEta_dy` (`native_gradient.
calculate_native_gradient_tracer`), and rect-grid `coriolis_f`.
J components → validated in `kinematic.ipynb` (identical arrays).

Processing operations: land masking; staggered→tracer interpolation
+ CS/SN rotation (U, V, J); native-grid differentiation (∇b, ∇η, J —
halo rim); f-division (ug, vg, W* — equatorial extremes expected);
face→lat-lon stitching; global downsampling.\
""",
    live_md=(
        "### Raw inputs & intermediates computed live\n\n"
        "The store holds only the six output channels; chains start "
        "from raw Eta, rotated velocities, buoyancy, and the "
        "buoyancy/SSH gradient components — computed here from the "
        "same OSN snapshot with the same code and batch-stitched.  "
        "coriolis_f is recomputed on the rect grid (independent "
        "cross-check)."),
    live_cell="""\
# Live raw inputs + intermediates (pipeline loaders/code).
import dbof.preprocessing.calculate_fields as calculate_fields
import dbof.utils.native_gradient as ng
from dbof.cli.generate_global import load_snapshot
from dbof.global_dataset_creation.data_sources import get_data_source
from dbof.global_dataset_creation.grid_setup import set_up_grid
from dbof.utils.faces_to_latlon import stitch_and_mask
from dbof.preprocessing.physical_constants import OMEGA_EARTH

ds_grid, land_mask, xgrid = set_up_grid(PIPELINE, None)
ds_raw, ds_merge, it = load_snapshot(
    PIPELINE, DATE, ds_grid, ["Theta", "Salt", "Eta", "U", "V"],
    surface_only=False, data_source=get_data_source(PIPELINE),
)
print(f"OSN iteration {it}  (store iteration {reader.iteration})")
for _v in ds_merge.data_vars:
    if ds_merge[_v].ndim >= 2:
        print(f"  raw {_v}: {ds_merge[_v].dtype}")

u_east, v_north = calculate_fields.geographic_velocity(
    ds_merge, xgrid)
bg = calculate_fields.compute_buoyancy_gradients(ds_merge, xgrid)
gE = ng.calculate_native_gradient_tracer(
    ds_merge.Eta, ds_merge, grid=xgrid)
J = calculate_fields.compute_velocity_jacobian(ds_merge, xgrid)

# Extra slice region for the Bachman et al. (2021) comparison.
EXTRA_REGIONS = ["kerguelen"]

live_map = {
    "Eta": ds_merge["Eta"], "U": u_east, "V": v_north,
    "buoyancy": calculate_fields.buoyancy_of_field(ds_merge),
    "db_dx": bg.zonal, "db_dy": bg.merid,
    "dEta_dx": gE[0], "dEta_dy": gE[1],
    "du_dx": J.du_dx, "du_dy": J.du_dy,
    "dv_dx": J.dv_dx, "dv_dy": J.dv_dy,
}\
""" + LIVE_TAIL + """

# coriolis_f on the rect grid (cross-check on the pipeline's f),
# ocean-masked via the sliced Eta NaN pattern per region.
f_full = (2.0 * OMEGA_EARTH
          * np.sin(np.radians(YC))).astype("float32")
region_arrays["coriolis_f"] = {}
for rname, (x, y, eta) in region_arrays["Eta"].items():
    jsl, isl = regions.region_index_slices(XC, YC, rname)
    f_sub = np.where(np.isfinite(eta), f_full[jsl, isl], np.nan)
    region_arrays["coriolis_f"][rname] = (x, y, f_sub)
del f_full
print("coriolis_f ready (rect-grid cross-check)")\
""",
    chains={
        "frontogenesis_tendency": ["U", "V", "du_dx", "du_dy",
                                   "dv_dx", "dv_dy", "db_dx",
                                   "db_dy", "frontogenesis_tendency"],
        "ug": ["Eta", "dEta_dy", "coriolis_f", "ug"],
        "vg": ["Eta", "dEta_dx", "coriolis_f", "vg"],
        "frontogenesis_geo": ["ug", "vg", "db_dx", "db_dy",
                              "frontogenesis_geo"],
        "frontogenesis_ageo": ["frontogenesis_tendency",
                               "frontogenesis_geo",
                               "frontogenesis_ageo"],
        "Wstar": ["U", "V", "du_dx", "du_dy", "dv_dx",
                  "dv_dy", "db_dx", "db_dy", "Wstar"],
    },
    f_norm={"ug", "vg", "frontogenesis_geo", "frontogenesis_ageo",
            "Wstar"},
    log_fields=set(),
    fields=[
        ("frontogenesis_tendency",
         "5.1 frontogenesis_tendency — "
         "F(u,v) = −[uₓbₓ² + (u_y+vₓ)bₓb_y + v_yb_y²]",
         "Kinematic frontogenesis function [s⁻⁵]: the rate of "
         "|∇b|² sharpening by the horizontal flow.  Positive "
         "filaments along strain-dominated fronts (Gulf Stream "
         "north wall, ACC)."),
        ("ug", "5.2 ug (geostrophic U)",
         "−(g/f)·dEta_dy.  Tracks rotated U at mesoscale away from "
         "the equator; equatorial blow-up expected."),
        ("vg", "5.3 vg (geostrophic V)",
         "+(g/f)·dEta_dx.  Same checks, meridional component."),
        ("frontogenesis_geo",
         "5.4 frontogenesis_geo — F(ug,vg), same formula with "
         "geostrophic gradients",
         "Geostrophic contribution [s⁻⁵]: "
         "−[ugₓbₓ² + (ug_y+vgₓ)bₓb_y + vg_yb_y²]; smoother than "
         "the full tendency."),
        ("frontogenesis_ageo",
         "5.5 frontogenesis_ageo — F(u,v) − F(ug,vg)",
         "Ageostrophic/submesoscale residual [s⁻⁵] "
         "(dispatcher-inline difference)."),
        ("Wstar",
         "5.6 Wstar — W* = 4·sgn(λ₂)·√(λ₁² + λ₂²)",
         "Modified Okubo-Weiss (Bachman 2021) [s⁻²]: λ₂ = W/4 "
         "(classical Okubo-Weiss), λ₁ = λ₂/2 + √(λ₂² + |Q|²/f²)/2 "
         "with the QG Q-vector Q = −(uₓbₓ + vₓb_y, u_ybₓ + v_yb_y).  "
         "Strain/vorticity partition sensitised to frontal ∇b; "
         "NaN-heavy at the equator (expected; PDF row filtered)."),
    ],
    lit_cells=[(BACHMAN_MAPS_MD, BACHMAN_MAPS_CELL),
               (F_DEF_MD, F_DEF_CELL),
               (BACHMAN_PDFS_MD, BACHMAN_PDFS_CELL),
               (FG_UG_MD, FG_UG_CELL)],
    crossref=(
        "**Cross-references** — J machinery → `kinematic.ipynb`; "
        "b and |∇b|² (gradb2) → `frontal_structure.ipynb`; raw "
        "Eta/U/V → `native_fields.ipynb`."),
)


# ─────────────────────────────────────────────────────────────────────
# Notebook assembly
# ─────────────────────────────────────────────────────────────────────

def build(subset, spec):
    cells = []
    md(cells, (
        f"# Field validation — `{subset}` (SURF pipeline)\n\n"
        "End-to-end validation of every calculated field in the "
        f"**{subset}** surface subset: the notebook RUNs the "
        "pipeline, LOADs its own output, and validates each field "
        "with dependency-chain maps, PDFs, and a literature "
        "comparison.\n\n"
        "| | |\n|---|---|\n"
        f"| Subset | `{subset}` (SURF) |\n"
        "| Timestep | 2012-11-09 12:00:00 (`20121109_120000`) |\n"
        "| run_id | `field_validation_v1` |\n"
        "| Plan | `prompts/field_validation.md` |\n"
        "| Field reference | `docs/Fields.md` |\n\n"
        + spec["header_extra"]))
    md(cells, RUN_MD.format(run_note=spec["run_note"]))
    code(cells, RUN_CELL.format(subset=subset))
    md(cells, LOAD_MD)
    code(cells, LOAD_CELL)
    md(cells, spec["section3_md"])
    code(cells, GUARD_CELL)
    md(cells, spec["dep_table"])
    if spec["live_cell"]:
        md(cells, spec["live_md"])
        code(cells, spec["live_cell"])
    code(cells, SLICE_HEAD + SLICE_TAIL)
    md(cells, SEC5_MD)

    def fmt_set(s):
        if not s:
            return "set()"
        inner = ", ".join(f'"{x}"' for x in sorted(s))
        return "{" + inner + "}"

    chains_lines = ["{"]
    for k, v in spec["chains"].items():
        vv = ", ".join(f'"{x}"' for x in v)
        chains_lines.append(f'    "{k}": [{vv}],')
    chains_lines.append("}")
    code(cells, HELPERS_CELL.format(
        chains="\n".join(chains_lines),
        f_norm=fmt_set(spec["f_norm"]),
        log_fields=fmt_set(spec["log_fields"])))

    for entry in spec["fields"]:
        field, title, desc = entry[0], entry[1], entry[2]
        md(cells, f"### {title}\n\n{desc}")
        code(cells, f'figure1_maps("{field}")')
        code(cells, f'figure2_pdfs("{field}")')

    md(cells, "## Section 6 — Literature comparisons\n\n"
              "One subsection per reference (a reference may "
              "validate several fields); only fields with published "
              "counterparts appear here.")
    lit = spec.get("lit_cells", [])
    for lit_md, lit_code in lit:
        md(cells, lit_md)
        code(cells, lit_code)
    if not lit:
        md(cells, "_No literature references supplied yet for this "
                  "subset — add per-reference subsections here as "
                  "they become available._")

    md(cells, SUMMARY_MD)
    code(cells, SUMMARY_CELL)
    if subset in CHECKS_SRC:
        code(cells,
             CONSISTENCY_CELL.format(checks=CHECKS_SRC[subset]))
    md(cells, spec["crossref"])

    nb = {"cells": cells,
          "metadata": {"kernelspec": {"display_name": "Python 3",
                                      "language": "python",
                                      "name": "python3"},
                       "language_info": {"name": "python",
                                         "version": "3"}},
          "nbformat": 4, "nbformat_minor": 5}
    path = OUT_DIR + f"{subset}.ipynb"
    with open(path, "w") as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)
    print(f"wrote {path} ({len(cells)} cells)")


if __name__ == "__main__":
    import sys

    only = set(sys.argv[1:])          # no args -> build all six
    for name, s in SPECS.items():
        if not only or name in only:
            build(name, s)
