"""
Shared fixtures for the field-migration safety-net tests.

MIGRATION SCAFFOLDING — see ``prompts/field_migration.md`` (Phase 0).
These tests verify that consolidating ``calculate_fields.py``
and ``calculated_fields_at_depth.py`` into ``calculate_fields.py`` /
``calculate_fields_at_depth.py`` is faithful.  They are not long-term
tests; the ``tests/field_migration/`` directory is deleted (or selectively
promoted) at Phase 5.

Running
-------
All fixtures are synthetic and in-memory (no network, no model data), so
the whole directory runs on a local machine::

    conda activate llcngp
    python -m pytest tests/field_migration -v

Design
------
The synthetic grid reproduces the full 13-face LLC topology (so xgcm
``face_connections`` are exercised) with uniform metrics, following the
approach of ``tests/test_jacobian.py``.  Two dask-backed datasets are
provided:

- ``ds2d`` — surface-style ``ds_merge`` (no vertical dimension), matching
  what the SURF pipeline feeds ``calculate_fields``.
- ``ds3d`` — depth-style ``ds_merge`` with ``k`` (tracer) and ``k_l``
  (W) vertical dimensions, ``Z``/``Zl`` coordinates and ``drF`` spacing,
  matching what the DEPTH pipeline feeds ``calculated_fields_at_depth``.

The k=0 level of every 3D variable equals the corresponding 2D variable
EXACTLY, so equivalence tests can assert::

    surface_fn(ds2d, grid2d) == fn_3d(ds3d, grid3d).isel(k=0)

Theta decreases and Salt increases with depth, giving a stable, stably
stratified water column (sigma0 increasing with depth) so MLD/N²-based
fields are physically meaningful in the golden-regression test.

Generated by LH and Claude
"""

import numpy as np
import dask.array as da
import xarray as xr
import pytest

from dbof.llc4320_ingestion.grid import set_xgcm_grid

# LLC4320 has 13 faces; reproducing all of them exercises the xgcm
# face_connections machinery exactly as production does.
N_FACES = 13

# Cells per face along each horizontal dimension.  Must comfortably exceed
# 2 * EDGE_MARGIN so tests can compare face interiors when needed.
N = 16

# Uniform grid spacing [m] for dxC and dyC.
D = 2500.0

# Number of tracer levels in the 3D dataset.
NK = 6

# Tracer-level depths [m, positive down -> stored negative-up like MITgcm].
# Includes a level near 10 m so the MLD reference-depth logic is exercised.
Z_LEVELS = np.array([1.0, 5.0, 10.0, 20.0, 40.0, 80.0])

# Cells trimmed from each face edge when a test compares against analytic
# answers (halo/boundary contamination; see tests/test_jacobian.py).
EDGE_MARGIN = 3


# ---------------------------------------------------------------------------
# Grid construction (adapted from tests/test_jacobian.py::make_synthetic_grid)
# ---------------------------------------------------------------------------

def _base_coords(n=N):
    """1D index coordinates with the comodo attributes xgcm needs."""
    idx = np.arange(n)
    return {
        "face": ("face", np.arange(N_FACES)),
        "i": ("i", idx, {"axis": "X"}),
        "i_g": ("i_g", idx, {"axis": "X", "c_grid_axis_shift": 0.5}),
        "j": ("j", idx, {"axis": "Y"}),
        "j_g": ("j_g", idx, {"axis": "Y", "c_grid_axis_shift": 0.5}),
    }


def _grid_metric_vars(n=N, d=D, cs=1.0, sn=0.0):
    """CS/SN on tracer points; dxC on U points; dyC on V points."""
    return {
        "CS": xr.DataArray(np.full((N_FACES, n, n), cs),
                           dims=("face", "j", "i")),
        "SN": xr.DataArray(np.full((N_FACES, n, n), sn),
                           dims=("face", "j", "i")),
        "dxC": xr.DataArray(np.full((N_FACES, n, n), d),
                            dims=("face", "j", "i_g")),
        "dyC": xr.DataArray(np.full((N_FACES, n, n), d),
                            dims=("face", "j_g", "i")),
    }


def _surface_fields(n=N, d=D):
    """Deterministic, smoothly varying 2D physical fields (numpy).

    Returns a dict of numpy arrays keyed by variable name.  Values are in
    realistic ranges so the JMD95 EOS and derived diagnostics behave
    physically.  Fields vary across (face, j, i) so no gradient is
    trivially zero.
    """
    idx = np.arange(n, dtype=float)
    x = idx[None, None, :] * d          # metres along i
    y = idx[None, :, None] * d          # metres along j
    f_off = np.arange(N_FACES, dtype=float)[:, None, None]  # per-face offset

    L = n * d  # face width [m], used to scale smooth variations

    theta = (14.0 + 2.0 * np.sin(2 * np.pi * x / L)
             + 1.5 * np.cos(2 * np.pi * y / L) + 0.1 * f_off)
    salt = (35.0 + 0.4 * np.cos(2 * np.pi * x / L)
            + 0.3 * np.sin(2 * np.pi * y / L) + 0.01 * f_off)
    eta = (0.2 * np.sin(2 * np.pi * x / L)
           * np.cos(2 * np.pi * y / L) + 0.005 * f_off)
    # Latitude: mid-latitude band, varying with j so f is non-constant but
    # never crosses the equator (avoids f=0 NaN bands in comparisons).
    yc = 30.0 + 10.0 * (y / L) + 0.2 * f_off

    shape = np.broadcast_shapes(theta.shape, (N_FACES, n, n))
    out = {
        "Theta": np.broadcast_to(theta, shape).copy(),
        "Salt": np.broadcast_to(salt, shape).copy(),
        "Eta": np.broadcast_to(eta, shape).copy(),
        "YC": np.broadcast_to(yc, shape).copy(),
    }

    # Staggered vector fields: linear + smooth so gradients are non-trivial.
    u = (0.3 + 1.0e-5 * x + 2.0e-5 * y
         + 0.05 * np.sin(2 * np.pi * y / L) + 0.01 * f_off)
    v = (-0.2 + 1.5e-5 * x - 1.0e-5 * y
         + 0.05 * np.cos(2 * np.pi * x / L) + 0.01 * f_off)
    taux = (0.05 + 0.02 * np.sin(2 * np.pi * y / L) + 0.001 * f_off)
    tauy = (0.02 + 0.02 * np.cos(2 * np.pi * x / L) + 0.001 * f_off)

    out["U"] = np.broadcast_to(u, shape).copy()          # -> (face, j, i_g)
    out["V"] = np.broadcast_to(v, shape).copy()          # -> (face, j_g, i)
    out["oceTAUX"] = np.broadcast_to(taux, shape).copy() # -> (face, j, i_g)
    out["oceTAUY"] = np.broadcast_to(tauy, shape).copy() # -> (face, j_g, i)
    return out


# Dims for each variable (tracer vs staggered points).
_VAR_DIMS = {
    "Theta": ("face", "j", "i"),
    "Salt": ("face", "j", "i"),
    "Eta": ("face", "j", "i"),
    "YC": ("face", "j", "i"),
    "U": ("face", "j", "i_g"),
    "V": ("face", "j_g", "i"),
    "oceTAUX": ("face", "j", "i_g"),
    "oceTAUY": ("face", "j_g", "i"),
}

# Per-level modulation of each 3D variable.  k=0 MUST be exactly the 2D
# field (offset 0 at k=0).  Theta decreases / Salt increases with depth ->
# sigma0 increases with depth (stable stratification).
_K_OFFSETS = {
    "Theta": lambda k: -0.4 * k,        # cooling with depth
    "Salt": lambda k: +0.02 * k,        # salinification with depth
    "U": lambda k: -0.03 * k,           # velocity decays with depth
    "V": lambda k: +0.02 * k,
}


def _to_dask(arr):
    """Wrap a numpy array in a single-chunk dask array (lazy, like prod)."""
    return da.from_array(arr, chunks=arr.shape)


def build_ds2d(cs=1.0, sn=0.0):
    """Surface-style ds_merge: 2D fields, no vertical dimension."""
    coords = _base_coords()
    fields = _surface_fields()
    data_vars = dict(_grid_metric_vars(cs=cs, sn=sn))
    for name, dims in _VAR_DIMS.items():
        if name == "YC":
            # Coordinates stay numpy-backed (as in production, where grid
            # coords are eagerly loaded).  A dask-backed coordinate makes
            # xarray's coord-merge compute it just to compare equality,
            # which would poison the laziness tests with a false positive.
            data_vars[name] = xr.DataArray(fields[name], dims=dims)
        else:
            data_vars[name] = xr.DataArray(_to_dask(fields[name]),
                                           dims=dims)
    ds = xr.Dataset(data_vars, coords=coords)
    # NOTE: YC stays a plain data variable (not set_coords).  If it were a
    # coordinate, functions that ds.chunk() internally (e.g. _density_lazy)
    # would make it dask-backed on derived arrays, and xarray's coordinate
    # merge then COMPUTES it for equality checks — an xarray internal, not
    # the field-function eagerness the laziness tests target.
    return ds


def build_ds3d(cs=1.0, sn=0.0, nk=NK):
    """Depth-style ds_merge: 3D fields with k / k_l, Z / Zl, drF.

    The k=0 slice of every 3D variable equals the 2D variable exactly.
    """
    coords = _base_coords()
    coords["k"] = ("k", np.arange(nk))
    # k_l carries nk+1 interface levels so W can be averaged onto the nk
    # tracer levels (0.5 * (W[k] + W[k+1]) needs one extra interface).
    coords["k_l"] = ("k_l", np.arange(nk + 1))
    fields = _surface_fields()

    data_vars = dict(_grid_metric_vars(cs=cs, sn=sn))

    for name, dims in _VAR_DIMS.items():
        base = fields[name]
        if name == "YC":
            # numpy-backed coordinate (see build_ds2d for rationale).
            data_vars[name] = xr.DataArray(base, dims=dims)
            continue
        if name == "Eta":                   # inherently 2D
            data_vars[name] = xr.DataArray(_to_dask(base), dims=dims)
            continue
        if name in ("oceTAUX", "oceTAUY"):  # wind stress is 2D
            data_vars[name] = xr.DataArray(_to_dask(base), dims=dims)
            continue
        offset_fn = _K_OFFSETS.get(name, lambda k: 0.0 * k)
        levels = np.stack(
            [base + offset_fn(float(k)) for k in range(nk)], axis=0)
        data_vars[name] = xr.DataArray(
            _to_dask(levels), dims=("k",) + dims)

    # Vertical velocity W on lower interfaces (k_l), Zl coordinate.
    idx = np.arange(N, dtype=float)
    x = idx[None, None, :] * D
    y = idx[None, :, None] * D
    L = N * D
    w2d = 1.0e-5 * np.sin(2 * np.pi * x / L) * np.cos(2 * np.pi * y / L)
    w2d = np.broadcast_to(
        w2d + 1.0e-6 * np.arange(N_FACES, dtype=float)[:, None, None],
        (N_FACES, N, N)).copy()
    w_levels = np.stack(
        [w2d * (1.0 - 0.1 * k) for k in range(nk + 1)], axis=0)
    data_vars["W"] = xr.DataArray(
        _to_dask(w_levels), dims=("k_l", "face", "j", "i"))

    ds = xr.Dataset(data_vars, coords=coords)

    # Depth coordinates (MITgcm convention: negative up) and spacing.
    # Kept as plain data variables, not set_coords — see build_ds2d note.
    ds["Z"] = xr.DataArray(-Z_LEVELS[:nk], dims=("k",))
    # Interface depths: surface, midpoints between tracer levels, bottom.
    zl = np.concatenate([
        [0.0],
        0.5 * (Z_LEVELS[:nk - 1] + Z_LEVELS[1:nk]),
        [Z_LEVELS[nk - 1] * 1.5],
    ])
    ds["Zl"] = xr.DataArray(-zl, dims=("k_l",))
    drf = np.gradient(Z_LEVELS[:nk])
    ds["drF"] = xr.DataArray(drf, dims=("k",))
    return ds


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

@pytest.fixture(scope="session")
def ds2d():
    """Dask-backed surface-style ds_merge (rotation angle ~26.6 deg)."""
    # Non-trivial rotation (cs, sn) so CS/SN handling is exercised;
    # cs^2 + sn^2 = 1.
    return build_ds2d(cs=0.8944271909999159, sn=0.4472135954999579)


@pytest.fixture(scope="session")
def ds3d():
    """Dask-backed depth-style ds_merge; k=0 equals ds2d exactly."""
    return build_ds3d(cs=0.8944271909999159, sn=0.4472135954999579)


@pytest.fixture(scope="session")
def grid2d(ds2d):
    """Production xgcm grid (with LLC face connections) for ds2d."""
    return set_xgcm_grid(ds2d, use_connections=True)


@pytest.fixture(scope="session")
def grid3d(ds3d):
    """Production xgcm grid (with LLC face connections) for ds3d."""
    return set_xgcm_grid(ds3d, use_connections=True)


# ---------------------------------------------------------------------------
# Comparison helper
# ---------------------------------------------------------------------------

def assert_k0_equal(surface_result, result_3d, rtol=1e-10, atol=0.0,
                    name=""):
    """Assert a surface-module result equals the k=0 slice of a 3D result.

    Both inputs may be xr.DataArray, dask or numpy backed.  Comparison is
    on values (coords/attrs intentionally ignored — those differences are
    resolved by the migration itself). NaNs must match in position.
    """
    a = np.asarray(getattr(surface_result, "values", surface_result))
    b3 = result_3d
    if hasattr(b3, "isel") and "k" in getattr(b3, "dims", ()):
        b3 = b3.isel(k=0)
    b = np.asarray(getattr(b3, "values", b3))
    assert a.shape == b.shape, (
        f"{name}: shape mismatch {a.shape} vs {b.shape}")
    np.testing.assert_allclose(
        a, b, rtol=rtol, atol=atol, equal_nan=True,
        err_msg=f"{name}: surface result != 3D result at k=0")
