"""
Equivalence tests: frontal structure & frontogenesis (surface vs _3d).

MIGRATION SCAFFOLDING — see ``prompts/field_migration.md`` (Phase 0).
Covers turner_angle, buoyancy gradients, frontogenesis (kinematic and
geostrophic), and geostrophic velocity.

Also PINS the known buoyancy-definition inconsistency the migration
resolves: the "phys" buoyancy-gradient route (b = 9.81*rho/1000, used by
R_ib and W*) differs from the scaled route (b = 9.8*rho/1025, used by
grad_b2/frontogenesis) by exactly the constant factor
(9.81/1000)/(9.8/1025).  When Phase 1/2 unify RHO0 = 1000 and g = 9.81,
``test_phys_vs_scaled_buoyancy_gradient_ratio`` will fail — DELETE it at
that point (its job is done); the equivalence tests must keep passing.

Running (local machine — synthetic data only, no network)::

    conda activate llcngp
    python -m pytest tests/field_migration/test_equivalence_frontal.py -v

Generated by LH and Claude
"""

import numpy as np

import dbof.preprocessing.calculate_additional_fields as caf
import dbof.preprocessing.calculated_fields_at_depth as cfad

from conftest import assert_k0_equal

# Expected constant ratio between the two legacy buoyancy definitions:
# phys (G/RHO0_BOUSSINESQ = 9.81/1000) over scaled (9.8/1025).
_PHYS_OVER_SCALED = (9.81 / 1000.0) / (9.8 / 1025.0)


def test_turner_angle_equivalence(ds2d, grid2d, ds3d, grid3d):
    """Turner angle values match at k=0.

    The surface version uses np.where (drops xr coords), the 3D version
    xr.where — values must nonetheless be identical.  The migration keeps
    the xr.where (lazy, coord-preserving) form.
    """
    assert_k0_equal(
        caf.turner_angle(ds2d, grid2d),
        cfad.turner_angle_3d(ds3d, grid3d),
        name="turner_angle")


def test_turner_angle_injection_consistent(ds2d, grid2d):
    """Pre-computed gradient kwargs must not change turner_angle values."""
    gt = caf.grad_theta2(ds2d, grid2d)
    gs = caf.grad_salt2(ds2d, grid2d)
    gr = caf.grad_rho2(ds2d, grid2d)
    assert_k0_equal(
        caf.turner_angle(ds2d, grid2d,
                         gradtheta2=gt, gradsalt2=gs, gradrho2=gr),
        caf.turner_angle(ds2d, grid2d),
        name="turner_angle injection")


def test_buoyancy_gradients_equivalence(ds2d, grid2d, ds3d, grid3d):
    """compute_buoyancy_gradients vs compute_buoyancy_gradients_3d.

    Both legacy scaled routes are b = 9.8*rho/1025; components must match
    at k=0 (zonal and meridional).
    """
    bg2 = caf.compute_buoyancy_gradients(ds2d, grid2d)
    bg3 = cfad.compute_buoyancy_gradients_3d(ds3d, grid3d)
    assert_k0_equal(bg2.zonal, bg3.zonal, name="buoyancy_gradients.zonal")
    assert_k0_equal(bg2.merid, bg3.merid, name="buoyancy_gradients.merid")


def test_frontogenesis_tendency_equivalence(ds2d, grid2d, ds3d, grid3d):
    assert_k0_equal(
        caf.frontogenesis_tendency(ds2d, grid2d),
        cfad.frontogenesis_tendency_3d(ds3d, grid3d),
        name="frontogenesis_tendency")


def test_geostrophic_velocity_equivalence(ds2d, grid2d, ds3d, grid3d):
    """ug/vg from Eta are inherently 2D; both versions must agree."""
    ug2, vg2 = caf.geostrophic_velocity(ds2d, grid2d)
    ug3, vg3 = cfad.geostrophic_velocity_3d(ds3d, grid3d)
    assert_k0_equal(ug2, ug3, name="ug")
    assert_k0_equal(vg2, vg3, name="vg")


def test_frontogenesis_geo_equivalence(ds2d, grid2d, ds3d, grid3d):
    assert_k0_equal(
        caf.frontogenesis_geo(ds2d, grid2d),
        cfad.frontogenesis_geo_3d(ds3d, grid3d),
        name="frontogenesis_geo")


def test_frontogenesis_injection_consistent(ds2d, grid2d):
    """Shared jacobian/buoyancy-gradient kwargs must not change values."""
    jac = caf.compute_velocity_jacobian(ds2d, grid2d)
    bg = caf.compute_buoyancy_gradients(ds2d, grid2d)
    assert_k0_equal(
        caf.frontogenesis_tendency(ds2d, grid2d,
                                   jacobian=jac, buoyancy_gradients=bg),
        caf.frontogenesis_tendency(ds2d, grid2d),
        name="frontogenesis_tendency injection")


def test_phys_vs_scaled_buoyancy_gradient_ratio(ds3d, grid3d):
    """PINS the legacy two-buoyancy inconsistency (DELETE after Phase 2).

    The private phys route (used by R_ib / W*) must differ from the
    scaled route (used by grad_b2 / frontogenesis) by exactly the
    constant factor (9.81/1000)/(9.8/1025) ≈ 1.02566 — i.e. the ONLY
    differences are g and rho_ref, as established in the migration plan.
    """
    bx_phys, by_phys = cfad._buoyancy_gradient_phys_3d(ds3d, grid3d)
    bg_scaled = cfad.compute_buoyancy_gradients_3d(ds3d, grid3d)

    bx_p = np.asarray(bx_phys.values)
    bx_s = np.asarray(bg_scaled.zonal.values)
    # Exclude near-zero gradients: the ratio is numerically ill-conditioned
    # where both routes' float rounding dominates the tiny values.
    mask = np.abs(bx_s) > 1e-6 * np.nanmax(np.abs(bx_s))
    ratio = bx_p[mask] / bx_s[mask]
    np.testing.assert_allclose(
        ratio, _PHYS_OVER_SCALED, rtol=1e-7,
        err_msg="phys/scaled buoyancy gradients differ by more than the "
                "expected constant factor — a third definition exists?")
