"""
CLI entry point for generating a single LLC4320 tile of a chosen property.

This is a thin wrapper around ``tile_utils.run``: it parses CLI args (which
property to extract, and where the tile is) and delegates the entire pipeline
to :func:`dbof.tiles.tile_utils.run`.

The tile location may be given either as a rect-grid pixel (``--i``/``--j``)
or as a geographic coordinate (``--lon``/``--lat``).  Supply exactly one of
the two pairs; a geographic request is resolved to the nearest rect pixel via
the grid file, so a user does not need to know rect indices.

CLI usage
---------

    # by rect-grid pixel
    generate-tile --i 8123 --j 6044 \\
        --timestamp '2012-11-09 12:00:00' --property density

    # by geographic location (resolved to i, j via grid.zarr)
    generate-tile --lon -45.0 --lat 33.0 \\
        --timestamp '2012-11-09 12:00:00' --property temperature \\
        [--output ./out_dir] [--clobber] [--qa-plot] [--s3-config over.yaml]

    # into the standard output tree
    generate-tile --lon -122.0 --lat 36.7 \\
        --timestamp '2012-11-09 12:00:00' --property Ri \\
        --netcdf-base /mnt/tank/Oceanography/data/OGCM/LLC/Fronts --run-id V4

    # a whole hourly series on one tile, surface-only, from the OSN store
    generate-tile --lon -121.9 --lat 36.8 --property gradb2 \\
        --pipeline OSN --continue-on-error \\
        --dates-config configs/tiles/tile330_gradb2_osn.yaml \\
        --output ./gradb2_tile330

``--dates-config`` switches this CLI from one snapshot to a series: it reads
``data.date_iterations`` from a run YAML (the same key the global configs use)
and dispatches to :func:`dbof.tiles.tile_utils.run_series`, which resolves the
tile and loads the grid once for the whole run.  ``--timestamp`` is then
ignored.

``--pipeline OSN`` reads Theta/Salt from the public hourly kerchunk surface
store instead of the S3 depth store -- the only source with consecutive hourly
snapshots, and the one the SURF global pipeline already uses.  The result is a
2D ``(j, i)`` field; the field functions are dimension-agnostic, so the numbers
match the ``k=0`` level of the 3D computation.

``--property`` accepts any key registered in
:data:`dbof.tiles.tile_utils.TILE_PROPERTIES` (``Ri``, ``N2``,
``relative_vorticity``, ``density``, ...), plus the legacy aliases
``temperature`` and ``salinity``.

Output location, in precedence order:

1. ``--output`` -- honoured verbatim (a directory gets the default filename).
2. ``--netcdf-base`` + ``--run-id`` (both required together) --
   ``{netcdf-base}/{run-id}/{YYYYMMDD_HHMMSS}/tiles/{default_name}``, the
   same tree ``run-all-subsets`` writes into, plus a ``tiles`` leaf.
3. neither -- ``./{default_name}`` in the current directory.

``{default_name}`` is ``{prefix}_tile{tile_idx:03d}_{YYYYMMDDTHH}.nc`` where
``{prefix}`` is the property's ``filename_prefix``
(``ri``, ``density``, ``theta``, ``salt``, ...).

Adding a new property does **not** require any change in this file -- just add
an entry to ``TILE_PROPERTIES`` in ``dbof/tiles/tile_utils.py``.

Generated by JXP and Claude
"""

# stdlib
from __future__ import annotations
import argparse
import logging
import sys
from pathlib import Path

import yaml

from dbof.tiles import tile_utils


def _read_dates_config(path: Path) -> list[str]:
    """Pull ``data.date_iterations`` out of a run YAML.

    Deliberately the SAME key the global/transfer configs use, so one config
    file can drive both a tile series and whatever else consumes those dates.

    Parameters
    ----------
    path : Path
        YAML file with a ``data.date_iterations`` list of
        ``'YYYY-MM-DD HH:MM:SS'`` strings.

    Returns
    -------
    list of str
        The timestamps, in file order.

    Raises
    ------
    ValueError
        If the key is missing or empty.
    """
    with open(path, "r") as fh:
        raw = yaml.safe_load(fh) or {}
    dates = (raw.get("data") or {}).get("date_iterations") or []
    if not dates:
        raise ValueError(f"'data.date_iterations' must be set in {path}")
    return [str(d) for d in dates]


def _parse_args(argv=None) -> argparse.Namespace:
    """Build the CLI argument parser and parse ``argv``.

    Parameters
    ----------
    argv : list of str or None
        Argument list (default: ``sys.argv[1:]``).

    Returns
    -------
    argparse.Namespace
        Parsed arguments with attributes ``i``, ``j``, ``lon``, ``lat``,
        ``timestamp``, ``property``, ``output``, ``s3_config``, ``clobber``,
        ``qa_plot``.
    """
    p = argparse.ArgumentParser(
        description=(
            "Generate a 3D tile of one property (density / temperature / "
            "salinity / ...) for one LLC4320 snapshot."
        ),
    )
    p.add_argument(
        "--i", type=int, default=None,
        help=(
            "rect-grid i coord (0..17279); any pixel inside the desired tile. "
            "Use with --j, or use --lon/--lat instead."
        ),
    )
    p.add_argument(
        "--j", type=int, default=None,
        help=(
            "rect-grid j coord (0..12959); any pixel inside the desired tile. "
            "Use with --i, or use --lon/--lat instead."
        ),
    )
    p.add_argument(
        "--lon", type=float, default=None,
        help=(
            "target longitude (deg E); resolved to the nearest rect pixel via "
            "the grid file.  Use with --lat, or use --i/--j instead."
        ),
    )
    p.add_argument(
        "--lat", type=float, default=None,
        help=(
            "target latitude (deg N); resolved to the nearest rect pixel via "
            "the grid file.  Use with --lon, or use --i/--j instead."
        ),
    )
    p.add_argument(
        "--timestamp", type=str, default=None,
        help=(
            "timestamp 'YYYY-MM-DD HH:MM:SS' for a single snapshot.  "
            "Required unless --dates-config is given."
        ),
    )
    p.add_argument(
        "--dates-config", dest="dates_config", type=Path, default=None,
        help=(
            "Run YAML holding data.date_iterations.  Switches this CLI to a "
            "series run (tile_utils.run_series): the tile and its grid are "
            "resolved once and reused for every timestamp."
        ),
    )
    p.add_argument(
        "--pipeline", type=str, default="DEPTH",
        choices=("DEPTH", "SURF", "OSN"),
        help=(
            "Which data source to read.  DEPTH (default) = the S3 full-depth "
            "timestep stores.  OSN = the public hourly kerchunk SURFACE store "
            "(surface-only, the only source with consecutive hourly dates).  "
            "Ignored when --s3-config is given."
        ),
    )
    p.add_argument(
        "--continue-on-error", dest="continue_on_error", action="store_true",
        help=(
            "Series runs only: log and skip a timestamp that fails instead of "
            "aborting the whole run."
        ),
    )
    p.add_argument(
        "--property", dest="property", type=str, default="density",
        choices=sorted(tile_utils.TILE_PROPERTIES),
        help=(
            "Which property to extract.  Add new properties by registering "
            "them in tile_utils.TILE_PROPERTIES."
        ),
    )
    p.add_argument(
        "--output", type=str, default=None,
        help=(
            "Explicit output path (file, or an existing directory to drop "
            "the default filename into).  Overrides --netcdf-base/--run-id."
        ),
    )
    p.add_argument(
        "--netcdf-base", dest="netcdf_base", type=str, default=None,
        help=(
            "Root of the standard output tree, e.g. "
            "/mnt/tank/Oceanography/data/OGCM/LLC/Fronts.  With --run-id the "
            "file lands in {netcdf-base}/{run-id}/{YYYYMMDD_HHMMSS}/tiles/ "
            "(same convention as run-all-subsets, plus a tiles leaf).  "
            "Must be given together with --run-id."
        ),
    )
    p.add_argument(
        "--run-id", dest="run_id", type=str, default=None,
        help=(
            "Dataset version directory under --netcdf-base (e.g. V4).  "
            "Must be given together with --netcdf-base."
        ),
    )
    p.add_argument(
        "--s3-config", type=Path, default=tile_utils.DEFAULT_CONFIG,
        help=(
            "Optional legacy YAML override with an s3_source block.  If "
            "omitted, the canonical LLC_DEPTH source (data_sources.py) is used."
        ),
    )
    p.add_argument(
        "--clobber", action="store_true",
        help="Overwrite an existing output file instead of skipping.",
    )
    p.add_argument(
        "--qa-plot", dest="qa_plot", action="store_true",
        help="Also write a surface QA plot (PNG) next to the NetCDF.",
    )
    p.add_argument(
        "--no-mask-land", dest="mask_land", action="store_false",
        help=(
            "Skip the hFacC==0 land mask (applied by default; see "
            "compute_tile_property)."
        ),
    )
    args = p.parse_args(argv)

    if args.timestamp is None and args.dates_config is None:
        p.error("supply --timestamp (one snapshot) or --dates-config (series)")

    # Enforce exactly one location convention here so the CLI gives a clean
    # argparse-style error rather than surfacing a ValueError from ``run``.
    have_ij = args.i is not None and args.j is not None
    have_lonlat = args.lon is not None and args.lat is not None
    if have_ij == have_lonlat:
        p.error(
            "supply exactly one location: either --i and --j, or --lon and "
            "--lat"
        )

    # The structured layout needs both halves; half of it is always a mistake,
    # and silently writing to CWD instead would scatter output unexpectedly.
    if (args.netcdf_base is None) != (args.run_id is None):
        p.error("--netcdf-base and --run-id must be supplied together")
    return args


def main(argv=None) -> None:
    """CLI entry point: configure logging, parse args, dispatch to ``tile_utils.run``.

    Parameters
    ----------
    argv : list of str or None
        Argument list (default: ``sys.argv[1:]``).

    Returns
    -------
    None
        Side effect: writes a NetCDF (and, with ``--qa-plot``, a PNG) to disk.
    """
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(message)s",
        stream=sys.stdout,
    )
    args = _parse_args(argv)
    if args.dates_config is not None:
        timestamps = _read_dates_config(args.dates_config)
        logging.info(
            f"Series run: {len(timestamps)} timestamps from {args.dates_config}"
        )
        tile_utils.run_series(
            timestamps,
            i_rect=args.i,
            j_rect=args.j,
            lon=args.lon,
            lat=args.lat,
            property=args.property,
            pipeline=args.pipeline,
            config_path=args.s3_config,
            output_dir=args.output,
            clobber=args.clobber,
            gen_qa_plot=args.qa_plot,
            mask_land=args.mask_land,
            netcdf_base=args.netcdf_base,
            run_id=args.run_id,
            continue_on_error=args.continue_on_error,
        )
        return

    tile_utils.run(
        i_rect=args.i,
        j_rect=args.j,
        lon=args.lon,
        lat=args.lat,
        timestamp=args.timestamp,
        property=args.property,
        output=args.output,
        config_path=args.s3_config,
        clobber=args.clobber,
        gen_qa_plot=args.qa_plot,
        mask_land=args.mask_land,
        netcdf_base=args.netcdf_base,
        run_id=args.run_id,
        pipeline=args.pipeline,
    )


if __name__ == "__main__":
    main()

# conda run -n ocean14 python -m pytest tests/test_generate_tile.py --deselect tests/test_generate_tile.py::test_rect_ij_to_tile_against_grid_zarr -v 2>&1 | tail -45
# generate-tile --i 9800 --j 9000 --timestamp '2012-11-09 12:00:00'
