"""
zarr_to_netcdf.py
-----------------
Reads global LLC4320 snapshots from the S3 Zarr store written by
generate_fronts_global.py and writes one NetCDF file per timestep to a
local directory on the HPC machine.

Why one file per timestep?
--------------------------
A single timestep at full resolution (12960 × 17280) with ~8 channels is
roughly 7 GB as float32. Keeping snapshots as individual files avoids
impractical single-file sizes and lets you load, share, or delete individual
timesteps without touching the rest.

Output file naming
------------------
  <output_dir>/<run_id>_it<iteration:07d>.nc

  e.g.  global_test00_it0184320.nc

Each file is a self-describing xr.Dataset with:
  - One data variable per channel (dims: y, x), e.g. Eta, Salt, Theta, ...
  - Global attributes: llc4320_iteration, run_id, channel_names
  - Spatial dims named 'y' (12960) and 'x' (17280) matching the rectangular
    lat/lon grid produced by faces_dataset_to_latlon.

Grid note
---------
Geographic coordinates (lat/lon, grid spacings, etc.) are NOT included in
these per-timestep files. Load the companion grid file generated by
generate-global-grid for that information.

Usage
-----
  zarr-to-netcdf \\
      --s3-endpoint https://s3-west.nrp-nautilus.io \\
      --bucket dbof \\
      --folder native_grid_dbof_training_data \\
      --run-id global_test00 \\
      --output-dir /scratch/llc4320_netcdf/

  Optional: convert only specific timesteps by LLC4320 iteration number:
      --iterations 184320 328320

  Or by date (DDMMYYYY-HH:MM:SS), converted to iteration numbers automatically:
      --dates 01012012-00:00:00 01042012-00:00:00

  Or convert only timestep indices 0 and 2 (0-based):
      --indices 0 2
"""

import argparse
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import xarray as xr

from dbof.io.filesystems import create_s3_filesystems
import dbof.dataset_creation.zarr_dataset_global as zarr_dataset_global

# LLC4320 calendar constants (same as generate_fronts_global.py)
LLC4320_START_DATE    = datetime(2011, 9, 13, 0, 0, 0, tzinfo=timezone.utc)
LLC4320_TIMESTEP_SECS = 25
DATE_FMT              = '%d%m%Y-%H:%M:%S'


def _date_to_iteration(date_str: str) -> int:
    """Convert 'DDMMYYYY-HH:MM:SS' → LLC4320 iteration number."""
    dt = datetime.strptime(date_str, DATE_FMT).replace(tzinfo=timezone.utc)
    delta = dt - LLC4320_START_DATE
    if delta.total_seconds() < 0:
        raise ValueError(
            f"Date '{date_str}' is before LLC4320 start "
            f"({LLC4320_START_DATE.date()}). "
            "Expected format: DDMMYYYY-HH:MM:SS, e.g. '01012012-00:00:00'."
        )
    return round(delta.total_seconds() / LLC4320_TIMESTEP_SECS)


def _iteration_to_datetime(iteration: int) -> datetime:
    """Convert LLC4320 iteration number → UTC datetime."""
    return LLC4320_START_DATE + __import__('datetime').timedelta(
        seconds=int(iteration) * LLC4320_TIMESTEP_SECS
    )


def zarr_to_netcdf(
    s3_endpoint: str,
    bucket: str,
    folder: str,
    run_id: str,
    dataset_name: str,
    output_dir: str,
    target_indices: list = None,   # list of t-axis indices, or None for all
) -> None:
    """
    Convert a GlobalZarrDataset on S3 to per-timestep NetCDF files locally.

    Parameters
    ----------
    s3_endpoint : str
        NRP S3 endpoint, e.g. 'https://s3-west.nrp-nautilus.io'.
    bucket : str
        S3 bucket name, e.g. 'dbof'.
    folder : str
        S3 folder path, e.g. 'native_grid_dbof_training_data'.
    run_id : str
        The run_id used when writing the Zarr store.
    dataset_name : str
        The dataset_name used when writing the Zarr store
        (e.g. 'dataset_creation.zarr').
    output_dir : str
        Local directory where NetCDF files will be written.
        Created if it does not exist.
    target_indices : list of int, optional
        Which t-axis indices to convert. If None, all timesteps are converted.
    """
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s | %(levelname)s | %(message)s",
        handlers=[logging.StreamHandler(sys.stdout)],
        force=True,
    )

    out_path = Path(output_dir)
    out_path.mkdir(parents=True, exist_ok=True)

    # ------------------------------------------------------------------
    # 1. Open Zarr reader
    # ------------------------------------------------------------------
    logging.info(f"Opening Zarr store: s3://{bucket}/{folder}/{run_id}/{dataset_name}")
    _, fs_synch = create_s3_filesystems(s3_endpoint)
    reader = zarr_dataset_global.GlobalZarrDatasetReader(
        bucket=bucket,
        folder=folder,
        run_id=run_id,
        dataset_name=dataset_name,
        fs=fs_synch,
    )

    n_total = len(reader)
    channel_names = reader.channel_names
    logging.info(
        f"Store contains {n_total} timestep(s), {len(channel_names)} channel(s): "
        f"{channel_names}"
    )

    if target_indices is None:
        target_indices = list(range(n_total))
    else:
        bad = [i for i in target_indices if i < 0 or i >= n_total]
        if bad:
            raise ValueError(
                f"Requested t-indices {bad} are out of range [0, {n_total - 1}]."
            )

    # ------------------------------------------------------------------
    # 2. Convert each selected timestep
    # ------------------------------------------------------------------
    for t in target_indices:
        iteration = int(reader.time[t])
        snapshot  = reader.get_snapshot(t)   # (C, H, W), numpy float32

        logging.info(
            f"[{t + 1}/{len(target_indices)}] "
            f"t={t}, iteration={iteration} "
            f"({_iteration_to_datetime(iteration).strftime('%Y-%m-%d %H:%M UTC')})"
        )

        # Build xarray Dataset — one variable per channel, dims (y, x)
        n_y, n_x = snapshot.shape[1], snapshot.shape[2]
        y_coord = np.arange(n_y, dtype=np.int32)
        x_coord = np.arange(n_x, dtype=np.int32)

        data_vars = {
            ch: xr.DataArray(
                snapshot[c].astype(np.float32),
                dims=['y', 'x'],
                coords={'y': y_coord, 'x': x_coord},
            )
            for c, ch in enumerate(channel_names)
        }

        ds = xr.Dataset(
            data_vars,
            attrs={
                'llc4320_iteration': iteration,
                'model_time_utc':    _iteration_to_datetime(iteration).isoformat(),
                'run_id':            run_id,
                'channel_names':     channel_names,
                'spatial_shape':     f'({n_y}, {n_x})',
                'description': (
                    'LLC4320 global snapshot in rectangular lat/lon format '
                    '(12960 × 17280). Produced by zarr_to_netcdf.py. '
                    'Load companion llc4320_grid.nc for XC/YC/Depth/etc.'
                ),
            },
        )

        nc_filename = out_path / f"{run_id}_it{iteration:07d}.nc"
        ds.to_netcdf(nc_filename)
        logging.info(f"  → written: {nc_filename}")

    logging.info(f"Done. {len(target_indices)} file(s) written to {out_path}")


def main():
    p = argparse.ArgumentParser(
        description=(
            "Convert S3 Zarr global LLC4320 dataset to per-timestep NetCDF files."
        )
    )

    # S3 source
    p.add_argument('--s3-endpoint', required=True,
                   help="NRP S3 endpoint, e.g. https://s3-west.nrp-nautilus.io")
    p.add_argument('--bucket',      required=True,
                   help="S3 bucket name, e.g. dbof")
    p.add_argument('--folder',      required=True,
                   help="S3 folder, e.g. native_grid_dbof_training_data")
    p.add_argument('--run-id',      required=True,
                   help="run_id used when writing the Zarr store")
    p.add_argument('--dataset-name', default='dataset_creation.zarr',
                   help="dataset_name used when writing (default: dataset_creation.zarr)")

    # Output
    p.add_argument('--output-dir', required=True,
                   help="Local directory to write NetCDF files into")

    # Timestep selection (mutually exclusive)
    sel = p.add_mutually_exclusive_group()
    sel.add_argument('--indices', nargs='+', type=int, metavar='T',
                     help="t-axis indices to convert (0-based). Default: all.")
    sel.add_argument('--iterations', nargs='+', type=int, metavar='IT',
                     help="LLC4320 iteration numbers to convert.")
    sel.add_argument('--dates', nargs='+', metavar='DDMMYYYY-HH:MM:SS',
                     help="Model dates to convert, e.g. 01012012-00:00:00")

    args = p.parse_args()

    # Resolve timestep selection to t-indices after opening the reader
    # (iteration → index lookup happens inside zarr_to_netcdf if needed)
    target_indices = None

    if args.iterations is not None or args.dates is not None:
        # We need a reader to map iteration→index; open it briefly here
        _, fs_synch = create_s3_filesystems(args.s3_endpoint)
        reader = zarr_dataset_global.GlobalZarrDatasetReader(
            bucket=args.bucket,
            folder=args.folder,
            run_id=args.run_id,
            dataset_name=args.dataset_name,
            fs=fs_synch,
        )
        if args.dates is not None:
            iters = [_date_to_iteration(d) for d in args.dates]
        else:
            iters = args.iterations
        target_indices = [reader.iteration_to_index(it) for it in iters]
    elif args.indices is not None:
        target_indices = args.indices

    zarr_to_netcdf(
        s3_endpoint=args.s3_endpoint,
        bucket=args.bucket,
        folder=args.folder,
        run_id=args.run_id,
        dataset_name=args.dataset_name,
        output_dir=args.output_dir,
        target_indices=target_indices,
    )


if __name__ == '__main__':
    main()
