# This dictionary is used to define the face connections for the LLC4320 grid.
# It is used to create the xgcm Grid object.

import numpy as np
import xarray as xr
import xgcm

#: COMODO coordinate attributes for the LLC4320 horizontal dimensions.
#: See docs/Grid.md.

COMODO_COORD_META = {
    'j':   {'axis': 'Y'},
    'j_g': {'axis': 'Y', 'c_grid_axis_shift': -0.5},
    'i':   {'axis': 'X'},
    'i_g': {'axis': 'X', 'c_grid_axis_shift': -0.5},
}

face_connections = {'face':  {
        0: {'X': ((12, 'Y', False), (3, 'X', False)),
            'Y': (None, (1, 'Y', False))},
        1: {'X': ((11, 'Y', False), (4, 'X', False)),
            'Y': ((0, 'Y', False), (2, 'Y', False))},
        2: {'X': ((10, 'Y', False), (5, 'X', False)),
            'Y': ((1, 'Y', False), (6, 'X', False))},
        3: {'X': ((0, 'X', False), (9, 'Y', False)),
            'Y': (None, (4, 'Y', False))},
        4: {'X': ((1, 'X', False), (8, 'Y', False)),
            'Y': ((3, 'Y', False), (5, 'Y', False))},
        5: {'X': ((2, 'X', False), (7, 'Y', False)),
            'Y': ((4, 'Y', False), (6, 'Y', False))},
        6: {'X': ((2, 'Y', False), (7, 'X', False)),
            'Y': ((5, 'Y', False), (10, 'X', False))},
        7: {'X': ((6, 'X', False), (8, 'X', False)),
            'Y': ((5, 'X', False), (10, 'Y', False))},
        8: {'X': ((7, 'X', False), (9, 'X', False)),
            'Y': ((4, 'X', False), (11, 'Y', False))},
        9: {'X': ((8, 'X', False), None),
            'Y': ((3, 'X', False), (12, 'Y', False))},
        10: {'X': ((6, 'Y', False), (11, 'X', False)),
                'Y': ((7, 'Y', False), (2, 'X', False))},
        11: {'X': ((10, 'X', False), (12, 'X', False)),
                'Y': ((8, 'Y', False), (1, 'X', False))},
        12: {'X': ((11, 'X', False), None),
                'Y': ((9, 'Y', False), (0, 'X', False))}
}}

def set_xgcm_grid(ds_grid, use_connections:bool=True):
    """ Set the xgcm Grid object for the LLC4320 grid 
    Args:
        ds_grid: xarray.Dataset
            The dataset containing the LLC4320 grid data 

    Returns:
        xgcm.Grid
            The xgcm Grid object for the LLC4320 grid
    """
    # Do it
    if use_connections:
        grid = xgcm.Grid(ds_grid, periodic=False, face_connections=face_connections)
    else:
        grid = xgcm.Grid(ds_grid, periodic=False)
    return grid


# ---------------------------------------------------------------------------
# Staggered vector pairs across face connections
# ---------------------------------------------------------------------------

def _mean(lo, hi):
    return 0.5 * (lo + hi)


def _delta(lo, hi):
    return hi - lo


def has_face_connections(grid):
    """Whether *grid* was built with face connections."""
    # attribute renamed between xgcm 0.8 and 0.9
    return any(getattr(grid, a, None) is not None
               for a in ('_face_connections', '_connections'))


def invalid_seam_edges():
    """Face edges whose halo cannot be copied from the neighbour.

    Rotated connections (neighbour reached along the other axis) and open
    domain edges (``None``).

    Returns
    -------
    set[tuple[int, str, str]]
        ``(face, axis, side)``, side in ``{'lower', 'upper'}``.

    Generated by LH and Claude
    """
    edges = set()
    for face, axes in face_connections['face'].items():
        for axis, (lower, upper) in axes.items():
            for side, link in (('lower', lower), ('upper', upper)):
                if link is None or link[1] != axis:
                    edges.add((face, axis, side))
    return edges


def face_seam_mask(da, width=1):
    """NaN the *width* cells adjacent to each invalid seam edge.

    Parameters
    ----------
    da : xarray.DataArray
        Field with a ``face`` dim plus one X and one Y horizontal dim.
    width : int, default 1
        Cells to invalidate at each edge.

    Returns
    -------
    xarray.DataArray

    Generated by LH and Claude
    """
    xdim = next(d for d in ('i_g', 'i') if d in da.dims)
    ydim = next(d for d in ('j_g', 'j') if d in da.dims)
    shape = (da.sizes['face'], da.sizes[ydim], da.sizes[xdim])
    bad = np.zeros(shape, dtype=bool)
    pos = {'Y': 1, 'X': 2}
    for face, axis, side in invalid_seam_edges():
        sl = [slice(None)] * 3
        sl[0] = face
        sl[pos[axis]] = (slice(0, width) if side == 'lower'
                         else slice(-width, None))
        bad[tuple(sl)] = True
    return da.where(~xr.DataArray(bad, dims=('face', ydim, xdim)))


def _pair_stencil(component, partner, grid, axis, partner_axis, combine):
    """Two-point stencil to cell centres, halo taken from *partner*
    where a face connection rotates the neighbour.

    Parameters
    ----------
    component : xarray.DataArray
        Part being moved, staggered on *axis*.
    partner : xarray.DataArray
        Its orthogonal part, staggered on *partner_axis*.
    grid : xgcm.Grid
    axis, partner_axis : str
        ``'X'`` / ``'Y'``.
    combine : callable
        ``(lower, upper) -> DataArray``.

    Returns
    -------
    xarray.DataArray
        On tracer points, lazy.

    Generated by LH and Claude
    """
    from xgcm.padding import pad

    coords = dict(grid.axes[axis].coords)
    centre = coords['center']
    position, stag = next((p, d) for p, d in coords.items()
                          if p != 'center' and d in component.dims)
    # Pad the side the stencil reads: 'left' the upper halo, 'right' the lower.
    width = (0, 1) if position == 'left' else (1, 0)
    padded = pad({axis: component}, grid, {axis: width}, {axis: 'fill'},
                 {axis: 0.0}, other_component={partner_axis: partner})
    lo = padded.isel({stag: slice(None, -1)}).drop_vars(stag, errors='ignore')
    hi = padded.isel({stag: slice(1, None)}).drop_vars(stag, errors='ignore')
    if component.chunks is not None:
        # slicing the padded array leaves a ragged block
        target = {stag: component.chunksizes[stag]}
        lo, hi = lo.chunk(target), hi.chunk(target)
    out = combine(lo, hi).rename({stag: centre})
    if centre in grid._ds.coords:
        out = out.assign_coords({centre: grid._ds[centre]})
    return out


def interp_pair_to_center(x_component, y_component, grid):
    """Interpolate an (X, Y) staggered pair to cell centres.

    The two parts must cross a face seam together: where a connection
    rotates the neighbour, one part's halo comes from the other.

    Parameters
    ----------
    x_component, y_component : xarray.DataArray
        Model-x part on ``i_g``, model-y part on ``j_g``.
    grid : xgcm.Grid

    Returns
    -------
    (xarray.DataArray, xarray.DataArray)
        Both on tracer points, lazy.

    Generated by LH and Claude
    """
    if not has_face_connections(grid):
        return (grid.interp(x_component, 'X', boundary='fill'),
                grid.interp(y_component, 'Y', boundary='fill'))
    return (_pair_stencil(x_component, y_component, grid, 'X', 'Y', _mean),
            _pair_stencil(y_component, x_component, grid, 'Y', 'X', _mean))


def diff_pair_along_own_axis(x_component, y_component, grid):
    """Difference an (X, Y) staggered pair, each along its own axis.

    Parameters
    ----------
    x_component, y_component : xarray.DataArray
        Model-x part on ``i_g``, model-y part on ``j_g``.
    grid : xgcm.Grid

    Returns
    -------
    (xarray.DataArray, xarray.DataArray)
        Both at cell centres, lazy.

    Generated by LH and Claude
    """
    if not has_face_connections(grid):
        return (grid.diff(x_component, 'X', boundary='fill'),
                grid.diff(y_component, 'Y', boundary='fill'))
    return (_pair_stencil(x_component, y_component, grid, 'X', 'Y', _delta),
            _pair_stencil(y_component, x_component, grid, 'Y', 'X', _delta))
