""" Data model for DBOF outputs """

import numpy as np

import pandas

# Descriptions of global outputs generated by the preprocessing code
fields_dmodel = {
    "gradb2": {
        "desc": "gradb2 (gradient of buoyancy, squared)",
        "units": "(s^-4)",
    },
    "log_gradb": {
        "desc": "log_gradb (log10 of gradient of buoyancy, squared)",
        "units": "log10(s^-4)",
    },
    "R_ib": {
        "desc": ("R_ib (balanced Richardson number, "
                 "N^2 f^2 / |grad_h b|^2)"),
        "units": "dimensionless",
    },
    "Wstar": {
        "desc": ("Wstar (modified Okubo-Weiss parameter, Bachman 2021; "
                 "4 sgn(l_2) sqrt(l_1^2 + l_2^2) with l_2 = W/4 and "
                 "l_1 = l_2/2 + sqrt(l_2^2 + |Q|^2/f^2)/2)"),
        "units": "(s^-2)",
    },
}