""" Data model for DBOF outputs """

import numpy as np

import pandas

# Descriptions of global outputs generated by the preprocessing code
fields_dmodel = {
    "gradb2": {
        "desc": "gradb2 (gradient of buoyancy, squared)",
        "units": "(s^4)",
    },
    "log_gradb": {
        "desc": "log_gradb (log10 of gradient of buoyancy, squared)",
        "units": "log10(s^4)",
    },
}