""" Data model for DBOF outputs """

import numpy as np

import pandas

# Descriptions of global outputs generated by the preprocessing code
fields_dmodel = {
    "gradb2": {
        "desc": "gradb2 (gradient of buoyancy, squared)",
        "units": "(km/s/m)^2",
    },
    "log_gradb": {
        "desc": "log_gradb (log of gradient of buoyancy, squared)",
        "units": "log10((km/s/m)^2)",
    },
}