"""
field_registry.py
-----------------
Registry of every field that can be extracted as an LLC4320 tile.

One :class:`TileProperty` per OUTPUT FIELD, named exactly like the
subset channels in ``global_dataset_creation.subset_definitions``
(``N2``, ``mixed_layer_depth``, ``relative_vorticity``, ...), plus
legacy aliases (``temperature`` -> ``Theta``, ``salinity`` ->
``Salt``; ``density`` is itself a channel name).

Design rules and rationale: docs/Tiles.md (§How the registry works,
§Edge margin, §Vector rotation).  Per-channel definitions, units and
equations: docs/Fields.md.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Callable

import numpy as np
import xarray as xr

import dbof.preprocessing.calculate_fields as CF
import dbof.preprocessing.calculate_fields_at_depth as CFAD
from dbof.preprocessing.vertical_helpers import _interp_w_to_tracer_levels


@dataclass(frozen=True)
class TileProperty:
    """Specification for a single field extractable as a tile.

    Attributes
    ----------
    name : str
        Public name at the CLI — the subset channel name.
    vars_needed : tuple of str
        S3 store variables required.
    out_name : str
        Variable name written to the output NetCDF.
    units : str
        ``units`` attribute for the output variable.
    long_name : str
        ``long_name`` attribute for the output variable.
    filename_prefix : str
        Prefix used in the default output filename.
    compute : Callable
        ``(ds_merge, grid) -> xr.DataArray`` (lazy), where ``ds_merge``
        is the merged tile dataset and ``grid`` the local xgcm grid.
    edge_margin : int
        Invalid-rim width (cells) at the tile boundary; NaN'd by
        ``compute_tile_property`` and recorded as an output attr.
    """
    name:            str
    vars_needed:     tuple[str, ...]
    out_name:        str
    units:           str
    long_name:       str
    filename_prefix: str
    compute:         Callable[[xr.Dataset, object], xr.DataArray]
    edge_margin:     int = 0


# ---------------------------------------------------------------------------
# Small adapter factories (plumbing only — no physics)
# ---------------------------------------------------------------------------

def _passthrough(var):
    """Adapter: return a stored (tracer-point, scalar) variable as-is.

    Valid only for scalars already on tracer points (``Theta``,
    ``Eta``, ``oceQnet``, ...).  Never use it for a vector component:
    ``U``/``V``/``oceTAUX``/``oceTAUY`` are on staggered C-grid faces
    and follow the MODEL x/y axes, so they need the canonical CS/SN
    rotation instead (docs/Tiles.md §Vector rotation).

    Inputs: var (str) — variable name in the tile dataset.
    Outputs: callable ``(ds_merge, grid) -> xr.DataArray``.
    Generated by LH and Claude
    """
    def _compute(ds_merge, grid):
        return ds_merge[var]
    return _compute


def _no_grid(fn):
    """Adapter for canonical functions with signature ``fn(ds_merge)``.

    Inputs: fn (callable).
    Outputs: callable ``(ds_merge, grid) -> xr.DataArray``.
    Generated by LH and Claude
    """
    def _compute(ds_merge, grid):
        return fn(ds_merge)
    return _compute


def _pick(fn, index):
    """Adapter extracting one component from a multi-output function.

    Inputs: fn (callable ``(ds_merge, grid) -> tuple | dict``); index
    (int or str) — position or key of the wanted component.
    Outputs: callable ``(ds_merge, grid) -> xr.DataArray``.
    Generated by LH and Claude
    """
    def _compute(ds_merge, grid):
        return fn(ds_merge, grid)[index]
    return _compute


def _w_centred(ds_merge, grid):
    """W interpolated from k_l interfaces to tracer levels.

    Inputs: ds_merge (tile dataset with ``W``); grid (unused).
    Outputs: xr.DataArray, W on tracer levels [m s-1].
    Generated by LH and Claude
    """
    return _interp_w_to_tracer_levels(ds_merge)


def _frontogenesis_ageo(ds_merge, grid):
    """Ageostrophic frontogenesis F(u,v) − F(ug,vg).

    Mirrors the dispatcher-inline definition in
    ``surface_subsets.compute_frontogenesis`` (no canonical CF
    function exists for the residual).
    Inputs: ds_merge (tile dataset); grid (local xgcm grid).
    Outputs: xr.DataArray [s-5], lazy.
    Generated by LH and Claude
    """
    tendency = CF.frontogenesis_tendency(ds_merge, grid)
    geo = CF.frontogenesis_geo(ds_merge, grid)
    return tendency - geo


# ---------------------------------------------------------------------------
# The registry — one entry per output field (channel names)
# ---------------------------------------------------------------------------

_TS = ("Theta", "Salt")
_UV = ("U", "V")
_UVTS = ("U", "V", "Theta", "Salt")
_UVWTS = ("U", "V", "W", "Theta", "Salt")
_TAU = ("oceTAUX", "oceTAUY")

TILE_PROPERTIES: dict[str, TileProperty] = {
    # --- native fields -----------------------------------------------------
    "Theta": TileProperty(
        "Theta", ("Theta",), "Theta", "degC",
        "potential temperature", "theta", _passthrough("Theta")),
    "Salt": TileProperty(
        "Salt", ("Salt",), "Salt", "psu",
        "salinity", "salt", _passthrough("Salt")),
    "Eta": TileProperty(
        "Eta", ("Eta",), "Eta", "m",
        "sea-surface height anomaly", "eta", _passthrough("Eta")),
    "U": TileProperty(
        "U", _UV, "U", "m s-1",
        "eastward velocity (tracer points, CS/SN rotated)", "u",
        _pick(CF.geographic_velocity, 0), edge_margin=1),
    "V": TileProperty(
        "V", _UV, "V", "m s-1",
        "northward velocity (tracer points, CS/SN rotated)", "v",
        _pick(CF.geographic_velocity, 1), edge_margin=1),
    "W": TileProperty(
        "W", ("W", "Theta"), "W", "m s-1",
        "vertical velocity (centred to tracer levels)", "w",
        _w_centred),
    # --- stratification ----------------------------------------------------
    "N2": TileProperty(
        "N2", _TS, "N2", "s-2",
        "buoyancy frequency squared", "n2",
        _no_grid(CFAD.buoyancy_frequency_squared)),
    "mixed_layer_depth": TileProperty(
        "mixed_layer_depth", _TS, "mixed_layer_depth", "m",
        "mixed layer depth (sigma0 threshold 0.03)", "mld",
        _no_grid(CFAD.mixed_layer_depth)),
    "ml_heat_content": TileProperty(
        "ml_heat_content", _TS, "ml_heat_content", "J m-2",
        "mixed layer heat content", "mlhc",
        _no_grid(CFAD.mixed_layer_heat_content)),
    # --- vertical shear ----------------------------------------------------
    "vertical_shear": TileProperty(
        "vertical_shear", _UVTS, "vertical_shear", "s-1",
        "vertical shear magnitude |dU/dz|", "shear",
        CFAD.vertical_shear_magnitude, edge_margin=1),
    "Ri": TileProperty(
        "Ri", _UVTS, "Ri", "1",
        "Richardson number N2/S2", "ri",
        CFAD.richardson_number, edge_margin=1),
    # --- mixing parameters -------------------------------------------------
    "Fr": TileProperty(
        "Fr", _UVTS, "Fr", "1",
        "Froude number", "fr",
        CFAD.froude_number, edge_margin=1),
    "Ro": TileProperty(
        "Ro", _UV, "Ro", "1",
        "Rossby number zeta/f", "ro",
        CF.rossby_number, edge_margin=3),
    "Bu": TileProperty(
        "Bu", _UVTS, "Bu", "1",
        "Burger number (Ro/Fr)^2", "bu",
        CFAD.burger_number, edge_margin=3),
    "R_ib": TileProperty(
        "R_ib", _TS, "R_ib", "1",
        "balanced Richardson number", "rib",
        CFAD.balanced_richardson_number, edge_margin=3),
    # --- Ertel PV ----------------------------------------------------------
    "ertel_pv": TileProperty(
        "ertel_pv", _UVWTS, "ertel_pv", "s-3",
        "Ertel potential vorticity q", "epv",
        _pick(CFAD.ertel_pv_terms, "ertel_pv"), edge_margin=3),
    "ertel_pv_vertical": TileProperty(
        "ertel_pv_vertical", _UVWTS, "ertel_pv_vertical", "s-3",
        "Ertel PV vertical component (zeta+f) b_z", "epvv",
        _pick(CFAD.ertel_pv_terms, "ertel_pv_vertical"), edge_margin=3),
    "ertel_pv_tilt": TileProperty(
        "ertel_pv_tilt", _UVWTS, "ertel_pv_tilt", "s-3",
        "Ertel PV tilting component", "epvt",
        _pick(CFAD.ertel_pv_terms, "ertel_pv_tilt"), edge_margin=3),
    # --- buoyancy fluxes ---------------------------------------------------
    "uB": TileProperty(
        "uB", _UVWTS, "uB", "m2 s-3",
        "zonal advective buoyancy flux u*b", "ub",
        _pick(CFAD.advective_buoyancy_fluxes, 0), edge_margin=1),
    "vB": TileProperty(
        "vB", _UVWTS, "vB", "m2 s-3",
        "meridional advective buoyancy flux v*b", "vb",
        _pick(CFAD.advective_buoyancy_fluxes, 1), edge_margin=1),
    "wB": TileProperty(
        "wB", _UVWTS, "wB", "m2 s-3",
        "vertical advective buoyancy flux w*b", "wb",
        _pick(CFAD.advective_buoyancy_fluxes, 2), edge_margin=1),
    # --- energetics ----------------------------------------------------------
    "KE": TileProperty(
        "KE", _TS, "KE", "m2 s-2",
        "mixed-layer eddy KE scale 0.5(MLD |grad b|/f)^2", "ke",
        CFAD.kinetic_energy, edge_margin=3),
    # --- frontal structure ---------------------------------------------------
    "density": TileProperty(
        "density", _TS, "sigma0", "kg m-3",
        "potential density anomaly referenced to surface (JMD95, p=0)",
        "density", _no_grid(CF.potential_density_anomaly)),
    "buoyancy": TileProperty(
        "buoyancy", _TS, "buoyancy", "m s-2",
        "buoyancy b = g sigma0 / rho0", "buoyancy",
        _no_grid(CF.buoyancy_of_field)),
    "gradb2": TileProperty(
        "gradb2", _TS, "gradb2", "s-4",
        "squared buoyancy gradient magnitude", "gradb2",
        CF.grad_b2, edge_margin=3),
    "gradtheta2": TileProperty(
        "gradtheta2", ("Theta",), "gradtheta2", "degC2 m-2",
        "squared temperature gradient magnitude", "gradtheta2",
        CF.grad_theta2, edge_margin=3),
    "gradsalt2": TileProperty(
        "gradsalt2", ("Salt",), "gradsalt2", "psu2 m-2",
        "squared salinity gradient magnitude", "gradsalt2",
        CF.grad_salt2, edge_margin=3),
    "gradrho2": TileProperty(
        "gradrho2", _TS, "gradrho2", "kg2 m-8",
        "squared density gradient magnitude", "gradrho2",
        CF.grad_rho2, edge_margin=3),
    "gradeta2": TileProperty(
        "gradeta2", ("Eta",), "gradeta2", "m2 m-2",
        "squared SSH gradient magnitude", "gradeta2",
        CF.grad_eta2, edge_margin=3),
    "turner_angle": TileProperty(
        "turner_angle", _TS, "turner_angle", "degrees",
        "horizontal Turner angle", "turner",
        CF.turner_angle, edge_margin=3),
    # --- kinematic -----------------------------------------------------------
    "relative_vorticity": TileProperty(
        "relative_vorticity", _UV, "relative_vorticity", "s-1",
        "relative vorticity zeta", "vorticity",
        CF.relative_vorticity, edge_margin=3),
    "strain_n": TileProperty(
        "strain_n", _UV, "strain_n", "s-1",
        "normal strain", "strainn",
        _pick(CF.strain, 1), edge_margin=3),
    "strain_s": TileProperty(
        "strain_s", _UV, "strain_s", "s-1",
        "shear strain", "strains",
        _pick(CF.strain, 2), edge_margin=3),
    "strain_mag": TileProperty(
        "strain_mag", _UV, "strain_mag", "s-1",
        "strain magnitude", "strainmag",
        _pick(CF.strain, 0), edge_margin=3),
    "divergence": TileProperty(
        "divergence", _UV, "divergence", "s-1",
        "horizontal divergence", "divergence",
        CF.divergence, edge_margin=3),
    "coriolis_f": TileProperty(
        "coriolis_f", (), "coriolis_f", "s-1",
        "Coriolis parameter f = 2 Omega sin(lat)", "coriolisf",
        CF.coriolis_parameter),
    "rossby_number": TileProperty(
        "rossby_number", _UV, "rossby_number", "1",
        "Rossby number zeta/f", "rossby",
        CF.rossby_number, edge_margin=3),
    "okubo_weiss": TileProperty(
        "okubo_weiss", _UV, "okubo_weiss", "s-2",
        "Okubo-Weiss parameter", "okuboweiss",
        CF.okubo_weiss_parameter, edge_margin=3),
    # --- frontogenesis ----------------------------------------------------
    "frontogenesis_tendency": TileProperty(
        "frontogenesis_tendency", _UVTS, "frontogenesis_tendency", "s-5",
        "frontogenesis function F(u,v) = Q.grad(b)", "ftend",
        CF.frontogenesis_tendency, edge_margin=3),
    "frontogenesis_geo": TileProperty(
        "frontogenesis_geo", ("Theta", "Salt", "Eta"),
        "frontogenesis_geo", "s-5",
        "geostrophic frontogenesis F(ug,vg)", "fgeo",
        CF.frontogenesis_geo, edge_margin=3),
    "frontogenesis_ageo": TileProperty(
        "frontogenesis_ageo", ("U", "V", "Theta", "Salt", "Eta"),
        "frontogenesis_ageo", "s-5",
        "ageostrophic frontogenesis F(u,v) - F(ug,vg)", "fageo",
        _frontogenesis_ageo, edge_margin=3),
    "ug": TileProperty(
        "ug", ("Eta",), "ug", "m s-1",
        "geostrophic zonal velocity -(g/f) dEta/dy", "ug",
        _pick(CF.geostrophic_velocity, 0), edge_margin=3),
    "vg": TileProperty(
        "vg", ("Eta",), "vg", "m s-1",
        "geostrophic meridional velocity (g/f) dEta/dx", "vg",
        _pick(CF.geostrophic_velocity, 1), edge_margin=3),
    "Wstar": TileProperty(
        "Wstar", _UVTS, "Wstar", "s-2",
        "modified Okubo-Weiss W* (Bachman 2021)", "wstar",
        CF.modified_okubo_weiss, edge_margin=3),
    # --- surface wind / ice (2D) ------------------------------------------
    "oceTAUX": TileProperty(
        "oceTAUX", _TAU, "oceTAUX", "N m-2",
        "eastward wind stress (tracer points, CS/SN rotated)", "taux",
        _pick(CF.geographic_wind_stress, 0), edge_margin=1),
    "oceTAUY": TileProperty(
        "oceTAUY", _TAU, "oceTAUY", "N m-2",
        "northward wind stress (tracer points, CS/SN rotated)", "tauy",
        _pick(CF.geographic_wind_stress, 1), edge_margin=1),
    "wind_stress_curl": TileProperty(
        "wind_stress_curl", _TAU, "wind_stress_curl", "N m-3",
        "wind stress curl", "curltau",
        CF.wind_stress_curl, edge_margin=3),
    "ekman_pumping": TileProperty(
        "ekman_pumping", _TAU, "ekman_pumping", "m s-1",
        "Ekman pumping curl(tau)/(rho0 f)", "ekmanw",
        CF.ekman_pumping, edge_margin=3),
    "u_ekman": TileProperty(
        "u_ekman", _TAU, "u_ekman", "m2 s-1",
        "zonal Ekman transport", "ekmanu",
        _pick(CF.ekman_transport, "u_ekman"), edge_margin=1),
    "v_ekman": TileProperty(
        "v_ekman", _TAU, "v_ekman", "m2 s-1",
        "meridional Ekman transport", "ekmanv",
        _pick(CF.ekman_transport, "v_ekman"), edge_margin=1),
    "oceQnet": TileProperty(
        "oceQnet", ("oceQnet",), "oceQnet", "W m-2",
        "net surface heat flux", "qnet", _passthrough("oceQnet")),
    "SIarea": TileProperty(
        "SIarea", ("SIarea",), "SIarea", "1",
        "sea-ice area fraction", "siarea", _passthrough("SIarea")),
}

#: Legacy CLI names (pre-generalization) -> channel names.
ALIASES: dict[str, str] = {
    "temperature": "Theta",
    "salinity": "Salt",
    # "density" is itself a channel name and needs no alias.
}


def resolve_property(name: str) -> TileProperty:
    """Look up a tile property by channel name or legacy alias.

    Inputs
    ------
    name : str
        Channel name (e.g. ``'N2'``) or legacy alias
        (``'temperature'``, ``'salinity'``).

    Outputs
    -------
    TileProperty
        The registry entry.

    Raises
    ------
    KeyError
        With the sorted list of valid names if ``name`` is unknown.

    Generated by LH and Claude
    """
    key = ALIASES.get(name, name)
    if key not in TILE_PROPERTIES:
        raise KeyError(
            f"Unknown property '{name}'.  Available: "
            f"{sorted(TILE_PROPERTIES) + sorted(ALIASES)}"
        )
    return TILE_PROPERTIES[key]
