"""
Depth-resolved derived diagnostics for LLC4320 data.

This module computes physical properties that require the full water column
(3D fields) and then reduces them to 2D outputs at specific depth definitions.

Design
------
Two orthogonal abstractions are combined:

1. **Field functions** — each computes a single 3D diagnostic from the merged
   dataset (e.g., buoyancy frequency squared, vertical shear magnitude).
   Signature: ``(ds_merge, grid=None, **intermediates) -> xr.DataArray``

2. **Depth-selection strategies** — each takes a 3D field and returns a 2D
   slice or reduction at a particular depth definition (see
   ``depth_strategies.py``).

All field functions are **fully lazy** — they build dask task graphs without
calling ``.compute()``.  A single ``dask.compute()`` at the end of each
``compute_*`` entry point (in ``depth_subsets.py``) materialises only the
final 2D outputs.

MITgcm / xmitgcm coordinate conventions
-----------------------------------------
Tracer fields (Theta, Salt, buoyancy, density) live on:
    ``('k', 'face', 'j', 'i')``  with vertical coordinate ``Z``

Zonal velocity (U) lives on:
    ``('k', 'face', 'j', 'i_g')``  with vertical coordinate ``Z``

Meridional velocity (V) lives on:
    ``('k', 'face', 'j_g', 'i')``  with vertical coordinate ``Z``

Vertical velocity (W) lives on:
    ``('k_l', 'face', 'j', 'i')``  with vertical coordinate ``Zl``

Vertical coordinates:
    Z   — depth of tracer cell centres (negative upward in MITgcm)
    Zl  — depth of lower cell interface (where W lives)
    Zu  — depth of upper cell interface
    Zp1 — depth at cell interfaces (nk+1 levels)
"""

import logging

import numpy as np
import xarray as xr

import dbof.utils.native_gradient as ng
from dbof.preprocessing.calculate_additional_fields import (
    coriolis_parameter,
    potential_density,
    buoyancy_of_field,
    VelocityJacobian,
    BuoyancyGradients,
)

from dbof.preprocessing.vertical_helpers import (
    _get_vertical_dim,
    _get_depth_coord,
    _get_vertical_spacing,
    _nearest_k_to_depth,
    _vertical_derivative,
    _interp_w_to_tracer_levels,
    _extract_at_mld,
    _masked_ml_mean,
)

from dbof.preprocessing.physical_constants import (
    RHO0_BOUSSINESQ,
    G,
    CP,
    OMEGA_EARTH,
    ALPHA,
    BETA,
    MLD_REFERENCE_DEPTH_M,
    MLD_INTEGRATION_DEPTH_M,
    SIGMA0_REFERENCE_DENSITY,
)


# ===========================================================================
#  DENSITY
# ===========================================================================

def _density_lazy(ds_merge):
    """Thin wrapper over :func:`calculate_additional_fields.potential_density`.

    Kept as an internal alias until Phase 3 of the field migration deletes
    it (see prompts/field_migration.md).  The output is surface-referenced
    POTENTIAL density (JMD95 at p = 0) — the historical "in-situ" wording
    was a misnomer.  The hard-coded tile rechunk this function used to
    perform now lives at the DEPTH pipeline entry points
    (``depth_subsets._ensure_depth_chunking``), keeping field functions
    chunking-agnostic.

    Generated by LH and Claude
    """
    return potential_density(ds_merge)


def potential_density_anomaly_3d(ds_merge, grid=None):
    """Potential density anomaly (σ₀) referenced to the surface.

    The single canonical σ₀ routine: it wraps :func:`_density_lazy` (JMD95 with
    ``p = 0`` at every level) and subtracts
    :data:`physical_constants.SIGMA0_REFERENCE_DENSITY`.  Any code that needs
    σ₀ -- the mixed-layer-depth criterion, the tile pipeline, future callers --
    should call this rather than re-implementing ``ρ − 1000``.

    Generated by JXP and Claude

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing at least ``Theta`` (deg C) and ``Salt`` (PSU)
        on tracer levels.  Works on any subset -- a full global snapshot or a
        single 720x720 tile -- as long as those two variables are present.
    grid : xgcm.Grid, optional
        Unused; accepted so the signature matches the other field functions in
        this module (``(ds_merge, grid=None, ...)``) and this function can be
        dropped into the same dispatch tables.

    Returns
    -------
    xr.DataArray
        σ₀ [kg m⁻³] on the same tracer-level dims as the inputs
        (``k``, ``face``, ``j``, ``i``), dask-backed if the inputs were, with
        ``name="sigma0"`` and standard ``units``/``long_name`` attrs.
    """
    sigma0 = _density_lazy(ds_merge) - SIGMA0_REFERENCE_DENSITY
    sigma0.name = "sigma0"
    sigma0.attrs["units"] = "kg m-3"
    sigma0.attrs["long_name"] = (
        "potential density anomaly referenced to surface (JMD95, p=0)"
    )
    return sigma0


# ===========================================================================
#  GROUP 1: STRATIFICATION & HEAT
# ===========================================================================

def mixed_layer_depth(ds_merge, density_threshold=0.03,
                      ref_depth_m=MLD_REFERENCE_DEPTH_M):
    """
    Mixed-layer depth following Bodner et al.:

        σ₀ = ρ(S, Θ, p=0) − 1000
        Δσ = σ₀ − σ₀(k_ref)             # k_ref = nearest level to ref_depth_m
        MLD = deepest Z where Δσ ≤ threshold

    The reference level is determined by finding the nearest model k-index
    to ``ref_depth_m`` (default 10 m ≈ k=6 on the LLC4320 grid), rather
    than hard-coding a k-index.

    Uses pure xarray operations so the computation stays fully lazy
    when inputs are dask-backed.

    Returns a 2D field (positive metres, no depth dispatch needed).

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``Theta``, ``Salt``, and vertical coordinate
        ``Z``.
    density_threshold : float, optional
        Potential-density anomaly threshold [kg m⁻³] defining the base of the
        mixed layer (default 0.03).
    ref_depth_m : float, optional
        Reference depth [m] used to locate the near-surface reference level
        (default ``MLD_REFERENCE_DEPTH_M``, typically 10 m).

    Returns
    -------
    xr.DataArray
        2D mixed-layer depth [m], positive metres below the surface,
        with ``name="MLD"``.
    """
    # Reuse the single canonical σ₀ routine (ρ(p=0) − 1000) rather than
    # re-deriving the anomaly here -- keeps one function per property.
    sigma0 = potential_density_anomaly_3d(ds_merge)
    zdim = _get_vertical_dim(sigma0)

    z = _get_depth_coord(ds_merge, zdim=zdim)
    z_vals = z.values.astype(np.float64)
    ref_k = _nearest_k_to_depth(z_vals, ref_depth_m)

    sigma0_ref = sigma0.isel({zdim: ref_k})
    delta_sigma = sigma0 - sigma0_ref

    z_masked = z.where(delta_sigma <= density_threshold)
    mld = z_masked.max(dim=zdim, skipna=True)

    mld.name = "MLD"
    mld.attrs["long_name"] = "Mixed layer depth"
    mld.attrs["units"] = "m"
    return mld


def buoyancy_frequency_squared_3d(ds_merge):
    """
    Full 3D profile of N² = (g/ρ₀) dρ/dz.

    With the positive-downward z convention used throughout this module,
    density increases with depth in a stably stratified ocean, so
    dρ/dz > 0 and N² > 0 without a leading negative sign.

    Computed on tracer levels (dim='k', coord='Z').

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``Theta``, ``Salt``, and vertical spacing
        variables.

    Returns
    -------
    xr.DataArray
        3D buoyancy frequency squared N² [s⁻²] on tracer levels
        (dims ``k``, ``face``, ``j``, ``i``), with ``name="N2"``.
    """
    rho = _density_lazy(ds_merge)
    drho_dz = _vertical_derivative(rho, ds_merge)

    n2 = (G / RHO0_BOUSSINESQ) * drho_dz
    n2.name = "N2"
    n2.attrs["long_name"] = "Buoyancy frequency squared"
    n2.attrs["units"] = "s^-2"
    return n2


def mixed_layer_depth_DI(ds_merge,
                         integration_depth_m=MLD_INTEGRATION_DEPTH_M,
                         n2=None):
    """
    Mixed-layer depth via the Depth Integration (DI) Method.

    The DI estimator defines the MLD as the N²-weighted mean depth over the
    upper ``integration_depth_m`` metres of the water column:

        MLD_DI = ∫₀ᴴ z N²(z) dz / ∫₀ᴴ N²(z) dz      (H = integration_depth_m)

    where N²(z) is the buoyancy frequency squared.  Discretised on the model
    levels (positive-downward depth ``z`` and layer thickness ``dz``):

        MLD_DI = Σ_{z≤H} z N² dz / Σ_{z≤H} N² dz

    Stratification dominates the weighting, so the estimator returns a depth
    near the base of the pycnocline.  Unlike the threshold estimator
    (:func:`mixed_layer_depth`) it does not land exactly on a discrete model
    level; it is a continuous, profile-weighted depth.

    Statically unstable layers (N² < 0) are floored to N² = 0 before
    weighting — consistent with the rest of this module
    (cf. :func:`balanced_richardson_number_3d`) — so convective columns
    contribute zero weight rather than a negative one.

    Uses pure xarray reductions so the computation stays fully lazy when the
    inputs are dask-backed.  Returns a 2D field (positive metres, no depth
    dispatch needed).

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``Theta``, ``Salt``, the vertical
        coordinate ``Z``, and the layer-thickness variable ``drF`` (used to
        build N² when *n2* is not supplied, and always for the depth
        coordinate / spacing).
    integration_depth_m : float, optional
        Upper-ocean integration depth H [m], positive downward (default
        ``MLD_INTEGRATION_DEPTH_M``, typically 300 m).  Only model levels
        with ``z ≤ integration_depth_m`` enter the integrals.
    n2 : xr.DataArray, optional
        Pre-computed 3D buoyancy frequency squared N² [s⁻²] on tracer
        levels.  If ``None``, computed via
        :func:`buoyancy_frequency_squared_3d`.  Supplying it lets callers
        that already have N² (or that only have density, not Theta/Salt)
        reuse it and avoid recomputation.

    Returns
    -------
    xr.DataArray
        2D mixed-layer depth [m], positive metres below the surface, with
        ``name="MLD_DI"``; ``NaN`` in columns where the N² weight integral
        is zero (e.g. fully unstable or land columns).

    Generated by JXP and Claude
    """
    # N² weighting field (reuse caller's if supplied to avoid recomputation).
    if n2 is None:
        n2 = buoyancy_frequency_squared_3d(ds_merge)
    # Floor statically unstable layers (N² < 0) to 0 so they carry zero,
    # not negative, weight in the depth integral.
    n2 = n2.clip(min=0.0)

    zdim = _get_vertical_dim(n2)
    # Positive-downward depth coordinate and layer thicknesses (both 1D).
    z = _get_depth_coord(ds_merge, zdim=zdim)
    dz = _get_vertical_spacing(ds_merge, zdim=zdim)

    # Restrict both integrals to the upper integration_depth_m metres.
    mask = z <= integration_depth_m
    numer = (z * n2 * dz).where(mask).sum(dim=zdim)   # ∫ z N² dz
    denom = (n2 * dz).where(mask).sum(dim=zdim)       # ∫ N² dz

    # Guard the (denom == 0) columns — the weighted mean is undefined there.
    mld = xr.where(denom > 0, numer / denom, np.nan)

    mld.name = "MLD_DI"
    mld.attrs["long_name"] = "Mixed layer depth (Depth Integration Method)"
    mld.attrs["units"] = "m"
    mld.attrs["description"] = (
        "The depth to the bottom of the mixed layer calculated using the "
        "Depth Integration Method"
    )
    return mld


def mixed_layer_heat_content(ds_merge, mld=None):
    """
    Mixed-layer heat content integrated over the mixed layer.

    Q_ml = ∫₀ᴹᴸᴰ cp ρ₀ Θ dz   [J m⁻²]

    This is a 2D field (no depth dispatch — it is inherently an MLD integral).

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``Theta``, ``Salt``, and vertical spacing
        variables.
    mld : xr.DataArray, optional
        Pre-computed 2D mixed-layer depth [m].  If ``None``, computed via
        :func:`mixed_layer_depth`.

    Returns
    -------
    xr.DataArray
        2D mixed-layer heat content [J m⁻²], with
        ``name="ml_heat_content"``.
    """
    if mld is None:
        mld = mixed_layer_depth(ds_merge)

    theta = ds_merge.Theta
    integrand = CP * RHO0_BOUSSINESQ * theta

    zdim = _get_vertical_dim(integrand)
    z = _get_depth_coord(ds_merge, zdim=zdim)
    dz = _get_vertical_spacing(ds_merge, zdim=zdim)
    mask = z <= mld

    out = (integrand * dz).where(mask).sum(dim=zdim)
    out.name = "ml_heat_content"
    out.attrs["long_name"] = "Mixed-layer heat content (integrated)"
    out.attrs["units"] = "J m^-2"
    return out


def buoyancy_field_3d(ds_merge):
    """Thin wrapper over :func:`calculate_additional_fields.buoyancy_of_field`.

    Single project-wide buoyancy definition b = G rho / RHO0_BOUSSINESQ
    [m s^-2] (see prompts/field_migration.md — replaces the legacy
    G_KM * rho / 1025 * 1e3 route).  Kept as an alias until Phase 3
    deletes it.

    Generated by LH and Claude
    """
    return buoyancy_of_field(ds_merge)


# ===========================================================================
#  NATIVE VECTOR FIELDS (geographic, tracer-collocated)
# ===========================================================================

def geographic_velocity_3d(ds_merge, grid):
    """Lazy 3D horizontal velocity rotated to geographic (east/north) components.

    The native ``U``/``V`` are stored on the staggered model grid and on
    model-relative axes; this returns them interpolated to tracer points and
    rotated to true east/north via the grid ``CS``/``SN`` coefficients.  

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``U``, ``V`` and rotation coefficients
        ``CS``/``SN``.
    grid : xgcm.Grid
        Grid used to interpolate the staggered components to tracer points.

    Returns
    -------
    u_east : xr.DataArray
        Eastward velocity [m s⁻¹] on tracer points.
    v_north : xr.DataArray
        Northward velocity [m s⁻¹] on tracer points.
    """
    u_east, v_north = ng.rotate_vector_to_geographic(
        ds_merge.U, ds_merge.V, ds_merge, grid,
    )
    u_east.name = "u_east"
    u_east.attrs.update({"long_name": "eastward velocity", "units": "m s-1"})
    v_north.name = "v_north"
    v_north.attrs.update({"long_name": "northward velocity", "units": "m s-1"})
    return u_east, v_north


def geographic_wind_stress(ds_merge, grid):
    """Lazy geographic wind stress (eastward, northward) on tracer points.

    Public field wrapper around the same interpolate-then-rotate step used by
    the Ekman diagnostics; rotates the native ``oceTAUX``/``oceTAUY`` to true
    east/north for a chunk or tile.

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``oceTAUX``, ``oceTAUY`` and ``CS``/``SN``.
    grid : xgcm.Grid
        Grid used to interpolate the staggered components to tracer points.

    Returns
    -------
    tau_east : xr.DataArray
        Eastward wind stress [N m⁻²] on tracer points.
    tau_north : xr.DataArray
        Northward wind stress [N m⁻²] on tracer points.
    """
    tau_east, tau_north = ng.rotate_vector_to_geographic(
        ds_merge.oceTAUX, ds_merge.oceTAUY, ds_merge, grid,
    )
    tau_east.name = "tau_east"
    tau_east.attrs.update({"long_name": "eastward wind stress", "units": "N m-2"})
    tau_north.name = "tau_north"
    tau_north.attrs.update({"long_name": "northward wind stress", "units": "N m-2"})
    return tau_east, tau_north


# ===========================================================================
#  GROUP 3: SHEAR & DIMENSIONLESS NUMBERS
# ===========================================================================

def vertical_shear_components_3d(ds_merge, grid):
    """Lazy 3D vertical shear (du/dz, dv/dz) in geographic coordinates.

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``U``, ``V``, rotation coefficients
        ``CS`` and ``SN``, and vertical spacing variables.
    grid : xgcm.Grid
        Grid object used for interpolation between velocity and tracer points.

    Returns
    -------
    uz : xr.DataArray
        Zonal shear du/dz [s⁻¹] on tracer levels.
    vz : xr.DataArray
        Meridional shear dv/dz [s⁻¹] on tracer levels.
    """
    dUdz = _vertical_derivative(ds_merge.U, ds_merge)
    dVdz = _vertical_derivative(ds_merge.V, ds_merge)

    # Interpolate the staggered shear components to tracer points and rotate
    # into the geographic (east/north) basis.
    uz, vz = ng.rotate_vector_to_geographic(dUdz, dVdz, ds_merge, grid)
    return uz, vz


def vertical_shear_magnitude_3d(ds_merge, grid):
    """Lazy 3D |S| = sqrt(uz² + vz²).

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``U``, ``V``, rotation coefficients, and
        vertical spacing variables.
    grid : xgcm.Grid
        Grid object used for interpolation between velocity and tracer points.

    Returns
    -------
    xr.DataArray
        3D vertical shear magnitude |S| [s⁻¹] on tracer levels.
    """
    uz, vz = vertical_shear_components_3d(ds_merge, grid)
    shear_mag = np.sqrt(uz**2 + vz**2)
    return shear_mag


def richardson_number_3d(ds_merge, grid):
    """Lazy 3D Ri = N² / (uz² + vz²).

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``Theta``, ``Salt``, ``U``, ``V``,
        rotation coefficients, and vertical spacing variables.
    grid : xgcm.Grid
        Grid object used for interpolation and differencing.

    Returns
    -------
    xr.DataArray
        3D Richardson number Ri [dimensionless] on tracer levels; ``NaN``
        where shear² ≤ 0.  Statically unstable columns (N² < 0) are floored
        to N² = 0, so Ri = 0 there rather than negative.
    """
    n2 = buoyancy_frequency_squared_3d(ds_merge)
    # Floor statically unstable stratification (N² < 0) to 0 so unstable
    # columns yield Ri = 0 rather than a negative Richardson number.
    n2 = n2.clip(min=0.0)
    uz, vz = vertical_shear_components_3d(ds_merge, grid)
    shear2 = uz**2 + vz**2
    ri = xr.where(shear2 > 0, n2 / shear2, np.nan)
    return ri


def froude_number_3d(ds_merge, grid, mld=None):
    """Lazy 3D Fr = speed / (N * MLD).

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``Theta``, ``Salt``, ``U``, ``V``,
        rotation coefficients, and vertical spacing variables.
    grid : xgcm.Grid
        Grid object used for interpolation and differencing.
    mld : xr.DataArray, optional
        Pre-computed 2D mixed-layer depth [m].  If ``None``, computed via
        :func:`mixed_layer_depth`.

    Returns
    -------
    xr.DataArray
        3D Froude number Fr [dimensionless] on tracer levels; ``NaN``
        where N * MLD ≤ 0.
    """
    if mld is None:
        mld = mixed_layer_depth(ds_merge)
    n2 = buoyancy_frequency_squared_3d(ds_merge)
    n_abs = np.sqrt(np.abs(n2))

    U_c = grid.interp(ds_merge.U, 'X', boundary='fill')
    V_c = grid.interp(ds_merge.V, 'Y', boundary='fill')
    speed = np.sqrt(U_c**2 + V_c**2)

    denom = n_abs * mld
    fr = xr.where(denom > 0, speed / denom, np.nan)
    return fr


def rossby_number_3d(ds_merge, grid):
    """Lazy 3D Ro = ζ / f.

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``U``, ``V``, grid metrics, rotation
        coefficients, and latitude coordinate ``YC``.
    grid : xgcm.Grid
        Grid object used for differencing and interpolation.

    Returns
    -------
    xr.DataArray
        3D Rossby number Ro [dimensionless] on tracer levels.
    """
    du_dx, du_dy, dv_dx, dv_dy = ng.calculate_jacobian(
        ds_merge.U, ds_merge.V, ds_merge, grid)
    zeta = dv_dx - du_dy
    f = coriolis_parameter(ds_merge, grid)
    ro = zeta / f
    return ro


def burger_number_3d(ds_merge, grid, mld=None):
    """Lazy 3D Bu = (Ro / Fr)².

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``Theta``, ``Salt``, ``U``, ``V``,
        rotation coefficients, and vertical spacing variables.
    grid : xgcm.Grid
        Grid object used for differencing and interpolation.
    mld : xr.DataArray, optional
        Pre-computed 2D mixed-layer depth [m].  If ``None``, computed via
        :func:`mixed_layer_depth`.

    Returns
    -------
    xr.DataArray
        3D Burger number Bu [dimensionless] on tracer levels; ``NaN``
        where Fr = 0.
    """
    if mld is None:
        mld = mixed_layer_depth(ds_merge)
    ro_3d = rossby_number_3d(ds_merge, grid)
    fr_3d = froude_number_3d(ds_merge, grid, mld=mld)
    bu_3d = xr.where(fr_3d != 0, (ro_3d / fr_3d) ** 2, np.nan)
    return bu_3d


def _buoyancy_gradient_phys_3d(ds_merge, grid):
    """Lazy 3D physical horizontal buoyancy gradient components (b_x, b_y).

    Returns the zonal and meridional components ∂b/∂x, ∂b/∂y of the
    *physical* buoyancy b = (g / ρ₀) ρ — the same unscaled definition
    implied by N² = (g / ρ₀) dρ/dz (Boussinesq reference density
    ``RHO0_BOUSSINESQ``).  This is the single source of truth for the
    physically consistent buoyancy gradient shared by the balanced
    Richardson number (which squares it) and the modified Okubo-Weiss
    parameter W* (which dots it with the velocity Jacobian).

    It differs deliberately from :func:`compute_buoyancy_gradients_3d`,
    which is built on :func:`buoyancy_field_3d` (a differently scaled
    buoyancy); using that gradient would bias |∇_h b|²-based diagnostics
    by a constant factor.  Deriving the gradient straight from density
    keeps every term on one common buoyancy definition.

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``Theta``, ``Salt``, and horizontal grid
        metrics.
    grid : xgcm.Grid
        Grid object used for horizontal differencing.

    Returns
    -------
    b_x : xr.DataArray
        Zonal buoyancy gradient ∂b/∂x [s⁻²] on tracer levels.
    b_y : xr.DataArray
        Meridional buoyancy gradient ∂b/∂y [s⁻²] on tracer levels.

    Generated by JXP and Claude
    """
    # Density from the JMD95 EOS — the same source used to build N².
    rho = _density_lazy(ds_merge)
    # Physical buoyancy b = (g / ρ₀) ρ (unscaled).  The additive constant
    # vanishes under differentiation, so only the slope matters here.
    b_phys = (G / RHO0_BOUSSINESQ) * rho
    # Horizontal gradient on tracer points (lazy), native-grid aware.
    b_x, b_y = ng.calculate_native_gradient_tracer(
        b_phys, ds_merge, grid=grid)
    return b_x, b_y


def _buoyancy_gradient_squared_phys_3d(ds_merge, grid):
    """Lazy 3D |∇_h b|² built on a buoyancy consistent with N².

    The buoyancy used here is b = (g / ρ₀) ρ — the *same* physical
    definition implied by N² = (g / ρ₀) dρ/dz (Boussinesq reference
    density ``RHO0_BOUSSINESQ``, no extra scaling).  Deriving the gradient
    straight from density keeps the N² numerator and the |∇_h b|²
    denominator on one common buoyancy definition, so R_ib comes out truly
    dimensionless.  Delegates the gradient to
    :func:`_buoyancy_gradient_phys_3d` so W* and R_ib share one source.

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``Theta``, ``Salt``, and horizontal grid
        metrics.
    grid : xgcm.Grid
        Grid object used for horizontal differencing.

    Returns
    -------
    xr.DataArray
        3D horizontal buoyancy gradient magnitude squared |∇_h b|² [s⁻⁴]
        on tracer levels, physically consistent with N².

    Generated by JXP and Claude
    """
    # |∇_h b|² = (∂b/∂x)² + (∂b/∂y)² on tracer points (lazy).  The sign of
    # each component vanishes once squared.
    b_x, b_y = _buoyancy_gradient_phys_3d(ds_merge, grid)
    return b_x**2 + b_y**2


def balanced_richardson_number_3d(ds_merge, grid, *, n2=None, gradb2=None):
    """Lazy 3D balanced Richardson number R_ib = N² f² / |∇_h b|².

    The balanced Richardson number (Thomas, Tandon & Mahadevan 2013) is
    the gradient Richardson number of a flow in thermal-wind balance and a
    dimensionless measure of frontal stability.  N² and the horizontal
    buoyancy gradient are both derived from the *same* physically
    consistent, unscaled buoyancy (b = (g / ρ₀) ρ), so the ratio is truly
    dimensionless — see :func:`_buoyancy_gradient_squared_phys_3d`.

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``Theta``, ``Salt``, latitude ``YC``,
        vertical spacing variables, and horizontal grid metrics.
    grid : xgcm.Grid
        Grid object used for horizontal differencing.
    n2 : xr.DataArray, optional
        Pre-computed 3D N² [s⁻²].  If ``None``, computed via
        :func:`buoyancy_frequency_squared_3d`.
    gradb2 : xr.DataArray, optional
        Pre-computed 3D |∇_h b|² [s⁻⁴].  Must use the physically
        consistent (unscaled) buoyancy of
        :func:`_buoyancy_gradient_squared_phys_3d`; passing the ×1e3-scaled
        :func:`grad_b2_3d` output would bias R_ib by a constant factor.
        If ``None``, computed internally.

    Returns
    -------
    xr.DataArray
        3D balanced Richardson number R_ib [dimensionless] on tracer
        levels, with ``name="R_ib"``; ``NaN`` where |∇_h b|² = 0 (the
        ratio is undefined).  At the equator f → 0 so R_ib → 0.  Statically
        unstable columns (N² < 0) are floored to N² = 0, so R_ib = 0 there
        rather than negative.

    Generated by JXP and Claude
    """
    # N² numerator term (reuse caller's if supplied to avoid recomputation).
    if n2 is None:
        n2 = buoyancy_frequency_squared_3d(ds_merge)
    # Floor statically unstable stratification (N² < 0) to 0 so unstable
    # columns yield R_ib = 0 rather than a negative value.
    n2 = n2.clip(min=0.0)
    # |∇_h b|² denominator term, on the same buoyancy definition as N².
    if gradb2 is None:
        gradb2 = _buoyancy_gradient_squared_phys_3d(ds_merge, grid)

    # Coriolis parameter f(YC); f² enters the numerator.
    f = coriolis_parameter(ds_merge, grid)

    # R_ib = N² f² / |∇_h b|²; mask the undefined |∇_h b|² = 0 columns.
    r_ib = xr.where(gradb2 > 0, n2 * f**2 / gradb2, np.nan)
    r_ib.name = "R_ib"
    r_ib.attrs["long_name"] = "Balanced Richardson number"
    r_ib.attrs["units"] = "1"
    return r_ib


# ===========================================================================
#  GROUP 3: WIND (inherently 2D)
# ===========================================================================

def wind_stress_curl(ds_merge, grid):
    """Lazy wind stress curl.

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``oceTAUX`` and ``oceTAUY`` on
        staggered velocity points, plus grid metrics.
    grid : xgcm.Grid
        Grid object used for differencing and interpolation.

    Returns
    -------
    xr.DataArray
        2D wind stress curl ∂τy/∂x − ∂τx/∂y [N m⁻³] on tracer points.
    """
    taux = ds_merge.oceTAUX
    tauy = ds_merge.oceTAUY
    _, dtaux_dphi, dtauy_dlambda, _ = ng.calculate_jacobian(
        taux, tauy, ds_merge, grid)
    curl_tau = dtauy_dlambda - dtaux_dphi
    return curl_tau


def ekman_pumping(ds_merge, grid, rho0=RHO0_BOUSSINESQ):
    """Lazy Ekman pumping w_E = curl(τ) / (ρ₀ f).

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``oceTAUX``, ``oceTAUY``, grid metrics,
        and latitude coordinate ``YC``.
    grid : xgcm.Grid
        Grid object used for differencing and interpolation.
    rho0 : float, optional
        Reference density [kg m⁻³] (default ``RHO0_BOUSSINESQ``).

    Returns
    -------
    xr.DataArray
        2D Ekman pumping velocity w_E [m s⁻¹] on tracer points; ``NaN``
        at the equator where f = 0.
    """
    curl_tau = wind_stress_curl(ds_merge, grid)
    f = coriolis_parameter(ds_merge, grid)
    w_e = xr.where(np.abs(f) > 0, curl_tau / (rho0 * f), np.nan)
    return w_e


def _wind_stress_geographic(ds_merge, grid):
    """Lazy geographic wind stress (τ_λ, τ_φ) on tracer points.

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``oceTAUX``, ``oceTAUY``, and rotation
        coefficients ``CS`` and ``SN``.
    grid : xgcm.Grid
        Grid object used for interpolation to tracer points.

    Returns
    -------
    tau_lambda : xr.DataArray
        Zonal (eastward) wind stress component [N m⁻²] on tracer points.
    tau_phi : xr.DataArray
        Meridional (northward) wind stress component [N m⁻²] on tracer
        points.
    """
    return ng.rotate_vector_to_geographic(
        ds_merge.oceTAUX, ds_merge.oceTAUY, ds_merge, grid,
    )


def ekman_transport(ds_merge, grid, rho0=RHO0_BOUSSINESQ):
    """Lazy Ekman transport (u_E, v_E).

    These are depth-integrated velocities (τ / (ρ₀ f)).
    https://sam.ucsd.edu/ltalley/sio210/dynamics_ekman/index.html

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``oceTAUX``, ``oceTAUY``, rotation
        coefficients ``CS`` and ``SN``, and latitude coordinate ``YC``.
    grid : xgcm.Grid
        Grid object used for interpolation to tracer points.
    rho0 : float, optional
        Reference density [kg m⁻³] (default ``RHO0_BOUSSINESQ``).

    Returns
    -------
    dict
        Dictionary with keys:

        ``"u_ekman"`` : xr.DataArray
            Zonal Ekman transport [m² s⁻¹] on tracer points.
        ``"v_ekman"`` : xr.DataArray
            Meridional Ekman transport [m² s⁻¹] on tracer points.
    """
    f = coriolis_parameter(ds_merge, grid)
    denom = rho0 * f
    safe_denom = xr.where(np.abs(f) > 0, denom, np.nan)
    tau_lambda, tau_phi = _wind_stress_geographic(ds_merge, grid)
    return {"u_ekman": tau_phi / safe_denom,
            "v_ekman": -tau_lambda / safe_denom}


# ===========================================================================
#  GROUP 4: ADVECTIVE BUOYANCY FLUXES (lazy 3D)
# ===========================================================================

def advective_buoyancy_fluxes_3d(ds_merge, grid):
    """Lazy (uB, vB, wB) in geographic coordinates.

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``Theta``, ``Salt``, ``U``, ``V``, ``W``,
        rotation coefficients ``CS`` and ``SN``, and standard grid variables.
    grid : xgcm.Grid
        Grid object used for interpolation to tracer points.

    Returns
    -------
    uB : xr.DataArray
        Zonal advective buoyancy flux u·b [m^2 s^-3] on tracer levels.
    vB : xr.DataArray
        Meridional advective buoyancy flux v·b [m^2 s^-3] on tracer levels.
    wB : xr.DataArray
        Vertical advective buoyancy flux w·b [m^2 s^-3] on tracer levels.
    """
    b = buoyancy_field_3d(ds_merge)

    u_geog, v_geog = geographic_velocity_3d(ds_merge, grid)

    W_c = _interp_w_to_tracer_levels(ds_merge)

    return u_geog * b, v_geog * b, W_c * b


# ===========================================================================
#  GROUP 5: ERTEL PV (lazy 3D)
# ===========================================================================

def ertel_pv_terms_3d(ds_merge, grid):
    """Lazy Ertel PV and its vertical/tilting decomposition.

    q = (ζ + f) b_z  +  (w_y - v_z) b_x  +  (u_z - w_x) b_y
        ─────────────    ──────────────────────────────────────
          q_vert                    q_tilt

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``Theta``, ``Salt``, ``U``, ``V``, ``W``,
        rotation coefficients, latitude ``YC``, and all grid metrics.
    grid : xgcm.Grid
        Grid object used for differencing and interpolation.

    Returns
    -------
    dict
        Dictionary with keys:

        ``"ertel_pv"`` : xr.DataArray
            Total Ertel PV q [s⁻³] on tracer levels.
        ``"ertel_pv_vertical"`` : xr.DataArray
            Vertical component q_vert = (ζ + f) b_z [s⁻³].
        ``"ertel_pv_tilt"`` : xr.DataArray
            Tilting component q_tilt [s⁻³].
    """
    U = ds_merge.U
    V = ds_merge.V

    du_dx, du_dy, dv_dx, dv_dy = ng.calculate_jacobian(U, V, ds_merge, grid)
    zeta = dv_dx - du_dy
    f = coriolis_parameter(ds_merge, grid)

    b = buoyancy_field_3d(ds_merge)
    b_x, b_y = ng.calculate_native_gradient_tracer(
        b, ds_merge, grid=grid)
    b_z = _vertical_derivative(b, ds_merge)

    u_z, v_z = vertical_shear_components_3d(ds_merge, grid)

    W_on_tracer = _interp_w_to_tracer_levels(ds_merge)
    w_x, w_y = ng.calculate_native_gradient_tracer(
        W_on_tracer, ds_merge, grid=grid)

    q_vert = (zeta + f) * b_z
    q_tilt = (w_y - v_z) * b_x + (u_z - w_x) * b_y
    q_total = q_vert + q_tilt

    return {
        "ertel_pv": q_total,
        "ertel_pv_vertical": q_vert,
        "ertel_pv_tilt": q_tilt,
    }


# ===========================================================================
#  GROUP 6: SCALAR GRADIENTS & FRONTAL STRUCTURE (lazy 3D)
# ===========================================================================

def grad_theta2_3d(ds_merge, grid):
    """Lazy 3D |∇θ|².  Units: (K/m)².

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``Theta`` and grid metrics.
    grid : xgcm.Grid
        Grid object used for differencing.

    Returns
    -------
    xr.DataArray
        3D horizontal temperature gradient squared |∇θ|² [(degrees C m⁻¹)²] on
        tracer levels.
    """
    gx, gy = ng.calculate_native_gradient_tracer(
        ds_merge.Theta, ds_merge, grid=grid)
    return ng.grad_squared(gx, gy)


def grad_salt2_3d(ds_merge, grid):
    """Lazy 3D |∇S|².  Units: (PSU/m)².

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``Salt`` and grid metrics.
    grid : xgcm.Grid
        Grid object used for differencing.

    Returns
    -------
    xr.DataArray
        3D horizontal salinity gradient squared |∇S|² [(PSU m⁻¹)²] on
        tracer levels.
    """
    gx, gy = ng.calculate_native_gradient_tracer(
        ds_merge.Salt, ds_merge, grid=grid)
    return ng.grad_squared(gx, gy)


def grad_rho2_3d(ds_merge, grid):
    """Lazy 3D |∇ρ|².  Derives density via JMD95.

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``Theta``, ``Salt``, and grid metrics.
    grid : xgcm.Grid
        Grid object used for differencing.

    Returns
    -------
    xr.DataArray
        3D horizontal density gradient squared |∇ρ|² [(kg m⁻⁴)²] on
        tracer levels.
    """
    rho = _density_lazy(ds_merge)
    gx, gy = ng.calculate_native_gradient_tracer(
        rho, ds_merge, grid=grid)
    return ng.grad_squared(gx, gy)


def grad_b2_3d(ds_merge, grid):
    """Lazy 3D |∇b|².  Units: s⁻⁴.

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``Theta``, ``Salt``, and grid metrics.
    grid : xgcm.Grid
        Grid object used for differencing.

    Returns
    -------
    xr.DataArray
        3D horizontal buoyancy gradient squared |∇b|² [s⁻⁴] on tracer
        levels.
    """
    b = buoyancy_field_3d(ds_merge)
    gx, gy = ng.calculate_native_gradient_tracer(
        b, ds_merge, grid=grid)
    return ng.grad_squared(gx, gy)


def grad_eta2(ds_merge, grid):
    """Lazy |∇η|² — inherently 2D (surface only).

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing sea-surface height ``Eta`` and grid
        metrics.
    grid : xgcm.Grid
        Grid object used for differencing.

    Returns
    -------
    xr.DataArray
        2D sea-surface height gradient squared |∇η|² [m² m⁻²] on tracer
        points (dims ``face``, ``j``, ``i``).
    """
    gx, gy = ng.calculate_native_gradient_tracer(
        ds_merge.Eta, ds_merge, grid=grid,
    )
    return gx**2 + gy**2


def turner_angle_3d(ds_merge, grid, *, gradtheta2=None, gradsalt2=None,
                    gradrho2=None):
    """Lazy 3D horizontal Turner angle (degrees).

    Tu_h = arctan(ρ₀(β²|∇S|² − α²|∇θ|²) / (−|∇ρ|²/ρ₀))

    Optional kwargs accept pre-computed 3D gradient fields to avoid
    recomputation when the caller already has them (e.g. Turner angle
    shares gradtheta2/gradsalt2/gradrho2 with the frontal_structure subset).

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``Theta``, ``Salt``, and grid metrics.
    grid : xgcm.Grid
        Grid object used for differencing.
    gradtheta2 : xr.DataArray, optional
        Pre-computed |∇θ|² [(K m⁻¹)²].  If ``None``, computed internally.
    gradsalt2 : xr.DataArray, optional
        Pre-computed |∇S|² [(PSU m⁻¹)²].  If ``None``, computed internally.
    gradrho2 : xr.DataArray, optional
        Pre-computed |∇ρ|² [(kg m⁻⁴)²].  If ``None``, computed internally.

    Returns
    -------
    xr.DataArray
        3D horizontal Turner angle [degrees] on tracer levels; ``NaN``
        where |∇ρ|² = 0.
    """
    if gradtheta2 is None:
        gradtheta2 = grad_theta2_3d(ds_merge, grid)
    if gradsalt2 is None:
        gradsalt2 = grad_salt2_3d(ds_merge, grid)
    if gradrho2 is None:
        gradrho2 = grad_rho2_3d(ds_merge, grid)

    numer = RHO0_BOUSSINESQ * (BETA**2 * gradsalt2 - ALPHA**2 * gradtheta2)
    denom = xr.where(gradrho2 > 0, -gradrho2 / RHO0_BOUSSINESQ, np.nan)
    return np.degrees(np.arctan(numer / denom))


# ===========================================================================
#  GROUP 6b: VELOCITY PROPERTIES (lazy 3D)
# ===========================================================================

def compute_velocity_jacobian_3d(ds_merge, grid):
    """3D velocity Jacobian → VelocityJacobian(du_dx, du_dy, dv_dx, dv_dy).

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``U``, ``V``, grid metrics, and rotation
        coefficients ``CS`` and ``SN``.
    grid : xgcm.Grid
        Grid object used for differencing and interpolation.

    Returns
    -------
    VelocityJacobian
        Named tuple with fields ``(du_dx, du_dy, dv_dx, dv_dy)``, each a
        dask-backed ``xr.DataArray`` on tracer levels [s⁻¹].
    """
    du_dx, du_dy, dv_dx, dv_dy = ng.calculate_jacobian(
        ds_merge.U, ds_merge.V, ds_merge, grid,
    )
    return VelocityJacobian(du_dx, du_dy, dv_dx, dv_dy)


def relative_vorticity_3d(ds_merge, grid, *, jacobian=None):
    """Lazy 3D ζ = dv/dx − du/dy.  Accepts optional *jacobian*.

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``U``, ``V``, grid metrics, and rotation
        coefficients.
    grid : xgcm.Grid
        Grid object used for differencing and interpolation.
    jacobian : VelocityJacobian, optional
        Pre-computed velocity Jacobian.  If ``None``, computed internally.

    Returns
    -------
    xr.DataArray
        3D relative vorticity ζ [s⁻¹] on tracer levels.
    """
    if jacobian is None:
        jacobian = compute_velocity_jacobian_3d(ds_merge, grid)
    return jacobian.dv_dx - jacobian.du_dy


def strain_3d(ds_merge, grid, *, jacobian=None):
    """Lazy 3D strain → (strain_mag, strain_n, strain_s).  Accepts optional *jacobian*.

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``U``, ``V``, grid metrics, and rotation
        coefficients.
    grid : xgcm.Grid
        Grid object used for differencing and interpolation.
    jacobian : VelocityJacobian, optional
        Pre-computed velocity Jacobian.  If ``None``, computed internally.

    Returns
    -------
    sm : xr.DataArray
        3D strain magnitude |S| = sqrt(Sn² + Ss²) [s⁻¹] on tracer levels.
    sn : xr.DataArray
        3D normal strain Sn = du/dx − dv/dy [s⁻¹] on tracer levels.
    ss : xr.DataArray
        3D shear strain Ss = du/dy + dv/dx [s⁻¹] on tracer levels.
    """
    if jacobian is None:
        jacobian = compute_velocity_jacobian_3d(ds_merge, grid)
    sn = jacobian.du_dx - jacobian.dv_dy
    ss = jacobian.du_dy + jacobian.dv_dx
    sm = np.sqrt(sn**2 + ss**2)
    return sm, sn, ss


def divergence_3d(ds_merge, grid, *, jacobian=None):
    """Lazy 3D divergence = du/dx + dv/dy.  Accepts optional *jacobian*.

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``U``, ``V``, grid metrics, and rotation
        coefficients.
    grid : xgcm.Grid
        Grid object used for differencing and interpolation.
    jacobian : VelocityJacobian, optional
        Pre-computed velocity Jacobian.  If ``None``, computed internally.

    Returns
    -------
    xr.DataArray
        3D horizontal divergence δ = du/dx + dv/dy [s⁻¹] on tracer levels.
    """
    if jacobian is None:
        jacobian = compute_velocity_jacobian_3d(ds_merge, grid)
    divergence = jacobian.du_dx + jacobian.dv_dy
    return divergence


def okubo_weiss_3d(ds_merge, grid, *, jacobian=None):
    """Lazy 3D Okubo-Weiss = Sn² + Ss² − ζ².  Accepts optional *jacobian*.

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``U``, ``V``, grid metrics, and rotation
        coefficients.
    grid : xgcm.Grid
        Grid object used for differencing and interpolation.
    jacobian : VelocityJacobian, optional
        Pre-computed velocity Jacobian.  If ``None``, computed internally.

    Returns
    -------
    xr.DataArray
        3D Okubo-Weiss parameter W = Sn² + Ss² − ζ² [s⁻²] on tracer
        levels; positive values indicate strain-dominated regions.
    """
    if jacobian is None:
        jacobian = compute_velocity_jacobian_3d(ds_merge, grid)
    omega = relative_vorticity_3d(ds_merge, grid, jacobian=jacobian)
    _, sn, ss = strain_3d(ds_merge, grid, jacobian=jacobian)
    return sn**2 + ss**2 - omega**2


def modified_okubo_weiss_3d(ds_merge, grid, *, jacobian=None,
                            okubo_weiss=None, q_squared=None):
    """Lazy 3D modified Okubo-Weiss parameter W* (Bachman 2021).

    Like the classical Okubo-Weiss parameter, W* compares strain and
    vorticity, but it is additionally sensitive to the vertical shear
    encoded in the quasigeostrophic Q vector.  It is defined as the
    eigenvalues (l₁, l₂) of the QG strain-squared-plus-vorticity-squared
    tensor combined as

        W* = 4 · sgn(l₂) · √(l₁² + l₂²)

    with

        l₂ = W / 4 ,           W = σ_n² + σ_s² − ω²   (Okubo-Weiss)
        l₁ = ½ l₂ + ½ √(l₂² + |Q|² / f²)

    and the QG Q vector (Hoskins, Draghici & Davies 1978)

        Q₁ = −(∂u/∂x ∂b/∂x + ∂v/∂x ∂b/∂y)
        Q₂ = −(∂u/∂y ∂b/∂x + ∂v/∂y ∂b/∂y) ,   |Q|² = Q₁² + Q₂².

    The Okubo-Weiss term reuses :func:`okubo_weiss_3d`; the buoyancy
    gradient reuses the physically consistent (unscaled) buoyancy of
    :func:`_buoyancy_gradient_phys_3d` (the same b = (g/ρ₀)ρ used for N²
    and R_ib), so ∂b/∂x is in s⁻², Q in s⁻³, |Q|²/f² in s⁻⁴, and W* in
    s⁻² — the same units as the classical W.  The computation stays fully
    lazy (dask task graph, no ``.compute()``).

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``Theta``, ``Salt``, ``U``, ``V``,
        latitude ``YC``, grid metrics, and rotation coefficients
        ``CS``/``SN``.
    grid : xgcm.Grid
        Grid object used for differencing and interpolation.
    jacobian : VelocityJacobian, optional
        Pre-computed velocity Jacobian ``(du_dx, du_dy, dv_dx, dv_dy)``.
        If ``None`` (and needed), computed internally.  Supplying it lets
        callers (e.g. the frontogenesis subset) share the Jacobian and
        avoid recomputing the single most expensive intermediate.
    okubo_weiss : xr.DataArray, optional
        Pre-computed classical Okubo-Weiss parameter W [s⁻²].  If ``None``,
        computed via :func:`okubo_weiss_3d`.
    q_squared : xr.DataArray, optional
        Pre-computed QG Q-vector magnitude squared |Q|² [s⁻⁶].  If
        ``None``, computed from the Jacobian and the physical buoyancy
        gradient.  (Together with *okubo_weiss* this lets the formula be
        exercised without an xgcm grid, mirroring the ``n2``/``gradb2``
        injection of :func:`balanced_richardson_number_3d`.)

    Returns
    -------
    xr.DataArray
        3D modified Okubo-Weiss parameter W* [s⁻²] on tracer levels, with
        ``name="Wstar"``; ``NaN`` at the equator where f → 0 (the QG
        scaling |Q|²/f² diverges).  Its sign follows that of the classical
        Okubo-Weiss parameter (positive ⇒ strain-dominated).

    Generated by JXP and Claude
    """
    # Classical Okubo-Weiss W = σ_n² + σ_s² − ω² (reuse caller's if given).
    if okubo_weiss is None:
        if jacobian is None:
            jacobian = compute_velocity_jacobian_3d(ds_merge, grid)
        okubo_weiss = okubo_weiss_3d(ds_merge, grid, jacobian=jacobian)
    # Smaller eigenvalue l₂ = W / 4.
    l2 = okubo_weiss / 4.0

    # QG Q-vector magnitude squared |Q|² (reuse caller's if supplied).
    if q_squared is None:
        if jacobian is None:
            jacobian = compute_velocity_jacobian_3d(ds_merge, grid)
        # Physical (unscaled) horizontal buoyancy gradient ∂b/∂x, ∂b/∂y —
        # consistent with N²/R_ib so the QG term is dimensionally honest.
        b_x, b_y = _buoyancy_gradient_phys_3d(ds_merge, grid)
        # QG Q-vector components from the velocity Jacobian and ∇_h b.
        q1 = -(jacobian.du_dx * b_x + jacobian.dv_dx * b_y)
        q2 = -(jacobian.du_dy * b_x + jacobian.dv_dy * b_y)
        q_squared = q1**2 + q2**2

    # Coriolis parameter f(YC); f² normalises |Q|².  Mask the equator
    # (f → 0), where the QG scaling diverges — mirrors ekman_pumping/R_ib.
    f = coriolis_parameter(ds_merge, grid)
    f2 = xr.where(np.abs(f) > 0, f**2, np.nan)

    # Larger eigenvalue l₁ = ½ l₂ + ½ √(l₂² + |Q|²/f²).
    l1 = 0.5 * l2 + 0.5 * np.sqrt(l2**2 + q_squared / f2)

    # Modified Okubo-Weiss W* = 4 sgn(l₂) √(l₁² + l₂²).
    wstar = 4.0 * np.sign(l2) * np.sqrt(l1**2 + l2**2)
    wstar.name = "Wstar"
    wstar.attrs["long_name"] = "Modified Okubo-Weiss parameter (W*)"
    wstar.attrs["units"] = "s^-2"
    return wstar



# ===========================================================================
#  GROUP 7: FRONTOGENESIS (lazy 3D)
# ===========================================================================

def compute_buoyancy_gradients_3d(ds_merge, grid):
    """3D buoyancy gradients → BuoyancyGradients(zonal, merid).

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``Theta``, ``Salt``, and grid metrics.
    grid : xgcm.Grid
        Grid object used for differencing.

    Returns
    -------
    BuoyancyGradients
        Named tuple with fields:

        ``zonal`` : xr.DataArray
            Zonal buoyancy gradient ∂b/∂x [m s⁻²  m⁻¹] on tracer levels.
        ``merid`` : xr.DataArray
            Meridional buoyancy gradient ∂b/∂y [m s⁻² m⁻¹] on tracer
            levels.
    """
    b = buoyancy_field_3d(ds_merge)
    zonal, merid = ng.calculate_native_gradient_tracer(
        b, ds_merge, grid=grid,
    )
    return BuoyancyGradients(zonal, merid)


def _frontogenesis_formula_3d(du_dx, du_dy, dv_dx, dv_dy, grad_bx, grad_by):
    """Kinematic frontogenesis tendency from velocity and buoyancy gradients.

    F = -(du/dx · bx² + (du/dy + dv/dx) · bx·by + dv/dy · by²)

    Internal helper shared by ``frontogenesis_tendency_3d`` and
    ``frontogenesis_geo_3d``.

    Parameters
    ----------
    du_dx : xr.DataArray
        Zonal velocity gradient ∂u/∂x [s⁻¹] on tracer levels.
    du_dy : xr.DataArray
        Cross-stream velocity gradient ∂u/∂y [s⁻¹] on tracer levels.
    dv_dx : xr.DataArray
        Along-stream velocity gradient ∂v/∂x [s⁻¹] on tracer levels.
    dv_dy : xr.DataArray
        Meridional velocity gradient ∂v/∂y [s⁻¹] on tracer levels.
    grad_bx : xr.DataArray
        Zonal buoyancy gradient ∂b/∂x [s⁻²] on tracer levels.
    grad_by : xr.DataArray
        Meridional buoyancy gradient ∂b/∂y [s⁻²] on tracer levels.

    Returns
    -------
    xr.DataArray
        3D frontogenesis tendency F [s⁻⁵] on tracer levels.
    """
    return -(du_dx * grad_bx**2
             + (du_dy + dv_dx) * grad_bx * grad_by
             + dv_dy * grad_by**2)


def frontogenesis_tendency_3d(ds_merge, grid, *, jacobian=None,
                              buoyancy_gradients=None):
    """Lazy 3D frontogenesis tendency F(u, v).  Accepts optional *jacobian* and *buoyancy_gradients*.

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``Theta``, ``Salt``, ``U``, ``V``,
        grid metrics, and rotation coefficients.
    grid : xgcm.Grid
        Grid object used for differencing and interpolation.
    jacobian : VelocityJacobian, optional
        Pre-computed velocity Jacobian.  If ``None``, computed internally.
    buoyancy_gradients : BuoyancyGradients, optional
        Pre-computed buoyancy gradients.  If ``None``, computed internally.

    Returns
    -------
    xr.DataArray
        3D kinematic frontogenesis tendency F(u, v) [s⁻⁵] on tracer levels.
    """
    if jacobian is None:
        jacobian = compute_velocity_jacobian_3d(ds_merge, grid)
    if buoyancy_gradients is None:
        buoyancy_gradients = compute_buoyancy_gradients_3d(ds_merge, grid)

    return _frontogenesis_formula_3d(
        jacobian.du_dx, jacobian.du_dy,
        jacobian.dv_dx, jacobian.dv_dy,
        buoyancy_gradients.zonal, buoyancy_gradients.merid,
    )


def geostrophic_velocity_3d(ds_merge, grid):
    """Geostrophic velocity → (ug, vg) from ∂η/∂x, ∂η/∂y.

    Eta is inherently 2D so ug/vg are surface-only; named ``_3d`` for
    module consistency (they broadcast against 3D buoyancy gradients).

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing sea-surface height ``Eta``, latitude
        coordinate ``YC``, and grid metrics.
    grid : xgcm.Grid
        Grid object used for differencing.

    Returns
    -------
    ug : xr.DataArray
        Zonal geostrophic velocity ug = −(g/f) ∂η/∂y [m s⁻¹] on tracer
        points.
    vg : xr.DataArray
        Meridional geostrophic velocity vg = (g/f) ∂η/∂x [m s⁻¹] on tracer
        points.
    """
    f = coriolis_parameter(ds_merge, grid)
    eta_grad_x, eta_grad_y = ng.calculate_native_gradient_tracer(
        ds_merge['Eta'], ds_merge, grid=grid,
    )
    ug = -(G / f) * eta_grad_y
    vg =  (G / f) * eta_grad_x
    return ug, vg


def frontogenesis_geo_3d(ds_merge, grid, *, ug=None, vg=None,
                         buoyancy_gradients=None):
    """Lazy 3D geostrophic frontogenesis F(ug, vg).  Accepts optional *ug*, *vg*, *buoyancy_gradients*.

    Parameters
    ----------
    ds_merge : xr.Dataset
        Merged dataset containing ``Eta``, ``Theta``, ``Salt``, latitude
        ``YC``, and grid metrics.
    grid : xgcm.Grid
        Grid object used for differencing and interpolation.
    ug : xr.DataArray, optional
        Pre-computed zonal geostrophic velocity [m s⁻¹].  If ``None``,
        computed internally together with ``vg``.
    vg : xr.DataArray, optional
        Pre-computed meridional geostrophic velocity [m s⁻¹].  If ``None``,
        computed internally together with ``ug``.
    buoyancy_gradients : BuoyancyGradients, optional
        Pre-computed buoyancy gradients.  If ``None``, computed internally.

    Returns
    -------
    xr.DataArray
        3D geostrophic frontogenesis tendency F(ug, vg) [s⁻⁵] on tracer
        levels.
    """
    if ug is None or vg is None:
        ug, vg = geostrophic_velocity_3d(ds_merge, grid)
    if buoyancy_gradients is None:
        buoyancy_gradients = compute_buoyancy_gradients_3d(ds_merge, grid)

    dug_dx, dug_dy = ng.calculate_native_gradient_tracer(
        ug, ds_merge, grid=grid,
    )
    dvg_dx, dvg_dy = ng.calculate_native_gradient_tracer(
        vg, ds_merge, grid=grid,
    )
    return _frontogenesis_formula_3d(
        dug_dx, dug_dy,
        dvg_dx, dvg_dy,
        buoyancy_gradients.zonal, buoyancy_gradients.merid,
    )

